Landuse Analyst: LaModel Class Reference
LaModel Class Reference
#include <lamodel.h>
Signals
void message (QString theMessage)
Public Member Functions
LaModel ()
~LaModel ()
LaModel (const LaModel &theModel)
LaModel & operator= (const LaModel &theModel)
QString name () const
float population () const
QString period () const
float projection () const
float easting () const
float northing () const
bool euclideanDistance () const
bool walkingTime () const
bool pathDistance () const
float precision () const
float dietPercent () const
float plantPercent () const
float meatPercent () const
float caloriesPerPersonDaily () const
float foodValueCommonLand () const
float dairyUtilisation () const
bool baseOnPlants () const
bool includeDairy () const
bool limitDairy () const
float limitDairyPercent () const
Status fallowStatus () const
float fallowRatio () const
float caloriesFromTameMeat ()
float caloriesFromMilk (QString theAnimalGuid)
float countCrops ()
float countAnimals ()
float caloriesFromDairyProducts ()
float caloriesProvidedByTheCrop (QString theCropParameterGuid)
float caloriesProvidedByTheMeatOfTheAnimal (QString theAnimalParameterGuid)
float caloriesProvidedByTheMilkOfTheAnimal (QString theAnimalParameterGuid, QString theAnimalGuid)
float getAreaTargetsCrops (QString theCropGuid, float theProductionTarget)
float getFallowLandForACrop (QString theCropParameterGuid, float theAreaTarget)
void allocateFallowGrazingLand ()
void adjustAnimalTargetsForFodder ()
float requiredValue (QString theAnimalGuid)
float adjustAreaTargetsCrops ()
float doTheFallowAllocation (Priority, float, float)
QMap< QString, float > animalCalorieTargetsMap () const
QMap< QString, float > animalFeedRequirementsMap () const
QMap< QString, float > animalProductionTargetsMap () const
QMap< QString, float > animalAreaTargetsMap () const
QMap< QString, float > cropCalorieTargetsMap () const
QMap< QString, float > cropProductionTargetsMap () const
QMap< QString, float > cropAreaTargetsMap () const
QMap< QString, QString > calcsCropsMap ()
QMap< QString, QString > calcsAnimalsMap ()
QString reportForAnimal (QString theAnimalGuid)
QString reportForCrop (QString theCropGuid)
QMap< QString, float > getAreaTargetsAnimalsMap ()
QMap< QString, float > getAreaTargetsCropsMap ()
void setName (QString theName)
void setPopulation (float thePopulation)
void setPeriod (QString thePeriod)
void setProjection (float theIndex)
void setEasting (float theEasting)
void setNorthing (float theNorthing)
void setEuclideanDistance (bool theBool)
void setWalkingTime (bool theBool)
void setPathDistance (bool theBool)
void setPrecision (float thePrecision)
void setDietPercent (float theDietPercent)
void setCropPercent (float theDietPercent)
void setMeatPercent (float theMeatPercent)
void setCaloriesPerPersonDaily (float theCaloriesPerPersonDaily)
void setDairyUtilisation (float thePercent)
void setBaseOnPlants (bool theBool)
void setIncludeDairy (bool theBool)
void setLimitDairy (bool theBool)
void setLimitDairyPercent (float thePercent)
void setCommonLandValue (float theValue, AreaUnits theAreaUnits)
void setCommonLandAreaUnits (AreaUnits theAreaUnits)
void setHerdSize (QString theAnimalGuid)
void setAnimals (QMap< QString, QString >)
void setCrops (QMap< QString, QString >)
LaDietLabels doCalcsPlantsFirstIncludeDairy ()
LaDietLabels doCalcsPlantsFirstDairySeperate ()
LaDietLabels doCalcsAnimalsFirstIncludeDiary ()
LaDietLabels doCalcsAnimalsFirstDairySeparate ()
QMap< QString, float > getAreaTargetsAnimalsMapAFID ()
QMap< QString, float > getAreaTargetsAnimalsMapAFDS ()
QMap< QString, float > getAreaTargetsAnimalsMapPFDS ()
QMap< QString, float > getAreaTargetsAnimalsMapPFID ()
QMap< QString, float > getAreaTargetsCropsMapAFID ()
QMap< QString, float > getAreaTargetsCropsMapAFDS ()
QMap< QString, float > getAreaTargetsCropsMapPFDS ()
QMap< QString, float > getAreaTargetsCropsMapPFID ()
float countCaloriesForAnimals ()
void setFallowStatus (Status theStatus)
void setFallowRatio (float theRatio)
QString toXml ()
QString toHtmlCalorieAnimalTargets ()
QString toHtmlCalorieCropTargets ()
QString toHtmlProductionAnimalTargets ()
QString toHtmlAreaCropTargets ()
QString toHtmlAreaAnimalTargets ()
QString toHtmlProductionCropTargets ()
QString toText ()
QString toHtml ()
bool fromXml (const QString theXml)
void logMessage (QString theMessage)
Private Member Functions
void initialiseCaloriesProvidedByMeatMap ()
void initialiseCaloriesProvidedByMilkMap ()
void initialiseCaloriesProvidedByCropsMap ()
void initialiseProductionRequiredAnimalsMap ()
void initialiseProductionRequiredCropsMap ()
void initialiseAreaTargetsAnimalsMap ()
void initialiseCalcsAnimalsMap ()
void initialiseCalcsCropsMap ()
void initialiseAreaTargetsCropsMap ()
void initialiseValueMap ()
void initialiseFodderMap ()
Private Attributes
QMap< QString, float > mCaloriesProvidedByMeatMap
QMap< QString, float > mCaloriesProvidedByMilkMap
QMap< QString, float > mCaloriesProvidedByCropsMap
QMap< QString, float > mProductionRequiredAnimalsMap
QMap< QString, float > mProductionRequiredCropsMap
QMap< QString, float > mAreaTargetsAnimalsMap
QMap< QString, float > mAreaTargetsCropsMap
QMap< QString, float > mValueMap
QMap< QString, LaFoodSourceMap > mFodderMap
QMap< QString, QString > mCalcsAnimalsMap
QMap< QString, QString > mCalcsCropsMap
QString mName
float mPopulation
QString mPeriod
float mProjection
float mEasting
float mNorthing
bool mEuclideanDistance
bool mWalkingTime
bool mPathDistance
float mPrecision
float mDietPercent
float mPercentOfDietThatIsFromCrops
float mMeatPercent
float mCaloriesPerPersonDaily
float mDairyUtilisation
float mBaseOnPlants
bool mIncludeDairy
float mLimitDairy
float mLimitDairyPercentage
QMap< QString, QString > mAnimalsMap
QMap< QString, QString > mCropsMap
AreaUnits mCommonLandAreaUnits
Status mFallowStatus
float mFallowRatio
float mCommonGrazingLandValueTarget
float mCommonGrazingValue
float mCommonGrazingLandAreaTarget
float mCommonCropLand
HerdSize mHerdSize
Detailed Description
A class to represent a model
Author:
Tim Sutton, Jason Jorgenson
Definition at line 40 of file lamodel.h.
Constructor & Destructor Documentation
LaModel::LaModel ()
Constructor .
Definition at line 42 of file lamodel.cpp.
References mCaloriesPerPersonDaily, mDietPercent, mMeatPercent, mName, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, and LaGuid::setGuid().
                 : QObject(),  LaSerialisable(), LaGuid()
{
  setGuid();
  mName="No Name Set";
  mPopulation=500;
  mPeriod="No Period Set";
  mProjection=100;
  mPrecision=5;
  mDietPercent=25;
  mPercentOfDietThatIsFromCrops=10;
  mMeatPercent=10;
  mCaloriesPerPersonDaily=2500;
}
LaModel::~LaModel ()
Desctructor .
Definition at line 55 of file lamodel.cpp.
{
}
LaModel::LaModel (const LaModel & theModel)
copy constructor
Definition at line 61 of file lamodel.cpp.
References baseOnPlants(), caloriesPerPersonDaily(), dairyUtilisation(), dietPercent(), easting(), euclideanDistance(), fallowRatio(), fallowStatus(), LaGuid::guid(), includeDairy(), limitDairy(), limitDairyPercent(), mBaseOnPlants, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, mEasting, meatPercent(), mEuclideanDistance, mFallowRatio, mFallowStatus, mIncludeDairy, mLimitDairy, mLimitDairyPercentage, mMeatPercent, mName, mNorthing, mPathDistance, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, mWalkingTime, name(), northing(), pathDistance(), period(), plantPercent(), population(), precision(), projection(), LaGuid::setGuid(), and walkingTime().
{
  mName=theModel.name();
  mPopulation=theModel.population();
  setGuid(theModel.guid());
  mPeriod=theModel.period();
  mProjection=theModel.projection();
  mEasting=theModel.easting();
  mNorthing=theModel.northing();
  mEuclideanDistance=theModel.euclideanDistance();
  mWalkingTime=theModel.walkingTime();
  mPathDistance=theModel.pathDistance();
  mPrecision=theModel.precision();
  mDietPercent=theModel.dietPercent();
  mPercentOfDietThatIsFromCrops=theModel.plantPercent();
  mMeatPercent=theModel.meatPercent();
  mCaloriesPerPersonDaily=theModel.caloriesPerPersonDaily();
  mDairyUtilisation=theModel.dairyUtilisation();
  mBaseOnPlants=theModel.baseOnPlants();
  mIncludeDairy=theModel.includeDairy();
  mLimitDairy=theModel.limitDairy();
  mLimitDairyPercentage=theModel.limitDairyPercent();
  mFallowStatus=theModel.fallowStatus();
  mFallowRatio=theModel.fallowRatio();
}
Member Function Documentation
LaModel & LaModel::operator= (const LaModel & theModel)
Assignement operator
Definition at line 87 of file lamodel.cpp.
References baseOnPlants(), caloriesPerPersonDaily(), dairyUtilisation(), dietPercent(), easting(), euclideanDistance(), fallowRatio(), fallowStatus(), LaGuid::guid(), includeDairy(), limitDairy(), limitDairyPercent(), mBaseOnPlants, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, mEasting, meatPercent(), mEuclideanDistance, mFallowRatio, mFallowStatus, mIncludeDairy, mLimitDairy, mLimitDairyPercentage, mMeatPercent, mName, mNorthing, mPathDistance, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, mWalkingTime, name(), northing(), pathDistance(), period(), plantPercent(), population(), precision(), projection(), LaGuid::setGuid(), and walkingTime().
{
  if (this == &theModel) return *this; // Gracefully handle self assignment
  mName=theModel.name();
  mPopulation=theModel.population();
  setGuid(theModel.guid());
  mPeriod=theModel.period();
  mProjection=theModel.projection();
  mEasting=theModel.easting();
  mNorthing=theModel.northing();
  mEuclideanDistance=theModel.euclideanDistance();
  mWalkingTime=theModel.walkingTime();
  mPathDistance=theModel.pathDistance();
  mPrecision=theModel.precision();
  mDietPercent=theModel.dietPercent();
  mPercentOfDietThatIsFromCrops=theModel.plantPercent();
  mMeatPercent=theModel.meatPercent();
  mCaloriesPerPersonDaily=theModel.caloriesPerPersonDaily();
  mDairyUtilisation=theModel.dairyUtilisation();
  mBaseOnPlants=theModel.baseOnPlants();
  mIncludeDairy=theModel.includeDairy();
  mLimitDairy=theModel.limitDairy();
  mLimitDairyPercentage=theModel.limitDairyPercent();
  mFallowStatus=theModel.fallowStatus();
  mFallowRatio=theModel.fallowRatio();
  return *this;
}
QString LaModel::name () const
The name of this model
Definition at line 116 of file lamodel.cpp.
References mName.
Referenced by LaModel(), and operator=().
{ return mName;}
float LaModel::population () const
The population of this model
Definition at line 118 of file lamodel.cpp.
References mPopulation.
Referenced by LaModel(), and operator=().
{ return mPopulation;}
QString LaModel::period () const
Term for the period or time of the analysis e.g. Chalcolithic
Definition at line 117 of file lamodel.cpp.
References mPeriod.
Referenced by LaModel(), and operator=().
{ return mPeriod;}
float LaModel::projection () const
What coordinate system being used
Definition at line 119 of file lamodel.cpp.
References mProjection.
Referenced by LaModel(), and operator=().
{ return mProjection;}
float LaModel::easting () const
East coordinates
Definition at line 120 of file lamodel.cpp.
References mEasting.
Referenced by LaModel(), and operator=().
{ return mEasting;}
float LaModel::northing () const
North coordinates
Definition at line 121 of file lamodel.cpp.
References mNorthing.
Referenced by LaModel(), and operator=().
{ return mNorthing;}
bool LaModel::euclideanDistance () const
euclidean Distance selected
Definition at line 122 of file lamodel.cpp.
References mEuclideanDistance.
Referenced by LaModel(), and operator=().
{ return mEuclideanDistance;}
bool LaModel::walkingTime () const
swalkingTime elected
Definition at line 123 of file lamodel.cpp.
References mWalkingTime.
Referenced by LaModel(), and operator=().
{ return mWalkingTime;}
bool LaModel::pathDistance () const
pathDistance selected
Definition at line 124 of file lamodel.cpp.
References mPathDistance.
Referenced by LaModel(), and operator=().
{ return mPathDistance;}
float LaModel::precision () const
The precision of the land area calculations
Definition at line 125 of file lamodel.cpp.
References mPrecision.
Referenced by LaModel(), and operator=().
{ return mPrecision;}
float LaModel::dietPercent () const
what percent of the diet comes from Meat
Definition at line 126 of file lamodel.cpp.
References mDietPercent.
Referenced by LaModel(), and operator=().
{ return mDietPercent;}
float LaModel::plantPercent () const
what percent of the diet comes from crops
Definition at line 127 of file lamodel.cpp.
References mPercentOfDietThatIsFromCrops.
Referenced by LaModel(), and operator=().
        {
          if (mPercentOfDietThatIsFromCrops < 0) {return 0;}
          else if (mPercentOfDietThatIsFromCrops > 100) {return 100;}
          else {return mPercentOfDietThatIsFromCrops;}
        }
float LaModel::meatPercent () const
what percent of the diet comes from meat
Definition at line 133 of file lamodel.cpp.
References mMeatPercent.
Referenced by LaModel(), and operator=().
{ return mMeatPercent; }
float LaModel::caloriesPerPersonDaily () const
TCalories per person per day
Definition at line 135 of file lamodel.cpp.
References mCaloriesPerPersonDaily.
Referenced by LaModel(), and operator=().
{ return mCaloriesPerPersonDaily;}
float LaModel::foodValueCommonLand () const
Food Value of the common grazing land
Definition at line 140 of file lamodel.cpp.
References mCommonGrazingValue.
{ return mCommonGrazingValue;}
float LaModel::dairyUtilisation () const
Dairy Utilisation
Definition at line 134 of file lamodel.cpp.
References mDairyUtilisation.
Referenced by LaModel(), and operator=().
{ return mDairyUtilisation;}
bool LaModel::baseOnPlants () const
a bool to indicate whether the diet ratios will be based on plants or animals. If te bool is TRUE it is based on plants
Definition at line 136 of file lamodel.cpp.
References mBaseOnPlants.
Referenced by LaModel(), and operator=().
{ return mBaseOnPlants;}
bool LaModel::includeDairy () const
this bool, if true, will consider dairy as part of meat when doing the diet calculations
Definition at line 137 of file lamodel.cpp.
References mIncludeDairy.
Referenced by LaModel(), and operator=().
{ return mIncludeDairy;}
bool LaModel::limitDairy () const
this bool will impose an overall limit on the portion of the diet that can be based on dairy products
Definition at line 138 of file lamodel.cpp.
References mLimitDairy.
Referenced by LaModel(), and operator=().
{ return mLimitDairy;}
float LaModel::limitDairyPercent () const
this is the maximum percent of the diet that dairy products can be includeDairy()
Definition at line 139 of file lamodel.cpp.
References mLimitDairyPercentage.
Referenced by LaModel(), and operator=().
{ return mLimitDairyPercentage;}
Status LaModel::fallowStatus () const
animals can be assigned an access to fallow grazing land from 0 to 3,, 0 being not allowed to graze, and then a three levels of preference
Definition at line 189 of file lamodel.cpp.
References mFallowStatus.
Referenced by LaModel(), and operator=().
{
  return mFallowStatus;
}
float LaModel::fallowRatio () const
the ratio of sown land to fallow land
Definition at line 194 of file lamodel.cpp.
References mFallowRatio.
Referenced by LaModel(), and operator=().
{
  return mFallowRatio;
}
float LaModel::caloriesFromTameMeat ()
this calculates how many calories will come from tame meat
float LaModel::caloriesFromMilk (QString theAnimalGuid)
this calculates how many calories will come from mailk products
float LaModel::countCrops ()
this returns the number of different crops being modeled
float LaModel::countAnimals ()
this returns the number of different animals being modelled
float LaModel::caloriesFromDairyProducts ()
this returns the calories from dairy produced by the herd of an animal
float LaModel::caloriesProvidedByTheCrop (QString theCropParameterGuid)
holder
float LaModel::caloriesProvidedByTheMeatOfTheAnimal (QString theAnimalParameterGuid)
holder
float LaModel::caloriesProvidedByTheMilkOfTheAnimal (QString theAnimalParameterGuid, QString theAnimalGuid)
holder
float LaModel::getAreaTargetsCrops (QString theCropGuid, float theProductionTarget)
holder holder holder
float LaModel::getFallowLandForACrop (QString theCropParameterGuid, float theAreaTarget)
holder
void LaModel::allocateFallowGrazingLand ()
holder
Definition at line 254 of file lamodel.cpp.
References LaCropParameter::areaUnits(), LaCrop::areaUnits(), LaUtils::convertAreaToHectares(), LaCrop::cropCalories(), LaCrop::cropYield(), doTheFallowAllocation(), LaCropParameter::fallowRatio(), LaAnimalParameter::fallowUsage(), LaCropParameter::fallowValue(), LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaUtils::getCrop(), LaUtils::getCropParameter(), High, logMessage(), Low, mAnimalsMap, mCropsMap, Medium, None, LaCropParameter::percentTameCrop(), and requiredValue().
{
  logMessage("method ==> void LaModel::allocateFallowGrazingLand()");
    // We need to divide the available fallow land amongst the animals
    // that graze fallow. We split the animal breeds by fallow land
    // access priority (high / medium and low priority).
    // e.g. We have 10 animal breeds, 6 of which graze fallow,
    // caw and horse are high priority, shee and pig medium,
    // chicken and gooxe low.
  float myHighPriorityCount=0, myMediumPriorityCount=0, myLowPriorityCount=0;
  float myHighPriorityValue=0;
  float myMediumPriorityValue=0;
  float myLowPriorityValue=0;
    // put starting caloric requirements of all used animals floato a map
    // for reduction due to grazing of fallow crop land
    // initialiseValueMap();
  float myTotalFallowValue=0;
    // Count the Animals in each Priority Level and sum their calorie requirements
  QMapIterator<QString, QString > myAnimalIterator(mAnimalsMap);
  while (myAnimalIterator.hasNext())
  {
    myAnimalIterator.next();
    QString myAnimalGuid = myAnimalIterator.key();
    QString myAnimalParameterGuid = myAnimalIterator.value();
    LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
    LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
    switch (myAnimalParameter.fallowUsage())
    {
      case  High:
            myHighPriorityCount++;
            myHighPriorityValue += requiredValue(myAnimalGuid);
            break;
      case  Medium:
            myMediumPriorityCount++;
            myMediumPriorityValue += requiredValue(myAnimalGuid);
            break;
      case  Low:
            myLowPriorityCount++;
            myLowPriorityValue += requiredValue(myAnimalGuid);
            break;
      case  None:
            break;
      default:
            break;
    }   //switch
  }   //while animal count
  logMessage("High Priority Animals: " + QString::number(myHighPriorityCount).toLocal8Bit() );
  logMessage("Medium Priority Animals: " + QString::number(myMediumPriorityCount).toLocal8Bit() );
  logMessage("Low Priority Animals: " + QString::number(myLowPriorityCount).toLocal8Bit() );
  logMessage("High Priority Animal Calorie requirements: " + QString::number(myHighPriorityValue).toLocal8Bit() );
  logMessage("Medium Priority Animal Calorie requirements: " + QString::number(myMediumPriorityValue).toLocal8Bit() );
  logMessage("Low Priority Animal Calorie requirements: " + QString::number(myLowPriorityValue).toLocal8Bit() );
    //  iterate through crops to determine the total calories available to animals
    //  by grazing fallow crop land
  QMapIterator<QString, QString > myCropIterator(mCropsMap);
  while (myCropIterator.hasNext())
  {
    myCropIterator.next();
    QString myCropGuid = myCropIterator.key();
    QString myCropParameterGuid = myCropIterator.value();
    LaCrop myCrop = LaUtils::getCrop(myCropGuid);
    LaCropParameter myCropParameter = LaUtils::getCropParameter(myCropParameterGuid);
    float myCropPercent = 0.01 * myCropParameter.percentTameCrop();
    float myCropCalorieTarget = /*caloriesFromCrops()*/  myCropPercent;   // already kcalories
    float myCropProductionTarget = myCropCalorieTarget / (myCrop.cropCalories()/1000.);
    AreaUnits myCropAreaUnits = myCrop.areaUnits();
    float myCropYield = LaUtils::convertAreaToHectares(myCropAreaUnits, static_cast<float> (myCrop.cropYield()));
      //QString myCropParameterGuid = mCropsMap.value(theCropGuid);
      //LaCropParameter myCropParameter = LaUtils::getCropParameter(myCropParameterGuid);
    float myFallowRatio = myCropParameter.fallowRatio();
    float myFallowArea = (myCropProductionTarget / myCropYield) * myFallowRatio;
    AreaUnits myFallowAreaUnits = myCropParameter.areaUnits();
    float myFallowValueBefore = myCropParameter.fallowValue();
    float myFallowValue = LaUtils::convertAreaToHectares(myFallowAreaUnits, myFallowValueBefore);
    float myAvailableFallowValue = myFallowRatio * myFallowArea * myFallowValue;
    myTotalFallowValue += static_cast<float>(myAvailableFallowValue);
  }   // while crop iterator
  logMessage("Total Available Fallow Calories before adjustments: " + QString::number(myTotalFallowValue).toLocal8Bit());
    // The following three if statements process all of the animals which
    // utilize fallow cropland as grazing land.  It first checks that there
    // is fallow land available, and next allocates the the fallow based on
    // the animals fallow access priority
    // HIGH priority animals get allocated fallow cropland
  if (myTotalFallowValue > 0)
  {
    Priority myPriority = High;
    float myLeftoverCalories = doTheFallowAllocation(myPriority, myTotalFallowValue, myHighPriorityValue);
    logMessage("Remaining Fallow Calories after HIGH adjustments: " + QString::number(myLeftoverCalories).toLocal8Bit());
    myTotalFallowValue = myLeftoverCalories;
  }
    // MEDIUM priority animals get allocated fallow cropland
  if (myTotalFallowValue > 0)
  {
    Priority myPriority = Medium;
    float myLeftoverCalories = doTheFallowAllocation(myPriority, myTotalFallowValue, myMediumPriorityValue);
    logMessage("Remaining Fallow Calories after MED adjustments: " + QString::number(myLeftoverCalories).toLocal8Bit());
    myTotalFallowValue = myLeftoverCalories;
  }
    // LOW priority animals get allocated fallow cropland
  if (myTotalFallowValue > 0)
  {
    Priority myPriority = Low;
    float myLeftoverCalories = doTheFallowAllocation(myPriority, myTotalFallowValue, myLowPriorityValue);
    logMessage("Remaining Fallow Calories after LOW adjustments: " + QString::number(myLeftoverCalories).toLocal8Bit());
    myTotalFallowValue = myLeftoverCalories;
  }
    //float myReturnValue = static_cast<float>(myTotalFallowValue);
    //return myReturnValue;
}
void LaModel::adjustAnimalTargetsForFodder ()
holder
float LaModel::requiredValue (QString theAnimalGuid)
holder
Definition at line 198 of file lamodel.cpp.
References LaAnimal::breedingExpectancy(), LaAnimal::deathRate(), LaAnimal::estrousCycle(), LaAnimal::gestating(), LaAnimal::gestationTime(), LaUtils::getAnimal(), LaAnimal::juvenile(), LaAnimal::killWeight(), logMessage(), mCaloriesProvidedByMeatMap, LaAnimal::meatFoodValue(), LaAnimal::name(), LaAnimal::usableMeat(), LaAnimal::weaningAge(), and LaAnimal::youngPerBirth().
Referenced by allocateFallowGrazingLand().
{   // this is the generic animal model
  LaAnimal myAnimal = LaUtils::getAnimal(theAnimalGuid);
  float myAnimalProductionTarget;// = getProductionTargetsAnimals (theAnimalGuid, static_cast <float> (mCaloriesProvidedByMeatMap.value (theAnimalGuid)));
  float myAnimalsRequired=(myAnimalProductionTarget / myAnimal.killWeight()) / (myAnimal.usableMeat()*.01);
  float myBirthsPerYear = 365.0 / (myAnimal.gestationTime() + myAnimal.estrousCycle() + myAnimal.weaningAge());
  float myOffspringPerMotherYearly = myBirthsPerYear * myAnimal.youngPerBirth() * (1.0-(0.01*myAnimal.deathRate()));
  float myMothersNeededStepOne = myAnimalsRequired/myOffspringPerMotherYearly;
  float myMalesStepOne = (myMothersNeededStepOne * myOffspringPerMotherYearly)/2.;
  float myFemalesStepOne = myMalesStepOne;
  float myMotherReplacementsPerYear = myMothersNeededStepOne/myAnimal.breedingExpectancy();
  float myAdditionalMothers = (myMotherReplacementsPerYear/myOffspringPerMotherYearly)*2.;
  float myMalesStepTwo = (myAdditionalMothers*myOffspringPerMotherYearly)/2.;
  float myFemalesStepTwo = (myAdditionalMothers*myOffspringPerMotherYearly)/2.;
  float myTotalMothers = myMothersNeededStepOne+myAdditionalMothers;
  float myTotalMales = myMalesStepOne+myMalesStepTwo;
  float myTotalFemales = myFemalesStepOne-myFemalesStepTwo;
  float myTotalJuveniles = myTotalMales+myTotalFemales;
  float myTotalMothersValueRequired = myTotalMothers * myAnimal.gestating();
  float myTotalJuvenilesValueRequired = myTotalJuveniles * myAnimal.juvenile();
  float myValueNeededToFeedAnimals = myTotalMothersValueRequired + myTotalJuvenilesValueRequired;
  float myReturnValue = static_cast<float>(myValueNeededToFeedAnimals);
    // log report
  logMessage("method ==> float LaModel::requiredValue(QString theAnimalGuid)");
  logMessage("animal prodn target = calorie target of animal / food value");
  logMessage("mCaloriesProvidedByMeatMap.value(theAnimalGuid): " + QString::number(mCaloriesProvidedByMeatMap.value(theAnimalGuid)).toLocal8Bit());
  logMessage("myAnimal.meatFoodValue(): " + QString::number(myAnimal.meatFoodValue()/1000.).toLocal8Bit());
  logMessage("myAnimalProductionTarget = " + QString::number(myAnimalProductionTarget).toLocal8Bit());
  logMessage("slaughter animals reqd: " + QString::number(myAnimalsRequired).toLocal8Bit());
  logMessage("BirthEventsPerYear: " + QString::number(myBirthsPerYear).toLocal8Bit());
  logMessage("OffspringPerMotherYearly = " + QString::number(myOffspringPerMotherYearly).toLocal8Bit());
  logMessage("MothersNeededStepOne = " + QString::number(myMothersNeededStepOne).toLocal8Bit());
  logMessage("MalesStepOne = " + QString::number(myMalesStepOne).toLocal8Bit());
  logMessage("FemalesStepOne = " + QString::number(myFemalesStepOne).toLocal8Bit());
  logMessage("MotherReplacementsPerYear = " + QString::number(myMotherReplacementsPerYear).toLocal8Bit());
  logMessage("AdditionalMothers = " + QString::number(myAdditionalMothers).toLocal8Bit());
  logMessage("MalesStepTwo = " + QString::number(myMalesStepTwo).toLocal8Bit());
  logMessage("FemalesStepTwo = " + QString::number(myFemalesStepTwo).toLocal8Bit());
  logMessage("TotalMothers = " + QString::number(myTotalMothers).toLocal8Bit());
  logMessage("TotalMales = " + QString::number(myTotalMales).toLocal8Bit());
  logMessage("TotalFemales = " + QString::number(myTotalFemales).toLocal8Bit());
  logMessage("TotalJuveniles = " + QString::number(myTotalJuveniles).toLocal8Bit());
  logMessage("Total Adult Females Value(Kg) = " + QString::number (myTotalMothersValueRequired).toLocal8Bit());
  logMessage("Total Juveniles Value(Kg) = " + QString::number (myTotalJuvenilesValueRequired).toLocal8Bit());
  logMessage("Total Value (Kg) Needed To Feed Animals = " + QString::number(myValueNeededToFeedAnimals).toLocal8Bit());
  logMessage("method ==> float LaModel::requiredValue(QString theAnimalGuid)");
  logMessage("Animal: " + myAnimal.name().toLocal8Bit());
  logMessage("Breeding Stock: " + QString::number(myTotalMothers).toLocal8Bit());
  logMessage("Juveniles: " + QString::number(myTotalJuveniles).toLocal8Bit());
  logMessage("Kg Value needed annually to feed the entire herd: " +
      QString::number(myReturnValue).toLocal8Bit());
  logMessage("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
  return myReturnValue;
}
float LaModel::adjustAreaTargetsCrops ()
holder
float LaModel::doTheFallowAllocation (Priority thePriority, float theAvailableFallowValue, float theValueNeeded)
holder
Definition at line 387 of file lamodel.cpp.
References LaAnimalParameter::fallowUsage(), LaUtils::getAnimal(), LaUtils::getAnimalParameter(), logMessage(), mAnimalsMap, MoreThanEnoughToCompletelySatisfy, mValueMap, LaAnimal::name(), and NotEnoughToCompletelySatisfy.
Referenced by allocateFallowGrazingLand().
{
  qDebug() << "Value Map: " << mValueMap;
    // when the total number of calories needed by the animals
    // is taken away from the total available calories (from crop fallow),
    // there will be one of two results.
    // 1. the result will be <=0, meaning that additional sources of
    //    food is required for the animals.  (fodder or grazing land)
    // 2. the result will be > 0, meaning that there is enough food value
    //    in the crop fallow to completely feed the animals.
  float myTotalFallowValue = theAvailableFallowValue - theValueNeeded;
  qDebug() << "myTotalFallowValue: "  << myTotalFallowValue;
    // set up the conditions for the fallow allocation...
    // there is either enough fallow to feed the animal completely
    // or not enough to feed them completely.  If there is enough,
    // the animal will not be requiring any additional source of
    // calories.  In other words, we won't be needing to graze them
    // on any other land besides the crop fallow.
  Status myFallowStatus;
  myFallowStatus = (myTotalFallowValue > 0) ? MoreThanEnoughToCompletelySatisfy : NotEnoughToCompletelySatisfy;
  QString myFallowStatusString = (myFallowStatus!=NotEnoughToCompletelySatisfy) ? "More than Enough" : "Not Enough";
  logMessage("Fallow Status: " + myFallowStatusString);
  qDebug () << "FallowStatus: " << myFallowStatus;
  switch (myFallowStatus)
  {
    case  MoreThanEnoughToCompletelySatisfy:
          {
            logMessage("MoreThanEnoughToCompletelySatisfy");
              // because there is leftover calories available to feed more critters, this
              // shows that all of the animals caloric requirements are met with crop fallow
              // and require no more feed so their values in the QMap will be set to 0
            QMapIterator<QString, QString > myAnimalIterator(mAnimalsMap);
            while (myAnimalIterator.hasNext())
            {
              myAnimalIterator.next();
              QString myAnimalGuid = myAnimalIterator.key();
              QString myAnimalParameterGuid = myAnimalIterator.value();
              LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
              LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
              if (myAnimalParameter.fallowUsage()==thePriority)
              {
                mValueMap[myAnimalGuid] = 0;
              }   //endif (fallowUsage(myAnimalGuid)
             }   // while animal iterating
               // myTotalFallowValue += theValueNeeded;
             break;
          }
    case  NotEnoughToCompletelySatisfy:
          {
            logMessage("CASE: NotEnoughToCompletelySatisfy");
              // because there ARE NO leftover Value available to feed more critters, this
              // shows that NOT ALL of the animals requirements are met with crop fallow
              // and therefore require more feed so their values in the QMap will be adjusted
            QMapIterator<QString, QString > myAnimalIterator(mAnimalsMap);
            while (myAnimalIterator.hasNext())
            {
              myAnimalIterator.next();
              logMessage("    Iterating through Animals looking for a match");
              QString myAnimalGuid = myAnimalIterator.key();
              QString myAnimalParameterGuid = myAnimalIterator.value();
              LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
              LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
              float myCurrentAnimalsValue = mValueMap.value( myAnimalGuid );
              logMessage("       Current Animal: " + myAnimal.name());
              qDebug() << "        theValueNeeded: " << theValueNeeded;
              qDebug() << "        theAvailableFallowValue: " << theAvailableFallowValue;
              qDebug() << "        myCurrentAnimalsValue: " << myCurrentAnimalsValue;
              if (myAnimalParameter.fallowUsage()==thePriority)
              {
                double myAllottedValue = ((myCurrentAnimalsValue / static_cast<float>(theValueNeeded)) * theAvailableFallowValue);
                logMessage("Adjusting calories required by: " + myAnimal.name());
                qDebug() << "myAllottedValue: " << myAllottedValue;
                logMessage("Allotted Value from fallow are: " + QString::number(myAllottedValue));
                logMessage("Original Value target was: " + QString::number(mValueMap.value(myAnimalGuid)));
                float myNewValueTarget = mValueMap.value(myAnimalGuid) - myAllottedValue;
                logMessage("New Value target is: " + QString::number(myNewValueTarget));
                mValueMap [myAnimalGuid] = static_cast<float>(myNewValueTarget);
                myTotalFallowValue += static_cast<float>(myAllottedValue);
              }   // endif (fallowUsage(myAnimalGuid)==High)
            }   // while animal iterating
            logMessage("After allocation, total available Value from fallow: " + QString::number(myTotalFallowValue).toLocal8Bit());
            myTotalFallowValue = 0;
            logMessage("WHICH HAS NOW BEEN SET TO 0");
            break;
          }
    default:
          break;
  }   //switch
  return static_cast<float>(myTotalFallowValue);
}
QMap< QString, float > LaModel::animalCalorieTargetsMap () const
holder holder
Definition at line 141 of file lamodel.cpp.
References mCaloriesProvidedByMeatMap.
{ return mCaloriesProvidedByMeatMap; }
QMap< QString, float > LaModel::animalFeedRequirementsMap () const
holder
Definition at line 142 of file lamodel.cpp.
References mValueMap.
{ return mValueMap;}
QMap< QString, float > LaModel::animalProductionTargetsMap () const
holder
Definition at line 143 of file lamodel.cpp.
References mProductionRequiredAnimalsMap.
{ return mProductionRequiredAnimalsMap;}
QMap< QString, float > LaModel::animalAreaTargetsMap () const
holder
Definition at line 144 of file lamodel.cpp.
References mAreaTargetsAnimalsMap.
                      { return mAreaTargetsAnimalsMap; }
QMap< QString, float > LaModel::cropCalorieTargetsMap () const
holder
Definition at line 146 of file lamodel.cpp.
References mCaloriesProvidedByCropsMap.
                      { return mCaloriesProvidedByCropsMap;}
QMap< QString, float > LaModel::cropProductionTargetsMap () const
holder
Definition at line 148 of file lamodel.cpp.
References mProductionRequiredCropsMap.
                      { return mProductionRequiredCropsMap;}
QMap< QString, float > LaModel::cropAreaTargetsMap () const
holder
Definition at line 150 of file lamodel.cpp.
References mAreaTargetsCropsMap.
                      { return mAreaTargetsCropsMap; }
QMap< QString, QString > LaModel::calcsCropsMap ()
holder
Definition at line 154 of file lamodel.cpp.
References mCalcsCropsMap.
Referenced by LaMainForm::cropCalcClicked().
                        { return mCalcsCropsMap; }
QMap< QString, QString > LaModel::calcsAnimalsMap ()
holder
Definition at line 152 of file lamodel.cpp.
References mCalcsAnimalsMap.
Referenced by LaMainForm::animalCalcClicked().
                        { return mCalcsAnimalsMap; }
QString LaModel::reportForAnimal (QString theAnimalGuid)
holder
QString LaModel::reportForCrop (QString theCropGuid)
holder
QMap< QString, float > LaModel::getAreaTargetsAnimalsMap ()
holder
Definition at line 1404 of file lamodel.cpp.
References mAreaTargetsAnimalsMap.
{
  return mAreaTargetsAnimalsMap;
}
QMap< QString, float > LaModel::getAreaTargetsCropsMap ()
holder
Definition at line 1409 of file lamodel.cpp.
References mAreaTargetsCropsMap.
{
  return mAreaTargetsCropsMap;
}
void LaModel::setName (QString theName)
holder Set the modelName
See also:
name()
Definition at line 158 of file lamodel.cpp.
References mName.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mName=theName; }
void LaModel::setPopulation (float thePopulation)
Set the model population
See also:
population()
Definition at line 159 of file lamodel.cpp.
References mPopulation.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mPopulation=thePopulation; }
void LaModel::setPeriod (QString thePeriod)
Set period of site being studied
See also:
period()
Definition at line 160 of file lamodel.cpp.
References mPeriod.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mPeriod=thePeriod; }
void LaModel::setProjection (float theIndex)
Set projection
See also:
projection()
Definition at line 161 of file lamodel.cpp.
References mProjection.
{ mProjection=theIndex;}
void LaModel::setEasting (float theEasting)
Set the easting
See also:
easting()
Definition at line 162 of file lamodel.cpp.
References mEasting.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mEasting=theEasting; }
void LaModel::setNorthing (float theNorthing)
Set the northing
See also:
northing()
Definition at line 163 of file lamodel.cpp.
References mNorthing.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mNorthing=theNorthing; }
void LaModel::setEuclideanDistance (bool theBool)
Set method of analysis to euclideanDistance
See also:
euclideanDistance()
Definition at line 164 of file lamodel.cpp.
References mEuclideanDistance.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mEuclideanDistance=theBool;}
void LaModel::setWalkingTime (bool theBool)
Set method of analysis to walkingTime
See also:
Period()
Definition at line 165 of file lamodel.cpp.
References mWalkingTime.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mWalkingTime=theBool;}
void LaModel::setPathDistance (bool theBool)
Set method of analysis to pathDistance
See also:
pathDistance()
Definition at line 166 of file lamodel.cpp.
References mPathDistance.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mPathDistance=theBool; }
void LaModel::setPrecision (float thePrecision)
Set mmodel's precision
See also:
precision()
Definition at line 167 of file lamodel.cpp.
References mPrecision.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mPrecision=thePrecision*.01; }
void LaModel::setDietPercent (float theDietPercent)
Set the overall percent that Plants form, for the entire population's diet
See also:
dietPercent()
Definition at line 168 of file lamodel.cpp.
References mDietPercent.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mDietPercent=thePercent*.01; }
void LaModel::setCropPercent (float theDietPercent)
Set the percent of TAME Plants, of the Plant based portion of the diet
See also:
plantPercent()
Definition at line 169 of file lamodel.cpp.
References mPercentOfDietThatIsFromCrops.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
     { mPercentOfDietThatIsFromCrops = thePercent * .01; }
void LaModel::setMeatPercent (float theMeatPercent)
Set the meatPercent in weeks
See also:
meatPercent()
Definition at line 171 of file lamodel.cpp.
References mMeatPercent.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mMeatPercent=thePercent*.01; }
void LaModel::setCaloriesPerPersonDaily (float theCaloriesPerPersonDaily)
Set the caloriesPerPersonDaily in Days
See also:
caloriesPerPersonDaily()
Definition at line 172 of file lamodel.cpp.
References mCaloriesPerPersonDaily.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
     { mCaloriesPerPersonDaily = theCalories; }
void LaModel::setDairyUtilisation (float thePercent)
Set the percent of dairy utilisation
See also:
dairyUtilisation()
Definition at line 179 of file lamodel.cpp.
References mDairyUtilisation.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
     { mDairyUtilisation = thePercent * .01; }
void LaModel::setBaseOnPlants (bool theBool)
Set the holder
See also:
holder()
Definition at line 174 of file lamodel.cpp.
References mBaseOnPlants.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mBaseOnPlants=theBool; }
void LaModel::setIncludeDairy (bool theBool)
Set the holder
See also:
holder()
Definition at line 175 of file lamodel.cpp.
References mIncludeDairy.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mIncludeDairy=theBool; }
void LaModel::setLimitDairy (bool theBool)
Set the holder
See also:
holder()
Definition at line 176 of file lamodel.cpp.
References mLimitDairy.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mLimitDairy=theBool; }
void LaModel::setLimitDairyPercent (float thePercent)
Set the holder
See also:
holder()
Definition at line 177 of file lamodel.cpp.
References mLimitDairyPercentage.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
     { mLimitDairyPercentage = thePercent * .01; }
void LaModel::setCommonLandValue (float theValue, AreaUnits theAreaUnits)
Set food value of the common land
See also:
commonLandValue()
Definition at line 183 of file lamodel.cpp.
References LaUtils::convertAreaToHectares(), and mCommonGrazingValue.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
     { mCommonGrazingValue = LaUtils::convertAreaToHectares(theAreaUnits,theValue); }
void LaModel::setCommonLandAreaUnits (AreaUnits theAreaUnits)
Set the holder
See also:
holder()
Definition at line 181 of file lamodel.cpp.
References mCommonLandAreaUnits.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
     { mCommonLandAreaUnits = theAreaUnits; }
void LaModel::setHerdSize (QString theAnimalGuid)
Set the holder
See also:
holder()
void LaModel::setAnimals (QMap< QString, QString > theAnimals)
Set the animals for this model
Parameters:
QMap<QString,QString> a list of animal guid and animal parameter guids
Definition at line 185 of file lamodel.cpp.
References mAnimalsMap.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mAnimalsMap = theAnimals; }
void LaModel::setCrops (QMap< QString, QString > theCrops)
Set the crop for this model
Parameters:
QMap<QString,QString> a list of crop guid and animal parameter guids
Definition at line 186 of file lamodel.cpp.
References mCropsMap.
Referenced by LaMainForm::cropCalcClicked(), LaMainForm::on_pushButtonRun_clicked(), LaMainForm::setDietLabels(), and LaMainForm::setModel().
{ mCropsMap = theCrops; }
LaDietLabels LaModel::doCalcsPlantsFirstIncludeDairy ()
In order to do these calculations, several pieces of informations are required. They are: 1. The overall settlement calorie target 2. The Percent of the diet that Animals are responsible forget 3. How many calories the dairy products are going to supply 4. The Percent of the Animals that are domestic sources 5. The Percent of the Plants that are domestic sources (crops)
Returns:
Definition at line 502 of file lamodel.cpp.
References mCaloriesPerPersonDaily, mPopulation, LaDietLabels::setAnimalPortionPct(), LaDietLabels::setCropMCalories(), LaDietLabels::setCropsPortionPct(), LaDietLabels::setDairyMCalories(), LaDietLabels::setDairyPortionPct(), LaDietLabels::setKiloCaloriesIndividualAnnual(), LaDietLabels::setMegaCaloriesSettlementAnnual(), LaDietLabels::setPlantsPortionPct(), LaDietLabels::setTameMeatPortionPct(), LaDietLabels::setWildAnimalMCalories(), LaDietLabels::setWildAnimalPortionPct(), LaDietLabels::setWildPlantsMCalories(), and LaDietLabels::setWildPlantsPortionPct().
Referenced by LaMainForm::on_pushButtonRun_clicked(), and LaMainForm::setDietLabels().
{
  LaDietLabels myDietLabels;
    float myKiloCaloriesIndividualAnnual = mCaloriesPerPersonDaily * 365.0 * 0.001;
  float myMegaCaloriesSettlementAnnual =  (myKiloCaloriesIndividualAnnual*0.001) * mPopulation * 365.0;
  /*float myDairyUtilisation;
  float myDairyMCalories = (myDairyUtilisation) * myDairyMCalorieCounter;
  float myDairyPortionPct = myDairyMCalories / myMCaloriesSettlementAnnual;
  float myPercentOfCalorieTarget = myMCaloriesSettlementAnnual * myDietPercentMeat;
  float myAnimalCalsMinusDairyBit = myPercentOfCalorieTarget - myDairyMCalories;
  float myWildAnimalMCalories = myAnimalCalsMinusDairyBit * myWildMeatPercentage;
  float myTameAnimalMCalories = myAnimalCalsMinusDairyBit * myTameMeatPercentage;
  float myWildAnimalPortionPct = myWildAnimalMCalories / myMCaloriesSettlementAnnual;
  float myTameMeatPortionPct = myTameAnimalMCalories / myMCaloriesSettlementAnnual;
  float myPlantsPortionPct = 1. - myAnimalPortionPct;
  float myCropsPortionPct = myPlantsPortionPct * myCropPercentage;
  float myWildPlantsPortionPct = myPlantsPortionPct * myWildPlantsPercentage;
  float myCropMCalories = myMCaloriesSettlementAnnual * myCropsPortionPct;
  float myWildPlantsMCalories = myMCaloriesSettlementAnnual * myWildPlantsPortionPct;
  */
  float myDairyMCalories =1.0;
  float myCropMCalories =2.0;
  float myWildAnimalMCalories =3.0;
  float myWildPlantsMCalories =4.0;
  float myDairyPortionPct =5.0;
  float myTameMeatPortionPct =6.0;
  float myCropsPortionPct =7.0;
  float myWildAnimalPortionPct =8.0;
  float myWildPlantsPortionPct =9.0;
  float myPlantsPortionPct =10.0;
  float myAnimalPortionPct =11.0;
  myDietLabels.setDairyMCalories(myDairyMCalories);
  myDietLabels.setCropMCalories(myCropMCalories);
  myDietLabels.setWildAnimalMCalories(myWildAnimalMCalories);
  myDietLabels.setWildPlantsMCalories(myWildPlantsMCalories);
  myDietLabels.setDairyPortionPct(myDairyPortionPct*100.);
  myDietLabels.setTameMeatPortionPct(myTameMeatPortionPct*100.);
  myDietLabels.setCropsPortionPct(myCropsPortionPct*100.);
  myDietLabels.setWildAnimalPortionPct(myWildAnimalPortionPct*100.);
  myDietLabels.setWildPlantsPortionPct(myWildPlantsPortionPct*100.);
  myDietLabels.setPlantsPortionPct(myPlantsPortionPct*100.);
  myDietLabels.setAnimalPortionPct(myAnimalPortionPct*100.);
  myDietLabels.setKiloCaloriesIndividualAnnual(myKiloCaloriesIndividualAnnual);
  myDietLabels.setMegaCaloriesSettlementAnnual(myMegaCaloriesSettlementAnnual);
  return myDietLabels;
}
LaDietLabels LaModel::doCalcsPlantsFirstDairySeperate ()
Definition at line 551 of file lamodel.cpp.
References mCaloriesPerPersonDaily, mPopulation, LaDietLabels::setAnimalPortionPct(), LaDietLabels::setCropMCalories(), LaDietLabels::setCropsPortionPct(), LaDietLabels::setDairyMCalories(), LaDietLabels::setDairyPortionPct(), LaDietLabels::setKiloCaloriesIndividualAnnual(), LaDietLabels::setMegaCaloriesSettlementAnnual(), LaDietLabels::setPlantsPortionPct(), LaDietLabels::setTameMeatPortionPct(), LaDietLabels::setWildAnimalMCalories(), LaDietLabels::setWildAnimalPortionPct(), LaDietLabels::setWildPlantsMCalories(), and LaDietLabels::setWildPlantsPortionPct().
Referenced by LaMainForm::on_pushButtonRun_clicked(), and LaMainForm::setDietLabels().
{
  LaDietLabels myDietLabels;
    float myKiloCaloriesIndividualAnnual = mCaloriesPerPersonDaily * 365.0 * 0.001;
  float myMegaCaloriesSettlementAnnual =  (myKiloCaloriesIndividualAnnual*0.001) * mPopulation * 365.0;
  /*float myDairyUtilisation;
  float myDairyMCalories = (myDairyUtilisation) * myDairyMCalorieCounter;
  float myDairyPortionPct = myDairyMCalories / myMCaloriesSettlementAnnual;
  float myPercentOfCalorieTarget = myMCaloriesSettlementAnnual * myDietPercentMeat;
  float myAnimalCalsMinusDairyBit = myPercentOfCalorieTarget - myDairyMCalories;
  float myWildAnimalMCalories = myAnimalCalsMinusDairyBit * myWildMeatPercentage;
  float myTameAnimalMCalories = myAnimalCalsMinusDairyBit * myTameMeatPercentage;
  float myWildAnimalPortionPct = myWildAnimalMCalories / myMCaloriesSettlementAnnual;
  float myTameMeatPortionPct = myTameAnimalMCalories / myMCaloriesSettlementAnnual;
  float myPlantsPortionPct = 1. - myAnimalPortionPct;
  float myCropsPortionPct = myPlantsPortionPct * myCropPercentage;
  float myWildPlantsPortionPct = myPlantsPortionPct * myWildPlantsPercentage;
  float myCropMCalories = myMCaloriesSettlementAnnual * myCropsPortionPct;
  float myWildPlantsMCalories = myMCaloriesSettlementAnnual * myWildPlantsPortionPct;
  */
  float myDairyMCalories =11.0;
  float myCropMCalories =12.0;
  float myWildAnimalMCalories =13.0;
  float myWildPlantsMCalories =14.0;
  float myDairyPortionPct =15.0;
  float myTameMeatPortionPct =16.0;
  float myCropsPortionPct =17.0;
  float myWildAnimalPortionPct =18.0;
  float myWildPlantsPortionPct =19.0;
  float myPlantsPortionPct =110.0;
  float myAnimalPortionPct =111.0;
  myDietLabels.setDairyMCalories(myDairyMCalories);
  myDietLabels.setCropMCalories(myCropMCalories);
  myDietLabels.setWildAnimalMCalories(myWildAnimalMCalories);
  myDietLabels.setWildPlantsMCalories(myWildPlantsMCalories);
  myDietLabels.setDairyPortionPct(myDairyPortionPct*100.);
  myDietLabels.setTameMeatPortionPct(myTameMeatPortionPct*100.);
  myDietLabels.setCropsPortionPct(myCropsPortionPct*100.);
  myDietLabels.setWildAnimalPortionPct(myWildAnimalPortionPct*100.);
  myDietLabels.setWildPlantsPortionPct(myWildPlantsPortionPct*100.);
  myDietLabels.setPlantsPortionPct(myPlantsPortionPct*100.);
  myDietLabels.setAnimalPortionPct(myAnimalPortionPct*100.);
  myDietLabels.setKiloCaloriesIndividualAnnual(myKiloCaloriesIndividualAnnual);
  myDietLabels.setMegaCaloriesSettlementAnnual(myMegaCaloriesSettlementAnnual);
  return myDietLabels;
}
LaDietLabels LaModel::doCalcsAnimalsFirstIncludeDiary ()
Calculates diet portions for setting the diet labels Animals First Includes Diary means that the dairy products from the animal herds will be considered as part of the animals' contribution to the diet, and plant based portion will be derived from these calculations. This assumes that the model has been 'set'
Returns:
Definition at line 608 of file lamodel.cpp.
References LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaAnimal::killWeight(), LaAnimal::lactationTime(), mAnimalsMap, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, LaAnimal::meatFoodValue(), LaAnimal::milkFoodValue(), LaAnimal::milkGramsPerDay(), mMeatPercent, mPercentOfDietThatIsFromCrops, mPopulation, LaDietLabels::setAnimalPortionPct(), LaDietLabels::setCropMCalories(), LaDietLabels::setCropsPortionPct(), LaDietLabels::setDairyMCalories(), LaDietLabels::setDairyPortionPct(), LaDietLabels::setKiloCaloriesIndividualAnnual(), LaDietLabels::setMegaCaloriesSettlementAnnual(), LaDietLabels::setPlantsPortionPct(), LaDietLabels::setTameMeatPortionPct(), LaDietLabels::setWildAnimalMCalories(), LaDietLabels::setWildAnimalPortionPct(), LaDietLabels::setWildPlantsMCalories(), LaDietLabels::setWildPlantsPortionPct(), LaAnimal::usableMeat(), and LaAnimal::weaningAge().
Referenced by LaMainForm::on_pushButtonRun_clicked(), and LaMainForm::setDietLabels().
{
  LaDietLabels myDietLabels;
  LaAnimal myAnimal;
  float myKiloCaloriesIndividualAnnual = mCaloriesPerPersonDaily * 365.0 * 0.001;
  float myMegaCaloriesSettlementAnnual = (myKiloCaloriesIndividualAnnual*0.001) * mPopulation;
  float myDairyMCalorieCounter = 0.0;
  float myTameMeatMCalorieCounter = 0.0;
  float myWildMeatMCalorieCounter = 0.0;
  QMap <QString,QString> mySelectedAnimalsMap = mAnimalsMap;
  float c1 = 1. - mMeatPercent;
  float c8 = mDairyUtilisation;
  float c10= mPopulation;
  float c11= mCaloriesPerPersonDaily;
  float c14= c10*c11*365.;
  float c15= mDietPercent;
  float c12= mPercentOfDietThatIsFromCrops;
  float e15= c14*c15;
  //float c17=1.-mMeatPercent;
  //float c18=mMeatPercent;
  QMapIterator <QString,QString> myNextAnimalIterator(mySelectedAnimalsMap);
  while (myNextAnimalIterator.hasNext())
  {
    myNextAnimalIterator.next();
    QString myAnimalGuid = myNextAnimalIterator.key();
    QString myAnimalParameterGuid = myNextAnimalIterator.value();
    LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
    LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter( myAnimalParameterGuid );
    // adjust the milk calories to correspond to value
    // per kg of each live weight animal
    float c2 = myAnimal.milkGramsPerDay()*.001;
    float c3 = myAnimal.milkFoodValue();
    float c4 = myAnimal.lactationTime();
    float c5 = myAnimal.weaningAge();
    float c6 = myAnimal.killWeight();
    float c7 = myAnimal.usableMeat()*.01;
    float e2 = c2*c3*(c4-c5);
    float e3 = e2*c8;
    float c9 = myAnimal.meatFoodValue();
    float e10= e3+(c9*c7*c6);
    float e7 = (e15*(1.-c1))/e10;
    float c21=e7*e3;
    float c23=e7*c6*c7*c9;
    float c22=e15-c21-c23;
    myDairyMCalorieCounter    += c21;
    myWildMeatMCalorieCounter += c22;
    myTameMeatMCalorieCounter += c23;
    qDebug() << "c1 = " << c1;
    qDebug() << "c2 = " << c2;
    qDebug() << "c3 = " << c3;
    qDebug() << "c4 = " << c4;
    qDebug() << "c5 = " << c5;
    qDebug() << "c6 = " << c6;
    qDebug() << "c7 = " << c7;
    qDebug() << "c14 = " << c14;
    qDebug() << "e2 = " << e2;
    qDebug() << "e3 = " << e3;
    qDebug() << "e10 = " << e10;
    qDebug() << "e15 = " << e15;
    qDebug() << "e7 = " << e7;
  }
  float c24=(1.-c12)*(c14-e15);
  float c25=(c12)*(c14-e15);
  float c30=c24/c14;
  float c31=c25/c14;
  float c28=(myWildMeatMCalorieCounter)/c14;
  float c29=(myTameMeatMCalorieCounter)/c14;
  float c27=myDairyMCalorieCounter/c14;
    qDebug() << "c27 = " << c27;
    qDebug() << "c28 = " << c28;
    qDebug() << "c29 = " << c29;
  //float myCropMCalories = c14*.001*.001*mDietPercent*mPercentOfDietThatIsFromCrops;
  //float myWildPlantMCalories = c14*.001*.001*mDietPercent*(1.-mPercentOfDietThatIsFromCrops);
  //float myCropOverallPortion = myWildPlantMCalories/(c14*.001*.001);
  //float myWildPlantOverallPortion = myWildPlantMCalories/(c14*.001*.001);
  myDietLabels.setDairyMCalories(myDairyMCalorieCounter*.001*.001);
  myDietLabels.setCropMCalories(c25*.001*.001);
  myDietLabels.setWildAnimalMCalories(myWildMeatMCalorieCounter*.001*.001);
  myDietLabels.setWildPlantsMCalories(c24*.001*.001);
  myDietLabels.setDairyPortionPct(c27*100.);
  myDietLabels.setTameMeatPortionPct(c29*100.);
  myDietLabels.setCropsPortionPct(c31*100.);
  myDietLabels.setWildAnimalPortionPct(c28*100.);
  myDietLabels.setWildPlantsPortionPct(c30*100.);
  myDietLabels.setAnimalPortionPct(mDietPercent*100.);
  myDietLabels.setPlantsPortionPct((1.-mDietPercent)*100.);
  myDietLabels.setKiloCaloriesIndividualAnnual(myKiloCaloriesIndividualAnnual);
  myDietLabels.setMegaCaloriesSettlementAnnual(myMegaCaloriesSettlementAnnual);
  return myDietLabels;
}
LaDietLabels LaModel::doCalcsAnimalsFirstDairySeparate ()
Definition at line 710 of file lamodel.cpp.
References mCaloriesPerPersonDaily, mPopulation, LaDietLabels::setAnimalPortionPct(), LaDietLabels::setCropMCalories(), LaDietLabels::setCropsPortionPct(), LaDietLabels::setDairyMCalories(), LaDietLabels::setDairyPortionPct(), LaDietLabels::setKiloCaloriesIndividualAnnual(), LaDietLabels::setMegaCaloriesSettlementAnnual(), LaDietLabels::setPlantsPortionPct(), LaDietLabels::setTameMeatPortionPct(), LaDietLabels::setWildAnimalMCalories(), LaDietLabels::setWildAnimalPortionPct(), LaDietLabels::setWildPlantsMCalories(), and LaDietLabels::setWildPlantsPortionPct().
Referenced by LaMainForm::on_pushButtonRun_clicked(), and LaMainForm::setDietLabels().
{
  LaDietLabels myDietLabels;
  float myKiloCaloriesIndividualAnnual = mCaloriesPerPersonDaily * 365.0 * 0.001;
  float myMegaCaloriesSettlementAnnual =  (myKiloCaloriesIndividualAnnual*0.001) * mPopulation * 365.0;
  /*float myDairyUtilisation;
  float myDairyMCalories = (myDairyUtilisation) * myDairyMCalorieCounter;
  float myDairyPortionPct = myDairyMCalories / myMCaloriesSettlementAnnual;
  float myPercentOfCalorieTarget = myMCaloriesSettlementAnnual * myDietPercentMeat;
  float myAnimalCalsMinusDairyBit = myPercentOfCalorieTarget - myDairyMCalories;
  float myWildAnimalMCalories = myAnimalCalsMinusDairyBit * myWildMeatPercentage;
  float myTameAnimalMCalories = myAnimalCalsMinusDairyBit * myTameMeatPercentage;
  float myWildAnimalPortionPct = myWildAnimalMCalories / myMCaloriesSettlementAnnual;
  float myTameMeatPortionPct = myTameAnimalMCalories / myMCaloriesSettlementAnnual;
  float myPlantsPortionPct = 1. - myAnimalPortionPct;
  float myCropsPortionPct = myPlantsPortionPct * myCropPercentage;
  float myWildPlantsPortionPct = myPlantsPortionPct * myWildPlantsPercentage;
  float myCropMCalories = myMCaloriesSettlementAnnual * myCropsPortionPct;
  float myWildPlantsMCalories = myMCaloriesSettlementAnnual * myWildPlantsPortionPct;
  */
  float myDairyMCalories =31.0;
  float myCropMCalories =32.0;
  float myWildAnimalMCalories =33.0;
  float myWildPlantsMCalories =34.0;
  float myDairyPortionPct =35.0;
  float myTameMeatPortionPct =36.0;
  float myCropsPortionPct =37.0;
  float myWildAnimalPortionPct =38.0;
  float myWildPlantsPortionPct =39.0;
  float myPlantsPortionPct =310.0;
  float myAnimalPortionPct =311.0;
  myDietLabels.setDairyMCalories(myDairyMCalories);
  myDietLabels.setCropMCalories(myCropMCalories);
  myDietLabels.setWildAnimalMCalories(myWildAnimalMCalories);
  myDietLabels.setWildPlantsMCalories(myWildPlantsMCalories);
  myDietLabels.setDairyPortionPct(myDairyPortionPct*100.);
  myDietLabels.setTameMeatPortionPct(myTameMeatPortionPct*100.);
  myDietLabels.setCropsPortionPct(myCropsPortionPct*100.);
  myDietLabels.setWildAnimalPortionPct(myWildAnimalPortionPct*100.);
  myDietLabels.setWildPlantsPortionPct(myWildPlantsPortionPct*100.);
  myDietLabels.setPlantsPortionPct(myPlantsPortionPct*100.);
  myDietLabels.setAnimalPortionPct(myAnimalPortionPct*100.);
  myDietLabels.setKiloCaloriesIndividualAnnual(myKiloCaloriesIndividualAnnual);
  myDietLabels.setMegaCaloriesSettlementAnnual(myMegaCaloriesSettlementAnnual);
  return myDietLabels;
}
QMap< QString, float > LaModel::getAreaTargetsAnimalsMapAFID ()
Definition at line 784 of file lamodel.cpp.
References LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaAnimal::lactationTime(), mAnimalsMap, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, LaAnimal::milkFoodValue(), LaAnimal::milkGramsPerDay(), mMeatPercent, mPercentOfDietThatIsFromCrops, mPopulation, LaDietLabels::setAnimalPortionPct(), LaDietLabels::setCropMCalories(), LaDietLabels::setCropsPortionPct(), LaDietLabels::setDairyMCalories(), LaDietLabels::setDairyPortionPct(), LaDietLabels::setKiloCaloriesIndividualAnnual(), LaDietLabels::setMegaCaloriesSettlementAnnual(), LaDietLabels::setPlantsPortionPct(), LaDietLabels::setTameMeatPortionPct(), LaDietLabels::setWildAnimalMCalories(), LaDietLabels::setWildAnimalPortionPct(), LaDietLabels::setWildPlantsMCalories(), LaDietLabels::setWildPlantsPortionPct(), and LaAnimal::weaningAge().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  LaDietLabels myDietLabels;
  float myKiloCaloriesIndividualAnnual = mCaloriesPerPersonDaily * 365.0 * 0.001;
  float myMegaCaloriesSettlementAnnual =  (myKiloCaloriesIndividualAnnual*0.001) * mPopulation;
  float myDairyUtilisation = mDairyUtilisation;
  float myDairyMCalorieCounter = 0.0;
  QMap <QString,QString> mySelectedAnimalsMap = mAnimalsMap;
  QMapIterator <QString,QString> myNextAnimalIterator(mySelectedAnimalsMap);
  while (myNextAnimalIterator.hasNext())
  {
    myNextAnimalIterator.next();
    QString myAnimalGuid = myNextAnimalIterator.key();
    QString myAnimalParameterGuid = myNextAnimalIterator.value();
    LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
    LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
    float c2 = myAnimal.milkGramsPerDay() * 1000.;
    float c3 = myAnimal.milkFoodValue();
    float myDaysOfMilking = myAnimal.lactationTime() - myAnimal.weaningAge();
    float myKCaloriesFromMilk = ( myDaysOfMilking
                              * c3
                              * c2 ) / 1000.;
    float myMCaloriesFromMilk = myKCaloriesFromMilk / 1000.;
    myDairyMCalorieCounter += myMCaloriesFromMilk;
    qDebug() << "Adding " << myKCaloriesFromMilk
        << " KCalories to total KCalories from milk which is now at: "
        << myDairyMCalorieCounter << "MCalories";
  }
  float myDairyMCalories = myDairyUtilisation * myDairyMCalorieCounter;
  float myDairyPortionPct = (myDairyMCalories) / myMegaCaloriesSettlementAnnual;
  float myAnimalsCalorieTarget = myMegaCaloriesSettlementAnnual * mDietPercent;
  float myAnimalCalsMinusDairyBit = myAnimalsCalorieTarget - myDairyMCalories;
  float myWildAnimalMCalories = myAnimalCalsMinusDairyBit * (1. - mMeatPercent);
  float myTameAnimalMCalories = myAnimalCalsMinusDairyBit * (mMeatPercent);
  float myWildAnimalPortionPct = myWildAnimalMCalories / myMegaCaloriesSettlementAnnual;
  float myTameMeatPortionPct = myTameAnimalMCalories / (myMegaCaloriesSettlementAnnual - myDairyMCalories);
  float myPlantsPortionPct = 1. - myWildAnimalPortionPct - myTameMeatPortionPct - myDairyPortionPct;
  float myCropsPortionPct = myPlantsPortionPct * (mPercentOfDietThatIsFromCrops);
  float myWildPlantsPortionPct = myPlantsPortionPct * (1. - mPercentOfDietThatIsFromCrops);
  float myCropMCalories = myMegaCaloriesSettlementAnnual * myCropsPortionPct;
  float myWildPlantsMCalories = myMegaCaloriesSettlementAnnual * myWildPlantsPortionPct;
  float myAnimalPortionPct = mDietPercent;
  myDietLabels.setDairyMCalories(myDairyMCalories);
  myDietLabels.setCropMCalories(myCropMCalories);
  myDietLabels.setWildAnimalMCalories(myWildAnimalMCalories);
  myDietLabels.setWildPlantsMCalories(myWildPlantsMCalories);
  myDietLabels.setDairyPortionPct(myDairyPortionPct*100.);
  myDietLabels.setTameMeatPortionPct(myTameMeatPortionPct*100.);
  myDietLabels.setCropsPortionPct(myCropsPortionPct*100.);
  myDietLabels.setWildAnimalPortionPct(myWildAnimalPortionPct*100.);
  myDietLabels.setWildPlantsPortionPct(myWildPlantsPortionPct*100.);
  myDietLabels.setPlantsPortionPct(myPlantsPortionPct*100.);
  myDietLabels.setAnimalPortionPct(myAnimalPortionPct*100.);
  myDietLabels.setKiloCaloriesIndividualAnnual(myKiloCaloriesIndividualAnnual);
  myDietLabels.setMegaCaloriesSettlementAnnual(myMegaCaloriesSettlementAnnual);
{
  QMap<QString, float> myAreaTargetsAnimalsMap;
  return myAreaTargetsAnimalsMap;
}
}
QMap< QString, float > LaModel::getAreaTargetsAnimalsMapAFDS ()
Definition at line 856 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsAnimalsMap;
  return myAreaTargetsAnimalsMap;
}
QMap< QString, float > LaModel::getAreaTargetsAnimalsMapPFDS ()
Definition at line 778 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsAnimalsMap;
  return myAreaTargetsAnimalsMap;
}
QMap< QString, float > LaModel::getAreaTargetsAnimalsMapPFID ()
Definition at line 772 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsAnimalsMap;
  return myAreaTargetsAnimalsMap;
}
QMap< QString, float > LaModel::getAreaTargetsCropsMapAFID ()
Definition at line 875 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsCropsMap;
  return myAreaTargetsCropsMap;
}
QMap< QString, float > LaModel::getAreaTargetsCropsMapAFDS ()
Definition at line 881 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsCropsMap;
  return myAreaTargetsCropsMap;
}
QMap< QString, float > LaModel::getAreaTargetsCropsMapPFDS ()
Definition at line 869 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsCropsMap;
  return myAreaTargetsCropsMap;
}
QMap< QString, float > LaModel::getAreaTargetsCropsMapPFID ()
Definition at line 863 of file lamodel.cpp.
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
  QMap<QString, float> myAreaTargetsCropsMap;
  return myAreaTargetsCropsMap;
}
float LaModel::countCaloriesForAnimals ()
void LaModel::setFallowStatus (Status theStatus)
Set the holder
See also:
holder()
Definition at line 156 of file lamodel.cpp.
References mFallowStatus.
{ mFallowStatus=theStatus; }
void LaModel::setFallowRatio (float theRatio)
Set the holder
See also:
holder()
Definition at line 157 of file lamodel.cpp.
References mFallowRatio.
{ mFallowRatio=theRatio; }
QString LaModel::toXml () [virtual]
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Implements LaSerialisable.
Definition at line 955 of file lamodel.cpp.
References LaGuid::guid(), logMessage(), mBaseOnPlants, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, mEasting, mEuclideanDistance, mIncludeDairy, mLimitDairy, mLimitDairyPercentage, mMeatPercent, mName, mNorthing, mPathDistance, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, mWalkingTime, and LaUtils::xmlEncode().
Referenced by LaModelTest::saveAndLoadModel().
{
  logMessage("method ==> QString LaModel::toXml()");
  QString myString;
  myString+=QString("<model guid=\"" + guid() + "\">\n");
  myString+=QString("  <name>" + LaUtils::xmlEncode(mName) + "</name>\n");
  myString+=QString("  <population>" + QString::number(mPopulation) + "</population>\n");
  myString+=QString("  <period>" + LaUtils::xmlEncode(mPeriod) + "</period>\n");
  myString+=QString("  <projection>" + QString::number(mProjection) + "</projection>\n");
  myString+=QString("  <easting>" + QString::number(mEasting) + "</easting>\n");
  myString+=QString("  <northing>" + QString::number(mNorthing) + "</northing>\n");
  myString+=QString("  <euclideanDistance>" + QString::number(mEuclideanDistance) + "</euclideanDistance>\n");
  myString+=QString("  <walkingTime>" + QString::number(mWalkingTime) + "</walkingTime>\n");
  myString+=QString("  <pathDistance>" + QString::number(mPathDistance) + "</pathDistance>\n");
  myString+=QString("  <precision>" + QString::number(mPrecision) + "</precision>\n");
  myString+=QString("  <dietPercent>" + QString::number(mDietPercent) + "</dietPercent>\n");
  myString+=QString("  <plantPercent>" + QString::number(mPercentOfDietThatIsFromCrops) + "</plantPercent>\n");
  myString+=QString("  <meatPercent>" + QString::number(mMeatPercent) + "</meatPercent>\n");
  myString+=QString("  <caloriesPerPersonDaily>" + QString::number(mCaloriesPerPersonDaily) + "</caloriesPerPersonDaily>\n");
  myString+=QString("  <baseOnPlants>" + QString::number(mBaseOnPlants) + "</baseOnPlants>\n");
  myString+=QString("  <includeDairy>" + QString::number(mIncludeDairy) + "</includeDairy>\n");
  myString+=QString("  <limitDairy>" + QString::number(mLimitDairy) + "</limitDairy>\n");
  myString+=QString("  <limitDairyPercent>" + QString::number(mLimitDairyPercentage) + "</limitDairyPercent>\n");
  myString+=QString("  <dairyUtilisation>" + QString::number(mDairyUtilisation) + "</dairyUtilisation>\n");
  myString+=QString("</model>\n");
  return myString;
}
QString LaModel::toHtmlCalorieAnimalTargets ()
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1144 of file lamodel.cpp.
References LaUtils::getAnimal(), LaUtils::getAnimalParameter(), mAnimalsMap, mCaloriesProvidedByMeatMap, and LaUtils::xmlEncode().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
    // This method returns a QString for an xml file containing the calorie
    // targets for each animal from mCaloriesProvidedByMeatMap
    // Loop through the mCaloriesProvidedByAniamlsMap
  QString myString;
  myString += QString("<h3> Animal Calorie Targets</h3>\n");
  myString += QString("<P STYLE=\"margin-bottom: 0in\"><BR>\n");
  myString += QString("\n");
  myString += QString("<table>");
  myString += QString("  <COL WIDTH=64*>\n");
  myString += QString("  <COL WIDTH=16*>\n");
  myString += QString("  <tr>\n");
  myString += QString("    <th>\n");
  myString += QString("      Animal\n");
  myString += QString("    </th>\n");
  myString += QString("    <th>\n");
  myString += QString("      kCalories\n");
  myString += QString("    </th>\n");
  myString += QString("  </tr>\n");
  QMapIterator<QString, float> myAnimalIterator (mCaloriesProvidedByMeatMap);
  while (myAnimalIterator.hasNext())
  {
    myAnimalIterator.next();
    QString myAnimalGuid = myAnimalIterator.key();
    float myCalorieTarget = static_cast <float>(myAnimalIterator.value());
    LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
    LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(mAnimalsMap.value(myAnimalGuid));
    myString += QString("  <tr>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + LaUtils::xmlEncode(myAnimal.name()) + "\n");
    myString += QString("    </td>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + QString::number(myCalorieTarget) + "\n");
    myString += QString("    </td>\n");
    myString += QString("  </tr>\n");
      // add to the QString to create the xml file
      //myString += QString("  <animal>\n");
      //myString += QString("    <guid=\"" + myAnimalIterator.key() + "\">\n");
      //myString += QString("    <name>" + LaUtils::xmlEncode(myAnimal.name()) + "</name>\n");
      //myString += QString("    <description>" + LaUtils::xmlEncode(myAnimal.description()) + "</description>\n");
      //myString += QString("    <parameterGuid=\"" + myAnimalParameter.guid() + "\">\n");
      //myString += QString("    <name>" + LaUtils::xmlEncode(myAnimalParameter.name()) + "</name>\n");
      //myString += QString("    <calorieTarget>" + QString::number(myCalorieTarget) + "</calorieTarget>\n");
      //myString += QString("  </animal>\n");
  }   // while animal iterator
    myString += QString("</table>\n");
  return myString;
}
QString LaModel::toHtmlCalorieCropTargets ()
Return an html representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1090 of file lamodel.cpp.
References LaUtils::getCrop(), LaUtils::getCropParameter(), mCaloriesProvidedByCropsMap, mCropsMap, and LaUtils::xmlEncode().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
    // This method returns a QString for an xml file containing the calorie
    // targets for each crop from mCaloriesProvidedByCropsMap
    // Loop through the mCaloriesProvidedByCropsMap
  QString myString;
  myString += QString("<h3> Crop Calorie Targets</h3>\n");
  myString += QString("<table>");
  myString += QString("  <tr>\n");
  myString += QString("    <th>\n");
  myString += QString("      Crop\n");
  myString += QString("    </th>\n");
  myString += QString("    <th>\n");
  myString += QString("      kCalories\n");
  myString += QString("    </th>\n");
  myString += QString("  </tr>\n");
  QMapIterator<QString, float> myCropIterator (mCaloriesProvidedByCropsMap);
  while (myCropIterator.hasNext())
  {
    myCropIterator.next();
    QString myCropGuid = myCropIterator.key();
    float myCalorieTarget = static_cast <float>(myCropIterator.value());
    LaCrop myCrop = LaUtils::getCrop(myCropGuid);
    LaCropParameter myCropParameter = LaUtils::getCropParameter(mCropsMap.value(myCropGuid));
      // add to the QString to create the html file
    myString += QString("  <tr>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + LaUtils::xmlEncode(myCrop.name()) + "\n");
    myString += QString("    </td>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + QString::number(myCalorieTarget) + "\n");
    myString += QString("    </td>\n");
    myString += QString("  </tr>\n");
      // add to the QString to create the xml file
      //myString += QString("  <crop>\n");
      //myString += QString("    <guid=\"" + myCropIterator.key() + "\">\n");
      //myString += QString("    <name>" + LaUtils::xmlEncode(myCrop.name()) + "</name>\n");
      //myString += QString("    <description>" + LaUtils::xmlEncode(myCrop.description()) + "</description>\n");
      //myString += QString("    <parameterGuid=\"" + myCropParameter.guid() + "\">\n");
      //myString += QString("    <name>" + LaUtils::xmlEncode(myCropParameter.name()) + "</name>\n");
      //myString += QString("    <calorieTarget>" + QString::number(myCalorieTarget) + "</calorieTarget>\n");
      //myString += QString("  </crop>\n");
  }   // while crop iterator
    myString += QString("</table>\n");
  return myString;
}
QString LaModel::toHtmlProductionAnimalTargets ()
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1241 of file lamodel.cpp.
References LaUtils::getAnimal(), LaUtils::getAnimalParameter(), mAnimalsMap, mProductionRequiredAnimalsMap, and LaUtils::xmlEncode().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
    // Sallah, I said *no* camels. That's *five* camels. Can't you count?
    // This method returns a QString for an xml file containing the production
    // targets for each animal from mProductionRequiredAnimalsMap
    // Loop through the mProductionRequiredAnimalsMap
  QString myString;
  myString += QString("<h3> Animal Production Targets</h3>\n");
  myString += QString("<P STYLE=\"margin-bottom: 0in\"><BR>\n");
  myString += QString("\n");
  myString += QString("<table>");
  myString += QString("  <COL WIDTH=64*>\n");
  myString += QString("  <COL WIDTH=16*>\n");
  myString += QString("  <tr>\n");
  myString += QString("    <th>\n");
  myString += QString("      Animal\n");
  myString += QString("    </th>\n");
  myString += QString("    <th>\n");
  myString += QString("      Kg\n");
  myString += QString("    </th>\n");
  myString += QString("  </tr>\n");
  QMapIterator<QString, float> myAnimalIterator (mProductionRequiredAnimalsMap);
  while (myAnimalIterator.hasNext())
  {
    myAnimalIterator.next();
    QString myAnimalGuid = myAnimalIterator.key();
    float myProductionTarget = static_cast <float>(myAnimalIterator.value());
    LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
    LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(mAnimalsMap.value(myAnimalGuid));
      // add to the QString to create the xml file
    myString += QString("  <tr>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + LaUtils::xmlEncode(myAnimal.name()) + "\n");
    myString += QString("    </td>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + QString::number(myProductionTarget) + "\n");
    myString += QString("    </td>\n");
    myString += QString("  </tr>\n");
  }   // while crop iterator
    myString += QString("</table>\n");
  return myString;
}
QString LaModel::toHtmlAreaCropTargets ()
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1288 of file lamodel.cpp.
References LaUtils::getCrop(), LaUtils::getCropParameter(), mAreaTargetsCropsMap, mCropsMap, and LaUtils::xmlEncode().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
    // This method returns a QString for an xml file containing the production
    // targets for each crop from mAreaTargetsCropsMap
    // Loop through the mAreaTargetsCropsMap
  QString myString;
  myString += QString("<h3> Crop Area Targets</h3>\n");
  myString += QString("<P STYLE=\"margin-bottom: 0in\"><BR>\n");
  myString += QString("\n");
  myString += QString("<table>");
  myString += QString("  <COL WIDTH=64*>\n");
  myString += QString("  <COL WIDTH=16*>\n");
  myString += QString("  <tr>\n");
  myString += QString("    <th>\n");
  myString += QString("      Crop\n");
  myString += QString("    </th>\n");
  myString += QString("    <th>\n");
  myString += QString("      Area\n");
  myString += QString("    </th>\n");
  myString += QString("  </tr>\n");
  QMapIterator<QString, float> myCropIterator (mAreaTargetsCropsMap);
  while (myCropIterator.hasNext())
  {
    myCropIterator.next();
    QString myCropGuid = myCropIterator.key();
    if (myCropGuid != "CommonTarget")
    {
      float myAreaTarget = static_cast <float>(myCropIterator.value());
      LaCrop myCrop = LaUtils::getCrop(myCropGuid);
      LaCropParameter myCropParameter = LaUtils::getCropParameter(mCropsMap.value(myCropGuid));
        // add to the QString to create the xml file
      myString += QString("  <tr>\n");
      myString += QString("    <td>\n");
      myString += QString("      " + LaUtils::xmlEncode(myCrop.name()) + "\n");
      myString += QString("    </td>\n");
      myString += QString("    <td>\n");
      myString += QString("      " + QString::number(myAreaTarget) + "\n");
      myString += QString("    </td>\n");
      myString += QString("  </tr>\n");
    }
    else
    {
      QString myAreaTarget = QString::number(mAreaTargetsCropsMap.value("CommonTarget"));
      myString += QString("  <tr>\n");
      myString += QString("    <td>\n");
      myString += QString("      CommonTarget\n");
      myString += QString("    </td>\n");
      myString += QString("    <td>\n");
      myString += QString("      " + myAreaTarget + "\n");
      myString += QString("    </td>\n");
      myString += QString("  </tr>\n");
    }
  }   // while crop iterator
    myString += QString("</table>\n");
  return myString;
}
QString LaModel::toHtmlAreaAnimalTargets ()
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1347 of file lamodel.cpp.
References LaAnimalParameter::areaUnits(), LaUtils::convertAreaToHectares(), LaUtils::getAnimal(), LaUtils::getAnimalParameter(), mAnimalsMap, mAreaTargetsAnimalsMap, and LaUtils::xmlEncode().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
    // This method returns a QString for an xml file containing the production
    // targets for each animal from mAreaTargetsAnimalsMap
    // Loop through the mAreaTargetsAnimalsMap
  QString myString;
  myString += QString("<h3> Animal Area Targets</h3>\n");
  myString += QString("\n");
  myString += QString("<table>");
  myString += QString("  <tr>\n");
  myString += QString("    <th>\n");
  myString += QString("      Animal\n");
  myString += QString("    </th>\n");
  myString += QString("    <th>\n");
  myString += QString("      Area\n");
  myString += QString("    </th>\n");
  myString += QString("  </tr>\n");
  QMapIterator<QString, float> myAnimalIterator (mAreaTargetsAnimalsMap);
  while (myAnimalIterator.hasNext())
  {
    myAnimalIterator.next();
    QString myAnimalGuid = myAnimalIterator.key();
    if (myAnimalGuid != "CommonTarget")
    {
      float myAreaTargetUnchanged = static_cast <float>(myAnimalIterator.value());
      LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
      LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(mAnimalsMap.value(myAnimalGuid));
      float myAreaTarget = LaUtils::convertAreaToHectares(myAnimalParameter.areaUnits(), myAreaTargetUnchanged);
        // add to the QString to create the xml file
      myString += QString("  <tr>\n");
      myString += QString("    <td>\n");
      myString += QString("      " + LaUtils::xmlEncode(myAnimal.name()) + "\n");
      myString += QString("    </td>\n");
      myString += QString("    <td>\n");
      myString += QString("      " + QString::number(myAreaTarget) + "\n");
      myString += QString("    </td>\n");
      myString += QString("  </tr>\n");
    }
    else
    {
      QString myAreaTarget = QString::number(mAreaTargetsAnimalsMap.value("CommonTarget"));
      myString += QString("  <tr>\n");
      myString += QString("    <td>\n");
      myString += QString("      CommonTarget\n");
      myString += QString("    </td>\n");
      myString += QString("    <td>\n");
      myString += QString("      " + myAreaTarget + "\n");
      myString += QString("    </td>\n");
      myString += QString("  </tr>\n");
    }
  }
    myString += QString("</table>\n");
  return myString;
}
QString LaModel::toHtmlProductionCropTargets ()
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1197 of file lamodel.cpp.
References LaUtils::getCrop(), LaUtils::getCropParameter(), mCropsMap, mProductionRequiredCropsMap, and LaUtils::xmlEncode().
Referenced by LaMainForm::on_pushButtonRun_clicked().
{
    // This method returns a QString for an xml file containing the production
    // targets for each crop from mProductionRequiredCropsMap
    // Loop through the mProductionRequiredCropsMap
  QString myString;
  myString += QString("<h3> Crop Production Targets</h3>\n");
  myString += QString("<P STYLE=\"margin-bottom: 0in\"><BR>\n");
  myString += QString("\n");
  myString += QString("<table>");
  myString += QString("  <COL WIDTH=64*>\n");
  myString += QString("  <COL WIDTH=16*>\n");
  myString += QString("  <tr>\n");
  myString += QString("    <th>\n");
  myString += QString("      Crop\n");
  myString += QString("    </th>\n");
  myString += QString("    <th>\n");
  myString += QString("      Kg\n");
  myString += QString("    </th>\n");
  myString += QString("  </tr>\n");
  QMapIterator<QString, float> myCropIterator (mProductionRequiredCropsMap);
  while (myCropIterator.hasNext())
  {
    myCropIterator.next();
    QString myCropGuid = myCropIterator.key();
    float myProductionTarget = static_cast <float>(myCropIterator.value());
    LaCrop myCrop = LaUtils::getCrop(myCropGuid);
    LaCropParameter myCropParameter = LaUtils::getCropParameter(mCropsMap.value(myCropGuid));
      // add to the QString to create the xml file
    myString += QString("  <tr>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + LaUtils::xmlEncode(myCrop.name()) + "\n");
    myString += QString("    </td>\n");
    myString += QString("    <td>\n");
    myString += QString("      " + QString::number(myProductionTarget) + "\n");
    myString += QString("    </td>\n");
    myString += QString("  </tr>\n");
  }   // while crop iterator
    myString += QString("</table>\n");
  return myString;
}
QString LaModel::toText ()
Return a plain text representation of this layer
Definition at line 985 of file lamodel.cpp.
References LaGuid::guid(), logMessage(), mBaseOnPlants, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, mEasting, mEuclideanDistance, mIncludeDairy, mLimitDairy, mLimitDairyPercentage, mMeatPercent, mName, mNorthing, mPathDistance, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, mWalkingTime, and LaUtils::xmlEncode().
{
  logMessage("method ==> QString LaModel::toText()");
  QString myString;
  myString+=QString("guid=>" + guid() + "\n");
  myString+=QString("name=>" + LaUtils::xmlEncode(mName) + "\n");
  myString+=QString("population=>" + QString::number(mPopulation) + "\n");
  myString+=QString("period=>" + LaUtils::xmlEncode(mPeriod) + "\n");
  myString+=QString("projection=>" + QString::number(mProjection) + "\n");
  myString+=QString("easting=>" + QString::number(mEasting) + "\n");
  myString+=QString("northing=>" + QString::number(mNorthing) + "\n");
  myString+=QString("euclideanDistance=>" + QString::number(mEuclideanDistance) + "\n");
  myString+=QString("walkingTime=>" + QString::number(mWalkingTime) + "\n");
  myString+=QString("pathDistance=>" + QString::number(mPathDistance) + "\n");
  myString+=QString("precision=>" + QString::number(mPrecision) + "\n");
  myString+=QString("dietPercent=>" + QString::number(mDietPercent) + "\n");
  myString+=QString("plantPercent=>" + QString::number(mPercentOfDietThatIsFromCrops) + "\n");
  myString+=QString("meatPercent=>" + QString::number(mMeatPercent) + "\n");
  myString+=QString("caloriesPerPersonDaily=>" + QString::number(mCaloriesPerPersonDaily) + "\n");
  myString+=QString("baseOnPlants=>" + QString::number(mBaseOnPlants) + "\n");
  myString+=QString("includeDairy=>" + QString::number(mIncludeDairy) + "\n");
  myString+=QString("limitDairy=>" + QString::number(mLimitDairy) + "\n");
  myString+=QString("limitDairyPercent=>" + QString::number(mLimitDairyPercentage) + "\n");
  myString+=QString("dairyUtilisation=>" + QString::number(mDairyUtilisation) + "\n");
  return myString;
}
QString LaModel::toHtml ()
Return an xml representation of this layer this class inherits the serialisable floaterface so it MUST implement this
Definition at line 1014 of file lamodel.cpp.
References LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaUtils::getCrop(), LaUtils::getCropParameter(), logMessage(), mAnimalsMap, mBaseOnPlants, mCaloriesPerPersonDaily, mCropsMap, mDairyUtilisation, mDietPercent, mEasting, mEuclideanDistance, mIncludeDairy, mLimitDairy, mLimitDairyPercentage, mMeatPercent, mName, mNorthing, mPathDistance, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, mWalkingTime, LaCropParameter::toHtml(), LaCrop::toHtml(), LaAnimalParameter::toHtml(), LaAnimal::toHtml(), and LaUtils::xmlEncode().
Referenced by LaMainForm::animalCalcClicked(), LaMainForm::cropCalcClicked(), and LaMainForm::on_pushButtonRun_clicked().
{
  logMessage("method ==> QString LaModel::toHtml()");
  QString myString;
  myString+="<h1>Model Report</h1>";
  myString+="<h3>" + LaUtils::xmlEncode(mName) + "</h3>";
    //myString+="GUID:" + guid() + "<br />";
  myString+="<br>Population:" + QString::number(mPopulation) + "</br>";
  myString+="<br>Period: " + LaUtils::xmlEncode(mPeriod) + "</br>";
  myString+="<br>Projection: " + QString::number(mProjection) + "</br>";
  myString+="<br>Easting: " + QString::number(mEasting) + "</br>";
  myString+="<br>Northing: " + QString::number(mNorthing) + "</br>";
  myString+="<br>Euclidean Distance: " + QString::number(mEuclideanDistance) + "</br>";
  myString+="<br>Walking Time: " + QString::number(mWalkingTime) + "</br>";
  myString+="<br>Path Distance: " + QString::number(mPathDistance) + "</br>";
  myString+="<br>Precision: " + QString::number(mPrecision) + "</br>";
  myString+="<br>Diet Percent" + QString::number(mDietPercent) + "</br>";
  myString+="<br>Plant Percent: " + QString::number(mPercentOfDietThatIsFromCrops) + "</br>";
  myString+="<br>Meat Percent: " + QString::number(mMeatPercent) + "</br>";
  myString+="<br>Calories Per Person Daily: " + QString::number(mCaloriesPerPersonDaily) + "</br>";
  myString+="<br>BaseOnPlants=>" + QString::number(mBaseOnPlants) + "</br>";
  myString+="<br>IncludeDairy=>" + QString::number(mIncludeDairy) + "</br>";
  myString+="<br>LimitDairy=>" + QString::number(mLimitDairy) + "</br>";
  myString+="<br>LimitDairyPercent=>" + QString::number(mLimitDairyPercentage) + "</br>";
  myString+="<br>Dairy Use: " + QString::number(mDairyUtilisation) + "</br>";
    //iterate through animals
  QMapIterator<QString, QString > myAnimalIterator(mAnimalsMap);
  while (myAnimalIterator.hasNext())
  {
    myAnimalIterator.next();
    QString myAnimalGuid = myAnimalIterator.key();
    QString myAnimalParameterGuid = myAnimalIterator.value();
      //QString myText = "Animal " + myAnimalGuid.toLocal8Bit() +
      //  " , ";
      //myText +=  myAnimalParameterGuid.toLocal8Bit() ;
      //myText += " ";
      //myString += myText + "<br />";
    LaAnimal myAnimal = LaUtils::getAnimal(myAnimalGuid);
    myString += "<br>";
    myString += myAnimal.toHtml();
    myString += "</br>";
    LaAnimalParameter myParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
    myString += "<br>";
    myString += myParameter.toHtml();
    myString += "</br>";
  }
    //iterate through crops
  QMapIterator<QString, QString > myCropIterator(mCropsMap);
  while (myCropIterator.hasNext())
  {
    myCropIterator.next();
    QString myCropGuid = myCropIterator.key();
    QString myCropParameterGuid = myCropIterator.value();
      //QString myText = "Crop " + myCropGuid.toLocal8Bit() +
      //  " , ";
      //myText += myCropParameterGuid.toLocal8Bit() ;
      //myText += " ";
      //myString += myText + "<br />";
    LaCrop myCrop = LaUtils::getCrop(myCropGuid);
    myString += myCrop.toHtml();
    myString += "<br />";
    LaCropParameter myParameter = LaUtils::getCropParameter(myCropParameterGuid);
    myString += myParameter.toHtml();
    myString += "<br />";
  }
  return myString;
}
bool LaModel::fromXml (const QString theXml) [virtual]
Read this object from xml and return result as true for success, false for failure.
See also:
LaSerialisable this class inherits the serialisable floaterface so it MUST implement this
Implements LaSerialisable.
Definition at line 891 of file lamodel.cpp.
References LaGuid::guid(), logMessage(), mBaseOnPlants, mCaloriesPerPersonDaily, mDairyUtilisation, mDietPercent, mEasting, mEuclideanDistance, mIncludeDairy, mLimitDairy, mLimitDairyPercentage, mMeatPercent, mName, mNorthing, mPathDistance, mPercentOfDietThatIsFromCrops, mPeriod, mPopulation, mPrecision, mProjection, mWalkingTime, LaGuid::setGuid(), and LaUtils::xmlDecode().
{
  logMessage("method ==> bool LaModel::fromXml(QString theXml)");
  QString myFlag;
  logMessage("Loading model from xml");
  QDomDocument myDocument("mydocument");
  myDocument.setContent(theXml);
  QDomElement myTopElement = myDocument.firstChildElement("model");
  if (myTopElement.isNull())
  {
      //TODO - just make this a warning
    logMessage("top element could not be found!");
  }
  logMessage("Model::fromXml - guid found : " + myTopElement.attribute("guid").toLocal8Bit());
  setGuid(myTopElement.attribute("guid"));
  logMessage("Model::fromXml - guid set to : " + guid().toLocal8Bit());
  mName=LaUtils::xmlDecode(myTopElement.firstChildElement("name").text());
  mPopulation=QString(myTopElement.firstChildElement("population").text()).toInt();
  mPeriod=LaUtils::xmlDecode(myTopElement.firstChildElement("period").text());
  mProjection=QString(myTopElement.firstChildElement("projection").text()).toInt();
  mEasting=QString(myTopElement.firstChildElement("easting").text()).toInt();
  mNorthing=QString(myTopElement.firstChildElement("northing").text()).toInt();
  myFlag = myTopElement.firstChildElement("euclideanDistance").text();
  if (myFlag=="1")
  {
    mEuclideanDistance=true;
  }
  else
  {
    mEuclideanDistance=false;
  }
  myFlag = myTopElement.firstChildElement("walkingTime").text();
  if (myFlag=="1")
  {
    mWalkingTime=true;
  }
  else
  {
    mWalkingTime=false;
  }
  myFlag = myTopElement.firstChildElement("pathDistance").text();
  if (myFlag=="1")
  {
    mPathDistance=true;
  }
  else
  {
    mPathDistance=false;
  }
  mPrecision=QString(myTopElement.firstChildElement("precision").text()).toInt();
  mDietPercent=QString(myTopElement.firstChildElement("dietPercent").text()).toInt();
  mPercentOfDietThatIsFromCrops=QString(myTopElement.firstChildElement("plantPercent").text()).toInt();
  mMeatPercent=QString(myTopElement.firstChildElement("meatPercent").text()).toInt();
  mCaloriesPerPersonDaily=QString(myTopElement.firstChildElement("caloriesPerPersonDaily").text()).toInt();
  mBaseOnPlants=QString(myTopElement.firstChildElement("baseOnPlants").text()).toInt();
  mIncludeDairy=QString(myTopElement.firstChildElement("includeDairy").text()).toInt();
  mLimitDairy=QString(myTopElement.firstChildElement("limitDairy").text()).toInt();
  mLimitDairyPercentage=QString(myTopElement.firstChildElement("limitDairyPercent").text()).toInt();
  mDairyUtilisation=QString(myTopElement.firstChildElement("dairyUtilisation").text()).toInt();
  return true;
}
void LaModel::logMessage (QString theMessage)
Broadcast to any listeners status messages. This is a convenience function. Internally it will do emit message(QString theMessage) each time it is called.
Parameters:
QString theMessage to be logged.
Definition at line 1085 of file lamodel.cpp.
References message().
Referenced by allocateFallowGrazingLand(), doTheFallowAllocation(), fromXml(), requiredValue(), toHtml(), toText(), and toXml().
{
  emit message(theMessage);
}
void LaModel::message (QString theMessage) [signal]
Send log info to any listeners.
Parameters:
QString the message to be logged.
Referenced by logMessage().
void LaModel::initialiseCaloriesProvidedByMeatMap () [private]
Initialise the map of calories needing to be provided by each individual animal.
void LaModel::initialiseCaloriesProvidedByMilkMap () [private]
Initialise the map of calories provided by milk.
void LaModel::initialiseCaloriesProvidedByCropsMap () [private]
Initialise the map of calories needing to be provided by each individual crop.
void LaModel::initialiseProductionRequiredAnimalsMap () [private]
Initialise the map of calories needing to be provided by each individual animal.
void LaModel::initialiseProductionRequiredCropsMap () [private]
Initialise the map of production levels needing to meet the calorie requirements
void LaModel::initialiseAreaTargetsAnimalsMap () [private]
Initialise the map of calories needing to be provided by each individual animal.
void LaModel::initialiseCalcsAnimalsMap () [private]
Initialise thecalculations map for Animals
void LaModel::initialiseCalcsCropsMap () [private]
Initialise thecalculations map for Crops
void LaModel::initialiseAreaTargetsCropsMap () [private]
Initialise the map of calories needing to be provided by each individual crop.
void LaModel::initialiseValueMap () [private]
Initialise the cumulative calories map to the calories required for each animal.
void LaModel::initialiseFodderMap () [private]
Initialise the cumulative calories map to the calories required for each animal.
Member Data Documentation
QMap<QString,float> LaModel::mCaloriesProvidedByMeatMap [private]
A map of calorie targets for animals.
Definition at line 401 of file lamodel.h.
Referenced by animalCalorieTargetsMap(), requiredValue(), and toHtmlCalorieAnimalTargets().
QMap<QString,float> LaModel::mCaloriesProvidedByMilkMap [private]
A map of calorie targets for animals.
Definition at line 409 of file lamodel.h.
QMap<QString,float> LaModel::mCaloriesProvidedByCropsMap [private]
A map of calorie targets for crops.
Definition at line 417 of file lamodel.h.
Referenced by cropCalorieTargetsMap(), and toHtmlCalorieCropTargets().
QMap<QString,float> LaModel::mProductionRequiredAnimalsMap [private]
A map of production targets for animals.
Definition at line 425 of file lamodel.h.
Referenced by animalProductionTargetsMap(), and toHtmlProductionAnimalTargets().
QMap<QString,float> LaModel::mProductionRequiredCropsMap [private]
A map of calorie targets for crops.
Definition at line 433 of file lamodel.h.
Referenced by cropProductionTargetsMap(), and toHtmlProductionCropTargets().
QMap<QString,float> LaModel::mAreaTargetsAnimalsMap [private]
A map of are targets for animals.
Definition at line 441 of file lamodel.h.
Referenced by animalAreaTargetsMap(), getAreaTargetsAnimalsMap(), and toHtmlAreaAnimalTargets().
QMap<QString,float> LaModel::mAreaTargetsCropsMap [private]
A map of are targets for crops.
Definition at line 456 of file lamodel.h.
Referenced by cropAreaTargetsMap(), getAreaTargetsCropsMap(), and toHtmlAreaCropTargets().
QMap<QString,float> LaModel::mValueMap [private]
A map of running totals for calorie requirements for animals. As we account for each resource (fallow, crop x, crop y etc) we can remove it from the cumulative total.
Definition at line 470 of file lamodel.h.
Referenced by animalFeedRequirementsMap(), and doTheFallowAllocation().
QMap<QString, LaFoodSourceMap> LaModel::mFodderMap [private]
Definition at line 476 of file lamodel.h.
QMap<QString,QString> LaModel::mCalcsAnimalsMap [private]
A map of all of the calculations for Animals
Definition at line 484 of file lamodel.h.
Referenced by calcsAnimalsMap().
QMap<QString,QString> LaModel::mCalcsCropsMap [private]
A map of all of the calculations for Crops
Definition at line 488 of file lamodel.h.
Referenced by calcsCropsMap().
QString LaModel::mName [private]
The name for this model
Definition at line 492 of file lamodel.h.
Referenced by fromXml(), LaModel(), name(), operator=(), setName(), toHtml(), toText(), and toXml().
float LaModel::mPopulation [private]
The population for this model
Definition at line 494 of file lamodel.h.
Referenced by doCalcsAnimalsFirstDairySeparate(), doCalcsAnimalsFirstIncludeDiary(), doCalcsPlantsFirstDairySeperate(), doCalcsPlantsFirstIncludeDairy(), fromXml(), getAreaTargetsAnimalsMapAFID(), LaModel(), operator=(), population(), setPopulation(), toHtml(), toText(), and toXml().
QString LaModel::mPeriod [private]
Period of the site
Definition at line 496 of file lamodel.h.
Referenced by fromXml(), LaModel(), operator=(), period(), setPeriod(), toHtml(), toText(), and toXml().
float LaModel::mProjection [private]
The projection of the data used in the model
Definition at line 498 of file lamodel.h.
Referenced by fromXml(), LaModel(), operator=(), projection(), setProjection(), toHtml(), toText(), and toXml().
float LaModel::mEasting [private]
East coordinate of the site being analysed
Definition at line 500 of file lamodel.h.
Referenced by easting(), fromXml(), LaModel(), operator=(), setEasting(), toHtml(), toText(), and toXml().
float LaModel::mNorthing [private]
North coordinate of the site being analysed
Definition at line 502 of file lamodel.h.
Referenced by fromXml(), LaModel(), northing(), operator=(), setNorthing(), toHtml(), toText(), and toXml().
bool LaModel::mEuclideanDistance [private]
Euclidean method of analysis
Definition at line 504 of file lamodel.h.
Referenced by euclideanDistance(), fromXml(), LaModel(), operator=(), setEuclideanDistance(), toHtml(), toText(), and toXml().
bool LaModel::mWalkingTime [private]
Walking time method of analysis
Definition at line 506 of file lamodel.h.
Referenced by fromXml(), LaModel(), operator=(), setWalkingTime(), toHtml(), toText(), toXml(), and walkingTime().
bool LaModel::mPathDistance [private]
Path distance method of analysis
Definition at line 508 of file lamodel.h.
Referenced by fromXml(), LaModel(), operator=(), pathDistance(), setPathDistance(), toHtml(), toText(), and toXml().
float LaModel::mPrecision [private]
Precision or degree of accuracy used to determine results
Definition at line 510 of file lamodel.h.
Referenced by fromXml(), LaModel(), operator=(), precision(), setPrecision(), toHtml(), toText(), and toXml().
float LaModel::mDietPercent [private]
Percentage of overall diet fulfilled by plant derived food
Definition at line 512 of file lamodel.h.
Referenced by dietPercent(), doCalcsAnimalsFirstIncludeDiary(), fromXml(), getAreaTargetsAnimalsMapAFID(), LaModel(), operator=(), setDietPercent(), toHtml(), toText(), and toXml().
float LaModel::mPercentOfDietThatIsFromCrops [private]
Percentage of Plant derived food fulfilled by domesticated crops
Definition at line 514 of file lamodel.h.
Referenced by doCalcsAnimalsFirstIncludeDiary(), fromXml(), getAreaTargetsAnimalsMapAFID(), LaModel(), operator=(), plantPercent(), setCropPercent(), toHtml(), toText(), and toXml().
float LaModel::mMeatPercent [private]
Percentage of Animal (meat) derived food fulfilled by domesticated animals
Definition at line 516 of file lamodel.h.
Referenced by doCalcsAnimalsFirstIncludeDiary(), fromXml(), getAreaTargetsAnimalsMapAFID(), LaModel(), meatPercent(), operator=(), setMeatPercent(), toHtml(), toText(), and toXml().
float LaModel::mCaloriesPerPersonDaily [private]
The number of calories required per person per day (average)
Definition at line 518 of file lamodel.h.
Referenced by caloriesPerPersonDaily(), doCalcsAnimalsFirstDairySeparate(), doCalcsAnimalsFirstIncludeDiary(), doCalcsPlantsFirstDairySeperate(), doCalcsPlantsFirstIncludeDairy(), fromXml(), getAreaTargetsAnimalsMapAFID(), LaModel(), operator=(), setCaloriesPerPersonDaily(), toHtml(), toText(), and toXml().
float LaModel::mDairyUtilisation [private]
The percent of dairy utilisation by the settlement
Definition at line 520 of file lamodel.h.
Referenced by dairyUtilisation(), doCalcsAnimalsFirstIncludeDiary(), fromXml(), getAreaTargetsAnimalsMapAFID(), LaModel(), operator=(), setDairyUtilisation(), toHtml(), toText(), and toXml().
float LaModel::mBaseOnPlants [private]
The percent of dairy utilisation by the settlement
Definition at line 523 of file lamodel.h.
Referenced by baseOnPlants(), fromXml(), LaModel(), operator=(), setBaseOnPlants(), toHtml(), toText(), and toXml().
bool LaModel::mIncludeDairy [private]
The percent of dairy utilisation by the settlement
Definition at line 525 of file lamodel.h.
Referenced by fromXml(), includeDairy(), LaModel(), operator=(), setIncludeDairy(), toHtml(), toText(), and toXml().
float LaModel::mLimitDairy [private]
The percent of dairy utilisation by the settlement
Definition at line 527 of file lamodel.h.
Referenced by fromXml(), LaModel(), limitDairy(), operator=(), setLimitDairy(), toHtml(), toText(), and toXml().
float LaModel::mLimitDairyPercentage [private]
The percent of dairy utilisation by the settlement
Definition at line 529 of file lamodel.h.
Referenced by fromXml(), LaModel(), limitDairyPercent(), operator=(), setLimitDairyPercent(), toHtml(), toText(), and toXml().
QMap<QString,QString> LaModel::mAnimalsMap [private]
A map to hold the associated animals and their parameters
Definition at line 532 of file lamodel.h.
Referenced by allocateFallowGrazingLand(), doCalcsAnimalsFirstIncludeDiary(), doTheFallowAllocation(), getAreaTargetsAnimalsMapAFID(), setAnimals(), toHtml(), toHtmlAreaAnimalTargets(), toHtmlCalorieAnimalTargets(), and toHtmlProductionAnimalTargets().
QMap<QString,QString> LaModel::mCropsMap [private]
A map to hold the associated crops and their parameters
Definition at line 534 of file lamodel.h.
Referenced by allocateFallowGrazingLand(), setCrops(), toHtml(), toHtmlAreaCropTargets(), toHtmlCalorieCropTargets(), and toHtmlProductionCropTargets().
AreaUnits LaModel::mCommonLandAreaUnits [private]
holder
Definition at line 536 of file lamodel.h.
Referenced by setCommonLandAreaUnits().
Status LaModel::mFallowStatus [private]
holder
Definition at line 538 of file lamodel.h.
Referenced by fallowStatus(), LaModel(), operator=(), and setFallowStatus().
float LaModel::mFallowRatio [private]
holder
Definition at line 540 of file lamodel.h.
Referenced by fallowRatio(), LaModel(), operator=(), and setFallowRatio().
float LaModel::mCommonGrazingLandValueTarget [private]
holder
Definition at line 542 of file lamodel.h.
float LaModel::mCommonGrazingValue [private]
holder
Definition at line 545 of file lamodel.h.
Referenced by foodValueCommonLand(), and setCommonLandValue().
float LaModel::mCommonGrazingLandAreaTarget [private]
holder
Definition at line 547 of file lamodel.h.
float LaModel::mCommonCropLand [private]
holder
Definition at line 549 of file lamodel.h.
HerdSize LaModel::mHerdSize [private]
holder
Definition at line 551 of file lamodel.h.
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/lamodel.h
dev/cpp/landuseanalyst/src/lib/lamodel.cpp