Landuse Analyst: LaGrassTest Class Reference
LaGrassTest Class Reference
Private Slots
void runCommand ()
void getMapsetList ()
void getRasterList ()
void createFrictionMap ()
Detailed Description
Definition at line 25 of file lagrasstest.cpp.
Member Function Documentation
void LaGrassTest::runCommand () [private, slot]
Definition at line 35 of file lagrasstest.cpp.
References LaGrass::runCommand().
{
  LaGrass myGrass;
  QString myCommand = "g.list";
  QStringList myArguments;
  myArguments << "type=rast";
    //first test with no error log param
  QString myResult = myGrass.runCommand(myCommand,myArguments);
  QVERIFY(!myResult.isEmpty());
    //now test with error log
  QString myErrors;
  myResult = myGrass.runCommand(myCommand,myArguments,myErrors);
  QVERIFY(!myResult.isEmpty());
  QVERIFY(myErrors.isEmpty());
}
void LaGrassTest::getMapsetList () [private, slot]
Definition at line 50 of file lagrasstest.cpp.
References LaGrass::getMapsetList().
{
  LaGrass myGrass;
  QStringList myList = myGrass.getMapsetList();
  QVERIFY(myList.count() > 0);
}
void LaGrassTest::getRasterList () [private, slot]
Definition at line 56 of file lagrasstest.cpp.
References LaGrass::getMapsetList(), and LaGrass::getRasterList().
{
  QStringList myList;
  LaGrass myGrass;
  QStringList myMapsetList = myGrass.getMapsetList();
  QStringListIterator myIterator(myMapsetList);
  while (myIterator.hasNext())
  {
      //append the raster names in this mapet to our full list
    myList << myGrass.getRasterList(myIterator.next());
  }
  qDebug() << "\n" << myList.join("\n").toLocal8Bit();
  QVERIFY(myList.count() > 0);
}
void LaGrassTest::createFrictionMap () [private, slot]
Definition at line 70 of file lagrasstest.cpp.
References LaGrass::createFrictionMap().
{
  LaGrass myGrass;
  myGrass.createFrictionMap("tim.dem","laFrictionMap");
}
The documentation for this class was generated from the following file:
dev/cpp/landuseanalyst/src/tests/lagrasstest.cpp