Landuse Analyst: LaCrop Class Reference
LaCrop Class Reference
#include <lacrop.h>
Public Member Functions
LaCrop ()
~LaCrop ()
LaCrop (const LaCrop &theCrop)
LaCrop & operator= (const LaCrop &theCrop)
QString name () const
QString description () const
int cropYield () const
int cropCalories () const
int fodderProduction () const
int fodderValue () const
AreaUnits areaUnits () const
EnergyType cropFodderEnergyType () const
QString imageFile () const
void setName (QString theName)
void setDescription (QString theDescription)
void setCropYield (int theKg)
void setCropCalories (int theCalories)
void setFodderProduction (int theKg)
void setCropFodderValue (int theValue)
void setAreaUnits (AreaUnits theAreaUnit)
void setCropFodderEnergyType (EnergyType theFodderEnergyType)
void setImageFile (QString theImageFileName)
QString toXml ()
QString toText ()
QString toHtml ()
bool fromXml (const QString theXml)
Private Attributes
QString mName
QString mDescription
int mCropYield
int mCropCalories
int mCropFodderProduction
int mCropFodderValue
AreaUnits mAreaUnits
EnergyType mCropFodderEnergyType
QString mImageFile
Detailed Description
An class to represent an crop
Author:
Tim Sutton, Jason Jorgenson
Definition at line 32 of file lacrop.h.
Constructor & Destructor Documentation
LaCrop::LaCrop ()
Constructor .
Definition at line 23 of file lacrop.cpp.
References mCropCalories, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mName, and LaGuid::setGuid().
               : LaSerialisable(), LaGuid()
{
  setGuid();
  mName="No Name Set";
  mDescription="Not Set";
  mCropYield=60;
  mCropCalories=3000;
  mCropFodderProduction=50;
  mCropFodderValue=1000;
}
LaCrop::~LaCrop ()
Desctructor .
Definition at line 34 of file lacrop.cpp.
{
}
LaCrop::LaCrop (const LaCrop & theCrop)
copy constructor
Definition at line 40 of file lacrop.cpp.
References areaUnits(), cropCalories(), cropFodderEnergyType(), cropYield(), description(), fodderProduction(), fodderValue(), LaGuid::guid(), imageFile(), mAreaUnits, mCropCalories, mCropFodderEnergyType, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mImageFile, mName, name(), and LaGuid::setGuid().
{
  mName=theCrop.name();
  mDescription=theCrop.description();
  setGuid(theCrop.guid());
  mCropYield=theCrop.cropYield();
  mCropCalories=theCrop.cropCalories();
  mCropFodderProduction=theCrop.fodderProduction();
  mCropFodderValue=theCrop.fodderValue();
  mCropFodderEnergyType=theCrop.cropFodderEnergyType();
  mAreaUnits=theCrop.areaUnits();
  mImageFile=theCrop.imageFile();
}
Member Function Documentation
LaCrop & LaCrop::operator= (const LaCrop & theCrop)
Assignement operator
Definition at line 54 of file lacrop.cpp.
References areaUnits(), cropCalories(), cropFodderEnergyType(), cropYield(), description(), fodderProduction(), fodderValue(), LaGuid::guid(), imageFile(), mAreaUnits, mCropCalories, mCropFodderEnergyType, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mImageFile, mName, name(), and LaGuid::setGuid().
{
  if (this == &theCrop) return *this;     // Gracefully handle self assignment
  mName=theCrop.name();
  mDescription=theCrop.description();
  setGuid(theCrop.guid());
  mCropYield=theCrop.cropYield();
  mCropCalories=theCrop.cropCalories();
  mCropFodderProduction=theCrop.fodderProduction();
  mCropFodderValue=theCrop.fodderValue();
  mCropFodderEnergyType=theCrop.cropFodderEnergyType();
  mAreaUnits=theCrop.areaUnits();
  mImageFile=theCrop.imageFile();
  return *this;
}
QString LaCrop::name () const
The name of this crop
Definition at line 71 of file lacrop.cpp.
References mName.
Referenced by LaGrassProcess::accept(), LaUtils::getAvailableCrops(), LaUtils::getCrop(), LaCrop(), LaCropParameterManager::LaCropParameterManager(), LaMainForm::loadCrops(), LaCropManager::on_toolCopy_clicked(), operator=(), LaAnimalParameterManager::populateFodder(), LaCropManager::refreshCropTable(), LaCropManager::selectCrop(), and LaCropManager::showCrop().
{
  return mName;
}
QString LaCrop::description () const
The description of this crop
Definition at line 76 of file lacrop.cpp.
References mDescription.
Referenced by LaCrop(), operator=(), and LaCropManager::showCrop().
{
  return mDescription;
}
int LaCrop::cropYield () const
Average amount in Kg of production per hectare or dunum
Definition at line 81 of file lacrop.cpp.
References mCropYield.
Referenced by LaModel::allocateFallowGrazingLand(), LaCrop(), operator=(), and LaCropManager::showCrop().
{
  return mCropYield;
}
int LaCrop::cropCalories () const
The food value in calories of 1 kg of crop product (ie/ grain/fruit)
Definition at line 85 of file lacrop.cpp.
References mCropCalories.
Referenced by LaModel::allocateFallowGrazingLand(), LaCrop(), operator=(), and LaCropManager::showCrop().
{
  return mCropCalories;
}
int LaCrop::fodderProduction () const
How many Kg of fodder is left for animal feed after harvesting
Definition at line 89 of file lacrop.cpp.
References mCropFodderProduction.
Referenced by LaCrop(), operator=(), and LaCropManager::showCrop().
{
  return mCropFodderProduction;
}
int LaCrop::fodderValue () const
The food value in calories of 1 Kg of fodder
Definition at line 93 of file lacrop.cpp.
References mCropFodderValue.
Referenced by LaCrop(), operator=(), and LaCropManager::showCrop().
{
  return mCropFodderValue;
}
AreaUnits LaCrop::areaUnits () const
All production levels based on either Kg/Dunum or Kg/Hectare 0==Dunum 1==Hectare
Definition at line 101 of file lacrop.cpp.
References mAreaUnits.
Referenced by LaModel::allocateFallowGrazingLand(), LaCrop(), operator=(), and LaCropManager::showCrop().
{
  return mAreaUnits;
}
EnergyType LaCrop::cropFodderEnergyType () const
Definition at line 97 of file lacrop.cpp.
References mCropFodderEnergyType.
Referenced by LaCrop(), operator=(), and LaCropManager::showCrop().
{
 return mCropFodderEnergyType;
}
QString LaCrop::imageFile () const
The image file associated with the animal
Definition at line 105 of file lacrop.cpp.
References mImageFile.
Referenced by LaGrassProcess::accept(), LaCropParameterManager::cellClicked(), LaMainForm::cropCalcClicked(), LaMainForm::cropCellClicked(), LaCrop(), LaCropParameterManager::on_cboCrop_changed(), operator=(), and LaCropManager::showCrop().
{
  return mImageFile;
}
void LaCrop::setName (QString theName)
Set the cropName
See also:
name()
Definition at line 109 of file lacrop.cpp.
References mName.
Referenced by LaCropManager::on_pbnApply_clicked(), and LaCropManager::on_toolCopy_clicked().
{
  mName=theName;
}
void LaCrop::setDescription (QString theDescription)
Set the animal description
See also:
description()
Definition at line 114 of file lacrop.cpp.
References mDescription.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mDescription=theDescription;
}
void LaCrop::setCropYield (int theKg)
Set cropYield as Kg/area
See also:
cropYield()
Definition at line 119 of file lacrop.cpp.
References mCropYield.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mCropYield=theKg;
}
void LaCrop::setCropCalories (int theCalories)
Set cropCalories as kg
See also:
cropCalories()
Definition at line 123 of file lacrop.cpp.
References mCropCalories.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mCropCalories=theInteger;
}
void LaCrop::setFodderProduction (int theKg)
Set the fodderProduction as Kg/area
See also:
fodderProduction()
Definition at line 127 of file lacrop.cpp.
References mCropFodderProduction.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mCropFodderProduction=theKg;
}
void LaCrop::setCropFodderValue (int theValue)
Set the fodderCalories with an integer
See also:
fodderCalories()
Definition at line 131 of file lacrop.cpp.
References mCropFodderValue.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mCropFodderValue=theValue;
}
void LaCrop::setAreaUnits (AreaUnits theAreaUnit)
Set the yieldUnits for area from index
See also:
yieldUnits()
Definition at line 139 of file lacrop.cpp.
References mAreaUnits.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mAreaUnits=theAreaUnit;
}
void LaCrop::setCropFodderEnergyType (EnergyType theFodderEnergyType)
Set the fodderEnergyType
See also:
fodderEnergyType()
Definition at line 135 of file lacrop.cpp.
References mCropFodderEnergyType.
{
  mCropFodderEnergyType=theEnergyType;
}
void LaCrop::setImageFile (QString theImageFileName)
Set the image file
See also:
imageFile()
Definition at line 143 of file lacrop.cpp.
References mImageFile.
Referenced by LaCropManager::on_pbnApply_clicked().
{
  mImageFile=theImageFileName;
}
QString LaCrop::toXml () [virtual]
Return an xml representation of this layer this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 190 of file lacrop.cpp.
References Dunum, LaGuid::guid(), Hectare, KCalories, mAreaUnits, mCropCalories, mCropFodderEnergyType, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mImageFile, mName, TDN, and LaUtils::xmlEncode().
{
  QString myString;
  myString+=QString("<crop guid=\"" + guid() + "\">\n");
    myString+=QString("  <name>" + LaUtils::xmlEncode(mName) + "</name>\n");
  myString+=QString("  <description>" + LaUtils::xmlEncode(mDescription) + "</description>\n");
  myString+=QString("  <cropYield>" + QString::number(mCropYield) + "</cropYield>\n");
  myString+=QString("  <cropCalories>" + QString::number(mCropCalories) + "</cropCalories>\n");
  myString+=QString("  <fodderProduction>" + QString::number(mCropFodderProduction) + "</fodderProduction>\n");
  myString+=QString("  <fodderCalories>" + QString::number(mCropFodderValue) + "</fodderCalories>\n");
  switch (mCropFodderEnergyType)
  {
    case KCalories:
      myString+=QString("  <cropFodderEnergyType>KCalories</cropFodderEnergyType>\n");
      break;
    case TDN:
      myString+=QString("  <cropFodderEnergyType>TDN</cropFodderEnergyType>\n");
      break;
  }
  switch (mAreaUnits)
  {
    case Dunum:
      myString+=QString("  <areaUnits>Dunum</areaUnits>\n");
      break;
    case Hectare:
      myString+=QString("  <areaUnits>Hectare</areaUnits>\n");
      break;
  }
  myString+=QString("  <imageFile>" + LaUtils::xmlEncode(mImageFile) + "</imageFile>\n");
  myString+=QString("</crop>\n");
  return myString;
}
QString LaCrop::toText ()
Return a plain text representation of this layer
Definition at line 225 of file lacrop.cpp.
References LaGuid::guid(), mAreaUnits, mCropCalories, mCropFodderEnergyType, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mName, and LaUtils::xmlEncode().
Referenced by LaCropManager::refreshCropTable().
{
  QString myString;
  myString+=QString("guid=>" + guid() + "\n");
  myString+=QString("name=>" + LaUtils::xmlEncode(mName) + "\n");
  myString+=QString("description=>" + LaUtils::xmlEncode(mDescription) + "\n");
  myString+=QString("cropYield=>" + QString::number(mCropYield) + "\n");
  myString+=QString("cropCalories=>" + QString::number(mCropCalories) + "\n");
  myString+=QString("fodderProduction=>" + QString::number(mCropFodderProduction) + "\n");
  myString+=QString("fodderCalories=>" + QString::number(mCropFodderValue) + "\n");
  QString myCropFodderEnergyType = (mCropFodderEnergyType==0) ? "KCalories" : "TDN";
  myString+=QString("cropFodderEnergyType=>" + myCropFodderEnergyType + "\n");
  QString myUnits = (mAreaUnits==0) ? "Dunum" : "Hectare";
  myString+=QString("yieldUnits=>" + myUnits + "\n");
  return myString;
}
QString LaCrop::toHtml ()
Return a html text representation of this layer
Definition at line 242 of file lacrop.cpp.
References mAreaUnits, mCropCalories, mCropFodderEnergyType, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mName, and LaUtils::xmlEncode().
Referenced by LaMainForm::cropCellClicked(), LaMainForm::showCropDefinitionReport(), and LaModel::toHtml().
{
  QString myString;
  myString+="<h3>Details for " + LaUtils::xmlEncode(mName) + "</h3>";
    //myString+="<p>GUID:" + guid() + "</p>";
  myString+="<table>";
  myString+="<tr><td><b>Description: </b></td><td>" + mDescription + "</td></tr>";
  myString+="<tr><td><b>Avg Yield: </b></td><td>" + QString::number(mCropYield) + "</td></tr>";
  myString+="<tr><td><b>Cals/Kg: </b></td><td>" + QString::number(mCropCalories) + "</td></tr>";
  QString myCropFodderEnergyType = (mCropFodderEnergyType==0) ? "KCalories" : "TDN";
  QString myUnits = (mAreaUnits==0) ? "Dunum" : "Hectare";
  myString+="<tr><td><b>Fodder (kg/" + myUnits + "): </b></td><td>" + QString::number(mCropFodderProduction) + "</td></tr>";
  myString+="<tr><td><b>Fodder Value/Kg: </b></td><td>" + QString::number(mCropFodderValue) + "</td></tr>";
  myString+="<tr><td><b>FodderEnergyType: </b></td><td>" + myCropFodderEnergyType + "</td></tr>";
  myString+="<tr><td><b>AreaUnits: </b></td><td>" + myUnits + "</td></tr>";
  myString+="</table>";
  return myString;
}
bool LaCrop::fromXml (const QString theXml) [virtual]
Read this object from xml and return result as true for success, false for failure.
See also:
LaSerialisable this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 147 of file lacrop.cpp.
References Dunum, Hectare, KCalories, mAreaUnits, mCropCalories, mCropFodderEnergyType, mCropFodderProduction, mCropFodderValue, mCropYield, mDescription, mImageFile, mName, LaGuid::setGuid(), TDN, and LaUtils::xmlDecode().
{
    //qDebug("Loading Crop from xml");
  QDomDocument myDocument("mydocument");
  myDocument.setContent(theXml);
  QDomElement myTopElement = myDocument.firstChildElement("crop");
  if (myTopElement.isNull())
  {
      //TODO - just make this a warning
     //qDebug("top element could not be found!");
  }
    //qDebug("Crop::fromXml - guid found : " + myTopElement.attribute("guid").toLocal8Bit());
  setGuid(myTopElement.attribute("guid"));
    //qDebug("Crop::fromXml - guid set to : " + guid().toLocal8Bit());
  mName=LaUtils::xmlDecode(myTopElement.firstChildElement("name").text());
  mDescription=LaUtils::xmlDecode(myTopElement.firstChildElement("description").text());
  mCropYield=QString(myTopElement.firstChildElement("cropYield").text()).toInt();
  mCropCalories=QString(myTopElement.firstChildElement("cropCalories").text()).toInt();
  mCropFodderProduction=QString(myTopElement.firstChildElement("fodderProduction").text()).toInt();
  mCropFodderValue=QString(myTopElement.firstChildElement("fodderCalories").text()).toInt();
  QString myCropFodderEnergyType = QString(myTopElement.firstChildElement("cropFodderEnergyType").text());
  if (myCropFodderEnergyType == "KCalories")
  {
    mCropFodderEnergyType=KCalories;
  }
  else if (myCropFodderEnergyType == "TDN")
  {
    mCropFodderEnergyType=TDN;
  }
    QString myAreaUnits = QString(myTopElement.firstChildElement("areaUnits").text());
  if (myAreaUnits == "Dunum")
  {
    mAreaUnits=Dunum;
  }
  else if (myAreaUnits == "Hectare")
  {
    mAreaUnits=Hectare;
  }
  mImageFile=QString(myTopElement.firstChildElement("imageFile").text());
  return true;
}
Member Data Documentation
QString LaCrop::mName [private]
The name for this crop
Definition at line 140 of file lacrop.h.
Referenced by fromXml(), LaCrop(), name(), operator=(), setName(), toHtml(), toText(), and toXml().
QString LaCrop::mDescription [private]
The description for this animal
Definition at line 143 of file lacrop.h.
Referenced by description(), fromXml(), LaCrop(), operator=(), setDescription(), toHtml(), toText(), and toXml().
int LaCrop::mCropYield [private]
Set cropYield as Kg/area
See also:
cropYield()
Definition at line 148 of file lacrop.h.
Referenced by cropYield(), fromXml(), LaCrop(), operator=(), setCropYield(), toHtml(), toText(), and toXml().
int LaCrop::mCropCalories [private]
Set cropCalories as kg
See also:
cropCalories()
Definition at line 153 of file lacrop.h.
Referenced by cropCalories(), fromXml(), LaCrop(), operator=(), setCropCalories(), toHtml(), toText(), and toXml().
int LaCrop::mCropFodderProduction [private]
Set the fodderProduction as Kg/area
See also:
fodderProduction()
Definition at line 158 of file lacrop.h.
Referenced by fodderProduction(), fromXml(), LaCrop(), operator=(), setFodderProduction(), toHtml(), toText(), and toXml().
int LaCrop::mCropFodderValue [private]
Set the fodderCalories with an integer
See also:
fodderCalories()
Definition at line 163 of file lacrop.h.
Referenced by fodderValue(), fromXml(), LaCrop(), operator=(), setCropFodderValue(), toHtml(), toText(), and toXml().
AreaUnits LaCrop::mAreaUnits [private]
Set the yieldUnits for area from index
See also:
yieldUnits()
Definition at line 168 of file lacrop.h.
Referenced by areaUnits(), fromXml(), LaCrop(), operator=(), setAreaUnits(), toHtml(), toText(), and toXml().
EnergyType LaCrop::mCropFodderEnergyType [private]
Set the fodderEnergyType
See also:
fodderEnergyType()
Definition at line 173 of file lacrop.h.
Referenced by cropFodderEnergyType(), fromXml(), LaCrop(), operator=(), setCropFodderEnergyType(), toHtml(), toText(), and toXml().
QString LaCrop::mImageFile [private]
Definition at line 176 of file lacrop.h.
Referenced by fromXml(), imageFile(), LaCrop(), operator=(), setImageFile(), and toXml().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/lacrop.h
dev/cpp/landuseanalyst/src/lib/lacrop.cpp