Landuse Analyst: LaGrassProcess Class Reference
LaGrassProcess Class Reference
#include <lagrassprocess.h>
Public Slots
void accept ()
void setPbarTargetRange (int theTarget)
void setPbarOverallRange (int theOverall)
void updateCurrentProgress (int theArea)
void updateOverallProgress (int theStep)
void writeGrassMessage (QString theGrassMessage)
void updatePreview (QString thePreviewFile)
void updateGraphic (QString theGraphicFile)
void toggleBusyProgressBar (bool theStatus)
float analyseModel (QString theItem, QString theRasterMask, int theAreaTarget)
LandFound getSearchStatus (int theCurrentlyContainedArea, int theAreaTarget, int thePrecision)
QString generateFilename (QString theItemName, float theExtent, int theAreaTarget)
Public Member Functions
LaGrassProcess (LaRasterInfo theRasterInfo, QPair< float, float > theCoordinates, QPair< QMap< QString, float >, QMap< QString, float > > &thePairOfAreaTargetMaps, QWidget *parent=0, Qt::WFlags fl=0)
~LaGrassProcess ()
Private Member Functions
void readSettings ()
void writeSettings ()
Private Attributes
int mCurrentAreaTarget
int mSearches
QMap< QString, float > mCropAreaTargetsMap
QMap< QString, float > mAnimalAreaTargetsMap
QPair< float, float > mCoordinates
QString mDEM
QString mCommonGrazingRaster
QString mCommonCropRaster
QString mMapset
Detailed Description
This is the grass process gui class
Author:
Jason Jorgenson
Definition at line 36 of file lagrassprocess.h.
Constructor & Destructor Documentation
LaGrassProcess::LaGrassProcess (LaRasterInfo theRasterInfo, QPair< float, float > theCoordinates, QPair< QMap< QString, float >, QMap< QString, float > > & thePairOfAreaTargetMaps, QWidget * parent = 0, Qt::WFlags fl = 0)
Definition at line 37 of file lagrassprocess.cpp.
References mAnimalAreaTargetsMap, mCommonCropRaster, mCommonGrazingRaster, mCoordinates, mCropAreaTargetsMap, mDEM, mMapset, and readSettings().
: QDialog(parent,fl)
{
    //required by Qt4 to initialise the ui
  setupUi(this);
  readSettings();
    //connect ( buttonBox, SIGNAL(rejected()), this, SLOT(reject()) );
  mAnimalAreaTargetsMap = thePairOfAreaTargetMaps.first;
  mCropAreaTargetsMap = thePairOfAreaTargetMaps.second;
  mDEM = (theRasterInfo.first).first;
  mMapset = (theRasterInfo.first).second;
  mCommonCropRaster = (theRasterInfo.second).first;
  mCommonGrazingRaster = (theRasterInfo.second).second;
  mCoordinates = theCoordinates;
  lblGraphic->setScaledContents(true);
  lblPreview->setScaledContents(true);
  pbarTarget->setRange(0,100);
  pbarTarget->setValue(0);
  pbarOverall->setRange(0,100);
  pbarOverall->setValue(0);
  lblCurrentArea->setText("0");
  lblAreaTarget->setText(0);
}
LaGrassProcess::~LaGrassProcess ()
Definition at line 63 of file lagrassprocess.cpp.
References writeSettings().
{
  writeSettings();
}
Member Function Documentation
void LaGrassProcess::accept () [slot]
when called starts the grass analysis
Definition at line 84 of file lagrassprocess.cpp.
References analyseModel(), LaGrass::createInverseMask(), LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaUtils::getCrop(), LaUtils::getCropParameter(), LaMainForm::getMatchingAnimalParameterGuid(), LaMainForm::getMatchingCropParameterGuid(), LaAnimal::imageFile(), LaCrop::imageFile(), LaGrass::makeWalkCost(), mAnimalAreaTargetsMap, mCommonCropRaster, mCommonGrazingRaster, mCoordinates, mCropAreaTargetsMap, mDEM, LaGrass::mergeMaps(), mMapset, LaAnimal::name(), LaCrop::name(), LaAnimalParameter::rasterName(), LaCropParameter::rasterName(), setPbarOverallRange(), setPbarTargetRange(), toggleBusyProgressBar(), updateOverallProgress(), LaAnimalParameter::useCommonGrazingLand(), and LaCropParameter::useCommonLand().
{
    // first, we need to remove the items from the map
    // that use Common Land, and then determine the
    // number of items in the map to set the overall
    // progress bar (number of steps)
  float myMinimumCost = 0.;
  tbGrass->setText("Creating Cost Surface Raster...");
  tbGrass->repaint();
  toggleBusyProgressBar(true);
  int myOverallProgress = 1;
  LaMainForm myMainForm;
  QMapIterator<QString, float > myCropCounter(mCropAreaTargetsMap);
  while (myCropCounter.hasNext())
  {
    myCropCounter.next();
    if (myCropCounter.key() != "CommonTarget")
    {
        // check for use of common targets
        // if it does not use common target then add to count
      QString myCropGuid = myCropCounter.key();
      QString myCropParameterGuid = myMainForm.getMatchingCropParameterGuid(myCropGuid);
      LaCropParameter myCropParameter = LaUtils::getCropParameter(myCropParameterGuid);
      bool myCommonLandUsed = myCropParameter.useCommonLand();
      if (myCommonLandUsed)
      {
        qDebug() << "removing from area map: "  << myCropGuid;
        mCropAreaTargetsMap.remove(myCropGuid);
      }
    }
  }
  QMapIterator<QString, float > myAnimalCounter(mAnimalAreaTargetsMap);
  while (myAnimalCounter.hasNext())
  {
    myAnimalCounter.next();
    if (myAnimalCounter.key() != "CommonTarget")
    {
        // check for use of common targets
        // if it does not use common target then add to count
      QString myAnimalGuid = myAnimalCounter.key();
      QString myAnimalParameterGuid = myMainForm.getMatchingAnimalParameterGuid(myAnimalGuid);
      LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
      bool myCommonLandUsed = myAnimalParameter.useCommonGrazingLand();
      if (myCommonLandUsed)
      {
        qDebug() << "removing from area map: "  << myAnimalGuid;
        mAnimalAreaTargetsMap.remove(myAnimalGuid);
      }
    }
  }
  int myNumberOfSearches = mCropAreaTargetsMap.size() + mAnimalAreaTargetsMap.size();
  setPbarOverallRange(myNumberOfSearches);
    // create cost surface maps
  LaGrass myGrass;
  int myEasting = mCoordinates.first;
  int myNorthing = mCoordinates.second;
  myGrass.makeWalkCost(myEasting, myNorthing, mDEM);
  tbGrass->append("Cost Surface Generation complete.");
  tbGrass->repaint();
  QMapIterator<QString, float > myCropIterator(mCropAreaTargetsMap);
  while (myCropIterator.hasNext())
  {
    myCropIterator.next();
    if (myCropIterator.key() != "CommonTarget")
    {
      LaCrop myCrop = LaUtils::getCrop(myCropIterator.key());
        // set the images and area target label
        lblGraphic->setPixmap(myCrop.imageFile());
        lblGraphic->repaint();
          //lblPreview->setPixmap(convertedRasterFile);
          //lblPreview->repaint();
        lblAreaTarget->setText("Target:\n" + QString::number(myCropIterator.value()));
        lblAreaTarget->repaint();
      int myAreaTarget = myCropIterator.value();
      QString myName = myCrop.name();
      LaMainForm myMainForm;
      QString myCropParameterGuid = myMainForm.getMatchingCropParameterGuid(myCropIterator.key());
      LaCropParameter myCropParameter = LaUtils::getCropParameter(myCropParameterGuid);
      QString myCropRasterFile = myCropParameter.rasterName();
      setPbarTargetRange(17);
        //for (int i=0; i<18; i++)
        //{
        //  pbarTarget->setValue(i);
        //}
        // go analyse the stuff...
      qDebug() << "myAreaTarget: " << myAreaTarget;
      qDebug() << "myName: " << myName;
      analyseModel(myName, myCropRasterFile, myAreaTarget);
      updateOverallProgress(myOverallProgress);
      myOverallProgress++;
    }
    else
    {
        //do stuff for commonTarget
        QString myCommonPixMap = ":/commonTarget.png";
        lblGraphic->setPixmap(myCommonPixMap);
        lblGraphic->repaint();
        lblAreaTarget->setText("Target:\n" + QString::number(myCropIterator.value()));
        lblAreaTarget->repaint();
      myMinimumCost = analyseModel("commonCrop", mCommonCropRaster, myCropIterator.value());
      updateOverallProgress(myOverallProgress);
      myOverallProgress++;
      myGrass.createInverseMask(myMinimumCost, mCommonCropRaster);   // creates laLeftOver
    }
  }
  QMapIterator<QString, float > myAnimalIterator(mAnimalAreaTargetsMap);
  while (myAnimalIterator.hasNext())
  {
    myAnimalIterator.next();
    if (myAnimalIterator.key() != "CommonTarget")
    {
      LaAnimal myAnimal = LaUtils::getAnimal(myAnimalIterator.key());
        // set the images and area target label
        lblGraphic->setPixmap(myAnimal.imageFile());
        lblGraphic->repaint();
          //lblPreview->setPixmap(convertedRasterFile);
          //lblPreview->repaint();
        lblAreaTarget->setText("Target:\n" + QString::number(myAnimalIterator.value()));
        lblAreaTarget->repaint();
      QString myName = myAnimal.name();
      LaMainForm myMainForm;
      QString myAnimalParameterGuid = myMainForm.getMatchingAnimalParameterGuid(myAnimalIterator.key());
      LaAnimalParameter myAnimalParameter = LaUtils::getAnimalParameter(myAnimalParameterGuid);
      QString myAnimalRasterFile = myAnimalParameter.rasterName();
      setPbarTargetRange(17);
        // go analyse the stuff...
      int myAreaTarget = myAnimalIterator.value();
        // hard coded to add the leftover mask to the common animal mask
      myGrass.mergeMaps(myAnimalRasterFile);
      analyseModel(myName, "laCombinedMasks@" + mMapset, myAreaTarget);
      updateOverallProgress(myOverallProgress);
      myOverallProgress++;
    }
    else
    {
        //do stuff for commonTarget
      myGrass.mergeMaps(mCommonGrazingRaster);   // creates laCombinedMasks
        QString myCommonPixMap = ":/commonTarget.png";
        lblGraphic->setPixmap(myCommonPixMap);
        lblGraphic->repaint();
        lblAreaTarget->setText("Target:\n" + QString::number(myAnimalIterator.value()));
        lblAreaTarget->repaint();
        // hard coded to add the leftover mask to the common animal mask
      analyseModel("commonGrazing", "laCombinedMasks@" + mMapset, myAnimalIterator.value());
      updateOverallProgress(myOverallProgress);
      myOverallProgress++;
    }
  }
  toggleBusyProgressBar(false);
}
void LaGrassProcess::setPbarTargetRange (int theTarget) [slot]
aborts the grass analysis process
Definition at line 252 of file lagrassprocess.cpp.
Referenced by accept(), and analyseModel().
{
  pbarTarget->reset();
  pbarTarget->setRange(0,theTarget);
  pbarTarget->setValue(0);
  lblAreaTarget->setText("Target:\n" + QString::number(theTarget));
}
void LaGrassProcess::setPbarOverallRange (int theOverall) [slot]
Definition at line 260 of file lagrassprocess.cpp.
Referenced by accept().
{
  pbarOverall->reset();
  pbarOverall->setRange(0,theOverall);
  pbarOverall->setValue(0);
}
void LaGrassProcess::updateCurrentProgress (int theArea) [slot]
Definition at line 272 of file lagrassprocess.cpp.
Referenced by analyseModel().
{
  pbarTarget->setValue(theArea);
  lblCurrentArea->setText(QString::number(theArea));
}
void LaGrassProcess::updateOverallProgress (int theStep) [slot]
Definition at line 278 of file lagrassprocess.cpp.
Referenced by accept().
{
  pbarOverall->setValue(theStep);
}
void LaGrassProcess::writeGrassMessage (QString theGrassMessage) [slot]
Definition at line 283 of file lagrassprocess.cpp.
{
  tbGrass->append(theGrassMessage);
}
void LaGrassProcess::updatePreview (QString thePreviewFile) [slot]
Definition at line 288 of file lagrassprocess.cpp.
{
  lblPreview->setPixmap(thePreviewFile);
}
void LaGrassProcess::updateGraphic (QString theGraphicFile) [slot]
Definition at line 293 of file lagrassprocess.cpp.
{
  lblGraphic->setPixmap(theGraphicFile);
}
void LaGrassProcess::toggleBusyProgressBar (bool theStatus) [slot]
Definition at line 298 of file lagrassprocess.cpp.
Referenced by accept().
{
  switch (theStatus)
  {
    case true:    // turn it on
                  // set the progress bar to move (min,max = 0,0)
                  //pbarBusy->setMinimum(0);
                pbarBusy->setMaximum(0);
                pbarBusy->repaint();
                break;
    case false:   // shut it off
                  // set the progress bar to not move (min,max = 0,1)
                  //pbarBusy->setMinimum(0);
                pbarBusy->setMaximum(1);
                break;
  }
}
float LaGrassProcess::analyseModel (QString theItem, QString theRasterMask, int theAreaTarget) [slot]
Definition at line 316 of file lagrassprocess.cpp.
References LaGrass::copyMap(), LaGrass::createMask(), FoundTarget, generateFilename(), LaGrass::getArea(), getSearchStatus(), NotEnough, LaGrass::reclass(), setPbarTargetRange(), TooMuch, and updateCurrentProgress().
Referenced by accept().
{
  LaGrass myGrass;
   float myFirst = 0;
   float myLast=120000;
   int myAreaTarget = theAreaTarget;
   float myCurrentlyContainedArea = 0.0;
   int myPrecision = 5;   // change this to real value
   int myStatusCount = 0;
   LandFound mySearchStatus = NotEnough;
   float myMid;
   setPbarTargetRange(17);
   while (myFirst <= myLast)
  {
    updateCurrentProgress(myStatusCount);
    myStatusCount++;
    myMid = (myFirst + myLast) / 2.;    // compute mid point.
      // reclass with 1 to midpoint and null beyond and then check results
      //    echo "0 thru $step = 1" | r.reclass input=$cost output=cost.reclass --o
      //    r.stats -n -a fs=- input=cost.reclass > $TMP1
    qDebug() << "midpoint value: " << myMid;
    qDebug() << "midpoint valueas int: " << static_cast<int>(myMid);
    myGrass.reclass("laWalkCost", static_cast<int>(myMid));   // makes a raster called laCostMapReclassed
    myGrass.createMask("laCostMapReclassed" , theRasterMask);   // creates tmpMask
    myCurrentlyContainedArea = myGrass.getArea("tmpMask");
      // find out if the contained area is within acceptable range
    mySearchStatus = getSearchStatus(static_cast<int>(myCurrentlyContainedArea), myAreaTarget, myPrecision);
    switch (mySearchStatus)
    {
      case NotEnough:
            qDebug() << "Not Close Enough. (low) Current is " << myCurrentlyContainedArea << "Needed: " << myAreaTarget;
            myFirst = myMid + 1.;    // repeat search in top half.
            break;;
      case TooMuch:
            qDebug() << "Not Close Enough. (high) Current is " << myCurrentlyContainedArea << "Needed: " << myAreaTarget;
            myLast = myMid - 1.;   // repeat search in bottom half.
            break;
      case FoundTarget:
              // found it. break out of loop   //  ///
              // copy final raster to permanentRaster
            qDebug() << "TARGET FOUND!  Current is " << myCurrentlyContainedArea << "Actual Needed: " << myAreaTarget;
            qDebug() << "which falls within the precision range";
            QString myRasterName = generateFilename(theItemName, myMid, myAreaTarget);
            myGrass.copyMap("tmpMask", myRasterName);
            updateCurrentProgress(myStatusCount);
            myFirst = myLast+1.;
            break;
    }
  }
  return myMid;
}
LandFound LaGrassProcess::getSearchStatus (int theCurrentlyContainedArea, int theAreaTarget, int thePrecision) [slot]
Definition at line 408 of file lagrassprocess.cpp.
References FoundTarget, NotEnough, and TooMuch.
Referenced by analyseModel().
{
  LandFound myStatus;
  float myPrecision=5.;    //get the real value for precision
  float myAcceptableRange=(theAreaTarget*myPrecision*0.01)/2.0;
  float myMinimumAcceptable = theAreaTarget - myAcceptableRange;
  float myMaximumAcceptable = theAreaTarget + myAcceptableRange;
  qDebug() << "myAcceptableRange:" << myAcceptableRange;
  qDebug() << "myMinimumAcceptable:" << myMinimumAcceptable;
  qDebug() << "myMaximumAcceptable:" << myMaximumAcceptable;
  if (theCurrentlyContainedArea >= myMinimumAcceptable)
    {
      qDebug() << "the currently contained area of " << theCurrentlyContainedArea << "is >= the MIN target of " << theAreaTarget;
      if (theCurrentlyContainedArea <= myMaximumAcceptable)
      {
      qDebug() << "the currently contained area of " << theCurrentlyContainedArea << "is also <= the MAX target of " << theAreaTarget;
        myStatus = FoundTarget;
      }
      else
      {
      qDebug() << "the currently contained area of " << theCurrentlyContainedArea << "is > the MAX target of " << theAreaTarget;
        myStatus = TooMuch;
      }
    }
  else
    {
      qDebug() << "the currently contained area of " << theCurrentlyContainedArea << "is < the MIN target of " << theAreaTarget;
      myStatus = NotEnough;
    }
  return myStatus;
}
QString LaGrassProcess::generateFilename (QString theItemName, float theExtent, int theAreaTarget) [slot]
Definition at line 377 of file lagrassprocess.cpp.
Referenced by analyseModel().
{
  QString myPeriod="";
  QString myPopulation="";
  QString myDietRatio="";
  QString myPeriodSetting = cbPeriod->currentText();
  QString myPopulationSetting = cbPopulation->currentText();
  QString myDietRatioSetting = cbDietRatio->currentText();
  QString myOtherText = leOtherText->text();
  if (myPeriodSetting == "Chalcolithic") {myPeriod = "Chalco";}
  else if (myPeriodSetting == "EEB1") {myPeriod = "EEB1";}
  else if (myPeriodSetting == "LEB1") {myPeriod = "LEB1";}
  if (myPopulationSetting == "Max") {myPopulation = "MaxPop";}
  else if (myPopulationSetting == "Min") {myPopulation = "MinPop";}
  if (myDietRatioSetting == "70:30") {myDietRatio = "DR7030";}
  else if (myDietRatioSetting == "80:20") {myDietRatio = "DR8020";}
  else if (myDietRatioSetting == "90:10") {myDietRatio = "DR9010";}
  QString myExtent = QString::number(static_cast<int>(theExtent));
  QString myArea = QString::number(theAreaTarget);
  QString myDescriptor = myOtherText + myPeriod + myPopulation + myDietRatio;
  QString myRasterName = theItemName + "_" + myDescriptor + "Extent" + myExtent + "Area" + myArea;
  return myRasterName;
}
void LaGrassProcess::readSettings () [private]
Definition at line 68 of file lagrassprocess.cpp.
Referenced by LaGrassProcess().
{
  QSettings mySettings;
  QPoint pos = mySettings.value("mainwindow/pos", QPoint(200, 200)).toPoint();
  QSize size = mySettings.value("mainwindow/size", QSize(200, 400)).toSize();
  resize(size);
  move(pos);
}
void LaGrassProcess::writeSettings () [private]
Definition at line 77 of file lagrassprocess.cpp.
Referenced by ~LaGrassProcess().
{
  QSettings mySettings;
  mySettings.setValue("mainwindow/pos", pos());
  mySettings.setValue("mainwindow/size", size());
}
Member Data Documentation
int LaGrassProcess::mCurrentAreaTarget [private]
Definition at line 68 of file lagrassprocess.h.
int LaGrassProcess::mSearches [private]
Definition at line 69 of file lagrassprocess.h.
QMap<QString, float> LaGrassProcess::mCropAreaTargetsMap [private]
Definition at line 71 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
QMap<QString, float> LaGrassProcess::mAnimalAreaTargetsMap [private]
Definition at line 72 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
QPair<float, float> LaGrassProcess::mCoordinates [private]
Definition at line 73 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
QString LaGrassProcess::mDEM [private]
Definition at line 74 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
QString LaGrassProcess::mCommonGrazingRaster [private]
Definition at line 75 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
QString LaGrassProcess::mCommonCropRaster [private]
Definition at line 76 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
QString LaGrassProcess::mMapset [private]
Definition at line 77 of file lagrassprocess.h.
Referenced by accept(), and LaGrassProcess().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/gui/lagrassprocess.h
dev/cpp/landuseanalyst/src/gui/lagrassprocess.cpp