Landuse Analyst: LaSerialisable Class Reference
LaSerialisable Class Reference
#include <laserialisable.h>
Public Member Functions
LaSerialisable ()
virtual ~LaSerialisable ()
virtual QString toXml ()=0
virtual bool toXmlFile (const QString theFileName)
virtual bool fromXml (const QString theXml)=0
virtual bool fromXmlFile (const QString theFileName)
Detailed Description
An abstract base class for any class that is serialiseable to xml
Author:
Tim Sutton
Definition at line 28 of file laserialisable.h.
Constructor & Destructor Documentation
LaSerialisable::LaSerialisable ()
Constructor .
Definition at line 24 of file laserialisable.cpp.
{
}
LaSerialisable::~LaSerialisable () [virtual]
Desctructor .
Definition at line 27 of file laserialisable.cpp.
{
}
Member Function Documentation
virtual QString LaSerialisable::toXml () [pure virtual]
Write this object to xml and return result as qstring (virtual) .
Implemented in LaAnimal, LaAnimalParameter, LaCrop, LaCropParameter, and LaModel.
Referenced by toXmlFile().
bool LaSerialisable::toXmlFile (const QString theFileName) [virtual]
Write this object to xml and return result as qstring (virtual). We provide a basic default implementation where given a file name, we will write the serialised xml to that file. Internally it uses toXml() method above so that must be properly implemented.
Definition at line 30 of file laserialisable.cpp.
References toXml().
Referenced by LaCropParameterManager::on_pbnApply_clicked(), LaCropManager::on_pbnApply_clicked(), LaAnimalParameterManager::on_pbnApply_clicked(), LaAnimalManager::on_pbnApply_clicked(), LaMainForm::on_pushButtonSave_clicked(), LaCropParameterManager::on_toolCopy_clicked(), LaCropManager::on_toolCopy_clicked(), LaAnimalParameterManager::on_toolCopy_clicked(), and LaAnimalManager::on_toolCopy_clicked().
{
  bool myResult = false;
  QFile myFile( theFileName );
  if ( myFile.open( QIODevice::WriteOnly ) )
  {
    QTextStream myQTextStream( &myFile );
    myQTextStream << this->toXml();
    myFile.close();
    myResult=true;
  }
  else
  {
      //@TODO Error handler!
    myResult=false;
  }
  return myResult ;
}
virtual bool LaSerialisable::fromXml (const QString theXml) [pure virtual]
Read this object from xml and return result as true for success, false for failure (virtual).
Implemented in LaAnimal, LaAnimalParameter, LaCrop, LaCropParameter, and LaModel.
Referenced by fromXmlFile().
bool LaSerialisable::fromXmlFile (const QString theFileName) [virtual]
Read this object from xml in a file and return result as true for success, false for failure. Internally it uses fromXml(QString) method above so that must be properly implemented.
Definition at line 50 of file laserialisable.cpp.
References fromXml().
Referenced by LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaUtils::getAvailableAnimalParameters(), LaUtils::getAvailableAnimals(), LaUtils::getAvailableCropParameters(), LaUtils::getAvailableCrops(), LaUtils::getCrop(), LaUtils::getCropParameter(), LaCropManager::on_pushButtonLoad_clicked(), LaAnimalManager::on_pushButtonLoad_clicked(), LaCropParameterManager::on_toolCopy_clicked(), LaCropManager::on_toolCopy_clicked(), LaAnimalParameterManager::on_toolCopy_clicked(), LaAnimalManager::on_toolCopy_clicked(), LaModelTest::run(), LaAnimalManager::selectAnimal(), LaAnimalParameterManager::selectAnimalParameter(), LaCropManager::selectCrop(), and LaCropParameterManager::selectCropParameter().
{
  bool myResult = false;
  QFile myFile( theFileName );
  if ( myFile.open( QIODevice::ReadOnly ) )
  {
    myResult=this->fromXml(myFile.readAll());
    myFile.close();
  }
  else
  {
    qDebug() << "Failed to open "  << theFileName << " for deserialisation ";
      //@TODO Error handler!
    myResult=false;
  }
  return myResult ;
}
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/laserialisable.h
dev/cpp/landuseanalyst/src/lib/laserialisable.cpp