# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arkygeek/dev/QGisPlugins/landuseanalyst/landuse_analyst/src/ui/laanimalparametermanagerbase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LaAnimalParameterManagerBase(object):
    def setupUi(self, LaAnimalParameterManagerBase):
        LaAnimalParameterManagerBase.setObjectName("LaAnimalParameterManagerBase")
        LaAnimalParameterManagerBase.resize(587, 686)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LaAnimalParameterManagerBase.sizePolicy().hasHeightForWidth())
        LaAnimalParameterManagerBase.setSizePolicy(sizePolicy)
        LaAnimalParameterManagerBase.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/la_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LaAnimalParameterManagerBase.setWindowIcon(icon)
        self.gridLayout_4 = QtWidgets.QGridLayout(LaAnimalParameterManagerBase)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(LaAnimalParameterManagerBase)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.grpProfiles = QtWidgets.QGroupBox(self.splitter)
        self.grpProfiles.setObjectName("grpProfiles")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grpProfiles)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tblAnimalParameterProfiles = QtWidgets.QTableWidget(self.grpProfiles)
        self.tblAnimalParameterProfiles.setAlternatingRowColors(True)
        self.tblAnimalParameterProfiles.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAnimalParameterProfiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAnimalParameterProfiles.setObjectName("tblAnimalParameterProfiles")
        self.tblAnimalParameterProfiles.setColumnCount(2)
        self.tblAnimalParameterProfiles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAnimalParameterProfiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAnimalParameterProfiles.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tblAnimalParameterProfiles, 0, 0, 1, 1)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.toolCopy = QtWidgets.QToolButton(self.grpProfiles)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCopy.setIcon(icon1)
        self.toolCopy.setObjectName("toolCopy")
        self.gridlayout.addWidget(self.toolCopy, 3, 1, 1, 1)
        self.toolDelete = QtWidgets.QToolButton(self.grpProfiles)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolDelete.setIcon(icon2)
        self.toolDelete.setObjectName("toolDelete")
        self.gridlayout.addWidget(self.toolDelete, 3, 2, 1, 1)
        self.toolNew = QtWidgets.QToolButton(self.grpProfiles)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolNew.setIcon(icon3)
        self.toolNew.setObjectName("toolNew")
        self.gridlayout.addWidget(self.toolNew, 3, 0, 1, 1)
        self.lblAnimalPic = QtWidgets.QLabel(self.grpProfiles)
        self.lblAnimalPic.setMinimumSize(QtCore.QSize(100, 100))
        self.lblAnimalPic.setMaximumSize(QtCore.QSize(100, 100))
        self.lblAnimalPic.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAnimalPic.setObjectName("lblAnimalPic")
        self.gridlayout.addWidget(self.lblAnimalPic, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridlayout, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout1 = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.leName = QtWidgets.QLineEdit(self.groupBox)
        self.leName.setMinimumSize(QtCore.QSize(0, 21))
        self.leName.setObjectName("leName")
        self.hboxlayout.addWidget(self.leName)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 0, 1, 2)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.hboxlayout1.addWidget(self.label_4)
        self.leDescription = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDescription.sizePolicy().hasHeightForWidth())
        self.leDescription.setSizePolicy(sizePolicy)
        self.leDescription.setMinimumSize(QtCore.QSize(0, 21))
        self.leDescription.setObjectName("leDescription")
        self.hboxlayout1.addWidget(self.leDescription)
        self.gridlayout1.addLayout(self.hboxlayout1, 1, 0, 1, 2)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.hboxlayout2.addWidget(self.label_2)
        self.cboAnimal = QtWidgets.QComboBox(self.groupBox)
        self.cboAnimal.setMinimumSize(QtCore.QSize(0, 21))
        self.cboAnimal.setObjectName("cboAnimal")
        self.hboxlayout2.addWidget(self.cboAnimal)
        self.gridlayout1.addLayout(self.hboxlayout2, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridlayout1.addWidget(self.label_3, 3, 0, 1, 1)
        self.cboRaster = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRaster.sizePolicy().hasHeightForWidth())
        self.cboRaster.setSizePolicy(sizePolicy)
        self.cboRaster.setObjectName("cboRaster")
        self.gridlayout1.addWidget(self.cboRaster, 3, 1, 1, 1)
        self.cbFallowUsage = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFallowUsage.sizePolicy().hasHeightForWidth())
        self.cbFallowUsage.setSizePolicy(sizePolicy)
        self.cbFallowUsage.setObjectName("cbFallowUsage")
        self.gridlayout1.addWidget(self.cbFallowUsage, 4, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.grpFodderUse = QtWidgets.QGroupBox(self.widget)
        self.grpFodderUse.setMinimumSize(QtCore.QSize(343, 0))
        self.grpFodderUse.setCheckable(True)
        self.grpFodderUse.setChecked(False)
        self.grpFodderUse.setObjectName("grpFodderUse")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grpFodderUse)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tblFodder = QtWidgets.QTableWidget(self.grpFodderUse)
        self.tblFodder.setAlternatingRowColors(True)
        self.tblFodder.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblFodder.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblFodder.setShowGrid(False)
        self.tblFodder.setObjectName("tblFodder")
        self.tblFodder.setColumnCount(4)
        self.tblFodder.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFodder.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFodder.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFodder.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFodder.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.tblFodder, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.grpFodderUse, 0, 1, 3, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.checkBoxCommonRaster = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxCommonRaster.setObjectName("checkBoxCommonRaster")
        self.hboxlayout3.addWidget(self.checkBoxCommonRaster)
        self.sbCommonRasterValue = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCommonRasterValue.sizePolicy().hasHeightForWidth())
        self.sbCommonRasterValue.setSizePolicy(sizePolicy)
        self.sbCommonRasterValue.setReadOnly(True)
        self.sbCommonRasterValue.setSuffix("")
        self.sbCommonRasterValue.setPrefix("")
        self.sbCommonRasterValue.setMaximum(50000)
        self.sbCommonRasterValue.setSingleStep(1)
        self.sbCommonRasterValue.setProperty("value", 0)
        self.sbCommonRasterValue.setObjectName("sbCommonRasterValue")
        self.hboxlayout3.addWidget(self.sbCommonRasterValue)
        self.gridLayout.addLayout(self.hboxlayout3, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 2, 3)
        self.checkBoxSpecificRaster = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSpecificRaster.setChecked(True)
        self.checkBoxSpecificRaster.setTristate(False)
        self.checkBoxSpecificRaster.setObjectName("checkBoxSpecificRaster")
        self.gridLayout.addWidget(self.checkBoxSpecificRaster, 3, 0, 1, 2)
        self.sbSpecificRasterValue = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbSpecificRasterValue.sizePolicy().hasHeightForWidth())
        self.sbSpecificRasterValue.setSizePolicy(sizePolicy)
        self.sbSpecificRasterValue.setSuffix("")
        self.sbSpecificRasterValue.setPrefix("")
        self.sbSpecificRasterValue.setMinimum(1)
        self.sbSpecificRasterValue.setMaximum(500000)
        self.sbSpecificRasterValue.setSingleStep(1)
        self.sbSpecificRasterValue.setProperty("value", 10)
        self.sbSpecificRasterValue.setObjectName("sbSpecificRasterValue")
        self.gridLayout.addWidget(self.sbSpecificRasterValue, 2, 2, 2, 1)
        self.cbSpecificLandEnergyType = QtWidgets.QComboBox(self.groupBox_3)
        self.cbSpecificLandEnergyType.setObjectName("cbSpecificLandEnergyType")
        self.gridLayout.addWidget(self.cbSpecificLandEnergyType, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.cbAreaUnits = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAreaUnits.sizePolicy().hasHeightForWidth())
        self.cbAreaUnits.setSizePolicy(sizePolicy)
        self.cbAreaUnits.setObjectName("cbAreaUnits")
        self.gridLayout.addWidget(self.cbAreaUnits, 4, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(173, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridlayout2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridlayout2.setContentsMargins(3, 3, 3, 3)
        self.gridlayout2.setObjectName("gridlayout2")
        self.sbPercentTameMeat = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sbPercentTameMeat.setAccelerated(True)
        self.sbPercentTameMeat.setMaximum(100.0)
        self.sbPercentTameMeat.setSingleStep(0.01)
        self.sbPercentTameMeat.setObjectName("sbPercentTameMeat")
        self.gridlayout2.addWidget(self.sbPercentTameMeat, 0, 0, 1, 1)
        self.pbnMore = QtWidgets.QPushButton(self.groupBox_2)
        self.pbnMore.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnMore.sizePolicy().hasHeightForWidth())
        self.pbnMore.setSizePolicy(sizePolicy)
        self.pbnMore.setMaximumSize(QtCore.QSize(41, 22))
        self.pbnMore.setObjectName("pbnMore")
        self.gridlayout2.addWidget(self.pbnMore, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 2, 1)
        self.pbnImport = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnImport.sizePolicy().hasHeightForWidth())
        self.pbnImport.setSizePolicy(sizePolicy)
        self.pbnImport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnImport.setObjectName("pbnImport")
        self.gridLayout_3.addWidget(self.pbnImport, 3, 1, 1, 1)
        self.pbnExport = QtWidgets.QPushButton(self.widget)
        self.pbnExport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnExport.setObjectName("pbnExport")
        self.gridLayout_3.addWidget(self.pbnExport, 3, 2, 1, 1)
        self.pbnApply = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnApply.sizePolicy().hasHeightForWidth())
        self.pbnApply.setSizePolicy(sizePolicy)
        self.pbnApply.setObjectName("pbnApply")
        self.gridLayout_3.addWidget(self.pbnApply, 3, 3, 1, 1)
        self.pbnClose = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnClose.sizePolicy().hasHeightForWidth())
        self.pbnClose.setSizePolicy(sizePolicy)
        self.pbnClose.setObjectName("pbnClose")
        self.gridLayout_3.addWidget(self.pbnClose, 3, 4, 1, 1)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.grpProfiles.raise_()
        self.pbnImport.raise_()
        self.pbnApply.raise_()
        self.grpFodderUse.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.pbnExport.raise_()

        self.retranslateUi(LaAnimalParameterManagerBase)
        self.pbnClose.clicked.connect(LaAnimalParameterManagerBase.close) # type: ignore
        self.checkBoxSpecificRaster.clicked.connect(self.checkBoxCommonRaster.toggle) # type: ignore
        self.checkBoxCommonRaster.clicked.connect(self.checkBoxSpecificRaster.toggle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LaAnimalParameterManagerBase)
        LaAnimalParameterManagerBase.setTabOrder(self.tblAnimalParameterProfiles, self.toolNew)
        LaAnimalParameterManagerBase.setTabOrder(self.toolNew, self.toolCopy)
        LaAnimalParameterManagerBase.setTabOrder(self.toolCopy, self.toolDelete)
        LaAnimalParameterManagerBase.setTabOrder(self.toolDelete, self.leName)
        LaAnimalParameterManagerBase.setTabOrder(self.leName, self.leDescription)
        LaAnimalParameterManagerBase.setTabOrder(self.leDescription, self.cboAnimal)
        LaAnimalParameterManagerBase.setTabOrder(self.cboAnimal, self.checkBoxSpecificRaster)
        LaAnimalParameterManagerBase.setTabOrder(self.checkBoxSpecificRaster, self.checkBoxCommonRaster)
        LaAnimalParameterManagerBase.setTabOrder(self.checkBoxCommonRaster, self.sbSpecificRasterValue)
        LaAnimalParameterManagerBase.setTabOrder(self.sbSpecificRasterValue, self.sbCommonRasterValue)
        LaAnimalParameterManagerBase.setTabOrder(self.sbCommonRasterValue, self.cbAreaUnits)
        LaAnimalParameterManagerBase.setTabOrder(self.cbAreaUnits, self.cbFallowUsage)
        LaAnimalParameterManagerBase.setTabOrder(self.cbFallowUsage, self.pbnClose)

    def retranslateUi(self, LaAnimalParameterManagerBase):
        _translate = QtCore.QCoreApplication.translate
        LaAnimalParameterManagerBase.setWindowTitle(_translate("LaAnimalParameterManagerBase", "Animal Parameter Manager"))
        self.grpProfiles.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model animals, several details must be supplied. Animal Parameter Manager asks for the specific information about the animal which tells the program how the animal was fed, and how big a part of the settlements diet it was. As with Animal Manager, it is possible to have more than one parameter named the same thing. Again, just enter a descriptor in the Notes: field.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different parameters for the same animal, follow the same procedure as for defining multiple animals with the same name. Let\'s say you want to have two parameters set up for cows as an example. The Name: field is Cow for both, but in Notes: field, enter Optimistic for one, and Conservative for the other. Then adjust the parameters as you wish for each. Even though the name is the same, the parameters are saved uniquely. Having multiple parameters can be useful for setting up different scenarios, such as drought years, diease, catastrophic events, etc. Eventually, LandUse Analyst will have the ability to model over time, and will ahve these types of scenarios incorporated into the model.</p></body></html>"))
        self.grpProfiles.setTitle(_translate("LaAnimalParameterManagerBase", "Available Animal Parameter Settings"))
        self.tblAnimalParameterProfiles.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a parameter here to see and/or edit it\'s properties below.</p></body></html>"))
        self.tblAnimalParameterProfiles.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model animals, several details must be supplied. Animal Parameter Manager asks for these specifics. As with Animal Manager, it is possible to have more than one parameter named the same thing. Again, just enter a descriptor in the Notes: field.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different parameters for the same animal, follow the same procedure as for defining multiple animals with the same name. Let\'s say you want to have two parameters set up for Cows as an example. The Name: field is Cow for both, but in Notes: field, enter Optimistic for one, and Conservative for the other. Then adjust the parameters as you wish for each. Even though the name is the same, the parameters are saved uniquely. Having multiple parameters can be useful for setting up different scenarios, such as drought years, diease, catastrophic events, etc. Eventually, LandUse Analyst will have the ability to model over time, and will have these types of scenarios incorporated into the model.</p></body></html>"))
        item = self.tblAnimalParameterProfiles.horizontalHeaderItem(0)
        item.setText(_translate("LaAnimalParameterManagerBase", "FileName"))
        item = self.tblAnimalParameterProfiles.horizontalHeaderItem(1)
        item.setText(_translate("LaAnimalParameterManagerBase", "Name"))
        self.toolCopy.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clone the currently selected parameter</p></body></html>"))
        self.toolCopy.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want to create a new parameter that is similar to one already defined, you can clone this parameter to save time. All of the settings of the parameter you are cloning are transferred to the new clone, but the name is changed to Clone of ... (whatever the name of the parameter you are cloning was).</p></body></html>"))
        self.toolCopy.setText(_translate("LaAnimalParameterManagerBase", "..."))
        self.toolDelete.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Delete the currently selected parameter</p></body></html>"))
        self.toolDelete.setText(_translate("LaAnimalParameterManagerBase", "..."))
        self.toolNew.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Define a new parameter</p></body></html>"))
        self.toolNew.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you simply change the name or settings and click apply in the Animal Parameter Manager, you are just editing the parameter currently selected. To create a new parameter, you <span style=\" font-weight:600;\">must</span> click on the New button.</p></body></html>"))
        self.toolNew.setText(_translate("LaAnimalParameterManagerBase", "..."))
        self.lblAnimalPic.setText(_translate("LaAnimalParameterManagerBase", "No Graphic\n"
"Selected"))
        self.groupBox.setTitle(_translate("LaAnimalParameterManagerBase", "Details"))
        self.label.setText(_translate("LaAnimalParameterManagerBase", "Name:"))
        self.leName.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the name of the animal parameter you are defining in this field. You do not need a unique name. You can have, for example, 10 different animal parameters defined, all named \"Jericho\". LandUse Analyst uses a special method of saving the animals to eliminate the issue of duplicate filenames. This way, you can have, for example, conservative and optimistic settings for each animal at a site.</p></body></html>"))
        self.label_4.setText(_translate("LaAnimalParameterManagerBase", "Notes:"))
        self.leDescription.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Because LandUse Analyst allows more than one type of parameter to be defined, the Notes: field allows you to give a brief description of the the parameter. For example, you may have two \"Shuna\" parameters defined, and the Notes: fields could contain \"Conservative\" and \"Optimistic\" to distinguish between them.</p></body></html>"))
        self.label_2.setText(_translate("LaAnimalParameterManagerBase", "Animal:"))
        self.cboAnimal.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Animal that these parameters are for.</p></body></html>"))
        self.cboAnimal.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It is very important to select which animal your parameter settings are for. Once you slect the animal it appies to, simply click Apply, and it will then be properly allocated, and will show up in the dropdown list for that animal in the table on the top.</p></body></html>"))
        self.label_3.setText(_translate("LaAnimalParameterManagerBase", "Raster Mask "))
        self.cbFallowUsage.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If your animal is to be allowed to graze fallow land resulting from crop rotation, set the priority of their access to this fallow land here.</p></body></html>"))
        self.cbFallowUsage.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LandUse Analyst allows animals to utilize fallow crop land as grazing land. There are many difficult aspects to including this in a model, but these difficulties are mostly transparent to the user. Essentially, you need to indicate only whether the animal will be allowed to graze fallow, and if so, what is it\'s access priority in relation to the other animals grazing the same fallow land. Given this, the software handles the rest!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Because some animals may have been given preferential access to the fallow land, LandUse Analyst has given three different priority levels to fallow access. The software first looks at the HIGH priority animals, and designates all fallow land to them, until either their needs are satisfied, or the available fallow land is all used. If there is more than enough fallow land for the HIGH priority animals, the remaining amount is then made available to the MED priority animals, and this repeats for the LOW priority ones as well.</p></body></html>"))
        self.grpFodderUse.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If your settlement fed the animal fodder, check off the Fodder section to enable the Fodder options to be accessible. Straw/Chaff is a percentage of what is available.  Grain is a percentage of the animals diet.</p></body></html>"))
        self.grpFodderUse.setWhatsThis(_translate("LaAnimalParameterManagerBase", "Select Fodder if you believe the animals were fed grain to supplement their grazing.  You will then have to select how many kg of the selected grain you believe they fed each animal either every day, week, or month."))
        self.grpFodderUse.setTitle(_translate("LaAnimalParameterManagerBase", "Fodder"))
        self.tblFodder.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The animal selected here will be displayed below.  If the animal is to be included in the model, it must be checked off on left.  The model parameters must also be defined and linked to each animal being modelled.</p></body></html>"))
        self.tblFodder.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Animal Interface has been designed to be very simple and easy to use. The top section lists all of the defined animals, and selecting one will display its settings in the two lower sections. The lower sections are divided into the animal definition details on the left, and the model parameter settings for the currently selected animal on the right.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you wish to edit either the animal or its parameters, you simply click on the Manage button below the display areas.</p></body></html>"))
        item = self.tblFodder.horizontalHeaderItem(0)
        item.setText(_translate("LaAnimalParameterManagerBase", "Used"))
        item = self.tblFodder.horizontalHeaderItem(1)
        item.setText(_translate("LaAnimalParameterManagerBase", "Crop"))
        item = self.tblFodder.horizontalHeaderItem(2)
        item.setText(_translate("LaAnimalParameterManagerBase", "Fodder"))
        item = self.tblFodder.horizontalHeaderItem(3)
        item.setText(_translate("LaAnimalParameterManagerBase", "Grain"))
        self.groupBox_3.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order for LandUse Analyst to create landuse maps, you must first create land suitability files to tell it what land is suitable for use by the crops and the animals. These files can be produced manually or automatically, but at the moment both must be done with external tools like QGis or GRASS. Future versions of Landuse Analyst will have the required features of these programs incorporated into it, but for now this step must be done externally. </p></body></html>"))
        self.groupBox_3.setTitle(_translate("LaAnimalParameterManagerBase", "Land Suitability Selection"))
        self.checkBoxCommonRaster.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">binary raster named common.grazing.mask which more than one animal can graze from</p></body></html>"))
        self.checkBoxCommonRaster.setText(_translate("LaAnimalParameterManagerBase", "Common Land"))
        self.sbCommonRasterValue.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TDN loaded from main form</p></body></html>"))
        self.sbCommonRasterValue.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#0000ff;\">This value </span><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#0000ff;\">MUST</span><span style=\" font-weight:600; color:#0000ff;\"> be the same for all animals grazing common land.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sometimes land is suitable for grazing by more than one type of animal. LandUse Analyst allows you to designate one suitability mask as common grazing land. Note that you can specify an animal to use both common land and specific land at the same time. If this is the case, equal preference is given to all animals grazing the common land. This is not always ideal, as it may have been the case that some animals were given preference to the common land if the other suitable land was further away than the other animals using it.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A workaround for this problem is that LandUse Analyst produces classified maps of the land being used, so if it is the case that you find one animal being forced to travel much further than others, you can simply change settings to balance this. This can be accomplished by removing the other animals one at a time from using the common grazing land. It may be the case, however, that there is no ideal solution, and that they simply had to travel the extra distance!</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note that this setting is the number of KCalories per land area unit available for grazing animals <span style=\" font-weight:600;\">per year</span>.  This value applies to all of the land selected in the common raster mask file.</p></body></html>"))
        self.checkBoxSpecificRaster.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">binary raster named: animalName.mask  where animalName is the name of the animal you are setting these parameters for.</p></body></html>"))
        self.checkBoxSpecificRaster.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sometimes you may want to specify that land is suitable for grazing by only one type of animal. LandUse Analyst allows you to designate a land suitability mask as being unique to that animal. Note that you can specify an animal to use both common land and specific land at the same time. For more detailed information on this, see the help section on Animal Common Land.</p></body></html>"))
        self.checkBoxSpecificRaster.setText(_translate("LaAnimalParameterManagerBase", "Specific Land"))
        self.sbSpecificRasterValue.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TDN (Total Digestive Nutrients) available</p></body></html>"))
        self.sbSpecificRasterValue.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note that this setting is the number of KCalories per land area unit available for grazing animals <span style=\" font-weight:600;\">per year</span>.  This value applies to only the land selected in the unique raster mask file created for this animal.</p></body></html>"))
        self.label_5.setText(_translate("LaAnimalParameterManagerBase", "per  "))
        self.cbAreaUnits.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 dunum = 1000 square meters</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 hectare = 10,000 square meters</p></body></html>"))
        self.cbAreaUnits.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select either Dunums or Hectares. This option is merely for convenience, to accomodate data that is available based on the two different units. (Basically I just got sick of having to convert between the two all the time! :P)</p></body></html>"))
        self.groupBox_2.setTitle(_translate("LaAnimalParameterManagerBase", "Portion of Domestic Meat Diet"))
        self.sbPercentTameMeat.setSuffix(_translate("LaAnimalParameterManagerBase", "%"))
        self.pbnMore.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click here to get help determining this figure</p></body></html>"))
        self.pbnMore.setText(_translate("LaAnimalParameterManagerBase", "More"))
        self.pbnImport.setText(_translate("LaAnimalParameterManagerBase", "Import"))
        self.pbnExport.setText(_translate("LaAnimalParameterManagerBase", "Export"))
        self.pbnApply.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Saves all settings</p></body></html>"))
        self.pbnApply.setWhatsThis(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After completing all fields to define a parameter, you <span style=\" font-weight:600;\">MUST</span> click the Apply button to save it. The name does not have to be unique, as LandUse Analyst has a special way of saving parameters to allow for duplicate parameter names. It is helpful, however, to utilize the Notes field to distinguish between same-named parameter definitions.</p></body></html>"))
        self.pbnApply.setText(_translate("LaAnimalParameterManagerBase", "Apply"))
        self.pbnClose.setToolTip(_translate("LaAnimalParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#0000ff;\">Have you applied your changes?</span></p></body></html>"))
        self.pbnClose.setText(_translate("LaAnimalParameterManagerBase", "Close"))
import resources_rc
