# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arkygeek/dev/QGisPlugins/landuseanalyst/landuse_analyst/src/ui/laanimalmanagerbase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LaAnimalManagerBase(object):
    def setupUi(self, LaAnimalManagerBase):
        LaAnimalManagerBase.setObjectName("LaAnimalManagerBase")
        LaAnimalManagerBase.resize(806, 750)
        icon = QtGui.QIcon()
        icon.addFile(":/la_icon.png")
        LaAnimalManagerBase.setWindowIcon(icon)
        self.gridlayout = QtWidgets.QGridLayout(LaAnimalManagerBase)
        self.gridlayout.setObjectName("gridlayout")
        self.groupBoxAnimalDescription = QtWidgets.QGroupBox(LaAnimalManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAnimalDescription.sizePolicy().hasHeightForWidth())
        self.groupBoxAnimalDescription.setSizePolicy(sizePolicy)
        self.groupBoxAnimalDescription.setObjectName("groupBoxAnimalDescription")
        self.gridlayout1 = QtWidgets.QGridLayout(self.groupBoxAnimalDescription)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.leName = QtWidgets.QLineEdit(self.groupBoxAnimalDescription)
        self.leName.setObjectName("leName")
        self.hboxlayout.addWidget(self.leName)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 0, 1, 2)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_4.setObjectName("label_4")
        self.hboxlayout1.addWidget(self.label_4)
        self.leDescription = QtWidgets.QLineEdit(self.groupBoxAnimalDescription)
        self.leDescription.setObjectName("leDescription")
        self.hboxlayout1.addWidget(self.leDescription)
        self.gridlayout1.addLayout(self.hboxlayout1, 1, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.groupBoxAnimalDescription)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout1.addWidget(self.line_2, 2, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridlayout1.addWidget(self.label_14, 3, 0, 1, 1)
        self.sbMeatFoodValue = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMeatFoodValue.sizePolicy().hasHeightForWidth())
        self.sbMeatFoodValue.setSizePolicy(sizePolicy)
        self.sbMeatFoodValue.setAlignment(QtCore.Qt.AlignRight)
        self.sbMeatFoodValue.setPrefix("")
        self.sbMeatFoodValue.setMaximum(20000)
        self.sbMeatFoodValue.setProperty("value", 3000)
        self.sbMeatFoodValue.setObjectName("sbMeatFoodValue")
        self.gridlayout1.addWidget(self.sbMeatFoodValue, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridlayout1.addWidget(self.label_9, 4, 0, 1, 1)
        self.sbUsableMeatPercent = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbUsableMeatPercent.sizePolicy().hasHeightForWidth())
        self.sbUsableMeatPercent.setSizePolicy(sizePolicy)
        self.sbUsableMeatPercent.setAlignment(QtCore.Qt.AlignRight)
        self.sbUsableMeatPercent.setPrefix("")
        self.sbUsableMeatPercent.setMaximum(120)
        self.sbUsableMeatPercent.setProperty("value", 80)
        self.sbUsableMeatPercent.setObjectName("sbUsableMeatPercent")
        self.gridlayout1.addWidget(self.sbUsableMeatPercent, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridlayout1.addWidget(self.label_10, 5, 0, 1, 1)
        self.sbKillWeight = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbKillWeight.sizePolicy().hasHeightForWidth())
        self.sbKillWeight.setSizePolicy(sizePolicy)
        self.sbKillWeight.setAlignment(QtCore.Qt.AlignRight)
        self.sbKillWeight.setPrefix("")
        self.sbKillWeight.setMaximum(2000)
        self.sbKillWeight.setProperty("value", 100)
        self.sbKillWeight.setObjectName("sbKillWeight")
        self.gridlayout1.addWidget(self.sbKillWeight, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridlayout1.addWidget(self.label_16, 6, 0, 1, 1)
        self.sbWeaningWeight = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbWeaningWeight.sizePolicy().hasHeightForWidth())
        self.sbWeaningWeight.setSizePolicy(sizePolicy)
        self.sbWeaningWeight.setAlignment(QtCore.Qt.AlignRight)
        self.sbWeaningWeight.setPrefix("")
        self.sbWeaningWeight.setMaximum(120)
        self.sbWeaningWeight.setProperty("value", 80)
        self.sbWeaningWeight.setObjectName("sbWeaningWeight")
        self.gridlayout1.addWidget(self.sbWeaningWeight, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridlayout1.addWidget(self.label_11, 7, 0, 1, 1)
        self.sbGrowTime = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbGrowTime.sizePolicy().hasHeightForWidth())
        self.sbGrowTime.setSizePolicy(sizePolicy)
        self.sbGrowTime.setAlignment(QtCore.Qt.AlignRight)
        self.sbGrowTime.setPrefix("")
        self.sbGrowTime.setMinimum(1)
        self.sbGrowTime.setMaximum(1000)
        self.sbGrowTime.setProperty("value", 60)
        self.sbGrowTime.setObjectName("sbGrowTime")
        self.gridlayout1.addWidget(self.sbGrowTime, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridlayout1.addWidget(self.label_12, 8, 0, 1, 1)
        self.sbDeathRate = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDeathRate.sizePolicy().hasHeightForWidth())
        self.sbDeathRate.setSizePolicy(sizePolicy)
        self.sbDeathRate.setAlignment(QtCore.Qt.AlignRight)
        self.sbDeathRate.setPrefix("")
        self.sbDeathRate.setMaximum(100)
        self.sbDeathRate.setProperty("value", 10)
        self.sbDeathRate.setObjectName("sbDeathRate")
        self.gridlayout1.addWidget(self.sbDeathRate, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridlayout1.addWidget(self.label_2, 9, 0, 1, 1)
        self.sbSexualMaturity = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbSexualMaturity.sizePolicy().hasHeightForWidth())
        self.sbSexualMaturity.setSizePolicy(sizePolicy)
        self.sbSexualMaturity.setAlignment(QtCore.Qt.AlignRight)
        self.sbSexualMaturity.setPrefix("")
        self.sbSexualMaturity.setMaximum(240)
        self.sbSexualMaturity.setProperty("value", 18)
        self.sbSexualMaturity.setObjectName("sbSexualMaturity")
        self.gridlayout1.addWidget(self.sbSexualMaturity, 9, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridlayout1.addWidget(self.label_17, 10, 0, 1, 1)
        self.sbAdultWeight = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAdultWeight.sizePolicy().hasHeightForWidth())
        self.sbAdultWeight.setSizePolicy(sizePolicy)
        self.sbAdultWeight.setAlignment(QtCore.Qt.AlignRight)
        self.sbAdultWeight.setPrefix("")
        self.sbAdultWeight.setMaximum(2000)
        self.sbAdultWeight.setProperty("value", 100)
        self.sbAdultWeight.setObjectName("sbAdultWeight")
        self.gridlayout1.addWidget(self.sbAdultWeight, 10, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridlayout1.addWidget(self.label_18, 11, 0, 1, 1)
        self.sbFemalesToMales = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbFemalesToMales.sizePolicy().hasHeightForWidth())
        self.sbFemalesToMales.setSizePolicy(sizePolicy)
        self.sbFemalesToMales.setAlignment(QtCore.Qt.AlignRight)
        self.sbFemalesToMales.setSuffix("")
        self.sbFemalesToMales.setPrefix("")
        self.sbFemalesToMales.setMinimum(1)
        self.sbFemalesToMales.setMaximum(2000)
        self.sbFemalesToMales.setProperty("value", 20)
        self.sbFemalesToMales.setObjectName("sbFemalesToMales")
        self.gridlayout1.addWidget(self.sbFemalesToMales, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridlayout1.addWidget(self.label_3, 12, 0, 1, 1)
        self.sbBreedingLife = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbBreedingLife.sizePolicy().hasHeightForWidth())
        self.sbBreedingLife.setSizePolicy(sizePolicy)
        self.sbBreedingLife.setAlignment(QtCore.Qt.AlignRight)
        self.sbBreedingLife.setPrefix("")
        self.sbBreedingLife.setMinimum(1)
        self.sbBreedingLife.setMaximum(120)
        self.sbBreedingLife.setProperty("value", 4)
        self.sbBreedingLife.setObjectName("sbBreedingLife")
        self.gridlayout1.addWidget(self.sbBreedingLife, 12, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridlayout1.addWidget(self.label_19, 13, 0, 1, 1)
        self.sbConceptionEfficiency = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbConceptionEfficiency.sizePolicy().hasHeightForWidth())
        self.sbConceptionEfficiency.setSizePolicy(sizePolicy)
        self.sbConceptionEfficiency.setAlignment(QtCore.Qt.AlignRight)
        self.sbConceptionEfficiency.setPrefix("")
        self.sbConceptionEfficiency.setMaximum(2000)
        self.sbConceptionEfficiency.setProperty("value", 100)
        self.sbConceptionEfficiency.setObjectName("sbConceptionEfficiency")
        self.gridlayout1.addWidget(self.sbConceptionEfficiency, 13, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridlayout1.addWidget(self.label_5, 14, 0, 1, 1)
        self.sbYoungPerBirth = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbYoungPerBirth.sizePolicy().hasHeightForWidth())
        self.sbYoungPerBirth.setSizePolicy(sizePolicy)
        self.sbYoungPerBirth.setAlignment(QtCore.Qt.AlignRight)
        self.sbYoungPerBirth.setSuffix("")
        self.sbYoungPerBirth.setMinimum(1)
        self.sbYoungPerBirth.setMaximum(20)
        self.sbYoungPerBirth.setProperty("value", 1)
        self.sbYoungPerBirth.setObjectName("sbYoungPerBirth")
        self.gridlayout1.addWidget(self.sbYoungPerBirth, 14, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridlayout1.addWidget(self.label_6, 15, 0, 1, 1)
        self.sbWeaningAge = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbWeaningAge.sizePolicy().hasHeightForWidth())
        self.sbWeaningAge.setSizePolicy(sizePolicy)
        self.sbWeaningAge.setAlignment(QtCore.Qt.AlignRight)
        self.sbWeaningAge.setPrefix("")
        self.sbWeaningAge.setMaximum(120)
        self.sbWeaningAge.setProperty("value", 80)
        self.sbWeaningAge.setObjectName("sbWeaningAge")
        self.gridlayout1.addWidget(self.sbWeaningAge, 15, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridlayout1.addWidget(self.label_7, 16, 0, 1, 1)
        self.sbGestationTime = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbGestationTime.sizePolicy().hasHeightForWidth())
        self.sbGestationTime.setSizePolicy(sizePolicy)
        self.sbGestationTime.setAlignment(QtCore.Qt.AlignRight)
        self.sbGestationTime.setPrefix("")
        self.sbGestationTime.setMinimum(1)
        self.sbGestationTime.setMaximum(365)
        self.sbGestationTime.setProperty("value", 120)
        self.sbGestationTime.setObjectName("sbGestationTime")
        self.gridlayout1.addWidget(self.sbGestationTime, 16, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridlayout1.addWidget(self.label_8, 17, 0, 1, 1)
        self.sbEstrousCycleTime = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEstrousCycleTime.sizePolicy().hasHeightForWidth())
        self.sbEstrousCycleTime.setSizePolicy(sizePolicy)
        self.sbEstrousCycleTime.setAlignment(QtCore.Qt.AlignRight)
        self.sbEstrousCycleTime.setPrefix("")
        self.sbEstrousCycleTime.setMaximum(120)
        self.sbEstrousCycleTime.setProperty("value", 21)
        self.sbEstrousCycleTime.setObjectName("sbEstrousCycleTime")
        self.gridlayout1.addWidget(self.sbEstrousCycleTime, 17, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBoxAnimalDescription)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridlayout1.addWidget(self.label_21, 18, 0, 1, 1)
        self.sbLactationTime = QtWidgets.QSpinBox(self.groupBoxAnimalDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbLactationTime.sizePolicy().hasHeightForWidth())
        self.sbLactationTime.setSizePolicy(sizePolicy)
        self.sbLactationTime.setAlignment(QtCore.Qt.AlignRight)
        self.sbLactationTime.setPrefix("")
        self.sbLactationTime.setMaximum(1000)
        self.sbLactationTime.setProperty("value", 210)
        self.sbLactationTime.setObjectName("sbLactationTime")
        self.gridlayout1.addWidget(self.sbLactationTime, 18, 1, 1, 1)
        self.gridlayout.addWidget(self.groupBoxAnimalDescription, 0, 0, 3, 1)
        self.grpProfiles = QtWidgets.QGroupBox(LaAnimalManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpProfiles.sizePolicy().hasHeightForWidth())
        self.grpProfiles.setSizePolicy(sizePolicy)
        self.grpProfiles.setObjectName("grpProfiles")
        self.gridlayout2 = QtWidgets.QGridLayout(self.grpProfiles)
        self.gridlayout2.setObjectName("gridlayout2")
        self.tblAnimals = QtWidgets.QTableWidget(self.grpProfiles)
        self.tblAnimals.setAlternatingRowColors(True)
        self.tblAnimals.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAnimals.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAnimals.setObjectName("tblAnimals")
        self.tblAnimals.setColumnCount(2)
        self.tblAnimals.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAnimals.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAnimals.setHorizontalHeaderItem(1, item)
        self.gridlayout2.addWidget(self.tblAnimals, 0, 0, 4, 1)
        self.gridlayout3 = QtWidgets.QGridLayout()
        self.gridlayout3.setObjectName("gridlayout3")
        self.toolCopy = QtWidgets.QToolButton(self.grpProfiles)
        icon1 = QtGui.QIcon()
        icon1.addFile(":/copy.png")
        self.toolCopy.setIcon(icon1)
        self.toolCopy.setObjectName("toolCopy")
        self.gridlayout3.addWidget(self.toolCopy, 2, 1, 1, 1)
        self.toolNew = QtWidgets.QToolButton(self.grpProfiles)
        icon2 = QtGui.QIcon()
        icon2.addFile(":/new.png")
        self.toolNew.setIcon(icon2)
        self.toolNew.setObjectName("toolNew")
        self.gridlayout3.addWidget(self.toolNew, 2, 0, 1, 1)
        self.toolDelete = QtWidgets.QToolButton(self.grpProfiles)
        icon3 = QtGui.QIcon()
        icon3.addFile(":/delete.png")
        self.toolDelete.setIcon(icon3)
        self.toolDelete.setObjectName("toolDelete")
        self.gridlayout3.addWidget(self.toolDelete, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem, 1, 1, 1, 1)
        self.lblAnimalPix = QtWidgets.QLabel(self.grpProfiles)
        self.lblAnimalPix.setMinimumSize(QtCore.QSize(100, 100))
        self.lblAnimalPix.setMaximumSize(QtCore.QSize(100, 100))
        self.lblAnimalPix.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAnimalPix.setObjectName("lblAnimalPix")
        self.gridlayout3.addWidget(self.lblAnimalPix, 0, 0, 1, 3)
        self.gridlayout2.addLayout(self.gridlayout3, 0, 1, 1, 1)
        self.pbnAnimalPic = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnAnimalPic.setObjectName("pbnAnimalPic")
        self.gridlayout2.addWidget(self.pbnAnimalPic, 1, 1, 1, 1)
        self.pbnImport = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnImport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnImport.setObjectName("pbnImport")
        self.gridlayout2.addWidget(self.pbnImport, 2, 1, 1, 1)
        self.pbnExport = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnExport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnExport.setObjectName("pbnExport")
        self.gridlayout2.addWidget(self.pbnExport, 3, 1, 1, 1)
        self.gridlayout.addWidget(self.grpProfiles, 0, 1, 1, 3)
        self.groupBoxFeedRequirements = QtWidgets.QGroupBox(LaAnimalManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFeedRequirements.sizePolicy().hasHeightForWidth())
        self.groupBoxFeedRequirements.setSizePolicy(sizePolicy)
        self.groupBoxFeedRequirements.setObjectName("groupBoxFeedRequirements")
        self.gridlayout4 = QtWidgets.QGridLayout(self.groupBoxFeedRequirements)
        self.gridlayout4.setObjectName("gridlayout4")
        self.gridlayout5 = QtWidgets.QGridLayout()
        self.gridlayout5.setObjectName("gridlayout5")
        self.label_13 = QtWidgets.QLabel(self.groupBoxFeedRequirements)
        self.label_13.setObjectName("label_13")
        self.gridlayout5.addWidget(self.label_13, 0, 0, 1, 1)
        self.cbFeedEnergyType = QtWidgets.QComboBox(self.groupBoxFeedRequirements)
        self.cbFeedEnergyType.setObjectName("cbFeedEnergyType")
        self.cbFeedEnergyType.addItem("")
        self.cbFeedEnergyType.addItem("")
        self.gridlayout5.addWidget(self.cbFeedEnergyType, 0, 1, 1, 1)
        self.labelFeedRequirements2 = QtWidgets.QLabel(self.groupBoxFeedRequirements)
        self.labelFeedRequirements2.setObjectName("labelFeedRequirements2")
        self.gridlayout5.addWidget(self.labelFeedRequirements2, 1, 0, 1, 1)
        self.sbEnergyForPregnant = QtWidgets.QSpinBox(self.groupBoxFeedRequirements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEnergyForPregnant.sizePolicy().hasHeightForWidth())
        self.sbEnergyForPregnant.setSizePolicy(sizePolicy)
        self.sbEnergyForPregnant.setSuffix("")
        self.sbEnergyForPregnant.setMaximum(20000)
        self.sbEnergyForPregnant.setProperty("value", 4000)
        self.sbEnergyForPregnant.setObjectName("sbEnergyForPregnant")
        self.gridlayout5.addWidget(self.sbEnergyForPregnant, 1, 1, 1, 1)
        self.labelFeedRequirements3 = QtWidgets.QLabel(self.groupBoxFeedRequirements)
        self.labelFeedRequirements3.setObjectName("labelFeedRequirements3")
        self.gridlayout5.addWidget(self.labelFeedRequirements3, 2, 0, 1, 1)
        self.sbEnergyForLactating = QtWidgets.QSpinBox(self.groupBoxFeedRequirements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEnergyForLactating.sizePolicy().hasHeightForWidth())
        self.sbEnergyForLactating.setSizePolicy(sizePolicy)
        self.sbEnergyForLactating.setSuffix("")
        self.sbEnergyForLactating.setMaximum(20000)
        self.sbEnergyForLactating.setProperty("value", 4000)
        self.sbEnergyForLactating.setObjectName("sbEnergyForLactating")
        self.gridlayout5.addWidget(self.sbEnergyForLactating, 2, 1, 1, 1)
        self.labelFeedRequirements3_2 = QtWidgets.QLabel(self.groupBoxFeedRequirements)
        self.labelFeedRequirements3_2.setObjectName("labelFeedRequirements3_2")
        self.gridlayout5.addWidget(self.labelFeedRequirements3_2, 3, 0, 1, 1)
        self.sbEnergyForMaintenance = QtWidgets.QSpinBox(self.groupBoxFeedRequirements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEnergyForMaintenance.sizePolicy().hasHeightForWidth())
        self.sbEnergyForMaintenance.setSizePolicy(sizePolicy)
        self.sbEnergyForMaintenance.setSuffix("")
        self.sbEnergyForMaintenance.setMaximum(20000)
        self.sbEnergyForMaintenance.setProperty("value", 4000)
        self.sbEnergyForMaintenance.setObjectName("sbEnergyForMaintenance")
        self.gridlayout5.addWidget(self.sbEnergyForMaintenance, 3, 1, 1, 1)
        self.labelFeedRequirements4 = QtWidgets.QLabel(self.groupBoxFeedRequirements)
        self.labelFeedRequirements4.setObjectName("labelFeedRequirements4")
        self.gridlayout5.addWidget(self.labelFeedRequirements4, 4, 0, 1, 1)
        self.sbEnergyForJuvenilePerKg = QtWidgets.QSpinBox(self.groupBoxFeedRequirements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEnergyForJuvenilePerKg.sizePolicy().hasHeightForWidth())
        self.sbEnergyForJuvenilePerKg.setSizePolicy(sizePolicy)
        self.sbEnergyForJuvenilePerKg.setMaximum(20000)
        self.sbEnergyForJuvenilePerKg.setProperty("value", 300)
        self.sbEnergyForJuvenilePerKg.setObjectName("sbEnergyForJuvenilePerKg")
        self.gridlayout5.addWidget(self.sbEnergyForJuvenilePerKg, 4, 1, 1, 1)
        self.gridlayout4.addLayout(self.gridlayout5, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBoxFeedRequirements, 1, 1, 2, 1)
        self.groupBoxByProducts = QtWidgets.QGroupBox(LaAnimalManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxByProducts.sizePolicy().hasHeightForWidth())
        self.groupBoxByProducts.setSizePolicy(sizePolicy)
        self.groupBoxByProducts.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxByProducts.setObjectName("groupBoxByProducts")
        self.gridlayout6 = QtWidgets.QGridLayout(self.groupBoxByProducts)
        self.gridlayout6.setObjectName("gridlayout6")
        self.checkBoxMilk = QtWidgets.QCheckBox(self.groupBoxByProducts)
        self.checkBoxMilk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxMilk.setObjectName("checkBoxMilk")
        self.gridlayout6.addWidget(self.checkBoxMilk, 0, 0, 1, 1)
        self.sbMilk = QtWidgets.QSpinBox(self.groupBoxByProducts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMilk.sizePolicy().hasHeightForWidth())
        self.sbMilk.setSizePolicy(sizePolicy)
        self.sbMilk.setAlignment(QtCore.Qt.AlignRight)
        self.sbMilk.setPrefix("")
        self.sbMilk.setMaximum(100000)
        self.sbMilk.setProperty("value", 18)
        self.sbMilk.setObjectName("sbMilk")
        self.gridlayout6.addWidget(self.sbMilk, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBoxByProducts)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridlayout6.addWidget(self.label_15, 1, 0, 1, 1)
        self.sbMilkFoodValue = QtWidgets.QSpinBox(self.groupBoxByProducts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMilkFoodValue.sizePolicy().hasHeightForWidth())
        self.sbMilkFoodValue.setSizePolicy(sizePolicy)
        self.sbMilkFoodValue.setAlignment(QtCore.Qt.AlignRight)
        self.sbMilkFoodValue.setPrefix("")
        self.sbMilkFoodValue.setMinimum(1)
        self.sbMilkFoodValue.setMaximum(10000)
        self.sbMilkFoodValue.setProperty("value", 4)
        self.sbMilkFoodValue.setObjectName("sbMilkFoodValue")
        self.gridlayout6.addWidget(self.sbMilkFoodValue, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBoxByProducts)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout6.addWidget(self.line, 2, 0, 1, 2)
        self.checkBoxFleece = QtWidgets.QCheckBox(self.groupBoxByProducts)
        self.checkBoxFleece.setObjectName("checkBoxFleece")
        self.gridlayout6.addWidget(self.checkBoxFleece, 3, 0, 1, 1)
        self.sbFleeceWeight = QtWidgets.QSpinBox(self.groupBoxByProducts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbFleeceWeight.sizePolicy().hasHeightForWidth())
        self.sbFleeceWeight.setSizePolicy(sizePolicy)
        self.sbFleeceWeight.setAlignment(QtCore.Qt.AlignRight)
        self.sbFleeceWeight.setMinimum(1)
        self.sbFleeceWeight.setMaximum(200)
        self.sbFleeceWeight.setProperty("value", 1)
        self.sbFleeceWeight.setObjectName("sbFleeceWeight")
        self.gridlayout6.addWidget(self.sbFleeceWeight, 3, 1, 1, 1)
        self.gridlayout.addWidget(self.groupBoxByProducts, 1, 2, 1, 2)
        self.pbnApply = QtWidgets.QPushButton(LaAnimalManagerBase)
        self.pbnApply.setCheckable(False)
        self.pbnApply.setFlat(False)
        self.pbnApply.setObjectName("pbnApply")
        self.gridlayout.addWidget(self.pbnApply, 2, 2, 1, 1)
        self.pbnClose = QtWidgets.QPushButton(LaAnimalManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnClose.sizePolicy().hasHeightForWidth())
        self.pbnClose.setSizePolicy(sizePolicy)
        self.pbnClose.setObjectName("pbnClose")
        self.gridlayout.addWidget(self.pbnClose, 2, 3, 1, 1)

        self.retranslateUi(LaAnimalManagerBase)
        self.pbnClose.clicked.connect(LaAnimalManagerBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LaAnimalManagerBase)
        LaAnimalManagerBase.setTabOrder(self.tblAnimals, self.pbnImport)
        LaAnimalManagerBase.setTabOrder(self.pbnImport, self.pbnExport)
        LaAnimalManagerBase.setTabOrder(self.pbnExport, self.toolNew)
        LaAnimalManagerBase.setTabOrder(self.toolNew, self.toolCopy)
        LaAnimalManagerBase.setTabOrder(self.toolCopy, self.toolDelete)
        LaAnimalManagerBase.setTabOrder(self.toolDelete, self.leName)
        LaAnimalManagerBase.setTabOrder(self.leName, self.leDescription)
        LaAnimalManagerBase.setTabOrder(self.leDescription, self.sbUsableMeatPercent)
        LaAnimalManagerBase.setTabOrder(self.sbUsableMeatPercent, self.sbKillWeight)
        LaAnimalManagerBase.setTabOrder(self.sbKillWeight, self.sbGrowTime)
        LaAnimalManagerBase.setTabOrder(self.sbGrowTime, self.sbDeathRate)
        LaAnimalManagerBase.setTabOrder(self.sbDeathRate, self.sbEnergyForPregnant)
        LaAnimalManagerBase.setTabOrder(self.sbEnergyForPregnant, self.sbEnergyForLactating)
        LaAnimalManagerBase.setTabOrder(self.sbEnergyForLactating, self.sbEnergyForJuvenilePerKg)

    def retranslateUi(self, LaAnimalManagerBase):
        _translate = QtCore.QCoreApplication.translate
        LaAnimalManagerBase.setWindowTitle(_translate("LaAnimalManagerBase", "Animal Profile Manager"))
        self.groupBoxAnimalDescription.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model any animal, several details must be entered to define specific types or breeds. Animal Manager asks for general information about the animal in this section. You might want to have more than one breed of the same species, however, which is allowed.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different breeds of the same species is quite easy. Let\'s say you want to have two kinds of cows for example. The Name: field is Cow for both, but in Notes: field, enter Dairy for one, and Beast of Burden for the other. Then adjust the other parameters as you wish. Even though the name is the same, the animal is saved uniquely.</p></body></html>"))
        self.groupBoxAnimalDescription.setTitle(_translate("LaAnimalManagerBase", "Animal Description"))
        self.label.setText(_translate("LaAnimalManagerBase", "Name:"))
        self.leName.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the name of the animal you are defining in this field. You do not need a unique name. You can have, for example, 10 animals defined, all named \"Sheep\". LandUse Analyst uses a special method of saving the animals to eliminate the issue of duplicate filenames.</p></body></html>"))
        self.label_4.setText(_translate("LaAnimalManagerBase", "Notes:"))
        self.leDescription.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Because LandUse Analyst allows more than one type of animal to be defined, the Notes: field allows you to give a brief description of the the animal. For example, you may have two \"Sheep\" defined, and the Notes: fields could contain \"For Slaughter\" and \"Wool Producers\" to distinguish between them.</p></body></html>"))
        self.label_14.setText(_translate("LaAnimalManagerBase", "Food Value"))
        self.sbMeatFoodValue.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Percent of live weight usable as meat</p></body></html>"))
        self.sbMeatFoodValue.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The production targets for animals are in Kg of meat, so to be compatible with animal numbers, you must know the percentage of the animal\'s live weight that is usable for food. You can also take into account here the efficiency of the butchering technique that the population used. In other words, if you believe they were wasteful, this is where you would make an adjustment to integrate that.</p></body></html>"))
        self.sbMeatFoodValue.setSuffix(_translate("LaAnimalManagerBase", " cal"))
        self.label_9.setText(_translate("LaAnimalManagerBase", "Usable Meat"))
        self.sbUsableMeatPercent.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Percent of live weight usable as meat</p></body></html>"))
        self.sbUsableMeatPercent.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The production targets for animals are in Kg of meat, so to be compatible with animal numbers, you must know the percentage of the animal\'s live weight that is usable for food. You can also take into account here the efficiency of the butchering technique that the population used. In other words, if you believe they were wasteful, this is where you would make an adjustment to integrate that.</p></body></html>"))
        self.sbUsableMeatPercent.setSuffix(_translate("LaAnimalManagerBase", " %"))
        self.label_10.setText(_translate("LaAnimalManagerBase", "Kill Weight"))
        self.sbKillWeight.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Average weight of animal (Kg) when slaughtered</p></body></html>"))
        self.sbKillWeight.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Animals can be slaughtered for butchering at any weight, but LandUse Analyst needs to know the average weight of the animals when they are slaughtered. This is their <span style=\" font-weight:600;\">live weight.</span></p></body></html>"))
        self.sbKillWeight.setSuffix(_translate("LaAnimalManagerBase", " Kg"))
        self.label_16.setText(_translate("LaAnimalManagerBase", "Weaning Weight"))
        self.sbWeaningWeight.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Weeks from birth to weaning</p></body></html>"))
        self.sbWeaningWeight.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The age of the babies, in weeks, at which they stop feeding from their mother. It is assumed by LandUse Analyst that mothers will become pregnant after one estrous cycle following weaning.</p></body></html>"))
        self.sbWeaningWeight.setProperty("text", _translate("LaAnimalManagerBase", "80 Kg"))
        self.sbWeaningWeight.setSuffix(_translate("LaAnimalManagerBase", " Kg"))
        self.label_11.setText(_translate("LaAnimalManagerBase", "Grow Time"))
        self.sbGrowTime.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Time from birth to slaughter weight</p></body></html>"))
        self.sbGrowTime.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Grow time, or the length of time from birth to slaughter weight, is quite important for estimating the herd size. The longer it takes an animal to reach slaughter weight from birth, the higher the number of animals alive at any given time.</p></body></html>"))
        self.sbGrowTime.setSuffix(_translate("LaAnimalManagerBase", " Weeks"))
        self.label_12.setText(_translate("LaAnimalManagerBase", "Death Rate"))
        self.sbDeathRate.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Percent of babies that do not survive to slaughter age.</p></body></html>"))
        self.sbDeathRate.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LandUse Analyst accommodates for birthing deaths only. If an animal survives to weaning age but dies before slaughter, it is not modelled at this time. However, you can adjust the death rate setting to indicate the average survival rate of births. This is important for determining herd size, as it affects the number of mothers needed to sustain the production levels required by the settlement.</p></body></html>"))
        self.sbDeathRate.setSuffix(_translate("LaAnimalManagerBase", " %"))
        self.label_2.setText(_translate("LaAnimalManagerBase", "Sexual Maturity"))
        self.sbSexualMaturity.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Age of females when they become sexually mature.</p></body></html>"))
        self.sbSexualMaturity.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Simply set the age, in months, at which the females become sexually mature, and are able to reliably breed.</p></body></html>"))
        self.sbSexualMaturity.setSuffix(_translate("LaAnimalManagerBase", " Mths"))
        self.label_17.setText(_translate("LaAnimalManagerBase", "Adult Weight"))
        self.sbAdultWeight.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Average weight of animal (Kg) when slaughtered</p></body></html>"))
        self.sbAdultWeight.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Animals can be slaughtered for butchering at any weight, but LandUse Analyst needs to know the average weight of the animals when they are slaughtered. This is their <span style=\" font-weight:600;\">live weight.</span></p></body></html>"))
        self.sbAdultWeight.setSuffix(_translate("LaAnimalManagerBase", " Kg"))
        self.label_18.setText(_translate("LaAnimalManagerBase", "Females:Males"))
        self.sbFemalesToMales.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Average weight of animal (Kg) when slaughtered</p></body></html>"))
        self.sbFemalesToMales.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Animals can be slaughtered for butchering at any weight, but LandUse Analyst needs to know the average weight of the animals when they are slaughtered. This is their <span style=\" font-weight:600;\">live weight.</span></p></body></html>"))
        self.label_3.setText(_translate("LaAnimalManagerBase", "Breeding Life"))
        self.sbBreedingLife.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Number of years females are useful for breeding</p></body></html>"))
        self.sbBreedingLife.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to determine the number of female offspring that need to be retained to sustain the adult female population (breeding herd) it is necessary to know how long a female of the species can be expected to breed reliably. This is <span style=\" font-weight:600;\">not</span> life expectancy.</p></body></html>"))
        self.sbBreedingLife.setSuffix(_translate("LaAnimalManagerBase", " Years"))
        self.label_19.setText(_translate("LaAnimalManagerBase", "Conception %"))
        self.sbConceptionEfficiency.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Average weight of animal (Kg) when slaughtered</p></body></html>"))
        self.sbConceptionEfficiency.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Animals can be slaughtered for butchering at any weight, but LandUse Analyst needs to know the average weight of the animals when they are slaughtered. This is their <span style=\" font-weight:600;\">live weight.</span></p></body></html>"))
        self.sbConceptionEfficiency.setSuffix(_translate("LaAnimalManagerBase", "  %"))
        self.label_5.setText(_translate("LaAnimalManagerBase", "Young / birth"))
        self.sbYoungPerBirth.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Number of young born per birth (average)</p></body></html>"))
        self.sbYoungPerBirth.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set the number of babies born to a mother. This is total number, not surviving numbers. To account for deaths between birth and weaning, adjust the Death Rate.</p></body></html>"))
        self.label_6.setText(_translate("LaAnimalManagerBase", "Weaning Age"))
        self.sbWeaningAge.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Weeks from birth to weaning</p></body></html>"))
        self.sbWeaningAge.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The age of the babies, in weeks, at which they stop feeding from their mother. It is assumed by LandUse Analyst that mothers will become pregnant after one estrous cycle following weaning.</p></body></html>"))
        self.sbWeaningAge.setSuffix(_translate("LaAnimalManagerBase", " days"))
        self.label_7.setText(_translate("LaAnimalManagerBase", "Gestation Time"))
        self.sbGestationTime.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Gestation time in days</p></body></html>"))
        self.sbGestationTime.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of days for gestation. </p></body></html>"))
        self.sbGestationTime.setSuffix(_translate("LaAnimalManagerBase", " days"))
        self.label_8.setText(_translate("LaAnimalManagerBase", "Estrous Cycle"))
        self.sbEstrousCycleTime.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of days in their estrous cycle</p></body></html>"))
        self.sbEstrousCycleTime.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of days in the animal\'s estrous cycle.</p></body></html>"))
        self.sbEstrousCycleTime.setSuffix(_translate("LaAnimalManagerBase", " days"))
        self.label_21.setText(_translate("LaAnimalManagerBase", "Lactation Time"))
        self.sbLactationTime.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of days in their estrous cycle</p></body></html>"))
        self.sbLactationTime.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of days in the animal\'s estrous cycle.</p></body></html>"))
        self.sbLactationTime.setProperty("text", _translate("LaAnimalManagerBase", "210 days"))
        self.sbLactationTime.setSuffix(_translate("LaAnimalManagerBase", " days"))
        self.grpProfiles.setTitle(_translate("LaAnimalManagerBase", "Available Animal Profiles"))
        self.tblAnimals.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select an animal here to see and/or edit it\'s properties below.</p></body></html>"))
        self.tblAnimals.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model animals, several details must be supplied. Animal Parameter Manager asks for these specifics. As with Animal Manager, it is possible to have more than one parameter named the same thing. Again, just enter a descriptor in the Notes: field.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different parameters for the same animal, follow the same procedure as for defining multiple animals with the same name. Let\'s say you want to have two parameters set up for Cows as an example. The Name: field is Cow for both, but in Notes: field, enter Optimistic for one, and Conservative for the other. Then adjust the parameters as you wish for each. Even though the name is the same, the parameters are saved uniquely. Having multiple parameters can be useful for setting up different scenarios, such as drought years, diease, catastrophic events, etc. Eventually, LandUse Analyst will have the ability to model over time, and will have these types of scenarios incorporated into the model.</p></body></html>"))
        item = self.tblAnimals.horizontalHeaderItem(0)
        item.setText(_translate("LaAnimalManagerBase", "FileName"))
        item = self.tblAnimals.horizontalHeaderItem(1)
        item.setText(_translate("LaAnimalManagerBase", "Name"))
        self.toolCopy.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clone the currently selected animal</p></body></html>"))
        self.toolCopy.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want to create a new animal that is similar to one already defined, you can clone this animal to save time. All of the settings of the animal you are cloning are transferred to the new clone, but the name is changed to Clone of ... (whatever the name of the animal you are cloning was).</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note that the parameters are <span style=\" font-weight:600;\">not</span> transferred.</p></body></html>"))
        self.toolCopy.setText(_translate("LaAnimalManagerBase", "..."))
        self.toolNew.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Define a new animal</p></body></html>"))
        self.toolNew.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you simply change the name or settings and click apply in the Animal Manager, you are just editing the animal currently selected. To create a new animal, you must click on the New button.</p></body></html>"))
        self.toolNew.setText(_translate("LaAnimalManagerBase", "..."))
        self.toolDelete.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Delete the currently selected animal</p></body></html>"))
        self.toolDelete.setText(_translate("LaAnimalManagerBase", "..."))
        self.lblAnimalPix.setText(_translate("LaAnimalManagerBase", "No Graphic\n"
"Selected"))
        self.pbnAnimalPic.setText(_translate("LaAnimalManagerBase", "Set Graphic"))
        self.pbnImport.setText(_translate("LaAnimalManagerBase", "Import"))
        self.pbnExport.setText(_translate("LaAnimalManagerBase", "Export"))
        self.groupBoxFeedRequirements.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LandUse Analyst breaks down the calorie requirements for the animal being modelled into three categories: Gestating, Lactating, and Juvenile. Enter the average calories required per day for an animal in each of these categories.</p></body></html>"))
        self.groupBoxFeedRequirements.setTitle(_translate("LaAnimalManagerBase", "Daily Feed Requirements"))
        self.label_13.setText(_translate("LaAnimalManagerBase", "Select Units"))
        self.cbFeedEnergyType.setItemText(0, _translate("LaAnimalManagerBase", "MCalories"))
        self.cbFeedEnergyType.setItemText(1, _translate("LaAnimalManagerBase", "TDN"))
        self.labelFeedRequirements2.setText(_translate("LaAnimalManagerBase", "Pregnant Female"))
        self.sbEnergyForPregnant.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Annual TDN (kg) required for an adult female</p></body></html>"))
        self.labelFeedRequirements3.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Annual TDN (kg) required for an adult male</p></body></html>"))
        self.labelFeedRequirements3.setText(_translate("LaAnimalManagerBase", "Lactating Female"))
        self.sbEnergyForLactating.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of calories required per day for a female that is lactating.</p></body></html>"))
        self.labelFeedRequirements3_2.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Annual TDN (kg) required for an adult male</p></body></html>"))
        self.labelFeedRequirements3_2.setText(_translate("LaAnimalManagerBase", "Maintenance (Adult)"))
        self.sbEnergyForMaintenance.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of calories required per day for a female that is lactating.</p></body></html>"))
        self.labelFeedRequirements4.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Annual TDN (kg) required for a juvenile</p></body></html>"))
        self.labelFeedRequirements4.setText(_translate("LaAnimalManagerBase", "Juvenile"))
        self.sbEnergyForJuvenilePerKg.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of calories required per day for a juvenile.</p></body></html>"))
        self.sbEnergyForJuvenilePerKg.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of calories required per day for a juvenile. LandUse Analyst considers a Juvenile to be an animal after weaning and before slaughter.</p></body></html>"))
        self.sbEnergyForJuvenilePerKg.setSuffix(_translate("LaAnimalManagerBase", " per Kg"))
        self.groupBoxByProducts.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All of the settings in Reproduction define an animal\'s reproductive characteristics. LandUse Analyst calculates the time between births by adding the gestation time, weaning age, and one estrous cycle.</p></body></html>"))
        self.groupBoxByProducts.setTitle(_translate("LaAnimalManagerBase", "By-Products"))
        self.checkBoxMilk.setText(_translate("LaAnimalManagerBase", "Milk"))
        self.sbMilk.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Age of females when they become sexually mature.</p></body></html>"))
        self.sbMilk.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Simply set the age, in months, at which the females become sexually mature, and are able to reliably breed.</p></body></html>"))
        self.sbMilk.setSuffix(_translate("LaAnimalManagerBase", " g"))
        self.label_15.setText(_translate("LaAnimalManagerBase", "Food Value"))
        self.sbMilkFoodValue.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Number of years females are useful for breeding</p></body></html>"))
        self.sbMilkFoodValue.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to determine the number of female offspring that need to be retained to sustain the adult female population (breeding herd) it is necessary to know how long a female of the species can be expected to breed reliably. This is <span style=\" font-weight:600;\">not</span> life expectancy.</p></body></html>"))
        self.sbMilkFoodValue.setSuffix(_translate("LaAnimalManagerBase", " Cals/Kg"))
        self.checkBoxFleece.setText(_translate("LaAnimalManagerBase", "Fleece"))
        self.sbFleeceWeight.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Number of young born per birth (average)</p></body></html>"))
        self.sbFleeceWeight.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set the number of babies born to a mother. This is total number, not surviving numbers. To account for deaths between birth and weaning, adjust the Death Rate.</p></body></html>"))
        self.sbFleeceWeight.setSuffix(_translate("LaAnimalManagerBase", " Kg/year"))
        self.pbnApply.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Saves all settings</p></body></html>"))
        self.pbnApply.setWhatsThis(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After completing all fields to define an animal, you <span style=\" font-weight:600;\">MUST</span> click the Apply button to save it. The name does not have to be unique, as LandUse Analyst has a special way of saving animals to allow for duplicate Animal names. It is helpful, however, to utilize the Notes field to distinguish between same-named animal definitions.</p></body></html>"))
        self.pbnApply.setText(_translate("LaAnimalManagerBase", "Apply"))
        self.pbnClose.setToolTip(_translate("LaAnimalManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#0000ff;\">Have you applied your changes?</span></p></body></html>"))
        self.pbnClose.setText(_translate("LaAnimalManagerBase", "Close"))
import resources_rc
