# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arkygeek/dev/QGisPlugins/landuseanalyst/landuse_analyst/src/ui/lacropmanagerbase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LaCropManagerBase(object):
    def setupUi(self, LaCropManagerBase):
        LaCropManagerBase.setObjectName("LaCropManagerBase")
        LaCropManagerBase.resize(454, 456)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/la_icon_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LaCropManagerBase.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(LaCropManagerBase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grpProfiles = QtWidgets.QGroupBox(LaCropManagerBase)
        self.grpProfiles.setObjectName("grpProfiles")
        self.gridlayout = QtWidgets.QGridLayout(self.grpProfiles)
        self.gridlayout.setContentsMargins(9, 9, 9, 9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.gridlayout1 = QtWidgets.QGridLayout()
        self.gridlayout1.setContentsMargins(0, 0, 0, 0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.toolNew = QtWidgets.QToolButton(self.grpProfiles)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolNew.setIcon(icon1)
        self.toolNew.setObjectName("toolNew")
        self.gridlayout1.addWidget(self.toolNew, 2, 0, 1, 1)
        self.toolDelete = QtWidgets.QToolButton(self.grpProfiles)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolDelete.setIcon(icon2)
        self.toolDelete.setObjectName("toolDelete")
        self.gridlayout1.addWidget(self.toolDelete, 2, 2, 1, 1)
        self.toolCopy = QtWidgets.QToolButton(self.grpProfiles)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCopy.setIcon(icon3)
        self.toolCopy.setObjectName("toolCopy")
        self.gridlayout1.addWidget(self.toolCopy, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem, 1, 1, 1, 1)
        self.lblCropPix = QtWidgets.QLabel(self.grpProfiles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCropPix.sizePolicy().hasHeightForWidth())
        self.lblCropPix.setSizePolicy(sizePolicy)
        self.lblCropPix.setMinimumSize(QtCore.QSize(100, 100))
        self.lblCropPix.setMaximumSize(QtCore.QSize(100, 100))
        self.lblCropPix.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCropPix.setObjectName("lblCropPix")
        self.gridlayout1.addWidget(self.lblCropPix, 0, 0, 1, 3)
        self.gridlayout.addLayout(self.gridlayout1, 0, 3, 2, 1)
        self.tblCrops = QtWidgets.QTableWidget(self.grpProfiles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblCrops.sizePolicy().hasHeightForWidth())
        self.tblCrops.setSizePolicy(sizePolicy)
        self.tblCrops.setMinimumSize(QtCore.QSize(0, 0))
        self.tblCrops.setAlternatingRowColors(True)
        self.tblCrops.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblCrops.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblCrops.setObjectName("tblCrops")
        self.tblCrops.setColumnCount(2)
        self.tblCrops.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCrops.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCrops.setHorizontalHeaderItem(1, item)
        self.gridlayout.addWidget(self.tblCrops, 0, 0, 1, 3)
        self.pbnImport = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnImport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnImport.setObjectName("pbnImport")
        self.gridlayout.addWidget(self.pbnImport, 1, 0, 1, 1)
        self.pbnExport = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnExport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnExport.setObjectName("pbnExport")
        self.gridlayout.addWidget(self.pbnExport, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(111, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.grpProfiles, 0, 0, 1, 3)
        self.groupBoxPlantDescription = QtWidgets.QGroupBox(LaCropManagerBase)
        self.groupBoxPlantDescription.setObjectName("groupBoxPlantDescription")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxPlantDescription)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBoxPlantDescription)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.leName = QtWidgets.QLineEdit(self.groupBoxPlantDescription)
        self.leName.setObjectName("leName")
        self.gridLayout.addWidget(self.leName, 0, 2, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.groupBoxPlantDescription)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 2, 2)
        self.leDescription = QtWidgets.QLineEdit(self.groupBoxPlantDescription)
        self.leDescription.setObjectName("leDescription")
        self.gridLayout.addWidget(self.leDescription, 1, 2, 1, 3)
        self.pbnCropPic = QtWidgets.QPushButton(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnCropPic.sizePolicy().hasHeightForWidth())
        self.pbnCropPic.setSizePolicy(sizePolicy)
        self.pbnCropPic.setObjectName("pbnCropPic")
        self.gridLayout.addWidget(self.pbnCropPic, 1, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBoxPlantDescription)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 1, 1, 5)
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.labelPlantDescription4 = QtWidgets.QLabel(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlantDescription4.sizePolicy().hasHeightForWidth())
        self.labelPlantDescription4.setSizePolicy(sizePolicy)
        self.labelPlantDescription4.setTextFormat(QtCore.Qt.AutoText)
        self.labelPlantDescription4.setWordWrap(False)
        self.labelPlantDescription4.setObjectName("labelPlantDescription4")
        self.vboxlayout.addWidget(self.labelPlantDescription4)
        self.labelPlantDescription6 = QtWidgets.QLabel(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlantDescription6.sizePolicy().hasHeightForWidth())
        self.labelPlantDescription6.setSizePolicy(sizePolicy)
        self.labelPlantDescription6.setTextFormat(QtCore.Qt.AutoText)
        self.labelPlantDescription6.setWordWrap(False)
        self.labelPlantDescription6.setObjectName("labelPlantDescription6")
        self.vboxlayout.addWidget(self.labelPlantDescription6)
        self.label_3 = QtWidgets.QLabel(self.groupBoxPlantDescription)
        self.label_3.setObjectName("label_3")
        self.vboxlayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.vboxlayout, 3, 0, 5, 2)
        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.sbCropYield = QtWidgets.QSpinBox(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCropYield.sizePolicy().hasHeightForWidth())
        self.sbCropYield.setSizePolicy(sizePolicy)
        self.sbCropYield.setMaximum(400)
        self.sbCropYield.setProperty("value", 60)
        self.sbCropYield.setObjectName("sbCropYield")
        self.vboxlayout1.addWidget(self.sbCropYield)
        self.sbCropFodderProduction = QtWidgets.QSpinBox(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCropFodderProduction.sizePolicy().hasHeightForWidth())
        self.sbCropFodderProduction.setSizePolicy(sizePolicy)
        self.sbCropFodderProduction.setMaximum(400)
        self.sbCropFodderProduction.setProperty("value", 60)
        self.sbCropFodderProduction.setObjectName("sbCropFodderProduction")
        self.vboxlayout1.addWidget(self.sbCropFodderProduction)
        self.cbAreaUnits = QtWidgets.QComboBox(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAreaUnits.sizePolicy().hasHeightForWidth())
        self.cbAreaUnits.setSizePolicy(sizePolicy)
        self.cbAreaUnits.setObjectName("cbAreaUnits")
        self.vboxlayout1.addWidget(self.cbAreaUnits)
        self.gridLayout.addLayout(self.vboxlayout1, 3, 2, 5, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxPlantDescription)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 3, 1, 1)
        self.sbCropCalories = QtWidgets.QSpinBox(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCropCalories.sizePolicy().hasHeightForWidth())
        self.sbCropCalories.setSizePolicy(sizePolicy)
        self.sbCropCalories.setMinimum(1)
        self.sbCropCalories.setMaximum(5000)
        self.sbCropCalories.setProperty("value", 3000)
        self.sbCropCalories.setObjectName("sbCropCalories")
        self.gridLayout.addWidget(self.sbCropCalories, 4, 4, 1, 2)
        self.line = QtWidgets.QFrame(self.groupBoxPlantDescription)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 3, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBoxPlantDescription)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 3, 1, 3)
        self.sbCropFodderValue = QtWidgets.QSpinBox(self.groupBoxPlantDescription)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCropFodderValue.sizePolicy().hasHeightForWidth())
        self.sbCropFodderValue.setSizePolicy(sizePolicy)
        self.sbCropFodderValue.setSuffix("")
        self.sbCropFodderValue.setMinimum(1)
        self.sbCropFodderValue.setMaximum(500000)
        self.sbCropFodderValue.setSingleStep(1)
        self.sbCropFodderValue.setProperty("value", 1123)
        self.sbCropFodderValue.setObjectName("sbCropFodderValue")
        self.gridLayout.addWidget(self.sbCropFodderValue, 7, 3, 1, 2)
        self.cbFodderEnergyType = QtWidgets.QComboBox(self.groupBoxPlantDescription)
        self.cbFodderEnergyType.setObjectName("cbFodderEnergyType")
        self.gridLayout.addWidget(self.cbFodderEnergyType, 7, 5, 1, 1)
        self.label.raise_()
        self.leName.raise_()
        self.label_4.raise_()
        self.leDescription.raise_()
        self.pbnCropPic.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.sbCropFodderValue.raise_()
        self.cbFodderEnergyType.raise_()
        self.gridLayout_2.addWidget(self.groupBoxPlantDescription, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(31, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.pbnApply = QtWidgets.QPushButton(LaCropManagerBase)
        self.pbnApply.setCheckable(False)
        self.pbnApply.setFlat(False)
        self.pbnApply.setObjectName("pbnApply")
        self.gridLayout_2.addWidget(self.pbnApply, 2, 1, 1, 1)
        self.pbnClose = QtWidgets.QPushButton(LaCropManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnClose.sizePolicy().hasHeightForWidth())
        self.pbnClose.setSizePolicy(sizePolicy)
        self.pbnClose.setObjectName("pbnClose")
        self.gridLayout_2.addWidget(self.pbnClose, 2, 2, 1, 1)

        self.retranslateUi(LaCropManagerBase)
        self.pbnClose.clicked.connect(LaCropManagerBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LaCropManagerBase)
        LaCropManagerBase.setTabOrder(self.tblCrops, self.pbnImport)
        LaCropManagerBase.setTabOrder(self.pbnImport, self.pbnExport)
        LaCropManagerBase.setTabOrder(self.pbnExport, self.toolNew)
        LaCropManagerBase.setTabOrder(self.toolNew, self.toolCopy)
        LaCropManagerBase.setTabOrder(self.toolCopy, self.toolDelete)
        LaCropManagerBase.setTabOrder(self.toolDelete, self.leName)
        LaCropManagerBase.setTabOrder(self.leName, self.leDescription)
        LaCropManagerBase.setTabOrder(self.leDescription, self.sbCropYield)
        LaCropManagerBase.setTabOrder(self.sbCropYield, self.sbCropCalories)
        LaCropManagerBase.setTabOrder(self.sbCropCalories, self.sbCropFodderProduction)
        LaCropManagerBase.setTabOrder(self.sbCropFodderProduction, self.sbCropFodderValue)
        LaCropManagerBase.setTabOrder(self.sbCropFodderValue, self.cbAreaUnits)
        LaCropManagerBase.setTabOrder(self.cbAreaUnits, self.pbnApply)
        LaCropManagerBase.setTabOrder(self.pbnApply, self.pbnClose)

    def retranslateUi(self, LaCropManagerBase):
        _translate = QtCore.QCoreApplication.translate
        LaCropManagerBase.setWindowTitle(_translate("LaCropManagerBase", "Crop Profile Manager"))
        self.grpProfiles.setTitle(_translate("LaCropManagerBase", "Available Crop Profiles"))
        self.toolNew.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Define a new crop</p></body></html>"))
        self.toolNew.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you simply change the name or settings and click apply in the Crop Manager, you are just editing the Crop currently selected. To create a new Crop, you must click on the New button.</p></body></html>"))
        self.toolNew.setText(_translate("LaCropManagerBase", "..."))
        self.toolDelete.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Delete the currently selected crop</p></body></html>"))
        self.toolDelete.setText(_translate("LaCropManagerBase", "..."))
        self.toolCopy.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clone the currently selected crop</p></body></html>"))
        self.toolCopy.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want to create a new crop that is similar to one already defined, you can clone this crop to save time. All of the settings of the crop you are cloning are transferred to the new clone, but the name is changed to Clone of ... (whatever the name of the crop you are cloning was).</p></body></html>"))
        self.toolCopy.setText(_translate("LaCropManagerBase", "..."))
        self.lblCropPix.setText(_translate("LaCropManagerBase", "No Graphic\n"
"Selected"))
        self.tblCrops.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a crop here to see and/or edit it\'s properties below.</p></body></html>"))
        self.tblCrops.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model any crop, several details must be entered to define specific varieties. Crop Manager asks for general information about the crop in this section. You might want to have more than one strain of the same variety, however, which is allowed.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different strains of the same variety is quite easy. Let\'s say you want to have two kinds of wheat for example. The Name: field is Wheat for both, but in Notes: field, enter Hard Red for one, and Soft White for the other. Then adjust the other parameters as you wish. Even though the name is the same, the crop is saved uniquely.</p></body></html>"))
        item = self.tblCrops.horizontalHeaderItem(0)
        item.setText(_translate("LaCropManagerBase", "FileName"))
        item = self.tblCrops.horizontalHeaderItem(1)
        item.setText(_translate("LaCropManagerBase", "Name"))
        self.pbnImport.setText(_translate("LaCropManagerBase", "Import"))
        self.pbnExport.setText(_translate("LaCropManagerBase", "Export"))
        self.groupBoxPlantDescription.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model any crop, several details must be entered to define specific varieties. Crop Manager asks for general information about the crop in this section. You might want to have more than one strain of the same variety, however, which is allowed.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different strains of the same variety is quite easy. Let\'s say you want to have two kinds of wheat for example. The Name: field is Wheat for both, but in Notes: field, enter Hard Red for one, and Soft White for the other. Then adjust the other parameters as you wish. Even though the name is the same, the crop is saved uniquely.</p></body></html>"))
        self.groupBoxPlantDescription.setTitle(_translate("LaCropManagerBase", "Crop Description"))
        self.label.setText(_translate("LaCropManagerBase", "Name:"))
        self.leName.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the name of the crop you are defining in this field. You do not need a unique name. You can have, for example, 10 crops defined, all named \"Wheat\". LandUse Analyst uses a special method of saving the crops to eliminate the issue of duplicate filenames.</p></body></html>"))
        self.label_4.setText(_translate("LaCropManagerBase", "Notes:"))
        self.leDescription.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Because LandUse Analyst allows more than one type of crop to be defined, the Notes: field allows you to give a brief description of the the crop. For example, you may have two \"Wheat\" crops defined, and the Notes: fields could contain \"Hard Red\" and \"Soft White\" to distinguish between them.</p></body></html>"))
        self.pbnCropPic.setText(_translate("LaCropManagerBase", "Set Graphic"))
        self.labelPlantDescription4.setText(_translate("LaCropManagerBase", "Crop Yield"))
        self.labelPlantDescription6.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fodder produced from Wheat</p></body></html>"))
        self.labelPlantDescription6.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fodder is the straw and chaff left after harvesting the grain.  Enter the number of Kilograms expected for this crop per (either) dunum or hectare</p></body></html>"))
        self.labelPlantDescription6.setText(_translate("LaCropManagerBase", "Fodder"))
        self.label_3.setText(_translate("LaCropManagerBase", "Area Units *"))
        self.sbCropYield.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Yield of Crop</p></body></html>"))
        self.sbCropYield.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here you must enter what you think the average yield for the crop would have been. This is a measure of Kg produced per the given area of sown land.</p></body></html>"))
        self.sbCropYield.setSuffix(_translate("LaCropManagerBase", " Kg/*"))
        self.sbCropFodderProduction.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fodder produced from Wheat</p></body></html>"))
        self.sbCropFodderProduction.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Fodder Yield is how many Kg of Straw and Chaff (per area unit) that is <span style=\" font-weight:600;\">made available to animals for feed</span>.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fodder is the straw and chaff left after harvesting the grain.  Enter the number of Kilograms expected to be produced from this crop per (either) dunum or hectare.  <span style=\" font-weight:600; color:#0000ff;\">Note that this fodder amount is solely for consumption by animals.</span>  If straw or chaff is being used for other purposes, it must be taken out of the total expected fodder level.</p></body></html>"))
        self.sbCropFodderProduction.setSuffix(_translate("LaCropManagerBase", " Kg/*"))
        self.cbAreaUnits.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 dunum = 1000 square meters</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 hectare = 10,000 square meters</p></body></html>"))
        self.cbAreaUnits.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select either Dunums or Hectares. This option is merely for convenience, to accomodate data that is available based on the two different units. (Basically I just got sick of having to convert between the two all the time! :P)</p></body></html>"))
        self.label_2.setText(_translate("LaCropManagerBase", "Crop Value:"))
        self.sbCropCalories.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The number of calories in 1 Kg of that part of the crop which is eaten (ie. the grain or fruit). </p></body></html>"))
        self.sbCropCalories.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.sbCropCalories.setSuffix(_translate("LaCropManagerBase", " Cal/Kg"))
        self.label_5.setText(_translate("LaCropManagerBase", "Food Value of Fodder:"))
        self.sbCropFodderValue.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Calories per kilogram of fodder</p></body></html>"))
        self.sbCropFodderValue.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Food value of fodder when used as feed for domestic animals.  This is measured in calories per kilogram.</p></body></html>"))
        self.pbnApply.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Saves all settings</p></body></html>"))
        self.pbnApply.setWhatsThis(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After completing all fields to define a crop, you <span style=\" font-weight:600;\">MUST</span> click the Apply button to save it. The name does not have to be unique, as LandUse Analyst has a special way of saving crops to allow for duplicate crop names. It is helpful, however, to utilize the Notes field to distinguish between same-named crop definitions.</p></body></html>"))
        self.pbnApply.setText(_translate("LaCropManagerBase", "Apply"))
        self.pbnClose.setToolTip(_translate("LaCropManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#0000ff;\">Have you applied your changes?</span></p></body></html>"))
        self.pbnClose.setText(_translate("LaCropManagerBase", "Close"))
import resources_rc
