# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arkygeek/dev/QGisPlugins/landuseanalyst/landuse_analyst/src/ui/laReportFallow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelTargets(object):
    def setupUi(self, ModelTargets):
        ModelTargets.setObjectName("ModelTargets")
        ModelTargets.resize(529, 217)
        self.gridlayout = QtWidgets.QGridLayout(ModelTargets)
        self.gridlayout.setObjectName("gridlayout")
        self.pbnClose = QtWidgets.QPushButton(ModelTargets)
        self.pbnClose.setObjectName("pbnClose")
        self.gridlayout.addWidget(self.pbnClose, 1, 3, 1, 1)
        self.pbnExport = QtWidgets.QPushButton(ModelTargets)
        self.pbnExport.setObjectName("pbnExport")
        self.gridlayout.addWidget(self.pbnExport, 1, 1, 1, 1)
        self.pbnPrint = QtWidgets.QPushButton(ModelTargets)
        self.pbnPrint.setObjectName("pbnPrint")
        self.gridlayout.addWidget(self.pbnPrint, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(ModelTargets)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tblFallow = QtWidgets.QTableWidget(self.splitter)
        self.tblFallow.setAlternatingRowColors(True)
        self.tblFallow.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblFallow.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblFallow.setObjectName("tblFallow")
        self.tblFallow.setColumnCount(5)
        self.tblFallow.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFallow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFallow.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFallow.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFallow.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFallow.setHorizontalHeaderItem(4, item)
        self.gridlayout.addWidget(self.splitter, 0, 0, 1, 4)

        self.retranslateUi(ModelTargets)
        self.pbnClose.clicked.connect(ModelTargets.close) # type: ignore
        self.pbnClose.clicked.connect(ModelTargets.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModelTargets)

    def retranslateUi(self, ModelTargets):
        _translate = QtCore.QCoreApplication.translate
        ModelTargets.setWindowTitle(_translate("ModelTargets", "Model Targets"))
        self.pbnClose.setText(_translate("ModelTargets", "Close"))
        self.pbnExport.setText(_translate("ModelTargets", "Export"))
        self.pbnPrint.setText(_translate("ModelTargets", "Print"))
        self.tblFallow.setToolTip(_translate("ModelTargets", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a crop here to see and/or edit it\'s properties below.</p></body></html>"))
        self.tblFallow.setWhatsThis(_translate("ModelTargets", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable LandUse Analyst to model any crop, several details must be entered to define specific varieties. Crop Manager asks for general information about the crop in this section. You might want to have more than one strain of the same variety, however, which is allowed.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different strains of the same variety is quite easy. Let\'s say you want to have two kinds of wheat for example. The Name: field is Wheat for both, but in Notes: field, enter Hard Red for one, and Soft White for the other. Then adjust the other parameters as you wish. Even though the name is the same, the crop is saved uniquely.</p></body></html>"))
        item = self.tblFallow.horizontalHeaderItem(0)
        item.setText(_translate("ModelTargets", "Crop"))
        item = self.tblFallow.horizontalHeaderItem(1)
        item.setText(_translate("ModelTargets", "Area Available"))
        item = self.tblFallow.horizontalHeaderItem(2)
        item.setText(_translate("ModelTargets", "Animal"))
        item = self.tblFallow.horizontalHeaderItem(3)
        item.setText(_translate("ModelTargets", "Allocated"))
        item = self.tblFallow.horizontalHeaderItem(4)
        item.setText(_translate("ModelTargets", "New Target"))
