[pytest]
# Directory containing tests
testpaths = la/test

# Test naming conventions
python_files = test_*.py
python_classes = *Test
python_functions = test_*

# CLI options
addopts = -v --tb=short

# Markers definition
markers =
    qgis: Tests that require a functional QGIS environment / libraries
    slow: Tests that might take longer to execute
