# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arkygeek/devcode/landuseanalyst/landuse_analyst/ui/lacropparametermanagerbase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LaCropParameterManagerBase(object):
    def setupUi(self, LaCropParameterManagerBase):
        LaCropParameterManagerBase.setObjectName("LaCropParameterManagerBase")
        LaCropParameterManagerBase.resize(520, 583)
        LaCropParameterManagerBase.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/la_icon_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LaCropParameterManagerBase.setWindowIcon(icon)
        self.gridlayout = QtWidgets.QGridLayout(LaCropParameterManagerBase)
        self.gridlayout.setObjectName("gridlayout")
        self.grpProfiles = QtWidgets.QGroupBox(LaCropParameterManagerBase)
        self.grpProfiles.setObjectName("grpProfiles")
        self.gridlayout1 = QtWidgets.QGridLayout(self.grpProfiles)
        self.gridlayout1.setObjectName("gridlayout1")
        self.gridlayout2 = QtWidgets.QGridLayout()
        self.gridlayout2.setObjectName("gridlayout2")
        self.toolDelete = QtWidgets.QToolButton(self.grpProfiles)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolDelete.setIcon(icon1)
        self.toolDelete.setObjectName("toolDelete")
        self.gridlayout2.addWidget(self.toolDelete, 2, 2, 1, 1)
        self.toolCopy = QtWidgets.QToolButton(self.grpProfiles)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolCopy.setIcon(icon2)
        self.toolCopy.setObjectName("toolCopy")
        self.gridlayout2.addWidget(self.toolCopy, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout2.addItem(spacerItem, 1, 1, 1, 1)
        self.lblCropPic = QtWidgets.QLabel(self.grpProfiles)
        self.lblCropPic.setMinimumSize(QtCore.QSize(100, 100))
        self.lblCropPic.setMaximumSize(QtCore.QSize(100, 100))
        self.lblCropPic.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCropPic.setObjectName("lblCropPic")
        self.gridlayout2.addWidget(self.lblCropPic, 0, 0, 1, 3)
        self.toolNew = QtWidgets.QToolButton(self.grpProfiles)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolNew.setIcon(icon3)
        self.toolNew.setObjectName("toolNew")
        self.gridlayout2.addWidget(self.toolNew, 2, 0, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 0, 3, 2, 1)
        self.pbnImport = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnImport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnImport.setObjectName("pbnImport")
        self.gridlayout1.addWidget(self.pbnImport, 1, 0, 1, 1)
        self.pbnExport = QtWidgets.QPushButton(self.grpProfiles)
        self.pbnExport.setMinimumSize(QtCore.QSize(80, 0))
        self.pbnExport.setObjectName("pbnExport")
        self.gridlayout1.addWidget(self.pbnExport, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(71, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem1, 1, 2, 1, 1)
        self.tblCropParameterProfiles = QtWidgets.QTableWidget(self.grpProfiles)
        self.tblCropParameterProfiles.setAlternatingRowColors(True)
        self.tblCropParameterProfiles.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblCropParameterProfiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblCropParameterProfiles.setObjectName("tblCropParameterProfiles")
        self.tblCropParameterProfiles.setColumnCount(2)
        self.tblCropParameterProfiles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCropParameterProfiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCropParameterProfiles.setHorizontalHeaderItem(1, item)
        self.gridlayout1.addWidget(self.tblCropParameterProfiles, 0, 0, 1, 3)
        self.gridlayout.addWidget(self.grpProfiles, 0, 0, 1, 6)
        self.label = QtWidgets.QLabel(LaCropParameterManagerBase)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 1, 0, 1, 1)
        self.leName = QtWidgets.QLineEdit(LaCropParameterManagerBase)
        self.leName.setObjectName("leName")
        self.gridlayout.addWidget(self.leName, 1, 1, 1, 1)
        self.grpCropRotation = QtWidgets.QGroupBox(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpCropRotation.sizePolicy().hasHeightForWidth())
        self.grpCropRotation.setSizePolicy(sizePolicy)
        self.grpCropRotation.setMinimumSize(QtCore.QSize(227, 100))
        self.grpCropRotation.setCheckable(True)
        self.grpCropRotation.setChecked(False)
        self.grpCropRotation.setObjectName("grpCropRotation")
        self.gridlayout3 = QtWidgets.QGridLayout(self.grpCropRotation)
        self.gridlayout3.setObjectName("gridlayout3")
        self.labelFallow1 = QtWidgets.QLabel(self.grpCropRotation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFallow1.sizePolicy().hasHeightForWidth())
        self.labelFallow1.setSizePolicy(sizePolicy)
        self.labelFallow1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFallow1.setObjectName("labelFallow1")
        self.gridlayout3.addWidget(self.labelFallow1, 0, 0, 1, 1)
        self.labelFallow3 = QtWidgets.QLabel(self.grpCropRotation)
        self.labelFallow3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelFallow3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFallow3.setObjectName("labelFallow3")
        self.gridlayout3.addWidget(self.labelFallow3, 0, 1, 1, 1)
        self.sbFallowRatio = QtWidgets.QDoubleSpinBox(self.grpCropRotation)
        self.sbFallowRatio.setMinimumSize(QtCore.QSize(0, 22))
        self.sbFallowRatio.setMaximum(5.0)
        self.sbFallowRatio.setSingleStep(0.25)
        self.sbFallowRatio.setProperty("value", 1.0)
        self.sbFallowRatio.setObjectName("sbFallowRatio")
        self.gridlayout3.addWidget(self.sbFallowRatio, 0, 2, 1, 1)
        self.labelFallow5 = QtWidgets.QLabel(self.grpCropRotation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFallow5.sizePolicy().hasHeightForWidth())
        self.labelFallow5.setSizePolicy(sizePolicy)
        self.labelFallow5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFallow5.setObjectName("labelFallow5")
        self.gridlayout3.addWidget(self.labelFallow5, 0, 3, 1, 2)
        self.labelFallow2 = QtWidgets.QLabel(self.grpCropRotation)
        self.labelFallow2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFallow2.setObjectName("labelFallow2")
        self.gridlayout3.addWidget(self.labelFallow2, 1, 0, 1, 5)
        self.sbFallowValue = QtWidgets.QSpinBox(self.grpCropRotation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbFallowValue.sizePolicy().hasHeightForWidth())
        self.sbFallowValue.setSizePolicy(sizePolicy)
        self.sbFallowValue.setMinimumSize(QtCore.QSize(0, 22))
        self.sbFallowValue.setSuffix("")
        self.sbFallowValue.setMinimum(1)
        self.sbFallowValue.setMaximum(5000)
        self.sbFallowValue.setSingleStep(10)
        self.sbFallowValue.setProperty("value", 500)
        self.sbFallowValue.setObjectName("sbFallowValue")
        self.gridlayout3.addWidget(self.sbFallowValue, 2, 0, 1, 2)
        self.cbFallowEnergyType = QtWidgets.QComboBox(self.grpCropRotation)
        self.cbFallowEnergyType.setMinimumSize(QtCore.QSize(0, 22))
        self.cbFallowEnergyType.setObjectName("cbFallowEnergyType")
        self.gridlayout3.addWidget(self.cbFallowEnergyType, 2, 2, 1, 2)
        self.cbAreaUnits = QtWidgets.QComboBox(self.grpCropRotation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAreaUnits.sizePolicy().hasHeightForWidth())
        self.cbAreaUnits.setSizePolicy(sizePolicy)
        self.cbAreaUnits.setMinimumSize(QtCore.QSize(0, 22))
        self.cbAreaUnits.setObjectName("cbAreaUnits")
        self.gridlayout3.addWidget(self.cbAreaUnits, 2, 4, 1, 1)
        self.gridlayout.addWidget(self.grpCropRotation, 1, 2, 4, 4)
        self.label_4 = QtWidgets.QLabel(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.leDescription = QtWidgets.QLineEdit(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDescription.sizePolicy().hasHeightForWidth())
        self.leDescription.setSizePolicy(sizePolicy)
        self.leDescription.setObjectName("leDescription")
        self.gridlayout.addWidget(self.leDescription, 2, 1, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_2 = QtWidgets.QLabel(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.hboxlayout.addWidget(self.label_2)
        self.cboCrop = QtWidgets.QComboBox(LaCropParameterManagerBase)
        self.cboCrop.setMinimumSize(QtCore.QSize(0, 26))
        self.cboCrop.setObjectName("cboCrop")
        self.hboxlayout.addWidget(self.cboCrop)
        self.gridlayout.addLayout(self.hboxlayout, 3, 0, 1, 2)
        self.groupBoxSuitableLand = QtWidgets.QGroupBox(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSuitableLand.sizePolicy().hasHeightForWidth())
        self.groupBoxSuitableLand.setSizePolicy(sizePolicy)
        self.groupBoxSuitableLand.setMinimumSize(QtCore.QSize(115, 0))
        self.groupBoxSuitableLand.setObjectName("groupBoxSuitableLand")
        self.gridlayout4 = QtWidgets.QGridLayout(self.groupBoxSuitableLand)
        self.gridlayout4.setObjectName("gridlayout4")
        self.checkBoxUseCommonLand = QtWidgets.QCheckBox(self.groupBoxSuitableLand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxUseCommonLand.sizePolicy().hasHeightForWidth())
        self.checkBoxUseCommonLand.setSizePolicy(sizePolicy)
        self.checkBoxUseCommonLand.setChecked(True)
        self.checkBoxUseCommonLand.setObjectName("checkBoxUseCommonLand")
        self.gridlayout4.addWidget(self.checkBoxUseCommonLand, 0, 0, 1, 2)
        self.checkBoxUseSpecificLand = QtWidgets.QCheckBox(self.groupBoxSuitableLand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxUseSpecificLand.sizePolicy().hasHeightForWidth())
        self.checkBoxUseSpecificLand.setSizePolicy(sizePolicy)
        self.checkBoxUseSpecificLand.setObjectName("checkBoxUseSpecificLand")
        self.gridlayout4.addWidget(self.checkBoxUseSpecificLand, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBoxSuitableLand)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.gridlayout4.addWidget(self.label_3, 2, 0, 1, 1)
        self.cboRaster = QtWidgets.QComboBox(self.groupBoxSuitableLand)
        self.cboRaster.setObjectName("cboRaster")
        self.gridlayout4.addWidget(self.cboRaster, 2, 1, 1, 1)
        self.gridlayout.addWidget(self.groupBoxSuitableLand, 4, 0, 4, 2)
        self.labelPortionDiet = QtWidgets.QLabel(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPortionDiet.sizePolicy().hasHeightForWidth())
        self.labelPortionDiet.setSizePolicy(sizePolicy)
        self.labelPortionDiet.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelPortionDiet.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelPortionDiet.setObjectName("labelPortionDiet")
        self.gridlayout.addWidget(self.labelPortionDiet, 5, 2, 1, 2)
        self.sbPercentTameCrop = QtWidgets.QDoubleSpinBox(LaCropParameterManagerBase)
        self.sbPercentTameCrop.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sbPercentTameCrop.setAccelerated(True)
        self.sbPercentTameCrop.setMaximum(100.0)
        self.sbPercentTameCrop.setSingleStep(0.01)
        self.sbPercentTameCrop.setObjectName("sbPercentTameCrop")
        self.gridlayout.addWidget(self.sbPercentTameCrop, 5, 4, 1, 2)
        self.labelPortionDiet_2 = QtWidgets.QLabel(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPortionDiet_2.sizePolicy().hasHeightForWidth())
        self.labelPortionDiet_2.setSizePolicy(sizePolicy)
        self.labelPortionDiet_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelPortionDiet_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelPortionDiet_2.setObjectName("labelPortionDiet_2")
        self.gridlayout.addWidget(self.labelPortionDiet_2, 6, 2, 1, 3)
        self.sbReseed = QtWidgets.QSpinBox(LaCropParameterManagerBase)
        self.sbReseed.setMaximum(100)
        self.sbReseed.setObjectName("sbReseed")
        self.gridlayout.addWidget(self.sbReseed, 6, 5, 1, 1)
        self.labelPortionDiet_3 = QtWidgets.QLabel(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPortionDiet_3.sizePolicy().hasHeightForWidth())
        self.labelPortionDiet_3.setSizePolicy(sizePolicy)
        self.labelPortionDiet_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelPortionDiet_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelPortionDiet_3.setObjectName("labelPortionDiet_3")
        self.gridlayout.addWidget(self.labelPortionDiet_3, 7, 2, 1, 3)
        self.sbSpoilage = QtWidgets.QSpinBox(LaCropParameterManagerBase)
        self.sbSpoilage.setMaximum(100)
        self.sbSpoilage.setObjectName("sbSpoilage")
        self.gridlayout.addWidget(self.sbSpoilage, 7, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(181, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 8, 0, 1, 2)
        self.pbnApply = QtWidgets.QPushButton(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnApply.sizePolicy().hasHeightForWidth())
        self.pbnApply.setSizePolicy(sizePolicy)
        self.pbnApply.setObjectName("pbnApply")
        self.gridlayout.addWidget(self.pbnApply, 8, 2, 1, 1)
        self.pbnClose = QtWidgets.QPushButton(LaCropParameterManagerBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbnClose.sizePolicy().hasHeightForWidth())
        self.pbnClose.setSizePolicy(sizePolicy)
        self.pbnClose.setObjectName("pbnClose")
        self.gridlayout.addWidget(self.pbnClose, 8, 3, 1, 3)

        self.retranslateUi(LaCropParameterManagerBase)
        self.pbnClose.pressed.connect(LaCropParameterManagerBase.close) # type: ignore
        self.checkBoxUseSpecificLand.clicked.connect(self.checkBoxUseCommonLand.toggle) # type: ignore
        self.checkBoxUseCommonLand.clicked.connect(self.checkBoxUseSpecificLand.toggle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LaCropParameterManagerBase)
        LaCropParameterManagerBase.setTabOrder(self.tblCropParameterProfiles, self.pbnImport)
        LaCropParameterManagerBase.setTabOrder(self.pbnImport, self.pbnExport)
        LaCropParameterManagerBase.setTabOrder(self.pbnExport, self.toolNew)
        LaCropParameterManagerBase.setTabOrder(self.toolNew, self.toolCopy)
        LaCropParameterManagerBase.setTabOrder(self.toolCopy, self.toolDelete)
        LaCropParameterManagerBase.setTabOrder(self.toolDelete, self.leName)
        LaCropParameterManagerBase.setTabOrder(self.leName, self.leDescription)
        LaCropParameterManagerBase.setTabOrder(self.leDescription, self.cboCrop)
        LaCropParameterManagerBase.setTabOrder(self.cboCrop, self.checkBoxUseCommonLand)
        LaCropParameterManagerBase.setTabOrder(self.checkBoxUseCommonLand, self.checkBoxUseSpecificLand)
        LaCropParameterManagerBase.setTabOrder(self.checkBoxUseSpecificLand, self.sbFallowRatio)
        LaCropParameterManagerBase.setTabOrder(self.sbFallowRatio, self.sbFallowValue)
        LaCropParameterManagerBase.setTabOrder(self.sbFallowValue, self.cbAreaUnits)
        LaCropParameterManagerBase.setTabOrder(self.cbAreaUnits, self.pbnApply)
        LaCropParameterManagerBase.setTabOrder(self.pbnApply, self.pbnClose)

    def retranslateUi(self, LaCropParameterManagerBase):
        _translate = QtCore.QCoreApplication.translate
        LaCropParameterManagerBase.setWindowTitle(_translate("LaCropParameterManagerBase", "Crop Parameter Manager"))
        self.grpProfiles.setTitle(_translate("LaCropParameterManagerBase", "Available Crop Parameter Settings"))
        self.toolDelete.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Delete the currently selected parameter</p></body></html>"))
        self.toolDelete.setText(_translate("LaCropParameterManagerBase", "..."))
        self.toolCopy.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Clone the currently selected parameter</p></body></html>"))
        self.toolCopy.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want to create a new parameter that is similar to one already defined, you can clone this parameter to save time. All of the settings of the parameter you are cloning are transferred to the new clone, but the name is changed to Clone of ... (whatever the name of the parameter you are cloning was).</p></body></html>"))
        self.toolCopy.setText(_translate("LaCropParameterManagerBase", "..."))
        self.lblCropPic.setText(_translate("LaCropParameterManagerBase", "No Graphic\n"
"Selected"))
        self.toolNew.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Define a new parameter</p></body></html>"))
        self.toolNew.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you simply change the name or settings and click apply in the Crop Parameter Manager, you are just editing the parameter currently selected. To create a new parameter, you <span style=\" font-weight:600;\">must</span> click on the New button.</p></body></html>"))
        self.toolNew.setText(_translate("LaCropParameterManagerBase", "..."))
        self.pbnImport.setText(_translate("LaCropParameterManagerBase", "Import"))
        self.pbnExport.setText(_translate("LaCropParameterManagerBase", "Export"))
        self.tblCropParameterProfiles.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a parameter here to see and/or edit it\'s properties below.</p></body></html>"))
        self.tblCropParameterProfiles.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order to enable Landuse Analyst to model crops, several details must be supplied. Crop Parameter Manager asks for these specifics. As with Crop Manager, it is possible to have more than one parameter named the same thing. Again, just enter a descriptor in the Notes: field.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To define different parameters for the same crop, follow the same procedure as for defining multiple crops with the same name. Let\'s say you want to have two parameters set up for Wheat as an example. The Name: field is Wheat for both, but in Notes: field, enter Optimistic for one, and Conservative for the other. Then adjust the parameters as you wish for each. Even though the name is the same, the parameters are saved uniquely. Having multiple parameters can be useful for setting up different scenarios, such as drought years, diease, catastrophic events, etc. Eventually, Landuse Analyst will have the ability to model over time, and will have these types of scenarios incorporated into the model.</p></body></html>"))
        item = self.tblCropParameterProfiles.horizontalHeaderItem(0)
        item.setText(_translate("LaCropParameterManagerBase", "FileName"))
        item = self.tblCropParameterProfiles.horizontalHeaderItem(1)
        item.setText(_translate("LaCropParameterManagerBase", "Name"))
        self.label.setText(_translate("LaCropParameterManagerBase", "Name:"))
        self.leName.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the name of the crop parameter you are defining in this field. You do not need a unique name. You can have, for example, 10 different crop parameters defined, all named \"Jericho\". Landuse Analyst uses a special method of saving the crop to eliminate the issue of duplicate filenames. This way, you can have, for example, conservative and optimistic settings for each crop at a site. </p></body></html>"))
        self.grpCropRotation.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If crops were rotated, the checkbox needs to be checked. The variables for crop rotation are unavailable until this has been done.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Keep in mind that animals can graze the fallow land. Because of this, you will need to estimate what the food value from the fallow land would have been, similar to what needs to be done when defining grazing land.</p></body></html>"))
        self.grpCropRotation.setTitle(_translate("LaCropParameterManagerBase", "Crop Rotation"))
        self.labelFallow1.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A value of 1:1 is default, and means that half the land is fallow, half is crop.  If there is a crop rotation so that it is only fallow every 3rd year, you could use a ratio of 2:1.  If they cropped continuously, the ratio would be 1:0.</p></body></html>"))
        self.labelFallow1.setText(_translate("LaCropParameterManagerBase", "Ratio"))
        self.labelFallow3.setText(_translate("LaCropParameterManagerBase", " 1: "))
        self.sbFallowRatio.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fallow Ratio</p></body></html>"))
        self.sbFallowRatio.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When crop rotation is used, this field must be set. If the land grows a crop one year, and is left fallow the next, then the crop to fallow ratio is 1:1 so you would set the value to 1. For more complicated rotations, such as a cereal-legume-fallow rotation, it gets slightly more complicated. That situation would be one year out of three fallow and two years out of three crop. In this case, the setting would be 0.50 which might seem confusing.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Just remember that you need to <span style=\" font-weight:600;\">divide the </span><span style=\" font-weight:600; font-style:italic;\">number of years of fallow</span><span style=\" font-weight:600;\"> by the </span><span style=\" font-weight:600; font-style:italic;\">number of years of crop</span> to set this properly.</p></body></html>"))
        self.labelFallow5.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A value of 1:1 is default, and means that half the land is fallow, half is crop.  If there is a crop rotation so that it is only fallow every 3rd year, you could use a ratio of 2:1.  If they cropped continuously, the ratio would be 1:0.</p></body></html>"))
        self.labelFallow5.setText(_translate("LaCropParameterManagerBase", "Crop:Fallow "))
        self.labelFallow2.setText(_translate("LaCropParameterManagerBase", "Fallow\'s Food Value"))
        self.sbFallowValue.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Food Value of Fallow Land</p></body></html>"))
        self.sbFallowValue.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If the selected crop is being grown in a rotation, producing fallow land, that land can be grazed. Landuse Analyst needs to know how many calories this land can give grazing animals per year. These numbers are in KCalories per dunum/hectare. (you can select the area units)</p></body></html>"))
        self.cbAreaUnits.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 dunum = 1000 square meters</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 hectare = 10,000 square meters</p></body></html>"))
        self.label_4.setText(_translate("LaCropParameterManagerBase", "Notes:"))
        self.leDescription.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Because Landuse Analyst allows more than one type of parameter to be defined, the Notes: field allows you to give a brief description of the the parameter. For example, you may have two \"Shuna\" parameters defined, and the Notes: fields could contain \"Conservative\" and \"Optimistic\" to distinguish between them.</p></body></html>"))
        self.label_2.setText(_translate("LaCropParameterManagerBase", "Crop:"))
        self.cboCrop.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Crop that these parameters are for.</p></body></html>"))
        self.cboCrop.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It is very important to select which crop your parameter settings are for. Once you slect the crop it appies to, simply click Apply, and it will then be properly allocated, and will show up in the dropdown list for that crop in the table on the top.</p></body></html>"))
        self.groupBoxSuitableLand.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In order for Landuse Analyst to create landuse maps, you must first create land suitability files to tell it what land is suitable for use by the crops and the crops. These files can be produced manually or automatically, but at the moment both must be done with external tools like QGis or GRASS. Future versions of Landuse Analyst will have the required features of these programs incorporated into it, but for now this step must be done externally. </p></body></html>"))
        self.groupBoxSuitableLand.setTitle(_translate("LaCropParameterManagerBase", "Suitability Masks"))
        self.checkBoxUseCommonLand.setToolTip(_translate("LaCropParameterManagerBase", "binary raster named: pigmask"))
        self.checkBoxUseCommonLand.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sometimes land is suitable for growing more than one type of crop. Landuse Analyst allows you to designate one suitability mask as common. Note that you can specify a crop to use both common land and specific land at the same time. If this is the case, equal preference is given to all crops using the common land.</p></body></html>"))
        self.checkBoxUseCommonLand.setText(_translate("LaCropParameterManagerBase", "Common Land"))
        self.checkBoxUseSpecificLand.setToolTip(_translate("LaCropParameterManagerBase", "binary raster named: pigmask"))
        self.checkBoxUseSpecificLand.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sometimes you may want to specify that land is suitable for growing only one type of crop. Landuse Analyst allows you to designate a land suitability mask as being unique to a certain crop. Note that you can specify a crop to use both common land and specific land at the same time. For more detailed information on this, see the help section on Crop Masks Common.</p></body></html>"))
        self.checkBoxUseSpecificLand.setText(_translate("LaCropParameterManagerBase", "Specific Land"))
        self.label_3.setText(_translate("LaCropParameterManagerBase", "Raster\n"
"Mask"))
        self.labelPortionDiet.setText(_translate("LaCropParameterManagerBase", "Portion of Tame Plant Diet"))
        self.sbPercentTameCrop.setSuffix(_translate("LaCropParameterManagerBase", "%"))
        self.labelPortionDiet_2.setText(_translate("LaCropParameterManagerBase", "Percent of harvest to re-seed"))
        self.sbReseed.setSuffix(_translate("LaCropParameterManagerBase", "%"))
        self.labelPortionDiet_3.setText(_translate("LaCropParameterManagerBase", "Percent of harvest to spoilage"))
        self.sbSpoilage.setSuffix(_translate("LaCropParameterManagerBase", "%"))
        self.pbnApply.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Saves all settings</p></body></html>"))
        self.pbnApply.setWhatsThis(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After completing all fields to define a parameter, you <span style=\" font-weight:600;\">MUST</span> click the Apply button to save it. The name does not have to be unique, as Landuse Analyst has a special way of saving parameters to allow for duplicate parameter names. It is helpful, however, to utilize the Notes field to distinguish between same-named parameter definitions.</p></body></html>"))
        self.pbnApply.setText(_translate("LaCropParameterManagerBase", "Apply"))
        self.pbnClose.setToolTip(_translate("LaCropParameterManagerBase", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#0000ff;\">Have you applied your changes?</span></p></body></html>"))
        self.pbnClose.setText(_translate("LaCropParameterManagerBase", "Close"))
import resources_rc
