Landuse Analyst: LaFoodSource Class Reference
LaFoodSource Class Reference
#include <lafoodsource.h>
Public Member Functions
LaFoodSource ()
~LaFoodSource ()
int grain () const
int fodder () const
int days () const
bool used () const
QString cropGuid () const
void setGrain (int theValue)
void setFodder (int theValue)
void setDays (int theValue)
void setUsed (bool theBool)
void setCropGuid (QString theCropGuid)
Private Attributes
int mGrain
int mFodder
int mDays
bool mUsed
QString mCropGuid
Detailed Description
Author:
Jason Jorgenson
Definition at line 27 of file lafoodsource.h.
Constructor & Destructor Documentation
LaFoodSource::LaFoodSource ()
Definition at line 23 of file lafoodsource.cpp.
{
}
LaFoodSource::~LaFoodSource ()
Definition at line 26 of file lafoodsource.cpp.
{
}
Member Function Documentation
int LaFoodSource::grain () const
Definition at line 32 of file lafoodsource.cpp.
References mGrain.
Referenced by LaModel::getProductionTargetsCrops(), LaAnimalParameterManager::refreshFodderTable(), LaAnimalParameter::toHtml(), and LaAnimalParameter::toXml().
{
  return mGrain;
}
int LaFoodSource::fodder () const
Definition at line 36 of file lafoodsource.cpp.
References mFodder.
Referenced by LaAnimalParameterManager::refreshFodderTable(), LaAnimalParameter::toHtml(), and LaAnimalParameter::toXml().
{
  return mFodder;
}
int LaFoodSource::days () const
Definition at line 40 of file lafoodsource.cpp.
References mDays.
Referenced by LaAnimalParameterManager::refreshFodderTable(), LaAnimalParameter::toHtml(), and LaAnimalParameter::toXml().
{
  return mDays;
}
bool LaFoodSource::used () const
Definition at line 44 of file lafoodsource.cpp.
References mUsed.
{
 return mUsed;
}
QString LaFoodSource::cropGuid () const
Definition at line 48 of file lafoodsource.cpp.
References mCropGuid.
{
 return mCropGuid;
}
void LaFoodSource::setGrain (int theValue)
Definition at line 54 of file lafoodsource.cpp.
References mGrain.
Referenced by LaAnimalParameter::fromXml(), and LaAnimalParameterManager::on_pbnApply_clicked().
{
  mGrain = theValue;
}
void LaFoodSource::setFodder (int theValue)
Definition at line 58 of file lafoodsource.cpp.
References mFodder.
Referenced by LaAnimalParameter::fromXml(), and LaAnimalParameterManager::on_pbnApply_clicked().
{
  mFodder = theValue;
}
void LaFoodSource::setDays (int theValue)
Definition at line 62 of file lafoodsource.cpp.
References mDays.
Referenced by LaAnimalParameter::fromXml(), and LaAnimalParameterManager::on_pbnApply_clicked().
{
  mDays = theValue;
}
void LaFoodSource::setUsed (bool theBool)
Definition at line 66 of file lafoodsource.cpp.
References mUsed.
Referenced by LaAnimalParameter::fromXml().
{
  mUsed = theBool;
}
void LaFoodSource::setCropGuid (QString theCropGuid)
Definition at line 70 of file lafoodsource.cpp.
References mCropGuid.
Referenced by LaAnimalParameter::fromXml().
{
  mCropGuid = theCropGuid;
}
Member Data Documentation
int LaFoodSource::mGrain [private]
Definition at line 46 of file lafoodsource.h.
Referenced by grain(), and setGrain().
int LaFoodSource::mFodder [private]
Definition at line 47 of file lafoodsource.h.
Referenced by fodder(), and setFodder().
int LaFoodSource::mDays [private]
Definition at line 48 of file lafoodsource.h.
Referenced by days(), and setDays().
bool LaFoodSource::mUsed [private]
Definition at line 49 of file lafoodsource.h.
Referenced by setUsed(), and used().
QString LaFoodSource::mCropGuid [private]
Definition at line 50 of file lafoodsource.h.
Referenced by cropGuid(), and setCropGuid().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/lafoodsource.h
dev/cpp/landuseanalyst/src/lib/lafoodsource.cpp