Landuse Analyst: LaGuid Class Reference
LaGuid Class Reference
#include <laguid.h>
Public Member Functions
LaGuid ()
virtual ~LaGuid ()
QString guid () const
void setGuid (QString theGuid="")
Private Attributes
QString mGuid
Detailed Description
An abstract base class for any class that has a globally unique identifier (GUID) to represent a unique instance.
Author:
Tim Sutton
Definition at line 28 of file laguid.h.
Constructor & Destructor Documentation
LaGuid::LaGuid ()
Constructor .
Definition at line 21 of file laguid.cpp.
{
}
LaGuid::~LaGuid () [virtual]
Desctructor .
Definition at line 24 of file laguid.cpp.
{
}
Member Function Documentation
QString LaGuid::guid () const
Retrieve the globally unique identifier
Definition at line 27 of file laguid.cpp.
References mGuid.
Referenced by LaModel::caloriesProvidedByTheMeatOfTheAnimal(), LaModel::caloriesProvidedByTheMilkOfTheAnimal(), LaModel::fromXml(), LaUtils::getAnimal(), LaUtils::getAnimalParameter(), LaModel::getAreaTargetsCrops(), LaUtils::getAvailableAnimalParameters(), LaUtils::getAvailableAnimals(), LaUtils::getAvailableCropParameters(), LaUtils::getAvailableCrops(), LaUtils::getCrop(), LaUtils::getCropParameter(), LaModel::getProductionTargetsAnimals(), LaModel::getProductionTargetsCrops(), LaAnimal::LaAnimal(), LaAnimalParameter::LaAnimalParameter(), LaAnimalParameterManager::LaAnimalParameterManager(), LaAssemblageConversion::LaAssemblageConversion(), LaCrop::LaCrop(), LaCropParameter::LaCropParameter(), LaCropParameterManager::LaCropParameterManager(), LaModel::LaModel(), LaMainForm::loadAnimals(), LaMainForm::loadCrops(), LaCropParameterManager::on_pbnApply_clicked(), LaCropManager::on_pbnApply_clicked(), LaAnimalParameterManager::on_pbnApply_clicked(), LaAnimalManager::on_pbnApply_clicked(), LaMainForm::on_pushButtonSave_clicked(), LaCropParameterManager::on_toolCopy_clicked(), LaCropManager::on_toolCopy_clicked(), LaAnimalParameterManager::on_toolCopy_clicked(), LaAnimalManager::on_toolCopy_clicked(), LaModel::operator=(), LaCropParameter::operator=(), LaCrop::operator=(), LaAnimalParameter::operator=(), LaAnimal::operator=(), LaAnimalParameterManager::populateFodder(), LaAnimalParameterManager::refreshAnimalParameterTable(), LaAnimalManager::refreshAnimalTable(), LaCropParameterManager::refreshCropParameterTable(), LaCropManager::refreshCropTable(), LaModelTest::saveAndLoadModel(), LaModel::toText(), LaCropParameter::toText(), LaCrop::toText(), LaAnimalParameter::toText(), LaAnimal::toText(), LaModel::toXml(), LaCropParameter::toXml(), LaCrop::toXml(), LaAnimalParameter::toXml(), and LaAnimal::toXml().
{
  return mGuid;
}
void LaGuid::setGuid (QString theGuid = "")
Set the globally unique identifier for this object. If no Parameter is passed a guid will be self assigned
Parameters:
theGuid - a guid for this model
Definition at line 32 of file laguid.cpp.
References mGuid.
Referenced by LaModel::fromXml(), LaCropParameter::fromXml(), LaCrop::fromXml(), LaAnimalParameter::fromXml(), LaAnimal::fromXml(), LaAnimal::LaAnimal(), LaAnimalParameter::LaAnimalParameter(), LaCrop::LaCrop(), LaCropParameter::LaCropParameter(), LaModel::LaModel(), LaCropParameterManager::on_toolCopy_clicked(), LaCropManager::on_toolCopy_clicked(), LaAnimalParameterManager::on_toolCopy_clicked(), LaAnimalManager::on_toolCopy_clicked(), LaCropParameterManager::on_toolNew_clicked(), LaCropManager::on_toolNew_clicked(), LaAnimalParameterManager::on_toolNew_clicked(), LaAnimalManager::on_toolNew_clicked(), LaModel::operator=(), LaCropParameter::operator=(), LaCrop::operator=(), LaAnimalParameter::operator=(), and LaAnimal::operator=().
{
  if (theGuid.isEmpty())
  {
    mGuid=QUuid::createUuid().toString().replace("{","").replace("}","");
  }
  else
  {
    mGuid=theGuid;
  }
}
Member Data Documentation
QString LaGuid::mGuid [private]
A globally unique identifier for this model
Definition at line 44 of file laguid.h.
Referenced by guid(), and setGuid().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/laguid.h
dev/cpp/landuseanalyst/src/lib/laguid.cpp