Landuse Analyst: LaGrass Class Reference
LaGrass Class Reference
#include <lagrass.h>
Signals
void message (QString theMessage)
Public Member Functions
LaGrass ()
~LaGrass ()
QString runCommand (QString theCommand, QStringList theArguments, QString &theErrorLog)
QString runCommand (QString theCommand, QStringList theArguments)
QStringList getMapsetList ()
QStringList getRasterList (QString theMapset, bool thePrependMapsetFlag=true)
bool createFrictionMap (QString theBaseRaster, QString theOututRaster)
bool copyMap (QString theOriginalRaster, QString theCopy)
bool createMask (QString theCostSurface, QString theMaskRaster)
bool createInverseMask (float theMin, QString theMaskRaster)
bool createCombinedMask (QString theCostSurface, QString theMaskRaster)
bool mergeMaps (QString theLeftoversGoHere)
float getArea (QString theLayerName)
bool reclass (QString theRaster, int theMax)
bool removeFile (QString theFile)
bool makeWalkCost (int theX, int theY, QString theDEM)
void makeEuclideanCost (int theX, int theY)
void makePathDistanceCost (int theX, int theY)
void writeMetaData (QStringList theMetaData)
void logMessage (QString theMessage)
Detailed Description
A class to wrap various grass functions
Author:
Tim Sutton, Jason Jorgenson
Definition at line 32 of file lagrass.h.
Constructor & Destructor Documentation
LaGrass::LaGrass ()
Constructor .
Definition at line 36 of file lagrass.cpp.
                 : QObject()
{
}
LaGrass::~LaGrass ()
Desctructor .
Definition at line 39 of file lagrass.cpp.
{
}
Member Function Documentation
QString LaGrass::runCommand (QString theCommand, QStringList theArguments, QString & theErrorLog)
This is the main wrapper function - most others will call it to actually invoke the grass engine.
Parameters:
QString theCommand - a single command name e.g. g.list
QString theArguments - a stringlist of paramters e.g. QStringList myArgs; myArgs << "type=rast" << "type=vect";
&QString theErrorLog - a string passed by reference. On completion, any errors from stderr will have been placed in this string.
Returns:
QString - verbatim output of the command as returned by GRASS. The calling function will be responsible for parsing that output.
Definition at line 399 of file lagrass.cpp.
References logMessage().
Referenced by copyMap(), createCombinedMask(), createFrictionMap(), createInverseMask(), createMask(), getArea(), getMapsetList(), getRasterList(), makeWalkCost(), mergeMaps(), reclass(), removeFile(), LaGrassTest::runCommand(), and runCommand().
{
  #ifdef Q_OS_MACX
  QString myProgram = "/Applications/GRASS-6.3.app/Contents/MacOS/bin/" + theCommand;
  #else
  QString myProgram = "/usr/lib/grass/bin/" + theCommand;
  #endif
    //windows users can wallow in self pity for now...
  QProcess myProcess;
  myProcess.start(myProgram, theArguments);
  if (!myProcess.waitForStarted())
  {
    logMessage("The process never started.....aaargh");
  }
  while (myProcess.waitForReadyRead(-1))
  {
  }
  QString myLog;
    //log
  myProcess.setReadChannel(QProcess::StandardOutput);
  QByteArray myArray = myProcess.readAll();
  myLog.append(myArray);
    //errors
  myProcess.setReadChannel(QProcess::StandardError);
  myArray = myProcess.readAll();
  theErrorLog.append(myArray);
    // get rid of some grass decorations...
  qDebug() <<"GRASS> " << myProgram << theCommand << theArguments;
  qDebug() <<"Results: " << myLog;
  myLog.replace("----------------------------------------------","");
  return myLog;
}
QString LaGrass::runCommand (QString theCommand, QStringList theArguments)
Overloaded version of above command that needs no log parameter.
Parameters:
QString theCommand - a single command name e.g. g.list
QString theArguments - a stringlist of paramters e.g. QStringList myArgs; myArgs << "type=rast" << "type=vect";
Returns:
QString - verbatim output of the command as returned by GRASS. The calling function will be responsible for parsing that output.
Definition at line 438 of file lagrass.cpp.
References runCommand().
{
  QString myErrors;
  QString myLog = runCommand(theCommand, theArguments, myErrors);
  return myLog;
}
QStringList LaGrass::getMapsetList ()
Get a list of grass mapsets
Returns:
QStringList of mapset names.
Definition at line 44 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassTest::getMapsetList(), LaGrassTest::getRasterList(), LaAnimalParameterManager::LaAnimalParameterManager(), LaCropParameterManager::LaCropParameterManager(), and LaMainForm::LaMainForm().
{
  QString myCommand = "g.mapsets";
  QStringList myArguments;
  myArguments << "-l";
    //run the command ignoring error logs
  QString myResult = runCommand(myCommand,myArguments);
  myResult = myResult.simplified();
  QStringList myList = myResult.split(QRegExp("\\s+"));   // splits on white space
  return myList;
}
QStringList LaGrass::getRasterList (QString theMapset, bool thePrependMapsetFlag = true)
Get a list of grass rasters from the PERMANENT and users mapset.
Parameters:
bool thePrependMapsetFlag. Optional paramter which defaults to true. Adds the mapset name in front of each layer e.g. PERMANENT.dem
Returns:
QStringList of layer names.
Definition at line 56 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassTest::getRasterList(), LaAnimalParameterManager::LaAnimalParameterManager(), LaCropParameterManager::LaCropParameterManager(), LaMainForm::LaMainForm(), and LaMainForm::on_cboMapSet_currentIndexChanged().
{
  QString myCommand = "g.list";
  QStringList myArguments;
  myArguments << "type=rast";
  myArguments << "mapset=" + theMapset;
    //run the command ignoring error logs
  QString myResult = runCommand(myCommand,myArguments);
    //check for no files
  if (myResult.contains("no raster files available"))
  {
      //return an empty list
    return QStringList();
  }
    //strip off grass decoration crap...
  myResult.replace("raster files available in mapset " + theMapset + ":","");
  myResult = myResult.simplified();
  QStringList myList = myResult.split(QRegExp("\\s+"));   // splits on white space
  QStringList myFinalList;
    //prepend the mapset name to each raster name
  if (thePrependMapsetFlag)
  {
    QStringListIterator myIterator(myList);
    while (myIterator.hasNext())
    {
      QString myString = myIterator.next();
      myFinalList << myString + "@" + theMapset;
    }
  }
  return myFinalList;
}
bool LaGrass::createFrictionMap (QString theBaseRaster, QString theOututRaster)
Create a friction map. All cells in the map will be set to a friction of 1.
Parameters:
QString grass raster layer name for a DEM on which the friction map will be based.
QString output layer name for the friction map (it will be put into the current active mapset)
Returns:
bool - false if the frictionmap creation failed
Definition at line 109 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassTest::createFrictionMap().
{
    //r.mapcalc "laFrictionMap = if(isnull(laDEM), null(), 1)"
  QString myCommand = "r.mapcalc";
  QStringList myArguments;
  myArguments << theOutputRaster + " = if(isnull(" + theBaseRaster + "), null(), 1)";
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::copyMap (QString theOriginalRaster, QString theCopy)
Definition at line 90 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassProcess::analyseModel().
{
  QString myCommand = "g.copy";
  QStringList myArguments;
  myArguments << "rast=" + theOriginalRaster + "," + theCopy;
    //qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
    //qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::createMask (QString theCostSurface, QString theMaskRaster)
Create a mask map. All cells in the map will be set to either a 1 or null.
Parameters:
QString grass raster layer name for generated cost surface used in analysis.
QString the layer name of the binary raster mask
Returns:
bool - false if the frictionmap creation failed
Note:
generates a raster called tmpMask which will be put into the current active mapset
Definition at line 151 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassProcess::analyseModel().
{
    //r.mapcalc "laFrictionMap = if(isnull(laDEM), null(), 1)"
  QString myCommand = "r.mapcalc";
  QStringList myArguments;
  QString myMaskName = "tmpMask";
  myArguments << myMaskName + "=" + theCostSurface + "*" + theMaskRaster;
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::createInverseMask (float theMin, QString theMaskRaster)
Definition at line 129 of file lagrass.cpp.
References createCombinedMask(), and runCommand().
Referenced by LaGrassProcess::accept().
{
  QString myCommand = "r.mapcalc";
  QStringList myArguments;
  myArguments << "laCostMapReclassed=if(laWalkCost>" + QString::number(theMin) + ",1,0)";
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  createCombinedMask("laCostMapReclassed", theMaskRaster);
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::createCombinedMask (QString theCostSurface, QString theMaskRaster)
Definition at line 172 of file lagrass.cpp.
References runCommand().
Referenced by createInverseMask().
{
  QString myCommand = "r.mapcalc";
  QStringList myArguments;
  QString myMaskName = "laLeftOver";
  myArguments << myMaskName + "=" + theCostSurface + "*" + theMaskRaster;
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::mergeMaps (QString theLeftoversGoHere)
Add leftovers from the current mask to the leftovers mask which is available to the animals for grazing
Parameters:
QString grass raster layer name for generated cost surface used in analysis.
QString the layer name of the binary raster mask
Returns:
bool - false if the frictionmap creation failed
Note:
generates a raster called laLeftOverMask which will be put into the current active mapset
Definition at line 192 of file lagrass.cpp.
References removeFile(), and runCommand().
Referenced by LaGrassProcess::accept().
{
  QString myErrorLog;
  QString myCommand = "r.mapcalc";
    // first we need to make the remaining land available
    // by changing all the null values to zero, and then
    // adding the two together.  (null + 1 is still null)
  QStringList myArguments;
  myArguments << "mergeTmp = if( isnull ( " + theLeftoversGoHere  + "),0," + theLeftoversGoHere + ")";
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  myArguments.clear();
   //+ if( isnull ( laLeftOver),0,laLeftOver)\'";
  myArguments << "laLeftOverTmp = if( isnull ( laLeftOver),0,laLeftOver)";
  myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  myArguments.clear();
  myArguments << "laCombinedMasks = laLeftOverTmp + mergeTmp";
  myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
    // clean up temp files
  removeFile("mergeTmp");
  removeFile("laLeftoverTmp");
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
float LaGrass::getArea (QString theLayerName)
Get the area stats for the raster
Parameters:
theRasterLayer - should be a boolean layer
Returns:
the first area for the first class.
Definition at line 233 of file lagrass.cpp.
References logMessage(), and runCommand().
Referenced by LaGrassProcess::analyseModel().
{
  logMessage("method ==> void LaGrass::getArea(float theArea)");
    //r.stats -a -n fs=,
  QString myCommand = "r.stats";
  QStringList myArguments;
  myArguments << "-a" << "-n" << "fs=," << "input="+theLayerName;
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return 0;
  }
  else
  {
    qDebug() << "myResult: " << myResult;
    myResult = myResult.simplified();
    qDebug() << "myResult.simplified(): " << myResult;
      //put each line of output into a list entry
    QStringList myList = myResult.split(QRegExp("\\s+"));
    qDebug() << "myList: " << myList;
     // if (myList.count() < 1)
      //{
        //row should be like 3,32323 (class,area)
      QStringList myList2 = myList.at(1).split((","));
      qDebug() << "myList2: " << myList2;
        //if (myList2.count() < 1)
        //{
          //get only area
        float myArea = myList2.at(1).toFloat() * 0.0001;   // adjust for hectares
        qDebug() << "Area (returnValue): " << myArea;
        return myArea;
        //}
      //}
  }
  return 0;
}
bool LaGrass::reclass (QString theRaster, int theMax)
Definition at line 350 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassProcess::analyseModel().
{
  qDebug() << "reclass invoked";
    //r.mapcalc "laFrictionMap = if(isnull(laDEM), null(), 1)"
  QString myCommand = "r.mapcalc";
  QStringList myArguments;
  myArguments << "laCostMapReclassed=if(" + theRaster + "<" + QString::number(theMax) + ",1,0)";
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::removeFile (QString theFile)
Definition at line 371 of file lagrass.cpp.
References runCommand().
Referenced by mergeMaps().
{
  QString myCommand = "g.remove";
  QStringList myArguments;
  myArguments << "rast=" + theFile;
  qDebug() << myCommand << " " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
  qDebug() << myResult;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
bool LaGrass::makeWalkCost (int theX, int theY, QString theDEM)
Definition at line 273 of file lagrass.cpp.
References runCommand().
Referenced by LaGrassProcess::accept().
{
    //logMessage("method ==> void LaGrass::makeWalkCost(int theX, int theY)");
    //r.walk max_cost=20000 elevation=dem_patched_filled@PERMANENT friction=theFrictionMap output=rwalkResultsSlopeMax20kFMap coordinate=744800,3611100 percent_memory=100 nseg=4 walk_coeff=0.72,6.0,1.9998,-1.9998 lambda=0 slope_factor=-0.2125 -k
    //qDebug() << "Coordinates: " << theX << "," << theY;
  QString myElevationMap=theDEM;
  QString myFrictionMap=theDEM;
  QString myCommand = "r.walk";
  QStringList myArguments;
  myArguments << "max_cost=120000"
              << "elevation=" + myElevationMap
              << "friction=shunaFrictionMap4"  // + myFrictionMap
              << "output=laWalkCost"
              << "coordinate=" + QString::number(theX) + "," + QString::number(theY)
              << "percent_memory=100"
              << "nseg=4"
              << "walk_coeff=0.72,6.0,1.9998,-1.999"
              << "lambda=1"
              << "slope_factor=-0.2125"
              << "-k"
              << "--overwrite";
  qDebug() << myCommand << "  " << myArguments.join(" ");
  QString myErrorLog;
  QString myResult = runCommand(myCommand,myArguments,myErrorLog);
    //qDebug() << myResult;
    //LaGrassProcess myLaGrassProcess;
  if (myErrorLog.isEmpty())
  {
    return true;
  }
  else
  {
    return false;
  }
}
void LaGrass::makeEuclideanCost (int theX, int theY)
Definition at line 311 of file lagrass.cpp.
References logMessage().
{
  logMessage("method ==> void LaGrass::makeEuclideanCost(int theX, int theY)");
}
void LaGrass::makePathDistanceCost (int theX, int theY)
Definition at line 316 of file lagrass.cpp.
References logMessage().
{
  logMessage("method ==> void LaGrass::makePathDistanceCost(int theX, int theY)");
}
void LaGrass::writeMetaData (QStringList theMetaData)
Definition at line 321 of file lagrass.cpp.
References logMessage().
{
  logMessage("method ==> void LaGrass::writeMetaData(QString theValue)");
  /*  ---> BASH example <---
    # write info to history section of raster map
    r.support map=catchment history="Radius was ${radius}"
    r.support map=catchment history="This results in ${area} sq meters and the target was ${land_reqrd_total}"
   */
    // iterate through the list, adding each to the history.
    //QString myCommand = "r.support";
    //QStringList myArguments;
    //QString myMaskName = "laLeftOver";
    //myArguments << myMaskName + "=" + theCostSurface + "*" + theMaskRaster;
    //qDebug() << myCommand << "  " << myArguments.join(" ");
    //QString myErrorLog;
    //QString myResult = runCommand(myCommand,myArguments,myErrorLog);
    //qDebug() <<myResult;
    //if (myErrorLog.isEmpty())
    //{
      //return true;
    //}
    //else
    //{
    //  return false;
    //}
}
void LaGrass::logMessage (QString theMessage)
Broadcast to any listeners status messages. This is a convenience function. Internally it will do emit message(QString theMessage) each time it is called.
Parameters:
QString theMessage to be logged.
Definition at line 394 of file lagrass.cpp.
References message().
Referenced by getArea(), makeEuclideanCost(), makePathDistanceCost(), runCommand(), and writeMetaData().
{
  emit message(theMessage);
}
void LaGrass::message (QString theMessage) [signal]
Send log info to any listeners.
Parameters:
QString the message to be logged.
Referenced by logMessage().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/lagrass.h
dev/cpp/landuseanalyst/src/lib/lagrass.cpp