Landuse Analyst: LaModelTest Class Reference
LaModelTest Class Reference
Private Slots
void run ()
void saveAndLoadModel ()
Detailed Description
Definition at line 25 of file lamodeltest.cpp.
Member Function Documentation
void LaModelTest::run () [private, slot]
Definition at line 44 of file lamodeltest.cpp.
References LaSerialisable::fromXmlFile().
{
  QString myFileName = "/../../../test_data/modelOutputs/24a192e7-dbb8-4531-b1c5-b9b2718614a2.xml";
  LaModel myModel;
  myModel.fromXmlFile(myFileName);
    //myModel.run();
}
void LaModelTest::saveAndLoadModel () [private, slot]
Definition at line 33 of file lamodeltest.cpp.
References LaUtils::createTextFile(), LaGuid::guid(), and LaModel::toXml().
{
  LaModel myModel;
  QString myFileName;
    //@TODO make this OS agnostic...
  myFileName = "/tmp/" + myModel.guid() + ".xml";
  LaUtils::createTextFile( myFileName , myModel.toXml());
  LaModel myModel2;
  myModel2.fromXmlFile(myFileName);
  QVERIFY(myModel2.guid()==myModel.guid());
}
The documentation for this class was generated from the following file:
dev/cpp/landuseanalyst/src/tests/lamodeltest.cpp