Landuse Analyst: LaAnimalParameter Class Reference
LaAnimalParameter Class Reference
#include <laanimalparameter.h>
Public Member Functions
LaAnimalParameter ()
~LaAnimalParameter ()
LaAnimalParameter (const LaAnimalParameter &theAnimalParameter)
LaAnimalParameter & operator= (const LaAnimalParameter &theAnimalParameter)
QString name () const
QString description () const
QString animalGuid () const
float percentTameMeat () const
bool useSpecificGrazingLand () const
bool useCommonGrazingLand () const
int ValueSpecificGrazingLand () const
int ValueCommonGrazingLand () const
AreaUnits areaUnits () const
EnergyType energyType () const
bool fodderUse () const
LaFoodSourceMap fodderSourceMap () const
Priority fallowUsage () const
QString rasterName () const
void setName (QString theName)
void setDescription (QString theDescription)
void setAnimalGuid (QString theGuid)
void setPercentTameMeat (float thePercentage)
void setUseSpecificGrazingLand (bool theBool)
void setUseCommonGrazingLand (bool theBool)
void setValueSpecificGrazingLand (int theCalories)
void setValueCommonGrazingLand (int theCalories)
void setFodderUse (bool theBool)
void setFodderData (LaFoodSourceMap theFoodSourceMap)
void setFallowUsage (Priority thePriority)
void setAreaUnits (AreaUnits theIndexValue)
void setEnergyType (EnergyType theEnergyType)
void setRasterName (QString theRasterName)
QString toXml ()
QString toText ()
QString toHtml ()
bool fromXml (const QString theXml)
Private Attributes
QString mName
QString mDescription
QString mAnimalGuid
float mPercentTameMeat
bool mUseSpecificGrazingLand
bool mUseCommonGrazingLand
int mValueSpecificGrazingLand
int mValueCommonGrazingLand
bool mFodderUse
LaFoodSourceMap mFoodSourceMap
Priority mFallowUsage
AreaUnits mAreaUnits
EnergyType mEnergyType
QString mRasterName
Detailed Description
A class to represent animal parameters
Author:
Tim Sutton, Jason Jorgenson
Definition at line 32 of file laanimalparameter.h.
Constructor & Destructor Documentation
LaAnimalParameter::LaAnimalParameter ()
Constructor .
Definition at line 32 of file laanimalparameter.cpp.
References mDescription, mName, and LaGuid::setGuid().
                                     : LaSerialisable(), LaGuid()
{
  setGuid();
  mName="No Name Set";
  mDescription="Not Set";
}
LaAnimalParameter::~LaAnimalParameter ()
Desctructor .
Definition at line 38 of file laanimalparameter.cpp.
{
}
LaAnimalParameter::LaAnimalParameter (const LaAnimalParameter & theAnimalParameter)
copy constructor
Definition at line 44 of file laanimalparameter.cpp.
References animalGuid(), areaUnits(), description(), energyType(), fallowUsage(), fodderSourceMap(), fodderUse(), LaGuid::guid(), mAreaUnits, mDescription, mEnergyType, mFallowUsage, mFodderUse, mFoodSourceMap, mName, mPercentTameMeat, mRasterName, mUseCommonGrazingLand, mUseSpecificGrazingLand, mValueCommonGrazingLand, mValueSpecificGrazingLand, name(), percentTameMeat(), rasterName(), setAnimalGuid(), LaGuid::setGuid(), useCommonGrazingLand(), useSpecificGrazingLand(), ValueCommonGrazingLand(), and ValueSpecificGrazingLand().
{
  mName=theAnimalParameter.name();
  mDescription=theAnimalParameter.description();
  setGuid(theAnimalParameter.guid());
  setAnimalGuid(theAnimalParameter.animalGuid());
  mPercentTameMeat=theAnimalParameter.percentTameMeat();
  mValueSpecificGrazingLand = theAnimalParameter.ValueSpecificGrazingLand();
  mValueCommonGrazingLand = theAnimalParameter.ValueCommonGrazingLand();
  mAreaUnits = theAnimalParameter.areaUnits();
  mEnergyType = theAnimalParameter.energyType();
  mFodderUse = theAnimalParameter.fodderUse();
  mFoodSourceMap = theAnimalParameter.fodderSourceMap();
    // fodder stuff here
  mUseSpecificGrazingLand = theAnimalParameter.useSpecificGrazingLand();
  mUseCommonGrazingLand = theAnimalParameter.useCommonGrazingLand();
  mFallowUsage = theAnimalParameter.fallowUsage();
  mRasterName = theAnimalParameter.rasterName();
}
Member Function Documentation
LaAnimalParameter & LaAnimalParameter::operator= (const LaAnimalParameter & theAnimalParameter)
Assignment operator
Definition at line 66 of file laanimalparameter.cpp.
References animalGuid(), areaUnits(), description(), energyType(), fallowUsage(), fodderSourceMap(), fodderUse(), LaGuid::guid(), mAreaUnits, mDescription, mEnergyType, mFallowUsage, mFodderUse, mFoodSourceMap, mName, mPercentTameMeat, mRasterName, mUseCommonGrazingLand, mUseSpecificGrazingLand, mValueCommonGrazingLand, mValueSpecificGrazingLand, name(), percentTameMeat(), rasterName(), setAnimalGuid(), LaGuid::setGuid(), useCommonGrazingLand(), useSpecificGrazingLand(), ValueCommonGrazingLand(), and ValueSpecificGrazingLand().
{
  if (this == &theAnimalParameter) return *this;     // Gracefully handle self assignment
  mName=theAnimalParameter.name();
  mDescription=theAnimalParameter.description();
  setGuid(theAnimalParameter.guid());
  setAnimalGuid(theAnimalParameter.animalGuid());
  mPercentTameMeat = theAnimalParameter.percentTameMeat();
  mValueSpecificGrazingLand = theAnimalParameter.ValueSpecificGrazingLand();
  mAreaUnits = theAnimalParameter.areaUnits();
  mValueCommonGrazingLand = theAnimalParameter.ValueCommonGrazingLand();
  mUseSpecificGrazingLand = theAnimalParameter.useSpecificGrazingLand();
  mUseCommonGrazingLand = theAnimalParameter.useCommonGrazingLand();
  mAreaUnits = theAnimalParameter.areaUnits();
  mEnergyType = theAnimalParameter.energyType();
  mFodderUse = theAnimalParameter.fodderUse();
  mFoodSourceMap = theAnimalParameter.fodderSourceMap();
    // fodder stuff here
  mFallowUsage = theAnimalParameter.fallowUsage();
  mRasterName = theAnimalParameter.rasterName();
  return *this;
}
QString LaAnimalParameter::name () const
Get the name for this set of animal model parameters
Definition at line 92 of file laanimalparameter.cpp.
References mName.
Referenced by LaModel::caloriesProvidedByTheMeatOfTheAnimal(), LaModel::caloriesProvidedByTheMilkOfTheAnimal(), LaUtils::getAnimalParameter(), LaUtils::getAvailableAnimalParameters(), LaAnimalParameter(), LaMainForm::loadAnimals(), LaAnimalParameterManager::on_toolCopy_clicked(), operator=(), LaAnimalParameterManager::refreshAnimalParameterTable(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mName;
}
QString LaAnimalParameter::description () const
Get the name for this set of animal model parameters
Definition at line 96 of file laanimalparameter.cpp.
References mDescription.
Referenced by LaAnimalParameter(), LaMainForm::loadAnimals(), operator=(), LaAnimalParameterManager::refreshAnimalParameterTable(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mDescription;
}
QString LaAnimalParameter::animalGuid () const
Get the guid of the animal this set of params is associated with
Definition at line 100 of file laanimalparameter.cpp.
References mAnimalGuid.
Referenced by LaAnimalParameter(), LaMainForm::loadAnimals(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mAnimalGuid;
}
float LaAnimalParameter::percentTameMeat () const
Portion of the Tame Meat Diet (Percentage)
Definition at line 104 of file laanimalparameter.cpp.
References mPercentTameMeat.
Referenced by LaModel::caloriesProvidedByTheMeatOfTheAnimal(), LaAnimalParameter(), LaMainForm::loadAnimals(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mPercentTameMeat;
}
bool LaAnimalParameter::useSpecificGrazingLand () const
A flag for whether the animal has it's own specific land designated to it for grazing
Definition at line 120 of file laanimalparameter.cpp.
References mUseSpecificGrazingLand.
Referenced by LaAnimalParameter(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mUseSpecificGrazingLand;
}
bool LaAnimalParameter::useCommonGrazingLand () const
A flag indicating that the animal grazes land shared with other animals
Definition at line 124 of file laanimalparameter.cpp.
References mUseCommonGrazingLand.
Referenced by LaGrassProcess::accept(), LaModel::initialiseAreaTargetsAnimalsMap(), LaAnimalParameter(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mUseCommonGrazingLand;
}
int LaAnimalParameter::ValueSpecificGrazingLand () const
Food value of specific (or unique) grazing land as calories per dunum/hectare
Definition at line 108 of file laanimalparameter.cpp.
References mValueSpecificGrazingLand.
Referenced by LaModel::initialiseAreaTargetsAnimalsMap(), LaAnimalParameter(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
    //int myAreaInHectares = LaUtils::convertAreaToHectares (mAreaUnits, mValueSpecificGrazingLand);
    //return myAreaInHectares;
  return mValueSpecificGrazingLand;
}
int LaAnimalParameter::ValueCommonGrazingLand () const
Food value of common (or shared) grazing land as calories per dunum/hectare NOTE that changing this value for any animal changes it for all!
Definition at line 114 of file laanimalparameter.cpp.
References mValueCommonGrazingLand.
Referenced by LaAnimalParameter(), and operator=().
{
    //int myAreaInHectares = LaUtils::convertAreaToHectares (mAreaUnits, mValueCommonGrazingLand);
    //return myAreaInHectares;
  return mValueCommonGrazingLand;
}
AreaUnits LaAnimalParameter::areaUnits () const
Selection between dunums and hectares
Definition at line 128 of file laanimalparameter.cpp.
References mAreaUnits.
Referenced by LaModel::initialiseAreaTargetsAnimalsMap(), LaAnimalParameter(), operator=(), LaAnimalParameterManager::showAnimalParameter(), and LaModel::toHtmlAreaAnimalTargets().
{
  return mAreaUnits;
}
EnergyType LaAnimalParameter::energyType () const
Select between Calories and TDN for food value wrt animals
Definition at line 133 of file laanimalparameter.cpp.
References mEnergyType.
Referenced by LaAnimalParameter(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mEnergyType;
}
bool LaAnimalParameter::fodderUse () const
If fallow is to be grazed, and if so, at either a HIGH MED or LOW priority to it's access
Definition at line 138 of file laanimalparameter.cpp.
References mFodderUse.
Referenced by LaAnimalParameter(), operator=(), LaMainForm::setDietLabels(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mFodderUse;
}
LaFoodSourceMap LaAnimalParameter::fodderSourceMap () const
Definition at line 143 of file laanimalparameter.cpp.
References mFoodSourceMap.
Referenced by LaModel::getProductionTargetsCrops(), LaAnimalParameter(), operator=(), LaAnimalParameterManager::refreshFodderTable(), and LaAnimalParameterManager::selectAnimalParameter().
{
  return mFoodSourceMap;
}
Priority LaAnimalParameter::fallowUsage () const
Definition at line 148 of file laanimalparameter.cpp.
References mFallowUsage.
Referenced by LaModel::allocateFallowGrazingLand(), LaModel::doTheFallowAllocation(), LaAnimalParameter(), operator=(), and LaAnimalParameterManager::showAnimalParameter().
{
  return mFallowUsage;
}
QString LaAnimalParameter::rasterName () const
Definition at line 153 of file laanimalparameter.cpp.
References mRasterName.
Referenced by LaGrassProcess::accept(), LaAnimalParameter(), and operator=().
{
  return mRasterName;
}
void LaAnimalParameter::setName (QString theName)
Set the name for this set of animal model parameters
Definition at line 160 of file laanimalparameter.cpp.
References mName.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked(), and LaAnimalParameterManager::on_toolCopy_clicked().
{
  mName=theName;
}
void LaAnimalParameter::setDescription (QString theDescription)
Set the name for this set of animal model parameters
Definition at line 164 of file laanimalparameter.cpp.
References mDescription.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mDescription=theDescription;
}
void LaAnimalParameter::setAnimalGuid (QString theGuid)
Set the guid of the animal this set of params is associated with
Definition at line 168 of file laanimalparameter.cpp.
References mAnimalGuid.
Referenced by LaAnimalParameter(), LaAnimalParameterManager::on_pbnApply_clicked(), and operator=().
{
  mAnimalGuid = theGuid;
}
void LaAnimalParameter::setPercentTameMeat (float thePercentage)
Portion of the Tame Meat Diet (Percentage)
Definition at line 172 of file laanimalparameter.cpp.
References mPercentTameMeat.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mPercentTameMeat=thePercentage;
}
void LaAnimalParameter::setUseSpecificGrazingLand (bool theBool)
A flag for whether the animal has it's own specific land designated to it for grazing
Definition at line 184 of file laanimalparameter.cpp.
References mUseSpecificGrazingLand.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mUseSpecificGrazingLand=theFlag;
}
void LaAnimalParameter::setUseCommonGrazingLand (bool theBool)
A flag indicating that the animal grazes land shared with other animals
Definition at line 188 of file laanimalparameter.cpp.
References mUseCommonGrazingLand.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mUseCommonGrazingLand=theFlag;
}
void LaAnimalParameter::setValueSpecificGrazingLand (int theCalories)
Food value of specific (or unique) grazing land as calories per dunum/hectare
Definition at line 176 of file laanimalparameter.cpp.
References mValueSpecificGrazingLand.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mValueSpecificGrazingLand=theCalories;
}
void LaAnimalParameter::setValueCommonGrazingLand (int theCalories)
Food value of common (or shared) grazing land as calories per dunum/hectare NOTE that changing this value for any animal changes it for all!
Definition at line 180 of file laanimalparameter.cpp.
References mValueCommonGrazingLand.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mValueCommonGrazingLand=theCalories;
}
void LaAnimalParameter::setFodderUse (bool theBool)
Definition at line 202 of file laanimalparameter.cpp.
References mFodderUse.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mFodderUse=theBool;
}
void LaAnimalParameter::setFodderData (LaFoodSourceMap theFoodSourceMap)
Definition at line 208 of file laanimalparameter.cpp.
References mFoodSourceMap.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mFoodSourceMap = theFoodSourceMap;
}
void LaAnimalParameter::setFallowUsage (Priority thePriority)
If fallow is to be grazed, and if so, at either a HIGH MED or LOW priority to it's access
Definition at line 214 of file laanimalparameter.cpp.
References mFallowUsage.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mFallowUsage=thePriority;
}
void LaAnimalParameter::setAreaUnits (AreaUnits theIndexValue)
Definition at line 192 of file laanimalparameter.cpp.
References mAreaUnits.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mAreaUnits=theAreaUnits;
}
void LaAnimalParameter::setEnergyType (EnergyType theEnergyType)
Definition at line 197 of file laanimalparameter.cpp.
References mEnergyType.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mEnergyType=theEnergyType;
}
void LaAnimalParameter::setRasterName (QString theRasterName)
Definition at line 219 of file laanimalparameter.cpp.
References mRasterName.
Referenced by LaAnimalParameterManager::on_pbnApply_clicked().
{
  mRasterName=theRasterName;
}
QString LaAnimalParameter::toXml () [virtual]
Return an xml representation of this layer this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 315 of file laanimalparameter.cpp.
References LaFoodSource::days(), Dunum, LaFoodSource::fodder(), LaFoodSource::grain(), LaGuid::guid(), Hectare, High, KCalories, Low, mAnimalGuid, mAreaUnits, mDescription, Medium, mEnergyType, mFallowUsage, mFodderUse, mFoodSourceMap, mName, mPercentTameMeat, mRasterName, mUseCommonGrazingLand, mUseSpecificGrazingLand, mValueCommonGrazingLand, mValueSpecificGrazingLand, TDN, and LaUtils::xmlEncode().
{
  QString myString;
  myString+=QString("<animalParameter guid=\"" + guid() + "\">\n");
  myString+=QString("  <name>" + LaUtils::xmlEncode(mName) + "</name>\n");
  myString+=QString("  <description>" + LaUtils::xmlEncode(mDescription) + "</description>\n");
  myString+=QString("  <animal>" + LaUtils::xmlEncode(mAnimalGuid) + "</animal>\n");
  myString+=QString("  <percentTameMeat>" + QString::number(mPercentTameMeat) + "</percentTameMeat>\n");
  myString+=QString("  <useCommonGrazingLand>" + QString::number(mUseCommonGrazingLand) + "</useCommonGrazingLand>\n");
  myString+=QString("  <useSpecificGrazingLand>" + QString::number(mUseSpecificGrazingLand) + "</useSpecificGrazingLand>\n");  myString+=QString("  <foodValueOfCommonGrazingLand>" + QString::number(mValueCommonGrazingLand) + "</foodValueOfCommonGrazingLand>\n");
  myString+=QString("  <foodValueOfSpecificGrazingLand>" + QString::number(mValueSpecificGrazingLand) + "</foodValueOfSpecificGrazingLand>\n");
  switch (mAreaUnits)
  {
    case Dunum:
      myString+=QString("  <areaUnits>Dunum</areaUnits>\n");
      break;
    case Hectare:
      myString+=QString("  <areaUnits>Hectare</areaUnits>\n");
      break;
  }
  switch (mEnergyType)
  {
    case KCalories:
      myString+=QString("  <energyType>KCalories</energyType>\n");
      break;
    case TDN:
      myString+=QString("  <energyType>TDN</energyType\n");
      break;
  }
  myString+=QString("  <fodderUse>"+ QString::number(mFodderUse) +"</fodderUse>\n");
  if (mFodderUse)
  {
     //qDebug("Fodder is used");
    myString+=QString("   <fodderCrops>\n");
      // write out the map for fodder info to xml
    QMapIterator<QString, LaFoodSource> myIterator(mFoodSourceMap);
    while (myIterator.hasNext())
    {
      myIterator.next();
      LaFoodSource myFoodSource = myIterator.value();
      QString myGuid = myIterator.key();
      QString myFodderStrawChaff = QString::number(myFoodSource.fodder());
      QString myFodderGrain = QString::number(myFoodSource.grain());
      QString myFodderDays = QString::number(myFoodSource.days());
      myString+=QString("    <fodderCrop>\n");
      myString+=QString("      <fodderCropGuid>" + myGuid + "</fodderCropGuid>\n");
      myString+=QString("      <fodderStrawChaff>" + myFodderStrawChaff + "</fodderStrawChaff>\n");
      myString+=QString("      <fodderGrain>"+ myFodderGrain + "</fodderGrain>\n");
      myString+=QString("      <fodderDays>"+ myFodderDays + "</fodderDays>\n");
      myString+=QString("    </fodderCrop>\n");
    }
    myString+=QString("   </fodderCrops>\n");
  }
  else
  {
     //qDebug("Fodder is not used");
  }
  switch (mFallowUsage)
  {
    case  High:
      myString+=QString("  <fallowUsage>High</fallowUsage>\n");
      break;
    case  Medium:
      myString+=QString("  <fallowUsage>Medium</fallowUsage>\n");
      break;
    case  Low:
      myString+=QString("  <fallowUsage>Low</fallowUsage>\n");
      break;
    default:
      myString+=QString("  <fallowUsage></fallowUsage>\n");
      break;
  }   //switch
  myString+=QString("  <rasterName>" + LaUtils::xmlEncode(mRasterName) + "</RasterName>\n");
  myString+=QString("</animalParameter>\n");
  return myString;
}
QString LaAnimalParameter::toText ()
Definition at line 400 of file laanimalparameter.cpp.
References LaGuid::guid(), mAnimalGuid, mAreaUnits, mDescription, mEnergyType, mFallowUsage, mFodderUse, mName, mPercentTameMeat, mRasterName, mUseCommonGrazingLand, mUseSpecificGrazingLand, mValueCommonGrazingLand, mValueSpecificGrazingLand, and LaUtils::xmlEncode().
{
  QString myString;
  myString+=QString("guid=>" + guid() + "\n");
  myString+=QString("name=>" + LaUtils::xmlEncode(mName) + "\n");
  myString+=QString("description=>" + LaUtils::xmlEncode(mDescription) + "\n");
  myString+=QString("animal=>" + mAnimalGuid + "\n");
  myString+=QString("percentTameMeat=>" + QString::number(mPercentTameMeat) + "\n");
  myString+=QString("useCommonGrazingLand=>" + QString::number(mUseCommonGrazingLand) + "\n");
  myString+=QString("useSpecificGrazingLand=>" + QString::number(mUseSpecificGrazingLand) + "\n");
  myString+=QString("foodValueOfCommonGrazingLand=>" + QString::number(mValueCommonGrazingLand) + "\n");
  myString+=QString("foodValueOfSpecificGrazingLand=>" + QString::number(mValueSpecificGrazingLand) + "\n");
  myString+=QString("areaUnits=>" + QString::number(mAreaUnits) + "\n");
  myString+=QString("energyType=>" + QString::number(mEnergyType) + "\n");
  myString+=QString("fodderUse=>" + QString::number(mFodderUse) + "\n");
  if (mFodderUse)
  {
      // write out the map for fodder info to text
  }
  else
  {
    myString+="Fodder not used";
  }
  myString+=QString("fallowUsage=>" + QString::number(mFallowUsage) + "\n");
  myString+=QString("rasterName=>" + LaUtils::xmlEncode(mRasterName) + "\n");
  return myString;
}
QString LaAnimalParameter::toHtml ()
Definition at line 431 of file laanimalparameter.cpp.
References LaFoodSource::days(), LaFoodSource::fodder(), LaFoodSource::grain(), High, Low, mAreaUnits, mDescription, Medium, mEnergyType, mFallowUsage, mFodderUse, mFoodSourceMap, mName, mPercentTameMeat, mRasterName, mUseCommonGrazingLand, mUseSpecificGrazingLand, mValueCommonGrazingLand, mValueSpecificGrazingLand, and LaUtils::xmlEncode().
Referenced by LaMainForm::showAnimalDefinitionReport(), and LaModel::toHtml().
{
  QString myString;
  QString myFallowUsage;
  switch (mFallowUsage)
  {
    case  High:
      myFallowUsage=QString("High Priority");
      break;
    case  Medium:
      myFallowUsage=QString("Medium Priority");
      break;
    case  Low:
      myFallowUsage=QString("Low Priority");
      break;
    default:
      myFallowUsage=QString("None");
      break;
  }
  myString+="<h3 >Details for " + LaUtils::xmlEncode(mName) + "</h3>";
  myString+="<table>";
    //myString+="<tr><td>GUID:</th><td>" + guid() + "</td></tr>";
  myString+="<tr><td>Description:</td><td>" + mDescription + "</td></tr>";
    //myString+="<tr><td>Animal:</td><td>" + mAnimalGuid + "</td></tr>";
  myString+="<tr><td>Raster Mask:</td><td>" + LaUtils::xmlEncode(mRasterName) + "</td></tr>";
  myString+="<tr><td>Percentage of Tame Meat:</td><td> " + QString::number(mPercentTameMeat) + "</td></tr>";
  myString+="<tr><td>Use Common Grazing Land:</td><td> " + QString::number(mUseCommonGrazingLand) + "</td></tr>";
  myString+="<tr><td>Use Specific Grazing Land:</td><td> " + QString::number(mUseSpecificGrazingLand) + "</td></tr>";
  myString+="<tr><td>Food Value Of Common Grazing Land:</td><td> " + QString::number(mValueCommonGrazingLand) + "</td></tr>";
  myString+="<tr><td>Food Value Of Specific Grazing Land:</td><td> " + QString::number(mValueSpecificGrazingLand) + "</td></tr>";
  myString+="<tr><td>Energy Type:</td><td> "+ QString::number(mEnergyType) + "</td></tr>";
  myString+="<tr><td>Area Units:</td><td> "+ QString::number(mAreaUnits) + "</td></tr>";
  if (myFallowUsage=="None")
  {
    myString+="<tr><td>No Fallow Grazing</td></tr>";
  }
  else
  {
    myString+="<tr><td>Fallow Grazing:</td><td>" + myFallowUsage + "</td></tr>";
  }
  if (mFodderUse)
  {
    myString+=QString("   <fodderCrops>\n");
      // write out the map for fodder info to xml
    int myCounter = 0;
    QMapIterator<QString, LaFoodSource> myIterator(mFoodSourceMap);
    while (myIterator.hasNext())
    {
      myIterator.next();
      myCounter++;
      LaFoodSource myFoodSource = myIterator.value();
      QString myGuid = myIterator.key();
      QString myFodderStrawChaff = QString::number(myFoodSource.fodder());
      QString myFodderGrain = QString::number(myFoodSource.grain());
      QString myFodderDays = QString::number(myFoodSource.days());
      myString+="<tr><td>Fodder Source #:</td><td> " + QString::number(myCounter) + "</td></tr>";
      myString+="<tr><td>Crop Guid: "+ myGuid + "</td></tr>";
      myString+="<tr><td>Straw and Chaff: "+ myFodderStrawChaff + "</td></tr>";
      myString+="<tr><td>Grain: "+ myFodderGrain + "</td></tr>";
      myString+="<tr><td>Days: "+ myFodderDays + "</td></tr>";
    }
  }
  else
  {
    myString+="<tr><td>Fodder not used</td><td>";
  }
  myString+="</table>";
  return myString;
}
bool LaAnimalParameter::fromXml (const QString theXml) [virtual]
Read this object from xml and return result as true for success, false for failure.
See also:
LaSerialisable this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 224 of file laanimalparameter.cpp.
References Dunum, Hectare, High, KCalories, Low, mAnimalGuid, mAreaUnits, mDescription, Medium, mEnergyType, mFallowUsage, mFodderUse, mFoodSourceMap, mName, mPercentTameMeat, mRasterName, mUseCommonGrazingLand, mUseSpecificGrazingLand, mValueCommonGrazingLand, mValueSpecificGrazingLand, None, LaFoodSource::setCropGuid(), LaFoodSource::setDays(), LaFoodSource::setFodder(), LaFoodSource::setGrain(), LaGuid::setGuid(), LaFoodSource::setUsed(), TDN, and LaUtils::xmlDecode().
{
    //qDebug("Loading animal parameter from xml");
  QDomDocument myDocument("mydocument");
  myDocument.setContent(theXml);
  QDomElement myTopElement = myDocument.firstChildElement("animalParameter");
  if (myTopElement.isNull())
  {
      //TODO - just make this a warning
     //qDebug("top element could not be found!");
  }
    //qDebug("AnimalParameter::fromXml - guid found : " + myTopElement.attribute("guid").toLocal8Bit());
  setGuid(myTopElement.attribute("guid"));
    //qDebug("AnimalParameter::fromXml - guid set to : " + guid().toLocal8Bit());
  mName=LaUtils::xmlDecode(myTopElement.firstChildElement("name").text());
  mDescription=LaUtils::xmlDecode(myTopElement.firstChildElement("description").text());
  mAnimalGuid=LaUtils::xmlDecode(myTopElement.firstChildElement("animal").text());
  mPercentTameMeat=QString(myTopElement.firstChildElement("percentTameMeat").text()).toFloat();
  mUseCommonGrazingLand=QString(myTopElement.firstChildElement("useCommonGrazingLand").text()).toInt();
  mUseSpecificGrazingLand=QString(myTopElement.firstChildElement("useSpecificGrazingLand").text()).toInt();
  mValueCommonGrazingLand=QString(myTopElement.firstChildElement("foodValueOfCommonGrazingLand").text()).toInt();
  mValueSpecificGrazingLand=QString(myTopElement.firstChildElement("foodValueOfSpecificGrazingLand").text()).toInt();
    //  //  //  //  ///
    //mAreaUnits=LaUtils::xmlDecode(myTopElement.firstChildElement("areaUnits").text());
  QString myAreaUnits = QString(myTopElement.firstChildElement("areaUnits").text());
  if (myAreaUnits == "Dunum")
  {
    mAreaUnits=Dunum;
  }
  else if (myAreaUnits == "Hectare")
  {
    mAreaUnits=Hectare;
  }
  QString myEnergyType = QString(myTopElement.firstChildElement("energyType").text());
  if (myEnergyType == "KCalories")
  {
    mEnergyType=KCalories;
  }
  else if (myEnergyType == "TDN")
  {
    mEnergyType=TDN;
  }
  mFodderUse=QString(myTopElement.firstChildElement("fodderUse").text()).toInt();
    // populate the fodder map
  mFoodSourceMap.clear();
  QDomNodeList myFodderCropsList = myDocument.elementsByTagName("fodderCrop");
  for (int myCounter=0; myCounter < myFodderCropsList.size(); myCounter++)
  {
    QDomNode myFoodSourceNode = myFodderCropsList.item(myCounter);
    QDomElement myFoodSourceElement = myFoodSourceNode.toElement();
      // load the data from the xml into local variables
    QString myCropGuid = myFoodSourceElement.firstChildElement("fodderCropGuid").text();
    int myFodderStrawChaff = myFoodSourceElement.firstChildElement("fodderStrawChaff").text().toInt();
    int myGrain = myFoodSourceElement.firstChildElement("fodderGrain").text().toInt();
    int myUsed = myFoodSourceElement.firstChildElement("fodderUse").text().toInt();
    int myDays = myFoodSourceElement.firstChildElement("fodderDays").text().toInt();
    LaFoodSource myFoodSource;
      // setup the data to insert into the map
    myFoodSource.setFodder(myFodderStrawChaff);
    myFoodSource.setGrain(myGrain);
    myFoodSource.setDays(myDays);
    myFoodSource.setUsed(myUsed);
    myFoodSource.setCropGuid(myCropGuid);
      // insert data into map
    mFoodSourceMap.insert(myCropGuid,myFoodSource);
  }   // end of for loop
   //qDebug("Number of food sources restored from xml: " + QString::number(mFoodSourceMap.count()).toLocal8Bit());
  QString myFallowUsage = QString(myTopElement.firstChildElement("fallowUsage").text());
  if (myFallowUsage == "High")
  {
    mFallowUsage=High;
  }
  else if (myFallowUsage == "Medium")
  {
    mFallowUsage=Medium;
  }
  else if (myFallowUsage == "Low")
  {
    mFallowUsage=Low;
  }
  else
  {
    mFallowUsage=None;
  }
  mRasterName=LaUtils::xmlDecode(myTopElement.firstChildElement("rasterName").text());
  return true;
}
Member Data Documentation
QString LaAnimalParameter::mName [private]
A name for this set of animal paremeters
Definition at line 135 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), name(), operator=(), setName(), toHtml(), toText(), and toXml().
QString LaAnimalParameter::mDescription [private]
A name for this set of animal paremeters
Definition at line 137 of file laanimalparameter.h.
Referenced by description(), fromXml(), LaAnimalParameter(), operator=(), setDescription(), toHtml(), toText(), and toXml().
QString LaAnimalParameter::mAnimalGuid [private]
The animal guid these parameters are associated with
Definition at line 139 of file laanimalparameter.h.
Referenced by animalGuid(), fromXml(), setAnimalGuid(), toText(), and toXml().
float LaAnimalParameter::mPercentTameMeat [private]
Portion of the Tame Meat Diet (Percentage)
Definition at line 141 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), operator=(), percentTameMeat(), setPercentTameMeat(), toHtml(), toText(), and toXml().
bool LaAnimalParameter::mUseSpecificGrazingLand [private]
A flag for whether the animal has it's own specific land designated to it for grazing
Definition at line 146 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), operator=(), setUseSpecificGrazingLand(), toHtml(), toText(), toXml(), and useSpecificGrazingLand().
bool LaAnimalParameter::mUseCommonGrazingLand [private]
A flag indicating that the animal grazes land shared with other animals
Definition at line 148 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), operator=(), setUseCommonGrazingLand(), toHtml(), toText(), toXml(), and useCommonGrazingLand().
int LaAnimalParameter::mValueSpecificGrazingLand [private]
Food value of specific (or unique) grazing land as calories per dunum/hectare
Definition at line 150 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), operator=(), setValueSpecificGrazingLand(), toHtml(), toText(), toXml(), and ValueSpecificGrazingLand().
int LaAnimalParameter::mValueCommonGrazingLand [private]
Food value of common (or shared) grazing land as calories per dunum/hectare NOTE that changing this value for any animal changes it for all!
Definition at line 154 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), operator=(), setValueCommonGrazingLand(), toHtml(), toText(), toXml(), and ValueCommonGrazingLand().
bool LaAnimalParameter::mFodderUse [private]
Definition at line 155 of file laanimalparameter.h.
Referenced by fodderUse(), fromXml(), LaAnimalParameter(), operator=(), setFodderUse(), toHtml(), toText(), and toXml().
LaFoodSourceMap LaAnimalParameter::mFoodSourceMap [private]
This QMap contains <GUID of the crop, a bool of it used>,<fodder,grain>
Definition at line 159 of file laanimalparameter.h.
Referenced by fodderSourceMap(), fromXml(), LaAnimalParameter(), operator=(), setFodderData(), toHtml(), and toXml().
Priority LaAnimalParameter::mFallowUsage [private]
If fallow is to be grazed, and if so, at either a HIGH MED or LOW priority to it's access
Definition at line 164 of file laanimalparameter.h.
Referenced by fallowUsage(), fromXml(), LaAnimalParameter(), operator=(), setFallowUsage(), toHtml(), toText(), and toXml().
AreaUnits LaAnimalParameter::mAreaUnits [private]
Definition at line 165 of file laanimalparameter.h.
Referenced by areaUnits(), fromXml(), LaAnimalParameter(), operator=(), setAreaUnits(), toHtml(), toText(), and toXml().
EnergyType LaAnimalParameter::mEnergyType [private]
Definition at line 166 of file laanimalparameter.h.
Referenced by energyType(), fromXml(), LaAnimalParameter(), operator=(), setEnergyType(), toHtml(), toText(), and toXml().
QString LaAnimalParameter::mRasterName [private]
Definition at line 167 of file laanimalparameter.h.
Referenced by fromXml(), LaAnimalParameter(), operator=(), rasterName(), setRasterName(), toHtml(), toText(), and toXml().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/laanimalparameter.h
dev/cpp/landuseanalyst/src/lib/laanimalparameter.cpp