Landuse Analyst: LaCropManager Class Reference
LaCropManager Class Reference
#include <lacropmanager.h>
Public Slots
void on_pushButtonLoad_clicked ()
void on_pushButtonSave_clicked ()
void on_pbnCropPic_clicked ()
Public Member Functions
LaCropManager (QWidget *parent=0, Qt::WFlags fl=0)
~LaCropManager ()
Private Slots
void cellClicked (int theRow, int theColumn)
void showCrop ()
void on_toolCopy_clicked ()
void on_toolNew_clicked ()
void on_toolDelete_clicked ()
void on_pbnApply_clicked ()
void resizeEvent (QResizeEvent *)
Private Member Functions
void refreshCropTable (QString theGuid=0)
void selectCrop (QString theFileName)
void readSettings ()
void writeSettings ()
Private Attributes
LaUtils::CropMap mCropMap
LaCrop mCrop
QString mImageFile
Detailed Description
This is the main gui class
Author:
Tim Sutton, Jason Jorgenson
Definition at line 34 of file lacropmanager.h.
Constructor & Destructor Documentation
LaCropManager::LaCropManager (QWidget * parent = 0, Qt::WFlags fl = 0)
Definition at line 40 of file lacropmanager.cpp.
References cellClicked(), readSettings(), and refreshCropTable().
: QDialog(parent,fl)
{
    //required by Qt4 to initialise the ui
  setupUi(this);
  readSettings();
  lblCropPix->setScaledContents(true);
  connect(tblCrops, SIGNAL(cellClicked( int,int)),
      this, SLOT(cellClicked( int,int)));
  cbAreaUnits->addItem("Dunum");
  cbAreaUnits->addItem("Hectare");
  cbFodderEnergyType->addItem("KCalories");
  cbFodderEnergyType->addItem("TDN");
  refreshCropTable();
    //disable these buttons unless experimental is allowed
  pbnImport->setVisible(false);
  pbnExport->setVisible(false);
}
LaCropManager::~LaCropManager ()
Definition at line 59 of file lacropmanager.cpp.
References writeSettings().
{
  writeSettings();
}
Member Function Documentation
void LaCropManager::on_pushButtonLoad_clicked () [slot]
Definition at line 205 of file lacropmanager.cpp.
References LaSerialisable::fromXmlFile(), mCrop, and showCrop().
{
    //
  mCrop.fromXmlFile("/tmp/crop.xml");
  showCrop();
}
void LaCropManager::on_pushButtonSave_clicked () [slot]
Definition at line 212 of file lacropmanager.cpp.
{
}
void LaCropManager::on_pbnCropPic_clicked () [slot]
Definition at line 80 of file lacropmanager.cpp.
References mImageFile, and LaUtils::openGraphicFile().
{
  LaUtils myUtils;
  QString myFile = myUtils.openGraphicFile();
  lblCropPix->setPixmap(myFile);
  mImageFile = myFile;
}
void LaCropManager::cellClicked (int theRow, int theColumn) [private, slot]
Definition at line 172 of file lacropmanager.cpp.
References selectCrop().
Referenced by LaCropManager(), and refreshCropTable().
{
    //note we use the alg name not the id because user may have customised params
  qDebug() << "LaCropManager::cellClicked";
  QString myGuid = tblCrops->item(tblCrops->currentRow(),0)->text();
  qDebug() << "Guid is: " << myGuid;
  QString myFileName = myGuid + ".xml";
  selectCrop(myFileName);
}
void LaCropManager::showCrop () [private, slot]
Definition at line 192 of file lacropmanager.cpp.
References LaCrop::areaUnits(), LaCrop::cropCalories(), LaCrop::cropFodderEnergyType(), LaCrop::cropYield(), LaCrop::description(), LaCrop::fodderProduction(), LaCrop::fodderValue(), LaCrop::imageFile(), mCrop, and LaCrop::name().
Referenced by on_pushButtonLoad_clicked(), on_toolNew_clicked(), and selectCrop().
{
  leName->setText(mCrop.name());
  leDescription->setText(mCrop.description());
  sbCropYield->setValue(mCrop.cropYield());
  sbCropCalories->setValue(mCrop.cropCalories());
  sbCropFodderProduction->setValue(mCrop.fodderProduction());
  sbCropFodderValue->setValue(mCrop.fodderValue());
  cbAreaUnits->setCurrentIndex(mCrop.areaUnits());
  cbFodderEnergyType->setCurrentIndex(mCrop.cropFodderEnergyType());
  lblCropPix->setPixmap(mCrop.imageFile());
}
void LaCropManager::on_toolCopy_clicked () [private, slot]
Definition at line 232 of file lacropmanager.cpp.
References LaSerialisable::fromXmlFile(), LaGuid::guid(), LaCrop::name(), refreshCropTable(), LaGuid::setGuid(), LaCrop::setName(), LaSerialisable::toXmlFile(), and LaUtils::userCropProfilesDirPath().
{
  qDebug() << "Copy toolbutton clicked";
  if (tblCrops->currentRow() < 0)
  {
    return;
  }
    //to clone, we get the algorithm guid that is currently selected
  QString myGuid = tblCrops->item(tblCrops->currentRow(),0)->text();
  if (myGuid.isEmpty())
  {
    return;
  }
  QString myOriginalFileName = LaUtils::userCropProfilesDirPath() + QDir::separator() + myGuid + ".xml";
  LaCrop myCrop;
  myCrop.fromXmlFile(myOriginalFileName);
  /*
  int myCount = 1;
  while (mCrop.contains(myProfileName))
  {
    myProfileName = tr("Copy ") + QString::number(myCount++) + " of " + myCrop.name();
  }
  */
    //assign this layerset its own guid
  myCrop.setGuid();
  QString myNewFileName = LaUtils::userCropProfilesDirPath() + QDir::separator() + myCrop.guid() + ".xml";
  myCrop.setName(tr("Copy of ") + myCrop.name());
  myCrop.toXmlFile(myNewFileName);
  refreshCropTable(myCrop.guid());
}
void LaCropManager::on_toolNew_clicked () [private, slot]
Definition at line 216 of file lacropmanager.cpp.
References mCrop, LaGuid::setGuid(), and showCrop().
Referenced by refreshCropTable().
{
  qDebug() << "New toolbutton clicked";
  LaCrop myCrop;
  myCrop.setGuid();
  mCrop = myCrop;
  showCrop();
}
void LaCropManager::on_toolDelete_clicked () [private, slot]
Definition at line 262 of file lacropmanager.cpp.
References refreshCropTable(), and LaUtils::userCropProfilesDirPath().
{
  qDebug() << "Delete toolbutton clicked";
  if (tblCrops->currentRow() < 0)
  {
    return;
  }
  QString myGuid = tblCrops->item(tblCrops->currentRow(),0)->text();
  if (!myGuid.isEmpty())
  {
    QFile myFile(LaUtils::userCropProfilesDirPath() + QDir::separator() + myGuid + ".xml");
    if (!myFile.remove())
    {
      QMessageBox::warning(this, tr("Landuse Analyst"),
      tr("Unable to delete file \n") + myFile.fileName());
    }
    refreshCropTable();
  }
}
void LaCropManager::on_pbnApply_clicked () [private, slot]
Definition at line 281 of file lacropmanager.cpp.
References Dunum, LaGuid::guid(), Hectare, mCrop, mImageFile, refreshCropTable(), LaCrop::setAreaUnits(), LaCrop::setCropCalories(), LaCrop::setCropFodderValue(), LaCrop::setCropYield(), LaCrop::setDescription(), LaCrop::setFodderProduction(), LaCrop::setImageFile(), LaCrop::setName(), LaSerialisable::toXmlFile(), and LaUtils::userCropProfilesDirPath().
{
  mCrop.setName(leName->text());
  mCrop.setDescription(leDescription->text());
  mCrop.setCropYield(sbCropYield->value());
  mCrop.setCropCalories(sbCropCalories->value());
  mCrop.setFodderProduction(sbCropFodderProduction->value());
  mCrop.setCropFodderValue(sbCropFodderValue->value());
  QString mySelectedAreaUnit = QString(cbAreaUnits->currentText());
  AreaUnits myAreaUnits;
  if (mySelectedAreaUnit == "Dunum")
  {
    myAreaUnits = Dunum;
    mCrop.setAreaUnits(myAreaUnits);
  }
  else if (mySelectedAreaUnit == "Hectare")
  {
    myAreaUnits = Hectare;
    mCrop.setAreaUnits(myAreaUnits);
  }
  mCrop.setImageFile(mImageFile);
  mCrop.toXmlFile( LaUtils::userCropProfilesDirPath() +
      QDir::separator() + mCrop.guid() + ".xml");
  refreshCropTable(mCrop.guid());
}
void LaCropManager::resizeEvent (QResizeEvent * theEvent) [private, slot]
Definition at line 225 of file lacropmanager.cpp.
{
  tblCrops->setColumnWidth(0,0);
  tblCrops->setColumnWidth(1,tblCrops->width());
  tblCrops->horizontalHeader()->setResizeMode(1,QHeaderView::Stretch);
}
void LaCropManager::refreshCropTable (QString theGuid = 0) [private]
Definition at line 88 of file lacropmanager.cpp.
References cellClicked(), LaUtils::getAvailableCrops(), LaGuid::guid(), mCropMap, LaCrop::name(), on_toolNew_clicked(), and LaCrop::toText().
Referenced by LaCropManager(), on_pbnApply_clicked(), on_toolCopy_clicked(), and on_toolDelete_clicked().
{
  mCropMap.clear();
  tblCrops->clear();
  tblCrops->setRowCount(0);
  tblCrops->setColumnCount(2);
    //we do this in two passes
    //in the first pass we populate a qmap with all the layersets
    //we find....
  mCropMap = LaUtils::getAvailableCrops();
    //the second pass populates the table
    //doing it from the map ensures that the rows
    //are sorted by layerset name
  int mySelectedRow=0;
  int myCurrentRow=0;
  QMapIterator<QString, LaCrop> myIterator(mCropMap);
  while (myIterator.hasNext())
  {
    myIterator.next();
    LaCrop myCrop = myIterator.value();
    qDebug() << myCrop.toText();
    if (theGuid.isEmpty())
    {
      qDebug() << "No default active row was requested.Assigning to myCrop.guid()!";
      theGuid=myCrop.guid();
    }
    if (myCrop.guid()==theGuid)
    {
      mySelectedRow=myCurrentRow;
    }
      // Insert new row ready to fill with details
    tblCrops->insertRow(myCurrentRow);
    QString myGuid = myCrop.guid();
    qDebug() << "Inserting crop with guid: " << myGuid;
      // Add details to the new row
    QTableWidgetItem *mypFileNameItem= new QTableWidgetItem(myGuid);
    tblCrops->setItem(myCurrentRow, 0, mypFileNameItem);
    QTableWidgetItem *mypNameItem = new QTableWidgetItem(myCrop.name());
    tblCrops->setItem(myCurrentRow, 1, mypNameItem);
      //display an icon indicating if the layerset is local or remote (e.g. terralib)
      //LaCrop::Origin myOrigin = myCrop.origin();
      //if (myOrigin==LaCrop::USERPROFILE)
      //{
    QIcon myIcon;
    myIcon.addFile(":/localdata.png");
    mypNameItem->setIcon(myIcon);
      //}
      //else if (myOrigin==LaCrop::ADAPTERPROFILE)
      //{
      //QIcon myIcon;
      //myIcon.addFile(":/remotedata.png");
      //mypNameItem->setIcon(myIcon);
      //}
      //else if (myOrigin==LaCrop::UNDEFINED)
      //{
      //  mypNameItem->setTextColor(Qt::yellow);
      //}
    myCurrentRow++;
  }
  if (myCurrentRow>0)
  {
    tblCrops->setCurrentCell(mySelectedRow,1);
    cellClicked(mySelectedRow,1);
  }
  else
  {
    on_toolNew_clicked();
  }
  QStringList headerLabels;
  headerLabels << "File Name" << "Name";
  tblCrops->setHorizontalHeaderLabels(headerLabels);
  tblCrops->setColumnWidth(0,0);
  tblCrops->setColumnWidth(1,tblCrops->width());
  tblCrops->horizontalHeader()->hide();
  tblCrops->verticalHeader()->hide();
  tblCrops->horizontalHeader()->setResizeMode(1,QHeaderView::Stretch);
}
void LaCropManager::selectCrop (QString theFileName) [private]
Definition at line 181 of file lacropmanager.cpp.
References LaSerialisable::fromXmlFile(), mCrop, LaCrop::name(), showCrop(), and LaUtils::userCropProfilesDirPath().
Referenced by cellClicked().
{
  qDebug() << "selectCrop Called : " << theFileName;
  QString myCropDir = LaUtils::userCropProfilesDirPath();
  LaCrop myCrop;
  myCrop.fromXmlFile(myCropDir + QDir::separator() + theFileName);
  leName->setText(myCrop.name());
  mCrop=myCrop;
  showCrop();
}
void LaCropManager::readSettings () [private]
Definition at line 64 of file lacropmanager.cpp.
Referenced by LaCropManager().
{
  QSettings mySettings;
  QPoint pos = mySettings.value("mainwindow/pos", QPoint(200, 200)).toPoint();
  QSize size = mySettings.value("mainwindow/size", QSize(400, 400)).toSize();
  resize(size);
  move(pos);
}
void LaCropManager::writeSettings () [private]
Definition at line 73 of file lacropmanager.cpp.
Referenced by ~LaCropManager().
{
  QSettings mySettings;
  mySettings.setValue("mainwindow/pos", pos());
  mySettings.setValue("mainwindow/size", size());
}
Member Data Documentation
LaUtils::CropMap LaCropManager::mCropMap [private]
Definition at line 59 of file lacropmanager.h.
Referenced by refreshCropTable().
LaCrop LaCropManager::mCrop [private]
Definition at line 60 of file lacropmanager.h.
Referenced by on_pbnApply_clicked(), on_pushButtonLoad_clicked(), on_toolNew_clicked(), selectCrop(), and showCrop().
QString LaCropManager::mImageFile [private]
Definition at line 63 of file lacropmanager.h.
Referenced by on_pbnApply_clicked(), and on_pbnCropPic_clicked().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/gui/lacropmanager.h
dev/cpp/landuseanalyst/src/gui/lacropmanager.cpp