Landuse Analyst: LaDietLabels Class Reference
LaDietLabels Class Reference
#include <ladietlabels.h>
Public Member Functions
LaDietLabels ()
~LaDietLabels ()
float dairyMCalories () const
float cropMCalories () const
float wildAnimalMCalories () const
float wildPlantsMCalories () const
float dairyPortionPct () const
float tameMeatPortionPct () const
float cropsPortionPct () const
float wildAnimalPortionPct () const
float wildPlantsPortionPct () const
float plantsPortionPct () const
float animalPortionPct () const
float kiloCaloriesIndividualAnnual () const
float megaCaloriesSettlementAnnual () const
void setDairyMCalories (float theDairyMCalories)
void setCropMCalories (float theCropMCalories)
void setWildAnimalMCalories (float theWildAnimalMCalorie)
void setWildPlantsMCalories (float theWildPlantsMCalories)
void setDairyPortionPct (float theDairyPortionPct)
void setTameMeatPortionPct (float theTameMeatPortionPct)
void setCropsPortionPct (float theCropsPortionPct)
void setWildAnimalPortionPct (float theWildAnimalPortionPct)
void setWildPlantsPortionPct (float theWildPlantsPortionPct)
void setPlantsPortionPct (float thePlantsPortionPct)
void setAnimalPortionPct (float theAnimalPortionPct)
void setKiloCaloriesIndividualAnnual (float theKCaloriesIndividualAnnual)
void setMegaCaloriesSettlementAnnual (float theMCaloriesSettlementAnnua)
Private Attributes
float mDairyMCalories
float mCropMCalories
float mWildAnimalMCalories
float mWildPlantsMCalories
float mDairyPortionPct
float mTameMeatPortionPct
float mCropsPortionPct
float mWildAnimalPortionPct
float mWildPlantsPortionPct
float mPlantsPortionPct
float mAnimalPortionPct
float mKiloCaloriesIndividualAnnual
float mMegaCaloriesSettlementAnnual
Detailed Description
This class represents all of the required data for setting labels in the diet tab.
Author:
Jason Jorgenson
Definition at line 27 of file ladietlabels.h.
Constructor & Destructor Documentation
LaDietLabels::LaDietLabels ()
Definition at line 21 of file ladietlabels.cpp.
{
}
LaDietLabels::~LaDietLabels ()
Definition at line 25 of file ladietlabels.cpp.
{
}
Member Function Documentation
float LaDietLabels::dairyMCalories () const
Definition at line 31 of file ladietlabels.cpp.
References mDairyMCalories.
Referenced by LaMainForm::setDietLabels().
{
  return mDairyMCalories;
}
float LaDietLabels::cropMCalories () const
Definition at line 35 of file ladietlabels.cpp.
References mCropMCalories.
Referenced by LaMainForm::setDietLabels().
{
  return mCropMCalories;
}
float LaDietLabels::wildAnimalMCalories () const
Definition at line 39 of file ladietlabels.cpp.
References mWildAnimalMCalories.
Referenced by LaMainForm::setDietLabels().
{
  return mWildAnimalMCalories;
}
float LaDietLabels::wildPlantsMCalories () const
Definition at line 43 of file ladietlabels.cpp.
References mWildPlantsMCalories.
Referenced by LaMainForm::setDietLabels().
{
  return mWildPlantsMCalories;
}
float LaDietLabels::dairyPortionPct () const
Definition at line 47 of file ladietlabels.cpp.
References mDairyPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mDairyPortionPct;
}
float LaDietLabels::tameMeatPortionPct () const
Definition at line 51 of file ladietlabels.cpp.
References mTameMeatPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mTameMeatPortionPct;
}
float LaDietLabels::cropsPortionPct () const
Definition at line 55 of file ladietlabels.cpp.
References mCropsPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mCropsPortionPct;
}
float LaDietLabels::wildAnimalPortionPct () const
Definition at line 59 of file ladietlabels.cpp.
References mWildAnimalPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mWildAnimalPortionPct;
}
float LaDietLabels::wildPlantsPortionPct () const
Definition at line 63 of file ladietlabels.cpp.
References mWildPlantsPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mWildPlantsPortionPct;
}
float LaDietLabels::plantsPortionPct () const
Definition at line 67 of file ladietlabels.cpp.
References mPlantsPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mPlantsPortionPct;
}
float LaDietLabels::animalPortionPct () const
Definition at line 71 of file ladietlabels.cpp.
References mAnimalPortionPct.
Referenced by LaMainForm::setDietLabels().
{
  return mAnimalPortionPct;
}
float LaDietLabels::kiloCaloriesIndividualAnnual () const
Definition at line 75 of file ladietlabels.cpp.
References mKiloCaloriesIndividualAnnual.
Referenced by LaMainForm::setDietLabels().
{
  return mKiloCaloriesIndividualAnnual;
}
float LaDietLabels::megaCaloriesSettlementAnnual () const
Definition at line 79 of file ladietlabels.cpp.
References mMegaCaloriesSettlementAnnual.
Referenced by LaMainForm::setDietLabels().
{
  return mMegaCaloriesSettlementAnnual;
}
void LaDietLabels::setDairyMCalories (float theDairyMCalories)
Definition at line 86 of file ladietlabels.cpp.
References mDairyMCalories.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mDairyMCalories = theDairyMCalories;
}
void LaDietLabels::setCropMCalories (float theCropMCalories)
Definition at line 90 of file ladietlabels.cpp.
References mCropMCalories.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mCropMCalories = theCropMCalories;
}
void LaDietLabels::setWildAnimalMCalories (float theWildAnimalMCalorie)
Definition at line 94 of file ladietlabels.cpp.
References mWildAnimalMCalories.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mWildAnimalMCalories = theWildAnimalMCalorie;
}
void LaDietLabels::setWildPlantsMCalories (float theWildPlantsMCalories)
Definition at line 98 of file ladietlabels.cpp.
References mWildPlantsMCalories.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mWildPlantsMCalories = theWildPlantsMCalories;
}
void LaDietLabels::setDairyPortionPct (float theDairyPortionPct)
Definition at line 102 of file ladietlabels.cpp.
References mDairyPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mDairyPortionPct = theDairyPortionPct;
}
void LaDietLabels::setTameMeatPortionPct (float theTameMeatPortionPct)
Definition at line 106 of file ladietlabels.cpp.
References mTameMeatPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mTameMeatPortionPct = theTameMeatPortionPct;
}
void LaDietLabels::setCropsPortionPct (float theCropsPortionPct)
Definition at line 110 of file ladietlabels.cpp.
References mCropsPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mCropsPortionPct = theCropsPortionPct;
}
void LaDietLabels::setWildAnimalPortionPct (float theWildAnimalPortionPct)
Definition at line 114 of file ladietlabels.cpp.
References mWildAnimalPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mWildAnimalPortionPct = theWildAnimalPortionPct;
}
void LaDietLabels::setWildPlantsPortionPct (float theWildPlantsPortionPct)
Definition at line 118 of file ladietlabels.cpp.
References mWildPlantsPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mWildPlantsPortionPct = theWildPlantsPortionPct;
}
void LaDietLabels::setPlantsPortionPct (float thePlantsPortionPct)
Definition at line 122 of file ladietlabels.cpp.
References mPlantsPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mPlantsPortionPct = thePlantsPortionPct;
}
void LaDietLabels::setAnimalPortionPct (float theAnimalPortionPct)
Definition at line 126 of file ladietlabels.cpp.
References mAnimalPortionPct.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mAnimalPortionPct = theAnimalPortionPct;
}
void LaDietLabels::setKiloCaloriesIndividualAnnual (float theKCaloriesIndividualAnnual)
Definition at line 130 of file ladietlabels.cpp.
References mKiloCaloriesIndividualAnnual.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mKiloCaloriesIndividualAnnual = theKiloCaloriesIndividualAnnual;
}
void LaDietLabels::setMegaCaloriesSettlementAnnual (float theMCaloriesSettlementAnnua)
Definition at line 134 of file ladietlabels.cpp.
References mMegaCaloriesSettlementAnnual.
Referenced by LaModel::doCalcsAnimalsFirstDairySeparate(), LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::doCalcsPlantsFirstDairySeperate(), and LaModel::doCalcsPlantsFirstIncludeDairy().
{
  mMegaCaloriesSettlementAnnual = theMegaCaloriesSettlementAnnua;
}
Member Data Documentation
float LaDietLabels::mDairyMCalories [private]
Definition at line 64 of file ladietlabels.h.
Referenced by dairyMCalories(), and setDairyMCalories().
float LaDietLabels::mCropMCalories [private]
Definition at line 65 of file ladietlabels.h.
Referenced by cropMCalories(), and setCropMCalories().
float LaDietLabels::mWildAnimalMCalories [private]
Definition at line 66 of file ladietlabels.h.
Referenced by setWildAnimalMCalories(), and wildAnimalMCalories().
float LaDietLabels::mWildPlantsMCalories [private]
Definition at line 67 of file ladietlabels.h.
Referenced by setWildPlantsMCalories(), and wildPlantsMCalories().
float LaDietLabels::mDairyPortionPct [private]
Definition at line 68 of file ladietlabels.h.
Referenced by dairyPortionPct(), and setDairyPortionPct().
float LaDietLabels::mTameMeatPortionPct [private]
Definition at line 69 of file ladietlabels.h.
Referenced by setTameMeatPortionPct(), and tameMeatPortionPct().
float LaDietLabels::mCropsPortionPct [private]
Definition at line 70 of file ladietlabels.h.
Referenced by cropsPortionPct(), and setCropsPortionPct().
float LaDietLabels::mWildAnimalPortionPct [private]
Definition at line 71 of file ladietlabels.h.
Referenced by setWildAnimalPortionPct(), and wildAnimalPortionPct().
float LaDietLabels::mWildPlantsPortionPct [private]
Definition at line 72 of file ladietlabels.h.
Referenced by setWildPlantsPortionPct(), and wildPlantsPortionPct().
float LaDietLabels::mPlantsPortionPct [private]
Definition at line 73 of file ladietlabels.h.
Referenced by plantsPortionPct(), and setPlantsPortionPct().
float LaDietLabels::mAnimalPortionPct [private]
Definition at line 74 of file ladietlabels.h.
Referenced by animalPortionPct(), and setAnimalPortionPct().
float LaDietLabels::mKiloCaloriesIndividualAnnual [private]
Definition at line 75 of file ladietlabels.h.
Referenced by kiloCaloriesIndividualAnnual(), and setKiloCaloriesIndividualAnnual().
float LaDietLabels::mMegaCaloriesSettlementAnnual [private]
Definition at line 76 of file ladietlabels.h.
Referenced by megaCaloriesSettlementAnnual(), and setMegaCaloriesSettlementAnnual().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/ladietlabels.h
dev/cpp/landuseanalyst/src/lib/ladietlabels.cpp