Landuse Analyst: LaAssemblageConversion Class Reference
LaAssemblageConversion Class Reference
#include <laassemblageconversion.h>
Public Slots
virtual void on_pbnInsert_clicked ()
virtual void on_pbnCalculate_clicked ()
virtual void on_pbnClearTable_clicked ()
virtual void on_pbnSave_clicked ()
Public Member Functions
LaAssemblageConversion (QWidget *parent=0, Qt::WFlags fl=0)
~LaAssemblageConversion ()
Private Slots
void resizeEvent (QResizeEvent *)
Private Member Functions
void refreshTable ()
void readSettings ()
void writeSettings ()
bool setComboToDefault (QComboBox *thepCombo, QString theDefault)
Private Attributes
LaUtils::AnimalParameterMap mAnimalParameterMap
LaUtils::CropMap mCropMap
LaAnimalParameter mAnimalParameter
Detailed Description
This is the main gui class
Author:
Tim Sutton, Jason Jorgenson
Definition at line 37 of file laassemblageconversion.h.
Constructor & Destructor Documentation
LaAssemblageConversion::LaAssemblageConversion (QWidget * parent = 0, Qt::WFlags fl = 0)
Definition at line 48 of file laassemblageconversion.cpp.
References LaUtils::getAvailableAnimals(), LaGuid::guid(), LaAnimal::name(), and readSettings().
: QDialog(parent,fl)
{
    //required by Qt4 to initialise the ui
  setupUi(this);
  readSettings();
  //  connect(pbnInsert, SIGNAL(clicked()),
   //     this, SLOT(on_pbnInsert_clicked()));
  tblAnimals->setColumnCount(5);
    //populate the animals combo
  LaUtils::AnimalMap myAnimalsMap;
  myAnimalsMap = LaUtils::getAvailableAnimals();
  QMapIterator<QString, LaAnimal> myIterator(myAnimalsMap);
  while (myIterator.hasNext())
  {
    myIterator.next();
    LaAnimal myAnimal = myIterator.value();
    QString myGuid = myAnimal.guid();
    QString myName = myAnimal.name();
    QIcon myIcon;
    myIcon.addFile(":/localdata.png");
    cboAnimal->addItem(myName,myGuid);
  }
}
LaAssemblageConversion::~LaAssemblageConversion ()
Definition at line 78 of file laassemblageconversion.cpp.
References writeSettings().
{
  writeSettings();
}
Member Function Documentation
void LaAssemblageConversion::on_pbnInsert_clicked () [virtual, slot]
Definition at line 106 of file laassemblageconversion.cpp.
References LaUtils::getAnimal(), LaAnimal::killWeight(), LaAnimal::meatFoodValue(), LaAnimal::name(), and LaAnimal::usableMeat().
{
    // add an animal to the table
  qDebug() << "pbnInsert";
  int myRowCount = tblAnimals->rowCount();
  qDebug() << "rowCount: " << myRowCount;
  if (rbManual->isChecked() == true)
  {
    qDebug() << "manual is checked";
      // add item to table from manual inputs
    tblAnimals->insertRow(myRowCount);
    QString myName = leAnimal->text();
    int myUsableMeat = sbUsableMeat->value();
    int myCalsPerKg = sbCalsPerKg->value();
    float myNumber = dsbNumber->value();
    QTableWidgetItem *mypNameItem = new QTableWidgetItem(myName);
    tblAnimals->setItem(myRowCount, 0, mypNameItem);
    qDebug() << "myName = " << myName;
    QTableWidgetItem *mypUsableMeatItem= new QTableWidgetItem(QString::number(myUsableMeat));
    tblAnimals->setItem(myRowCount, 2, mypUsableMeatItem);
    QTableWidgetItem *mypCalsPerKgItem= new QTableWidgetItem(QString::number(myCalsPerKg));
    tblAnimals->setItem(myRowCount, 3, mypCalsPerKgItem);
    QTableWidgetItem *mypNumber= new QTableWidgetItem(QString::number(myNumber));
    tblAnimals->setItem(myRowCount, 1, mypNumber);
      //tblAnimals->insertRow(myRowCount);
  }
  else if (rbAuto->isChecked() == true)
  {
      // add item to table from pre-defined animals
    qDebug() << "auto is checked";
    LaAnimal myAnimal = LaUtils::getAnimal( cboAnimal->itemData( cboAnimal->currentIndex(), Qt::UserRole).toString());
    tblAnimals->insertRow(myRowCount);
    QString myName = myAnimal.name();
    int myUsableMeatPercent = myAnimal.usableMeat();
    int myKillWeight = myAnimal.killWeight();
    int myCalsPerKg = myAnimal.meatFoodValue();
    float myUsableMeat = (0.01*myUsableMeatPercent) * myKillWeight;
    float myNumber = dsbNumber->value();
    QTableWidgetItem *mypNameItem = new QTableWidgetItem(myName);
    tblAnimals->setItem(myRowCount, 0, mypNameItem);
    qDebug() << "myName = " << myName;
    QTableWidgetItem *mypUsableMeatItem= new QTableWidgetItem(QString::number(myUsableMeat));
    tblAnimals->setItem(myRowCount, 2, mypUsableMeatItem);
    QTableWidgetItem *mypCalsPerKgItem= new QTableWidgetItem(QString::number(myCalsPerKg));
    tblAnimals->setItem(myRowCount, 3, mypCalsPerKgItem);
    QTableWidgetItem *mypNumber= new QTableWidgetItem(QString::number(myNumber));
    tblAnimals->setItem(myRowCount, 1, mypNumber);
  }
  else
    {
      qDebug() << "nothing selected, just returning";
      return;
    }
  return;
}
void LaAssemblageConversion::on_pbnCalculate_clicked () [virtual, slot]
Definition at line 174 of file laassemblageconversion.cpp.
{
    // calculate the percent of diet based on entries in tblAnimals
    // iterate through the table and get a sum of the adjusted meat value
    // which is the NISP * weight of usable meat * calories per kg
  float myAdjustmentSum = 0.0;
  float myContributionToDiet = 0.0;
    // iterate through table
  for (int myCurrentRow=0; myCurrentRow < tblAnimals->rowCount(); myCurrentRow++)
  {
      //QTableWidgetItem * mypNameWidget        = tblAnimals->item(myCurrentRow,0);
    QTableWidgetItem * mypNumberWidget      = tblAnimals->item(myCurrentRow,1);
    QTableWidgetItem * mypUsableMeatWidget  = tblAnimals->item(myCurrentRow,2);
    QTableWidgetItem * mypCalsPerKgWidget   = tblAnimals->item(myCurrentRow,3);
    myAdjustmentSum += (mypNumberWidget->text().toFloat())
                     * (mypUsableMeatWidget->text().toInt())
                     * (mypCalsPerKgWidget->text().toInt())
                     * 0.001;   // to keep figures within limits
    qDebug() << "row: " << myCurrentRow <<" Adjustment sum: " << myAdjustmentSum;
  }
    // iterate table again, adding percentage contribution to diet
  float myDebugSumCheck = 0.0;
  for (int myCurrentRow1=0; myCurrentRow1 < tblAnimals->rowCount(); myCurrentRow1++)
  {
    QTableWidgetItem * mypNumberWidget      = tblAnimals->item(myCurrentRow1,1);
    QTableWidgetItem * mypUsableMeatWidget  = tblAnimals->item(myCurrentRow1,2);
    QTableWidgetItem * mypCalsPerKgWidget   = tblAnimals->item(myCurrentRow1,3);
    myContributionToDiet = (((mypNumberWidget->text().toFloat())
                     * (mypUsableMeatWidget->text().toInt())
                     * (mypCalsPerKgWidget->text().toInt())
                     * 0.001)
                     / myAdjustmentSum)
                     * 100.0;   // to make it percent (ie. 10.56% instead of 0.1056)
   myDebugSumCheck += myContributionToDiet;
    QTableWidgetItem *mypContributionToDiet= new QTableWidgetItem(QString::number(myContributionToDiet));
    tblAnimals->setItem(myCurrentRow1, 4, mypContributionToDiet);
    qDebug() << "debug sum check: " << myDebugSumCheck;
  }
  qDebug() << "Final debug sum (should be 100) : " << myDebugSumCheck;
}
void LaAssemblageConversion::on_pbnClearTable_clicked () [virtual, slot]
Definition at line 247 of file laassemblageconversion.cpp.
{
  tblAnimals->clear();
}
void LaAssemblageConversion::on_pbnSave_clicked () [virtual, slot]
Definition at line 220 of file laassemblageconversion.cpp.
References LaUtils::createTextFile(), and LaUtils::saveFile().
{
  QString myString= "Name,Number,UsableMeat,CalsPerKg,PercentDiet";
  myString += "\n";
  for (int myCurrentRow=0; myCurrentRow < tblAnimals->rowCount(); myCurrentRow++)
  {
    QTableWidgetItem * mypNameWidget          = tblAnimals->item(myCurrentRow,0);
    QTableWidgetItem * mypNumberWidget        = tblAnimals->item(myCurrentRow,1);
    QTableWidgetItem * mypUsableMeatWidget    = tblAnimals->item(myCurrentRow,2);
    QTableWidgetItem * mypCalsPerKgWidget     = tblAnimals->item(myCurrentRow,3);
    QTableWidgetItem * mypContributionToDiet  = tblAnimals->item(myCurrentRow,4);
    myString += mypNameWidget->text()         + ",";
    myString += mypNumberWidget->text()       + ",";
    myString += mypUsableMeatWidget->text()   + ",";
    myString += mypCalsPerKgWidget->text()    + ",";
    myString += mypContributionToDiet->text() + ",";
    myString += "\n";
  }
  LaUtils myUtils;
  QString myFileName = myUtils.saveFile();
  myUtils.createTextFile(myFileName, myString);
  return;
}
void LaAssemblageConversion::resizeEvent (QResizeEvent * theEvent) [private, slot]
Definition at line 99 of file laassemblageconversion.cpp.
{
    //tblAnimals->setColumnWidth(0,0);
    //tblAnimals->setColumnWidth(1,tblAnimals->width());
  tblAnimals->horizontalHeader()->setResizeMode(0,QHeaderView::Stretch);
}
void LaAssemblageConversion::refreshTable () [private]
Definition at line 252 of file laassemblageconversion.cpp.
{
    //
}
void LaAssemblageConversion::readSettings () [private]
Definition at line 83 of file laassemblageconversion.cpp.
Referenced by LaAssemblageConversion().
{
  QSettings mySettings;
  QPoint pos = mySettings.value("mainwindow/pos", QPoint(200, 200)).toPoint();
  QSize size = mySettings.value("mainwindow/size", QSize(400, 400)).toSize();
  resize(size);
  move(pos);
}
void LaAssemblageConversion::writeSettings () [private]
Definition at line 92 of file laassemblageconversion.cpp.
Referenced by ~LaAssemblageConversion().
{
  QSettings mySettings;
  mySettings.setValue("mainwindow/pos", pos());
  mySettings.setValue("mainwindow/size", size());
}
bool LaAssemblageConversion::setComboToDefault (QComboBox * thepCombo, QString theDefault) [private]
move this into LaGuiUtils - a gui subclass of LaUtils
Definition at line 257 of file laassemblageconversion.cpp.
{
  if (!theDefault.isEmpty())
  {
      //loop through list looking for a match
    for ( int myCounter = 0; myCounter < thepCombo->count(); myCounter++ )
    {
      thepCombo->setCurrentIndex(myCounter);
      if (thepCombo->itemData(myCounter,Qt::UserRole)==theDefault)
      {
        break;
      }
    }
  }
  else
  {
    return false;
  }
  return true;
}
Member Data Documentation
LaUtils::AnimalParameterMap LaAssemblageConversion::mAnimalParameterMap [private]
Definition at line 61 of file laassemblageconversion.h.
LaUtils::CropMap LaAssemblageConversion::mCropMap [private]
Definition at line 62 of file laassemblageconversion.h.
LaAnimalParameter LaAssemblageConversion::mAnimalParameter [private]
Definition at line 63 of file laassemblageconversion.h.
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/gui/laassemblageconversion.h
dev/cpp/landuseanalyst/src/gui/laassemblageconversion.cpp