from typing import Optional, Dict
from PyQt5.QtCore import QObject, pyqtSlot
from PyQt5.QtWidgets import QListWidgetItem

class LaMainForm(QObject):
    """Type stub for LaMainForm class"""

    def __init__(self, parent: Optional[QObject] = None) -> None: ...

    def logToAllChannels(self, message: str) -> None: ...

    def refresh(self) -> None: ...

    def setup(self) -> None: ...

    def loadImages(self) -> None: ...

    def connect_additional_signals(self) -> None: ...

    def setDietLabels(self) -> None: ...

    def updateCalculations(self) -> None: ...

    def calculateTotalLandNeeded(self) -> None: ...

    def readSettings(self) -> None: ...

    def writeSettings(self) -> None: ...

    def closeEvent(self, event) -> None: ...

    def _override_on_cbDebug_clicked(self) -> None: ...

    def _on_debug_dialog_closed(self) -> None: ...

    def _ensure_debug_dialog_visible(self) -> None: ...

    def on_debug_message(self, message: str) -> None: ...

    def logMessage(self, message: str) -> None: ...

    def connect_diet_label_signals(self) -> None: ...

    def _connect_diet_label_signals(self, dietLabels) -> None: ...

    def connectSignalsSlots(self) -> None: ...

    @pyqtSlot(int)
    def on_sliderDiet_valueChanged(self, value: int) -> None: ...

    @pyqtSlot(int)
    def on_sliderMeat_valueChanged(self, value: int) -> None: ...

    @pyqtSlot(int)
    def on_sbDailyCalories_valueChanged(self, value: int) -> None: ...

    @pyqtSlot(bool)
    def on_cboxIncludeDairy_clicked(self, checked: bool) -> None: ...

    @pyqtSlot(bool)
    def on_cboxLimitDairy_clicked(self, checked: bool) -> None: ...

    @pyqtSlot(int)
    def on_sbLimitDairyPercent_valueChanged(self, value: int) -> None: ...

    @pyqtSlot(bool)
    def on_cboxBaseOnPlants_clicked(self, checked: bool) -> None: ...

    @pyqtSlot(int)
    def on_sbDairyUtilisation_valueChanged(self, value: int) -> None: ...

    @pyqtSlot(QListWidgetItem, QListWidgetItem)
    def animalCalcClicked(self, current_item: QListWidgetItem, previous_item: QListWidgetItem) -> None: ...

    @pyqtSlot(QListWidgetItem, QListWidgetItem)
    def cropCalcClicked(self, current_item: QListWidgetItem, previous_item: QListWidgetItem) -> None: ...

    def _configureModelFromUi(self) -> None: ...

    def getSelectedAnimals(self) -> Dict[str, str]: ...

    def getSelectedCrops(self) -> Dict[str, str]: ...

    def _getPropertyValue(self, obj, prop_name: str): ...

    def updateDietLabels(self, dairy_portion_pct: float = 0.0, tame_meat_portion_pct: float = 0.0, crops_portion_pct: float = 0.0) -> None: ...