landuseanalyst.kdevelop: qrc_resources.cxx File Reference
build/src/gui/qrc_resources.cxx File Reference
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_resources ()
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_resources)) int QT_MANGLE_NAMESPACE(qCleanupResources_resources)()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Function Documentation
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_resources))
Definition at line 21469 of file build/src/gui/qrc_resources.cxx.
References qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_resources ()
Definition at line 21462 of file build/src/gui/qrc_resources.cxx.
References qRegisterResourceData(), qt_resource_data, qt_resource_name, and qt_resource_struct.
QT_BEGIN_NAMESPACE bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_resources().
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by Q_CONSTRUCTOR_FUNCTION().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 12 of file build/src/gui/qrc_resources.cxx.
Referenced by Q_CONSTRUCTOR_FUNCTION(), and qInitResources_resources().
const unsigned char qt_resource_name[] [static]
Definition at line 20547 of file build/src/gui/qrc_resources.cxx.
Referenced by Q_CONSTRUCTOR_FUNCTION(), and qInitResources_resources().
const unsigned char qt_resource_struct[] [static]
Definition at line 21209 of file build/src/gui/qrc_resources.cxx.
Referenced by Q_CONSTRUCTOR_FUNCTION(), and qInitResources_resources().