from typing import Any, Dict, List, Optional, Union
from la.lib.la import EnergyType

class LaAnimal:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def description(self) -> str: ...
    def meatFoodValue(self) -> int: ...
    def usableMeat(self) -> int: ...
    def killWeight(self) -> int: ...
    def adultWeight(self) -> int: ...
    def growTime(self) -> int: ...
    def deathRate(self) -> int: ...
    def feedEnergyType(self) -> EnergyType: ...
    def gestating(self) -> int: ...
    def lactating(self) -> int: ...
    def maintenance(self) -> int: ...
    def juvenile(self) -> int: ...
    def sexualMaturity(self) -> int: ...
    def breedingExpectancy(self) -> int: ...
    def conceptionEfficiency(self) -> int: ...
    def femalesPerMale(self) -> int: ...
    def youngPerBirth(self) -> int: ...
    def weaningAge(self) -> int: ...
    def weaningWeight(self) -> int: ...
    def gestationTime(self) -> int: ...
    def estrousCycle(self) -> int: ...
    def lactationTime(self) -> int: ...
    def milk(self) -> bool: ...
    def milkGramsPerDay(self) -> int: ...
    def milkFoodValue(self) -> int: ...
    def fleece(self) -> bool: ...
    def fleeceWeightKg(self) -> int: ...
    def imageFile(self) -> str: ...
    def setName(self, theName: str) -> None: ...
    def setDescription(self, theDescription: str) -> None: ...
    def setMeatFoodValue(self, theFoodValue: int) -> None: ...
    def setUsableMeat(self, thePercentage: int) -> None: ...
    def setKillWeight(self, theKg: int) -> None: ...
    def setGrowTime(self, theWeeks: int) -> None: ...
    def setAdultWeight(self, theKg: int) -> None: ...
    def setConceptionEfficiency(self, thePercentage: int) -> None: ...
    def setFemalesToMales(self, theInt: int) -> None: ...
    def setDeathRate(self, thePercentage: int) -> None: ...
    def setFeedEnergyType(self, theFeedEnergyType: EnergyType) -> None: ...
    def setGestating(self, theCalories: int) -> None: ...
    def setLactating(self, theCalories: int) -> None: ...
    def setMaintenance(self, theCalories: int) -> None: ...
    def setJuvenile(self, theCalories: int) -> None: ...
    def setSexualMaturity(self, theMonths: int) -> None: ...
    def setBreedingExpectancy(self, theYears: int) -> None: ...
    def setYoungPerBirth(self, theInteger: int) -> None: ...
    def setWeaningWeight(self, theWeight: int) -> None: ...
    def setWeaningAge(self, theDays: int) -> None: ...
    def setGestationTime(self, theDays: int) -> None: ...
    def setEstrousCycle(self, theDays: int) -> None: ...
    def setLactationTime(self, theTime: int) -> None: ...
    def setMilk(self, theBool: bool) -> None: ...
    def setMilkGramsPerDay(self, theMilkGrams: int) -> None: ...
    def setMilkFoodValue(self, theMilkFoodValue: int) -> None: ...
    def setFleece(self, theFleeceBool: bool) -> None: ...
    def setFleeceWeightKg(self, theFleeceWeight: int) -> None: ...
    def setImageFile(self, theImageFileName: str) -> None: ...
    def toXml(self) -> str: ...
    def toText(self) -> str: ...
    def toHtml(self) -> str: ...
    def fromXml(self, theXml: str) -> bool: ... # returns true if successful