from typing import Any, Union
from la.lib.la import AreaUnits
""" 
    This file is a stub for the LaCropParameter class.
    The stub is used for type checking and IDE support.
    The stub does not contain any actual code.
    
"""
class LaCropParameter:
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def __copy__(self) -> 'LaCropParameter': ...
    def __eq__(self, theCropParameter: 'LaCropParameter') -> 'LaCropParameter': ...

    def name(self) -> str: ...
    def description(self) -> str: ...
    def cropGuid(self) -> str: ...
    def percentTameCrop(self) -> float: ...
    def spoilage(self) -> float: ...
    def reseed(self) -> float: ...
    def cropRotation(self) -> bool: ...
    def fallowRatio(self) -> float: ...
    def fallowValue(self) -> int: ...
    def areaUnits(self) -> AreaUnits: ...  
    def useCommonLand(self) -> bool: ...
    def useSpecificLand(self) -> bool: ...
    def rasterName(self) -> str: ...

    def setName(self, theName: str) -> None: ...
    def setDescription(self, theDescription: str) -> None: ...
    def setCropGuid(self, theGuid: str) -> None: ...
    def setPercentTameCrop(self, thePercentage: float) -> None: ...
    def setSpoilage(self, thePercentage: float) -> None: ...
    def setReseed(self, thePercentage: float) -> None: ...
    def setCropRotation(self, theFlag: bool) -> None: ...
    def setFallowRatio(self, theRatio: float) -> None: ...
    def setFallowValue(self, theKg: int) -> None: ...
    def setAreaUnits(self, theAreaUnit: AreaUnits) -> None: ... 
    def setUseCommonLand(self, theBool: bool) -> None: ...
    def setUseSpecificLand(self, theBool: bool) -> None: ...
    def setRasterName(self, theRasterName: str) -> None: ...

    def toXml(self) -> str: ...
    def toText(self) -> str: ...
    def toHtml(self) -> str: ...
    def fromXml(self, theXml: str) -> bool: ...