from typing import Optional
from qgis.PyQt.QtCore import QObject, pyqtSignal
from la.lib.laserialisable import LaSerialisable
from la.lib.laguid import LaGuid
from la.lib.la import AreaUnits as LaAreaUnits

class LaCropParameter(QObject, LaSerialisable, LaGuid):
    nameChanged: pyqtSignal
    descriptionChanged: pyqtSignal
    guidChanged: pyqtSignal
    cropGuidChanged: pyqtSignal
    percentTameCropChanged: pyqtSignal
    spoilageChanged: pyqtSignal
    reseedChanged: pyqtSignal
    cropRotationChanged: pyqtSignal
    fallowRatioChanged: pyqtSignal
    fallowValueChanged: pyqtSignal
    areaUnitsChanged: pyqtSignal
    useCommonLandChanged: pyqtSignal
    useSpecificLandChanged: pyqtSignal
    rasterNameChanged: pyqtSignal

    def __init__(self, theCropParameter: Optional["LaCropParameter"] = ...) -> None: ...

    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, theName: str) -> None: ...

    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, description: str) -> None: ...

    @property
    def guid(self) -> str: ...
    @guid.setter
    def guid(self, guid: str) -> None: ...

    @property
    def cropGuid(self) -> str: ...
    @cropGuid.setter
    def cropGuid(self, cropGuid: str) -> None: ...

    @property
    def percentTameCrop(self) -> float: ...
    @percentTameCrop.setter
    def percentTameCrop(self, value: float) -> None: ...

    @property
    def spoilage(self) -> float: ...
    @spoilage.setter
    def spoilage(self, value: float) -> None: ...

    @property
    def reseed(self) -> float: ...
    @reseed.setter
    def reseed(self, value: float) -> None: ...

    @property
    def cropRotation(self) -> bool: ...
    @cropRotation.setter
    def cropRotation(self, value: bool) -> None: ...

    @property
    def fallowRatio(self) -> float: ...
    @fallowRatio.setter
    def fallowRatio(self, value: float) -> None: ...

    @property
    def fallowValue(self) -> int: ...
    @fallowValue.setter
    def fallowValue(self, value: int) -> None: ...

    @property
    def areaUnits(self) -> LaAreaUnits: ...
    @areaUnits.setter
    def areaUnits(self, value: LaAreaUnits) -> None: ...

    @property
    def useCommonLand(self) -> bool: ...
    @useCommonLand.setter
    def useCommonLand(self, value: bool) -> None: ...

    @property
    def useSpecificLand(self) -> bool: ...
    @useSpecificLand.setter
    def useSpecificLand(self, value: bool) -> None: ...

    @property
    def rasterName(self) -> str: ...
    @rasterName.setter
    def rasterName(self, value: str) -> None: ...

    def fromXml(self, theXml: str) -> bool: ...
    def fromXmlFile(self, theFilePath: str) -> bool: ...
    def toXml(self) -> str: ...
    def toXmlFile(self, theFilePath: str) -> bool: ...
    def debug_info(self) -> str: ...