# ladietlabels.pyi

import copy
from typing import Dict, List, Tuple, Union, Any
from qgis.PyQt.QtCore import QObject, pyqtSignal, pyqtSlot, Qt

# Assuming these types are defined/imported elsewhere
from la.lib.laserialisable import LaSerialisable
from la.lib.laguid import LaGuid
from la.lib.lautils import LaUtils # Keep LaUtils for debug logging if used in stubbed methods? No, just for type hint maybe
from la.lib.la import EnergyType # Used in calculateAnimalAreaTarget
# Types needed for method hints, replace Any if more specific types are known
# from la.lib.laanimal import LaAnimal
# from la.lib.laanimalparameter import LaAnimalParameter
# from la.lib.lacrop import LaCrop

class LaDietLabels(QObject, LaSerialisable, LaGuid):
    # Signals (Keep as pyqtSignal)
    _dairyMCaloriesChanged: pyqtSignal = ...
    _cropMCaloriesChanged: pyqtSignal = ...
    _animalMCaloriesChanged: pyqtSignal = ...
    _wildAnimalMCaloriesChanged: pyqtSignal = ...
    _wildPlantsMCaloriesChanged: pyqtSignal = ...
    _dairyPortionPctChanged: pyqtSignal = ...
    _tameMeatPortionPctChanged: pyqtSignal = ...
    _cropsPortionPctChanged: pyqtSignal = ...
    _wildAnimalPortionPctChanged: pyqtSignal = ...
    _wildPlantsPortionPctChanged: pyqtSignal = ...
    _plantsPortionPctChanged: pyqtSignal = ...
    _animalPortionPctChanged: pyqtSignal = ...
    _kiloCaloriesIndividualAnnualChanged: pyqtSignal = ...
    _megaCaloriesSettlementAnnualChanged: pyqtSignal = ...
    _dairySurplusMCaloriesChanged: pyqtSignal = ...
    _cropCalcsReportMapChanged: pyqtSignal = ... # Use pyqtSignal() if dict typing fails
    _animalCalcsReportMapChanged: pyqtSignal = ... # Use pyqtSignal() if dict typing fails
    _specificLandEnergyTypeChanged: pyqtSignal = ... # Use pyqtSignal() if str typing fails
    _commonLandValueChanged: pyqtSignal = ... # Use pyqtSignal() if float typing fails
    _animalAreaTargetsMapChanged: pyqtSignal = ... # Use pyqtSignal() if dict typing fails
    _cropAreaTargetsMapChanged: pyqtSignal = ... # Use pyqtSignal() if dict typing fails

    # Instance Attributes (from __init__)
    _dairyMCalories: float = ...
    _cropMCalories: float = ...
    _animalMCalories: float = ...
    _wildAnimalMCalories: float = ...
    _wildPlantsMCalories: float = ...
    _dairyPortionPct: float = ...
    _tameMeatPortionPct: float = ...
    _cropsPortionPct: float = ...
    _wildAnimalPortionPct: float = ...
    _wildPlantsPortionPct: float = ...
    _plantsPortionPct: float = ...
    _animalPortionPct: float = ...
    _kiloCaloriesIndividualAnnual: float = ...
    _megaCaloriesSettlementAnnual: float = ...
    _dairySurplusMCalories: float = ...
    _cropAreaTargetsMap: Dict[str, float] = ...
    _animalAreaTargetsMap: Dict[str, float] = ...
    _cropCalcsReportMap: Dict[str, Tuple[str, float]] = ...
    _animalCalcsReportMap: Dict[str, Tuple[str, float]] = ...

    # --- Placeholders for attributes used in calculateAnimalAreaTarget ---
    # These would typically be part of another object (like LaModel) passed in,
    # but including them here if they are meant to be direct attributes somehow.
    # If they are accessed via another object (e.g., self.model.commonLandValue),
    # this part of the stub might not be accurate for LaDietLabels itself.
    specificLandEnergyType: EnergyType = ...
    commonLandValue: float = ...
    # ---------------------------------------------------------------------

    def __init__(self, parent: QObject | None = None) -> None: ...
    # def __del__(self) -> None: ... # Not usually needed in stubs
    def __copy__(self) -> LaDietLabels: ...
    def __deepcopy__(self, memo: Any) -> LaDietLabels: ...

    # Properties (Using standard @property)
    @property
    def dairyMCalories(self) -> float: ...
    @dairyMCalories.setter
    def dairyMCalories(self, theDairyMCalories: float) -> None: ...

    @property
    def cropMCalories(self) -> float: ...
    @cropMCalories.setter
    def cropMCalories(self, theCropMCalories: float) -> None: ...

    @property
    def animalMCalories(self) -> float: ...
    @animalMCalories.setter
    def animalMCalories(self, theAnimalMCalories: float) -> None: ...

    @property
    def wildAnimalMCalories(self) -> float: ...
    @wildAnimalMCalories.setter
    def wildAnimalMCalories(self, theWildAnimalMCalories: float) -> None: ...

    @property
    def wildPlantsMCalories(self) -> float: ...
    @wildPlantsMCalories.setter
    def wildPlantsMCalories(self, theWildPlantsMCalories: float) -> None: ...

    @property
    def dairyPortionPct(self) -> float: ...
    @dairyPortionPct.setter
    def dairyPortionPct(self, theDairyPortionPct: float) -> None: ...

    @property
    def tameMeatPortionPct(self) -> float: ...
    @tameMeatPortionPct.setter
    def tameMeatPortionPct(self, theTameMeatPortionPct: float) -> None: ...

    @property
    def cropsPortionPct(self) -> float: ...
    @cropsPortionPct.setter
    def cropsPortionPct(self, theCropsPortionPct: float) -> None: ...

    @property
    def wildAnimalPortionPct(self) -> float: ...
    @wildAnimalPortionPct.setter
    def wildAnimalPortionPct(self, theWildAnimalPortionPct: float) -> None: ...

    @property
    def wildPlantsPortionPct(self) -> float: ...
    @wildPlantsPortionPct.setter
    def wildPlantsPortionPct(self, theWildPlantsPortionPct: float) -> None: ...

    @property
    def plantsPortionPct(self) -> float: ...
    @plantsPortionPct.setter
    def plantsPortionPct(self, thePlantsPortionPct: float) -> None: ...

    @property
    def animalPortionPct(self) -> float: ...
    @animalPortionPct.setter
    def animalPortionPct(self, theAnimalPortionPct: float) -> None: ...

    @property
    def kiloCaloriesIndividualAnnual(self) -> float: ...
    @kiloCaloriesIndividualAnnual.setter
    def kiloCaloriesIndividualAnnual(self, theKiloCaloriesIndividualAnnual: float) -> None: ...

    @property
    def megaCaloriesSettlementAnnual(self) -> float: ...
    @megaCaloriesSettlementAnnual.setter
    def megaCaloriesSettlementAnnual(self, theMegaCaloriesSettlementAnnual: float) -> None: ...

    @property
    def dairySurplusMCalories(self) -> float: ...
    @dairySurplusMCalories.setter
    def dairySurplusMCalories(self, theDairySurplusMCalories: float) -> None: ...

    @property
    def cropAreaTargetsMap(self) -> Dict[str, float]: ...
    @cropAreaTargetsMap.setter
    def cropAreaTargetsMap(self, theCropAreaTargetsMap: Dict[str, float]) -> None: ...

    @property
    def animalAreaTargetsMap(self) -> Dict[str, float]: ...
    @animalAreaTargetsMap.setter
    def animalAreaTargetsMap(self, theAnimalAreaTargetsMap: Dict[str, float]) -> None: ...

    @property
    def cropCalcsReportMap(self) -> Dict[str, Tuple[str, float]]: ...
    @cropCalcsReportMap.setter
    def cropCalcsReportMap(self, theCropCalcsReportMap: Dict[str, Tuple[str, float]]) -> None: ...

    @property
    def animalCalcsReportMap(self) -> Dict[str, Tuple[str, float]]: ...
    @animalCalcsReportMap.setter
    def animalCalcsReportMap(self, theAnimalCalcsReportMap: Dict[str, Tuple[str, float]]) -> None: ...

    # Methods
    def calculateFodderNeeds(self, animalGuid: str, animalParameter: Any, herdSize: Dict[str, float]) -> Dict[str, float]: ...
    # Helper method referenced in calculateFodderNeeds - assuming it exists or is part of base class/mixin
    def getCrop(self, cropGuid: str) -> Any | None: ... # Replace Any with actual Crop type if known
    def calculateAnimalAreaTarget(self, animalGuid: str, animalParameter: Any, adjustedFeedRequirement: float) -> float: ...
    def toXml(self) -> str: ...
    def fromXml(self, xmlStr: str) -> None: ...