from typing import Any
from la.lib.la import La


class LaDietLabels:
    def __init__(self): ...
    def __del__(self): ...

    def dairyMCalories(self) -> float: ...
    def cropMCalories(self) -> float: ...
    def animalMCalories(self) -> float: ...
    def wildAnimalMCalories(self) -> float: ...
    def wildPlantsMCalories(self) -> float: ...
    def dairyPortionPct(self) -> float: ...
    def tameMeatPortionPct(self) -> float: ...
    def cropsPortionPct(self) -> float: ...
    def wildAnimalPortionPct(self) -> float: ...
    def wildPlantsPortionPct(self) -> float: ...
    def plantsPortionPct(self) -> float: ...
    def animalPortionPct(self) -> float: ...
    def kiloCaloriesIndividualAnnual(self) -> float: ...
    def megaCaloriesSettlementAnnual(self) -> float: ...
    def dairySurplusMCalories(self) -> float: ...
    def cropCalcsReportMap(self) -> La.LaReportMap: ...
    def animalCalcsReportMap(self) -> La.LaReportMap: ...

    def setDairyMCalories(self, theDairyMCalories: float): ...
    def setCropMCalories(self, theCropMCalories: float): ...
    def setAnimalMCalories(self, theAnimalMCalories: float): ...
    def setWildAnimalMCalories(self, theWildAnimalMCalorie: float): ...
    def setWildPlantsMCalories(self, theWildPlantsMCalories: float): ...
    def setDairyPortionPct(self, theDairyPortionPct: float): ...
    def setTameMeatPortionPct(self, theTameMeatPortionPct: float): ...
    def setCropsPortionPct(self, theCropsPortionPct: float): ...
    def setWildAnimalPortionPct(self, theWildAnimalPortionPct: float): ...
    def setWildPlantsPortionPct(self, theWildPlantsPortionPct: float): ...
    def setPlantsPortionPct(self, thePlantsPortionPct: float): ...
    def setAnimalPortionPct(self, theAnimalPortionPct: float): ...
    def setMCalsIndividualAnnual(self, theKCaloriesIndividualAnnual: float): ...
    def setMCalsSettlementAnnual(self, theMCaloriesSettlementAnnua: float): ...
    def setDairySurplusMCalories(self, theDairySurplusMCalories: float): ...
    def setCropCalcsReportMap(self, theCropCalcsReportMap: La.LaReportMap): ...
    def setAnimalCalcsReportMap(self, theAnimalCalcsReportMap: La.LaReportMap): ...