from typing import Any, Optional

class LaGuid:
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def __copy__(self) -> 'LaGuid': ...
    def __deepcopy__(self, memo: Any) -> 'LaGuid': ...
    def guid(self) -> str: ...
    def setGuid(self, theGuid: Optional[str]) -> None: ...