# lamodel.pyi

import logging
from typing import Dict, List, Tuple, Union, Any
from qgis.PyQt.QtCore import pyqtSignal, pyqtProperty
from qgis.PyQt.QtWidgets import QDialog, QWidget

# Assuming these types are defined/imported elsewhere in your project structure
from la.lib.laserialisable import LaSerialisable
from la.lib.laguid import LaGuid
from la.lib.ladietlabels import LaDietLabels
from la.lib.lautils import LaUtils, LaMessageBus # Assuming LaMessageBus exists
from la.lib.la import AreaUnits, Status, Priority, LandBeingGrazed, LandFound, EnergyType
# Assuming these exist for type hinting methods, replace 'Any' if concrete types are available/needed
from la.lib.laanimal import LaAnimal
from la.lib.laanimalparameter import LaAnimalParameter
from la.lib.lacrop import LaCrop
from la.lib.lacropparameter import LaCropParameter

MESSAGE_BUS: LaMessageBus = ...

class LaModel(QDialog, LaSerialisable, LaGuid):
    # Signals
    _animalsChanged: pyqtSignal = ...
    _areaUnitsChanged: pyqtSignal = ...
    _baseOnPlantsChanged: pyqtSignal = ...
    _caloriesPerPersonDailyChanged: pyqtSignal = ...
    _commonLandAreaUnitsChanged: pyqtSignal = ...
    _commonLandValueChanged: pyqtSignal = ...
    _specificLandAreaUnitsChanged: pyqtSignal = ...
    _specificLandEnergyTypeChanged: pyqtSignal = ...
    _cropsChanged: pyqtSignal = ...
    _dairyUtilisationChanged: pyqtSignal = ...
    _descriptionChanged: pyqtSignal = ...
    _dietLabelsChanged: pyqtSignal = ...
    _dietPercentChanged: pyqtSignal = ...
    _dietsChanged: pyqtSignal = ...
    _eastingChanged: pyqtSignal = ...
    _euclideanDistanceChanged: pyqtSignal = ...
    _fallowRatioChanged: pyqtSignal = ...
    _fallowStatusChanged: pyqtSignal = ...
    _guidChanged: pyqtSignal = ...
    _herdSizeChanged: pyqtSignal = ...
    _iconChanged: pyqtSignal = ...
    _includeDairyChanged: pyqtSignal = ...
    _landBeingGrazedChanged: pyqtSignal = ...
    _landFoundChanged: pyqtSignal = ...
    _limitDairyChanged: pyqtSignal = ...
    _limitDairyPercentChanged: pyqtSignal = ...
    _meatPercentChanged: pyqtSignal = ...
    _nameChanged: pyqtSignal = ...
    _northingChanged: pyqtSignal = ...
    _pathDistanceChanged: pyqtSignal = ...
    _percentOfDietThatIsFromCropsChanged: pyqtSignal = ...
    _periodChanged: pyqtSignal = ...
    _populationChanged: pyqtSignal = ...
    _precisionChanged: pyqtSignal = ...
    _priorityChanged: pyqtSignal = ...
    _projectionChanged: pyqtSignal = ...
    _statusChanged: pyqtSignal = ...
    _walkingTimeChanged: pyqtSignal = ...
    _dairyMCaloriesChanged: pyqtSignal = ...
    _cropMCaloriesChanged: pyqtSignal = ...
    _animalMCaloriesChanged: pyqtSignal = ...
    _wildAnimalMCaloriesChanged: pyqtSignal = ...
    _wildPlantsMCaloriesChanged: pyqtSignal = ...
    _dairyPortionPctChanged: pyqtSignal = ...
    _tameMeatPortionPctChanged: pyqtSignal = ...
    _cropsPortionPctChanged: pyqtSignal = ...
    _wildAnimalPortionPctChanged: pyqtSignal = ...
    _wildPlantsPortionPctChanged: pyqtSignal = ...
    _animalPortionPctChanged: pyqtSignal = ...
    _plantsPortionPctChanged: pyqtSignal = ...
    _kiloCaloriesIndividualAnnualChanged: pyqtSignal = ...
    _megaCaloriesSettlementAnnualChanged: pyqtSignal = ...
    _dairySurplusMCaloriesChanged: pyqtSignal = ...
    _cropCalcsReportMapChanged: pyqtSignal = ... # pyqtSignal(dict) # Use pyqtSignal() if type checking dict fails
    _animalCalcsReportMapChanged: pyqtSignal = ... # pyqtSignal(dict) # Use pyqtSignal() if type checking dict fails
    _logCalculationStep: pyqtSignal = ... # pyqtSignal(str)

    # Instance Attributes (based on __init__ and properties)
    mName: str = ...
    mPopulation: int = ...
    mPeriod: str = ...
    mProjection: int = ...
    mPrecision: int = ...
    mDietPercent: int = ...
    mPercentOfDietThatIsFromCrops: int = ...
    mMeatPercent: int = ...
    mCaloriesPerPersonDaily: int = ...
    mDairyUtilisation: int = ...
    mBaseOnPlants: bool = ...
    mIncludeDairy: bool = ...
    mLimitDairy: bool = ...
    mLimitDairyPercent: int = ...
    mFallowStatus: Status = ...
    mFallowRatio: int = ...
    mEasting: int = ...
    mNorthing: int = ...
    mEuclideanDistance: bool = ...
    mWalkingTime: bool = ...
    mPathDistance: bool = ...
    mLandBeingGrazed: LandBeingGrazed = ...
    mLandFound: LandFound = ...
    mCommonLandValue: float = ...
    mCommonLandAreaUnits: AreaUnits = ...
    mSpecificLandAreaUnits: AreaUnits = ...
    mSpecificLandEnergyType: EnergyType = ...
    mHerdSize: int = ...
    mAnimals: Dict[str, str] = ...
    mCrops: Dict[str, str] = ...
    mDiets: Dict[str, LaDietLabels] = ...
    mDietLabels: List[LaDietLabels] = ...
    mPriority: Priority = ...
    mDescription: str = ...
    mAreaUnits: AreaUnits = ...
    mStatus: Status = ...
    mIcon: Any | None = ... # Type unclear from code
    _mValueMap: Dict[str, float] = ...
    logger: logging.Logger = ...
    # Attributes populated by setters
    dairyMCalories: float = ...
    cropMCalories: float = ...
    animalMCalories: float = ...
    wildAnimalMCalories: float = ...
    wildPlantsMCalories: float = ...
    dairyPortionPct: float = ...
    tameMeatPortionPct: float = ...
    cropsPortionPct: float = ...
    wildAnimalPortionPct: float = ...
    wildPlantsPortionPct: float = ...
    animalPortionPct: float = ...
    plantsPortionPct: float = ...
    kiloCaloriesIndividualAnnual: float = ...
    megaCaloriesSettlementAnnual: float = ...
    dairySurplusMCalories: float = ...

    def __init__(self, parent: QWidget | None = None, theModel: LaModel | None = None) -> None: ...
    def logMessage(self, theMessage: str) -> None: ...
    # def __del__(self) -> None: ... # Not typically needed in stubs
    def __copy__(self) -> LaModel: ...
    def __deepcopy__(self, memo: Any) -> LaModel: ...

    # Properties
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, theName: str) -> None: ...

    @property
    def population(self) -> int: ...
    @population.setter
    def population(self, thePopulation: int) -> None: ...

    @property
    def period(self) -> str: ...
    @period.setter
    def period(self, thePeriod: str) -> None: ...

    @property
    def projection(self) -> int: ...
    @projection.setter
    def projection(self, theProjection: int) -> None: ...

    @property
    def precision(self) -> int: ...
    @precision.setter
    def precision(self, thePrecision: int) -> None: ...

    @property
    def dietPercent(self) -> int: ...
    @dietPercent.setter
    def dietPercent(self, theDietPercent: int) -> None: ...

    @property
    def percentOfDietThatIsFromCrops(self) -> int: ...
    @percentOfDietThatIsFromCrops.setter
    def percentOfDietThatIsFromCrops(self, thePercent: int) -> None: ...

    @property
    def meatPercent(self) -> int: ...
    @meatPercent.setter
    def meatPercent(self, theMeatPercent: int) -> None: ...

    @property
    def caloriesPerPersonDaily(self) -> int: ...
    @caloriesPerPersonDaily.setter
    def caloriesPerPersonDaily(self, theCaloriesPerPersonDaily: int) -> None: ...

    @property
    def dairyUtilisation(self) -> int: ...
    @dairyUtilisation.setter
    def dairyUtilisation(self, thePercent: Union[int, float, str]) -> None: ...

    @property
    def baseOnPlants(self) -> bool: ...
    @baseOnPlants.setter
    def baseOnPlants(self, theBool: bool) -> None: ...

    @property
    def includeDairy(self) -> bool: ...
    @includeDairy.setter
    def includeDairy(self, theBool: bool) -> None: ...

    @property
    def limitDairy(self) -> bool: ...
    @limitDairy.setter
    def limitDairy(self, theBool: bool) -> None: ...

    @property
    def limitDairyPercent(self) -> int: ...
    @limitDairyPercent.setter
    def limitDairyPercent(self, thePercent: int) -> None: ...

    @property # Note: Property type hint is str, return is Status
    def fallowStatus(self) -> Status: ...
    @fallowStatus.setter
    def fallowStatus(self, theStatus: Status) -> None: ...

    @property
    def fallowRatio(self) -> int: ...
    @fallowRatio.setter
    def fallowRatio(self, theRatio: int) -> None: ...

    @property
    def easting(self) -> int: ...
    @easting.setter
    def easting(self, theEasting: int) -> None: ...

    @property
    def northing(self) -> int: ...
    @northing.setter
    def northing(self, theNorthing: int) -> None: ...

    @property
    def euclideanDistance(self) -> bool: ...
    @euclideanDistance.setter
    def euclideanDistance(self, theBool: bool) -> None: ...

    @property
    def walkingTime(self) -> bool: ...
    @walkingTime.setter
    def walkingTime(self, theBool: bool) -> None: ...

    @property
    def pathDistance(self) -> bool: ...
    @pathDistance.setter
    def pathDistance(self, theBool: bool) -> None: ...

    @property
    def commonLandValue(self) -> float: ...
    @commonLandValue.setter
    def commonLandValue(self, theValue: float) -> None: ...

    @property
    def commonLandAreaUnits(self) -> AreaUnits: ...
    @commonLandAreaUnits.setter
    def commonLandAreaUnits(self, theAreaUnits: AreaUnits) -> None: ...

    @property
    def specificLandAreaUnits(self) -> AreaUnits: ...
    @specificLandAreaUnits.setter
    def specificLandAreaUnits(self, theAreaUnits: AreaUnits) -> None: ...

    @property
    def specificLandEnergyType(self) -> EnergyType: ...
    @specificLandEnergyType.setter
    def specificLandEnergyType(self, theEnergyType: EnergyType) -> None: ...

    @property
    def herdSize(self) -> int: ...
    @herdSize.setter
    def herdSize(self, theAnimalGuid: str) -> None: ... # Type hint based on C++ usage? Check if correct

    @property # Note: Property type hint is str, return is Dict
    def animals(self) -> Dict[str, str]: ...
    @animals.setter
    def animals(self, theAnimals: Dict[str, str]) -> None: ...

    @property # Note: Property type hint is str, return is Dict
    def crops(self) -> Dict[str, str]: ...
    @crops.setter
    def crops(self, theCrops: Dict[str, str]) -> None: ...

    @property # Note: Property type hint is str, return is Dict
    def diets(self) -> Dict[str, LaDietLabels]: ...
    @diets.setter
    def diets(self, theDiets: Dict[str, LaDietLabels]) -> None: ...

    @property # Note: Property type hint is str, return is List
    def dietLabels(self) -> List[LaDietLabels]: ...
    @dietLabels.setter
    def dietLabels(self, theDietLabels: List[LaDietLabels]) -> None: ...

    @property # Note: Property type hint is str, return is Enum
    def landBeingGrazed(self) -> LandBeingGrazed: ...
    @landBeingGrazed.setter
    def landBeingGrazed(self, theLandBeingGrazed: LandBeingGrazed) -> None: ...

    @property # Note: Property type hint is str, return is Enum
    def landFound(self) -> LandFound: ...
    @landFound.setter
    def landFound(self, theLandFound: LandFound) -> None: ...

    @property # Note: Property type hint is str, return is Enum
    def priority(self) -> Priority: ...
    @priority.setter
    def priority(self, thePriority: Priority) -> None: ...

    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, theDescription: str) -> None: ...

    @property # Note: Property type hint is str, return is Enum
    def areaUnits(self) -> AreaUnits: ...
    @areaUnits.setter
    def areaUnits(self, theAreaUnits: AreaUnits) -> None: ...

    @property # Note: Property type hint is str, return is Enum
    def status(self) -> Status: ...
    @status.setter
    def status(self, theStatus: Status) -> None: ...

    # Regular property for GUID (from LaGuid base potentially)
    @property
    def guid(self) -> str: ...
    @guid.setter
    def guid(self, theGuid: str) -> None: ...

    # Methods
    def requiredValue(self, theAnimalGuid: str) -> float: ...
    def fromXml(self, theXml: str) -> bool: ... # Corrected based on code
    def toXml(self) -> str: ...
    def _GetAnimalValue(self, animal: Any, prop_name: str) -> float: ... # Use specific type if known e.g. LaAnimal
    def _GetAnimalParamValue(self, theParam: Any, thePropName: str) -> float: ... # Use specific type if known e.g. LaAnimalParameter

    # Setters for calculated values
    def setDairyMCalories(self, value: float) -> None: ...
    def setCropMCalories(self, value: float) -> None: ...
    def setAnimalMCalories(self, value: float) -> None: ...
    def setWildAnimalMCalories(self, value: float) -> None: ...
    def setWildPlantsMCalories(self, value: float) -> None: ...
    def setDairyPortionPct(self, value: float) -> None: ...
    def setTameMeatPortionPct(self, value: float) -> None: ...
    def setCropsPortionPct(self, value: float) -> None: ...
    def setWildAnimalPortionPct(self, value: float) -> None: ...
    def setWildPlantsPortionPct(self, value: float) -> None: ...
    def setAnimalPortionPct(self, value: float) -> None: ...
    def setPlantsPortionPct(self, value: float) -> None: ...
    def setKiloCaloriesIndividualAnnual(self, value: float) -> None: ...
    def setMegaCaloriesSettlementAnnual(self, value: float) -> None: ...
    def setDairySurplusMCalories(self, value: float) -> None: ...

    def _setDietLabels(
        self,
        theDietLabels: LaDietLabels,
        theOverallDairyMCals: float,
        theOverallCropsMCals: float,
        theOverallMeatMCals: float,
        theOverallWildMeatMCals: float,
        theOverallWildPlantsMCals: float,
        theOverallDairyPercent: float,
        theDomesticMeatPercent: float,
        theOverallCropPercent: float,
        theWildMeatPercent: float,
        theOverallWildPlantPercent: float,
        theOverallMeatPercent: float,
        theOverallPlantPercent: float,
        theMCalsIndividualAnnual: float,
        theMCalsSettlementAnnual: float,
        theOverallDairySurplusMCals: float,
        theCropCalcsReportMap: Dict[str, Tuple[str, float]],
        theAnimalCalcsReportMap: Dict[str, Tuple[str, float]],
    ) -> None: ...

    # Calculation Methods
    def doCalcsPlantsFirstIncludeDairy(self) -> LaDietLabels: ...
    def doCalcsPlantsFirstDairySeparate(self) -> LaDietLabels: ...
    def doCalcsAnimalsFirstIncludeDairy(self) -> LaDietLabels: ...
    def doCalcsAnimalsFirstDairySeparate(self) -> LaDietLabels: ...

    def toHtml(self) -> str: ...

    # Fallow Allocation Methods
    def allocateFallowGrazingLand(self, theFallowMCalsAvailable: float, theAnimalMCalRequirementMap: Dict[str, float]) -> None: ...
    def doTheFallowAllocation(self, thePriority: Priority, theAvailableFallowValue: float, theAnimalMCalRequirementMap: Dict[str, float]) -> float: ...