Landuse Analyst: LaCropParameter Class Reference
LaCropParameter Class Reference
#include <lacropparameter.h>
Public Member Functions
LaCropParameter ()
~LaCropParameter ()
LaCropParameter (const LaCropParameter &theCropParameter)
LaCropParameter & operator= (const LaCropParameter &theCropParameter)
QString name () const
QString description () const
QString cropGuid () const
float percentTameCrop () const
bool cropRotation () const
float fallowRatio () const
int fallowValue () const
AreaUnits areaUnits () const
bool useCommonLand () const
bool useSpecificLand () const
QString rasterName () const
void setName (QString theName)
void setDescription (QString theDescription)
void setCropGuid (QString theGuid)
void setPercentTameCrop (float thePercentage)
void setCropRotation (bool theFlag)
void setFallowRatio (float theRatio)
void setFallowValue (int theKg)
void setAreaUnits (AreaUnits theAreaUnit)
void setUseCommonLand (bool theBool)
void setUseSpecificLand (bool theBool)
void setRasterName (QString theRasterName)
QString toXml ()
QString toText ()
QString toHtml ()
bool fromXml (const QString theXml)
Private Attributes
QString mName
QString mDescription
QString mCropGuid
float mPercentTameCrop
bool mCropRotation
float mFallowRatio
int mFallowValue
AreaUnits mAreaUnits
bool mUseCommonLand
bool mUseSpecificLand
QString mRasterName
Detailed Description
A class to represent a crop
Author:
Tim Sutton, Jason Jorgenson
Definition at line 31 of file lacropparameter.h.
Constructor & Destructor Documentation
LaCropParameter::LaCropParameter ()
Constructor .
Definition at line 23 of file lacropparameter.cpp.
References mDescription, mName, and LaGuid::setGuid().
                                 : LaSerialisable(), LaGuid()
{
  setGuid();
  mName="No Name Set";
  mDescription="Not Set";
    //mCropYield=60;
    //mCropCalories=3000;
    //mCropFodderProduction=50;
    //mCropFodderValue=1000;
    //mYieldUnits=0;
}
LaCropParameter::~LaCropParameter ()
Desctructor .
Definition at line 34 of file lacropparameter.cpp.
{
}
LaCropParameter::LaCropParameter (const LaCropParameter & theCropParameter)
copy constructor
Definition at line 40 of file lacropparameter.cpp.
References areaUnits(), cropGuid(), cropRotation(), description(), fallowRatio(), fallowValue(), LaGuid::guid(), mAreaUnits, mCropRotation, mDescription, mFallowRatio, mFallowValue, mName, mPercentTameCrop, mRasterName, mUseCommonLand, mUseSpecificLand, name(), percentTameCrop(), rasterName(), setCropGuid(), LaGuid::setGuid(), useCommonLand(), and useSpecificLand().
{
  mName=theCropParameter.name();
  mDescription=theCropParameter.description();
  setGuid(theCropParameter.guid());
  setCropGuid(theCropParameter.cropGuid());
  mPercentTameCrop=theCropParameter.percentTameCrop();
  mCropRotation = theCropParameter.cropRotation();
  mFallowRatio = theCropParameter.fallowRatio();
  mFallowValue = theCropParameter.fallowValue();
  mAreaUnits = theCropParameter.areaUnits();
  mUseCommonLand = theCropParameter.useCommonLand();
  mUseSpecificLand = theCropParameter.useSpecificLand();
  mRasterName = theCropParameter.rasterName();
}
Member Function Documentation
LaCropParameter & LaCropParameter::operator= (const LaCropParameter & theCropParameter)
Assignement operator
Definition at line 56 of file lacropparameter.cpp.
References areaUnits(), cropGuid(), cropRotation(), description(), fallowRatio(), fallowValue(), LaGuid::guid(), mAreaUnits, mCropRotation, mDescription, mFallowRatio, mFallowValue, mName, mPercentTameCrop, mRasterName, mUseCommonLand, mUseSpecificLand, name(), percentTameCrop(), rasterName(), setCropGuid(), LaGuid::setGuid(), useCommonLand(), and useSpecificLand().
{
  if (this == &theCropParameter) return *this;     // Gracefully handle self assignment
  mName=theCropParameter.name();
  mDescription=theCropParameter.description();
  setGuid(theCropParameter.guid());
  setCropGuid(theCropParameter.cropGuid());
  mPercentTameCrop=theCropParameter.percentTameCrop();
  mCropRotation = theCropParameter.cropRotation();
  mFallowRatio = theCropParameter.fallowRatio();
  mFallowValue = theCropParameter.fallowValue();
  mAreaUnits = theCropParameter.areaUnits();
  mUseCommonLand = theCropParameter.useCommonLand();
  mUseSpecificLand = theCropParameter.useSpecificLand();
  mRasterName = theCropParameter.rasterName();
  return *this;
}
QString LaCropParameter::name () const
Get the name for this set of crop model parameters
Definition at line 75 of file lacropparameter.cpp.
References mName.
Referenced by LaUtils::getAvailableCropParameters(), LaUtils::getCropParameter(), LaCropParameter(), LaMainForm::loadCrops(), LaCropParameterManager::on_toolCopy_clicked(), operator=(), LaCropParameterManager::refreshCropParameterTable(), LaCropParameterManager::selectCropParameter(), and LaCropParameterManager::showCropParameter().
{
  return mName;
}
QString LaCropParameter::description () const
Set the description for this set of crop model parameters
Definition at line 80 of file lacropparameter.cpp.
References mDescription.
Referenced by LaCropParameter(), LaMainForm::loadCrops(), operator=(), LaCropParameterManager::refreshCropParameterTable(), and LaCropParameterManager::showCropParameter().
{
  return mDescription;
}
QString LaCropParameter::cropGuid () const
Get the guid of the crop this set of params is associated with
Definition at line 85 of file lacropparameter.cpp.
References mCropGuid.
Referenced by LaCropParameter(), LaMainForm::loadCrops(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mCropGuid;
}
float LaCropParameter::percentTameCrop () const
Portion of the Tame Crop Diet (Percentage)
Definition at line 90 of file lacropparameter.cpp.
References mPercentTameCrop.
Referenced by LaModel::allocateFallowGrazingLand(), LaCropParameter(), LaMainForm::loadCrops(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mPercentTameCrop;
}
bool LaCropParameter::cropRotation () const
Flag for determining use of crop rotation
Definition at line 94 of file lacropparameter.cpp.
References mCropRotation.
Referenced by LaCropParameter(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mCropRotation;
}
float LaCropParameter::fallowRatio () const
The ratio of crop to fallow land
Definition at line 98 of file lacropparameter.cpp.
References mFallowRatio.
Referenced by LaModel::allocateFallowGrazingLand(), LaCropParameter(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mFallowRatio;
}
int LaCropParameter::fallowValue () const
The food value, in calories, of a dunum/hectare of fallow land
Definition at line 102 of file lacropparameter.cpp.
References mFallowValue.
Referenced by LaModel::allocateFallowGrazingLand(), LaCropParameter(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mFallowValue;
}
AreaUnits LaCropParameter::areaUnits () const
Selects 0==dunums 1==hectares as units for area
Definition at line 106 of file lacropparameter.cpp.
References mAreaUnits.
Referenced by LaModel::allocateFallowGrazingLand(), LaCropParameter(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mAreaUnits;
}
bool LaCropParameter::useCommonLand () const
A flag indicating that the crop can be grown on land that is also suitable for other crops
Definition at line 110 of file lacropparameter.cpp.
References mUseCommonLand.
Referenced by LaGrassProcess::accept(), LaCropParameter(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mUseCommonLand;
}
bool LaCropParameter::useSpecificLand () const
A flag indicating that the crop requires specific land apart from common agricultural land
Definition at line 114 of file lacropparameter.cpp.
References mUseSpecificLand.
Referenced by LaCropParameter(), operator=(), and LaCropParameterManager::showCropParameter().
{
  return mUseSpecificLand;
}
QString LaCropParameter::rasterName () const
Definition at line 118 of file lacropparameter.cpp.
References mRasterName.
Referenced by LaGrassProcess::accept(), LaCropParameter(), and operator=().
{
  return mRasterName;
}
void LaCropParameter::setName (QString theName)
Set the name for this set of crop model parameters
Definition at line 123 of file lacropparameter.cpp.
References mName.
Referenced by LaCropParameterManager::on_pbnApply_clicked(), and LaCropParameterManager::on_toolCopy_clicked().
{
  mName=theName;
}
void LaCropParameter::setDescription (QString theDescription)
Set the description for this set of crop model parameters
Definition at line 127 of file lacropparameter.cpp.
References mDescription.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mDescription=theDescription;
}
void LaCropParameter::setCropGuid (QString theGuid)
Set the guid of the crop this set of params is associated with
Definition at line 132 of file lacropparameter.cpp.
References mCropGuid.
Referenced by LaCropParameter(), LaCropParameterManager::on_pbnApply_clicked(), and operator=().
{
  mCropGuid = theGuid;
}
void LaCropParameter::setPercentTameCrop (float thePercentage)
Portion of the Tame Crop Diet (Percentage)
Definition at line 137 of file lacropparameter.cpp.
References mPercentTameCrop.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mPercentTameCrop=thePercentage;
}
void LaCropParameter::setCropRotation (bool theFlag)
Flag for determining use of crop rotation
Definition at line 141 of file lacropparameter.cpp.
References mCropRotation.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mCropRotation=theFlag;
}
void LaCropParameter::setFallowRatio (float theRatio)
The ratio of crop to fallow land
Definition at line 145 of file lacropparameter.cpp.
References mFallowRatio.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mFallowRatio=theFallowRatio;
}
void LaCropParameter::setFallowValue (int theKg)
The food value, in calories, of a dunum/hectare of fallow land
Definition at line 149 of file lacropparameter.cpp.
References mFallowValue.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mFallowValue=theKg;
}
void LaCropParameter::setAreaUnits (AreaUnits theAreaUnit)
Selects 0==dunums 1==hectares as units for area
Definition at line 153 of file lacropparameter.cpp.
References mAreaUnits.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mAreaUnits=theAreaUnit;
}
void LaCropParameter::setUseCommonLand (bool theBool)
A flag indicating that the crop can be grown on land that is also suitable for other crops
Definition at line 161 of file lacropparameter.cpp.
References mUseCommonLand.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mUseCommonLand=theFlag;
}
void LaCropParameter::setUseSpecificLand (bool theBool)
A flag indicating that the crop requires specific land apart from common agricultural land
Definition at line 157 of file lacropparameter.cpp.
References mUseSpecificLand.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mUseSpecificLand=theFlag;
}
void LaCropParameter::setRasterName (QString theRasterName)
Definition at line 166 of file lacropparameter.cpp.
References mRasterName.
Referenced by LaCropParameterManager::on_pbnApply_clicked().
{
  mRasterName=theRasterName;
}
QString LaCropParameter::toXml () [virtual]
Return an xml representation of this layer this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 209 of file lacropparameter.cpp.
References LaGuid::guid(), mAreaUnits, mCropGuid, mCropRotation, mDescription, mFallowRatio, mFallowValue, mName, mPercentTameCrop, mRasterName, mUseCommonLand, mUseSpecificLand, and LaUtils::xmlEncode().
{
  QString myString;
  QString myUnits = (mAreaUnits==0) ? "Dunum" : "Hectare";
  myString+=QString("<cropParameter guid=\"" + guid() + "\">\n");
  myString+=QString("  <name>" + LaUtils::xmlEncode(mName) + "</name>\n");
  myString+=QString("  <description>" + LaUtils::xmlEncode(mDescription) + "</description>\n");
  myString+=QString("  <crop>" + LaUtils::xmlEncode(mCropGuid) + "</crop>\n");
  myString+=QString("  <percentTameCrop>" + QString::number(mPercentTameCrop) + "</percentTameCrop>\n");
  myString+=QString("  <cropRotation>" + QString::number(mCropRotation) + "</cropRotation>\n");
  myString+=QString("  <fallowRatio>" + QString::number(mFallowRatio) + "</fallowRatio>\n");
  myString+=QString("  <fallowValue>" + QString::number(mFallowValue) + "</fallowValue>\n");
  myString+=QString("  <areaUnits>" + myUnits + "</areaUnits>\n");
  myString+=QString("  <useCommonLand>" + QString::number(mUseCommonLand) + "</useCommonLand>\n");
  myString+=QString("  <useSpecificLand>" + QString::number(mUseSpecificLand) + "</useSpecificLand>\n");
  myString+=QString("  <rasterName>" + LaUtils::xmlEncode(mRasterName) + "</rasterName>\n");
  myString+=QString("</cropParameter>\n");
  return myString;
}
QString LaCropParameter::toText ()
Return a plain text representation of this layer
Definition at line 229 of file lacropparameter.cpp.
References LaGuid::guid(), mAreaUnits, mCropGuid, mCropRotation, mDescription, mFallowRatio, mFallowValue, mName, mPercentTameCrop, mRasterName, mUseCommonLand, and LaUtils::xmlEncode().
{
  QString myString;
  myString+=QString("guid=>" + guid() + "\n");
  myString+=QString("name=>" + LaUtils::xmlEncode(mName) + "\n");
  myString+=QString("description=>" + LaUtils::xmlEncode(mDescription) + "\n");
  myString+=QString("crop=>" + mCropGuid + "\n");
  myString+=QString("percentTameCrop=>" + QString::number(mPercentTameCrop) + "\n");
  QString myCropRotation = (mCropRotation==0) ? "None" : "Used";
  myString+=QString("cropRotation=>" + myCropRotation + "\n");
  myString+=QString("fallowRatio=>" + QString::number(mFallowRatio) + "\n");
  QString myUnits = (mAreaUnits==0) ? "Dunum" : "Hectare";
  myString+=QString("fallowValue kg/" + myUnits + "=>" + QString::number(mFallowValue) + "\n");
    //myString+=QString("areaUnits=>" + QString::number(mAreaUnits) + "\n");
  QString myLandUsed = (mUseCommonLand==1) ? "Common" : "Specific";
  myString+=QString("Landused=>" + myLandUsed + "\n");
    //myString+=QString("useSpecificLand=>" + QString::number(mUseSpecificLand) + "\n");
  myString+=QString("rasterName=>" + LaUtils::xmlEncode(mRasterName) + "\n");
  return myString;
}
QString LaCropParameter::toHtml ()
Return a html text representation of this layer
Definition at line 251 of file lacropparameter.cpp.
References mAreaUnits, mCropRotation, mDescription, mFallowRatio, mFallowValue, mName, mPercentTameCrop, mRasterName, mUseCommonLand, and LaUtils::xmlEncode().
Referenced by LaMainForm::showCropDefinitionReport(), and LaModel::toHtml().
{
  QString myString;
  QString myCropRotation = (mCropRotation==0) ? "None" : "Used";
  QString myUnits = (mAreaUnits==0) ? "Dunum" : "Hectare";
  QString myLandUsed = (mUseCommonLand==1) ? "Common" : "Specific";
  QString myRasterName = (mUseCommonLand==1) ? "LaCropCommonMask" : mRasterName;
  myString+="<h3 >Details for " + LaUtils::xmlEncode(mName) + "</h3>";
  myString+="<table>";    //  myString+="<tr><td><b>GUID:</th><td>" + guid() + "</td></tr>";
  myString+="<tr><td><b>Description: </b></td><td>" + mDescription + "</td></tr>";
  myString+="<tr><td><b>Raster Mask: </b></td><td>" + mRasterName + "</td></tr>";
  myString+="<tr><td><b>Percent Tame Crop Diet: </b></td><td>" + QString::number(mPercentTameCrop) + "</td></tr>";
  myString+="<tr><td><b>cropRotation: </b></td><td>" + myCropRotation + "</td></tr>";
  myString+="<tr><td><b>fallowRatio: </b></th><td>" + QString::number(mFallowRatio) + "</td></tr>";
  myString+="<tr><td><b>Fallow Value kg/" + myUnits + ": </b></td><td>" + QString::number(mFallowValue) + "</td></tr>";
  myString+=("<tr><td><b>" + myLandUsed + " Land Raster: </b></td><td>" + myRasterName + "</td></tr>");
  myString+="</table>";
  return myString;
}
bool LaCropParameter::fromXml (const QString theXml) [virtual]
Read this object from xml and return result as true for success, false for failure.
See also:
LaSerialisable this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 171 of file lacropparameter.cpp.
References Dunum, Hectare, mAreaUnits, mCropGuid, mCropRotation, mDescription, mFallowRatio, mFallowValue, mName, mPercentTameCrop, mRasterName, mUseCommonLand, mUseSpecificLand, LaGuid::setGuid(), and LaUtils::xmlDecode().
{
    //qDebug("Loading CropParameter from xml");
  QDomDocument myDocument("mydocument");
  myDocument.setContent(theXml);
  QDomElement myTopElement = myDocument.firstChildElement("cropParameter");
  if (myTopElement.isNull())
  {
      //TODO - just make this a warning
     //qDebug("top element could not be found!");
  }
    //qDebug("CropParameter::fromXml - guid found : " + myTopElement.attribute("guid").toLocal8Bit());
  setGuid(myTopElement.attribute("guid"));
    //qDebug("CropParameter::fromXml - guid set to : " + guid().toLocal8Bit());
  mName=LaUtils::xmlDecode(myTopElement.firstChildElement("name").text());
  mDescription=LaUtils::xmlDecode(myTopElement.firstChildElement("description").text());
  mCropGuid=LaUtils::xmlDecode(myTopElement.firstChildElement("crop").text());
  mPercentTameCrop=QString(myTopElement.firstChildElement("percentTameCrop").text()).toFloat();
  mCropRotation=QString(myTopElement.firstChildElement("cropRotation").text()).toInt();
  mFallowRatio=QString(myTopElement.firstChildElement("fallowRatio").text()).toFloat();
  mFallowValue=QString(myTopElement.firstChildElement("fallowValue").text()).toInt();
  QString myAreaUnits = QString(myTopElement.firstChildElement("areaUnits").text());
  if (myAreaUnits == "Dunum")
  {
    mAreaUnits=Dunum;
  }
  else if (myAreaUnits == "Hectare")
  {
    mAreaUnits=Hectare;
  }
    //mAreaUnits=QString(myTopElement.firstChildElement("areaUnits").text()).toInt();
  mUseCommonLand=QString(myTopElement.firstChildElement("useCommonLand").text()).toInt();
  mUseSpecificLand=QString(myTopElement.firstChildElement("useSpecificLand").text()).toInt();
  mRasterName=LaUtils::xmlDecode(myTopElement.firstChildElement("rasterName").text());
  return true;
}
Member Data Documentation
QString LaCropParameter::mName [private]
The name for this crop paremeter
Definition at line 127 of file lacropparameter.h.
Referenced by fromXml(), LaCropParameter(), name(), operator=(), setName(), toHtml(), toText(), and toXml().
QString LaCropParameter::mDescription [private]
The description for this crop parameter
Definition at line 129 of file lacropparameter.h.
Referenced by description(), fromXml(), LaCropParameter(), operator=(), setDescription(), toHtml(), toText(), and toXml().
QString LaCropParameter::mCropGuid [private]
The crop guid these parameters are associated with
Definition at line 131 of file lacropparameter.h.
Referenced by cropGuid(), fromXml(), setCropGuid(), toText(), and toXml().
float LaCropParameter::mPercentTameCrop [private]
Portion of the Tame Crop Diet (Percentage)
Definition at line 133 of file lacropparameter.h.
Referenced by fromXml(), LaCropParameter(), operator=(), percentTameCrop(), setPercentTameCrop(), toHtml(), toText(), and toXml().
bool LaCropParameter::mCropRotation [private]
Food value of specific (or unique) land as calories per dunum/hectare
Definition at line 135 of file lacropparameter.h.
Referenced by cropRotation(), fromXml(), LaCropParameter(), operator=(), setCropRotation(), toHtml(), toText(), and toXml().
float LaCropParameter::mFallowRatio [private]
The ratio of crop to fallow land
Definition at line 137 of file lacropparameter.h.
Referenced by fallowRatio(), fromXml(), LaCropParameter(), operator=(), setFallowRatio(), toHtml(), toText(), and toXml().
int LaCropParameter::mFallowValue [private]
The food value, in calories, of a dunum/hectare of fallow land
Definition at line 141 of file lacropparameter.h.
Referenced by fallowValue(), fromXml(), LaCropParameter(), operator=(), setFallowValue(), toHtml(), toText(), and toXml().
AreaUnits LaCropParameter::mAreaUnits [private]
Selects 0==dunums 1==hectares as units for area
Definition at line 143 of file lacropparameter.h.
Referenced by areaUnits(), fromXml(), LaCropParameter(), operator=(), setAreaUnits(), toHtml(), toText(), and toXml().
bool LaCropParameter::mUseCommonLand [private]
A flag indicating that the crop can be grown on land that is also suitable for other crops
Definition at line 147 of file lacropparameter.h.
Referenced by fromXml(), LaCropParameter(), operator=(), setUseCommonLand(), toHtml(), toText(), toXml(), and useCommonLand().
bool LaCropParameter::mUseSpecificLand [private]
A flag indicating that the crop requires specific land apart from common agricultural land
Definition at line 151 of file lacropparameter.h.
Referenced by fromXml(), LaCropParameter(), operator=(), setUseSpecificLand(), toXml(), and useSpecificLand().
QString LaCropParameter::mRasterName [private]
Definition at line 152 of file lacropparameter.h.
Referenced by fromXml(), LaCropParameter(), operator=(), rasterName(), setRasterName(), toHtml(), toText(), and toXml().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/lacropparameter.h
dev/cpp/landuseanalyst/src/lib/lacropparameter.cpp