Landuse Analyst: LaAnimal Class Reference
LaAnimal Class Reference
#include <laanimal.h>
Public Member Functions
LaAnimal ()
~LaAnimal ()
LaAnimal (const LaAnimal &theAnimal)
LaAnimal & operator= (const LaAnimal &theAnimal)
QString name () const
QString description () const
int meatFoodValue () const
int usableMeat () const
int killWeight () const
int growTime () const
int deathRate () const
EnergyType feedEnergyType () const
int gestating () const
int lactating () const
int maintenance () const
int juvenile () const
int sexualMaturity () const
int breedingExpectancy () const
int youngPerBirth () const
int weaningAge () const
int weaningWeight () const
int gestationTime () const
int estrousCycle () const
int lactationTime () const
bool milk () const
int milkGramsPerDay () const
int milkFoodValue () const
bool fleece () const
int fleeceWeightKg () const
QString imageFile () const
void setName (QString theName)
void setDescription (QString theDescription)
void setMeatFoodValue (int theFoodValue)
void setUsableMeat (int thePercentage)
void setKillWeight (int theKg)
void setGrowTime (int theWeeks)
void setDeathRate (int thePercentage)
void setFeedEnergyType (EnergyType theFeedEnergyType)
void setGestating (int theCalories)
void setLactating (int theCalories)
void setMaintenance (int theCalories)
void setJuvenile (int theCalories)
void setSexualMaturity (int theMonths)
void setBreedingExpectancy (int theYears)
void setYoungPerBirth (int theInteger)
void setWeaningWeight (int theWeight)
void setWeaningAge (int theDays)
void setGestationTime (int theDays)
void setEstrousCycle (int theDays)
void setLactationTime (int theTime)
void setMilk (bool theBool)
void setMilkGramsPerDay (int theMilkGrams)
void setMilkFoodValue (int theMilkFoodValue)
void setFleece (bool theFleeceBool)
void setFleeceWeightKg (int theFleeceWeight)
void setImageFile (QString theImageFileName)
QString toXml ()
QString toText ()
QString toHtml ()
bool fromXml (const QString theXml)
Private Attributes
QString mName
QString mDescription
int mMeatFoodValue
int mUsableMeat
int mKillWeight
int mGrowTime
int mDeathRate
EnergyType mFeedEnergyType
int mGestating
int mLactating
int mMaintenance
int mJuvenile
int mSexualMaturity
int mBreedingExpectancy
int mYoungPerBirth
int mWeaningAge
int mWeaningWeight
int mGestationTime
int mEstrousCycle
int mLactationTime
bool mMilk
int mMilkGramsPerDay
int mMilkFoodValue
bool mFleece
int mFleeceWeightKg
QString mImageFile
Detailed Description
An class to represent an animal
Author:
Tim Sutton
Definition at line 31 of file laanimal.h.
Constructor & Destructor Documentation
LaAnimal::LaAnimal ()
Constructor .
Definition at line 25 of file laanimal.cpp.
References mBreedingExpectancy, mDeathRate, mDescription, mEstrousCycle, mGestationTime, mGrowTime, mKillWeight, mMeatFoodValue, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, and LaGuid::setGuid().
                   : LaSerialisable(), LaGuid()
{
  setGuid();
  mName="No Name Set";
  mDescription="Not Set";
  mMeatFoodValue=3000;
  mUsableMeat=50;
  mKillWeight=100;
  mGrowTime=10;
  mDeathRate=10;
    //mGestating=5000;//
    //mLactating=5000;
    //mJuvenile=3500;
  mSexualMaturity=18;
  mBreedingExpectancy=5;
  mYoungPerBirth=1;
  mWeaningAge=12;
  mWeaningWeight=30;
  mGestationTime=120;
  mEstrousCycle=21;
}
LaAnimal::~LaAnimal ()
Desctructor .
Definition at line 46 of file laanimal.cpp.
{
}
LaAnimal::LaAnimal (const LaAnimal & theAnimal)
copy constructor
Definition at line 52 of file laanimal.cpp.
References breedingExpectancy(), deathRate(), description(), estrousCycle(), feedEnergyType(), fleece(), fleeceWeightKg(), gestating(), gestationTime(), growTime(), LaGuid::guid(), imageFile(), juvenile(), killWeight(), lactating(), lactationTime(), maintenance(), mBreedingExpectancy, mDeathRate, mDescription, meatFoodValue(), mEstrousCycle, mFeedEnergyType, mFleece, mFleeceWeightKg, mGestating, mGestationTime, mGrowTime, milk(), milkFoodValue(), milkGramsPerDay(), mImageFile, mJuvenile, mKillWeight, mLactating, mLactationTime, mMaintenance, mMeatFoodValue, mMilk, mMilkFoodValue, mMilkGramsPerDay, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, name(), LaGuid::setGuid(), sexualMaturity(), usableMeat(), weaningAge(), weaningWeight(), and youngPerBirth().
{
  mName=theAnimal.name();
  mDescription=theAnimal.description();
  mMeatFoodValue=theAnimal.meatFoodValue();
  setGuid(theAnimal.guid());
  mUsableMeat=theAnimal.usableMeat();
  mKillWeight=theAnimal.killWeight();
  mGrowTime=theAnimal.growTime();
  mDeathRate=theAnimal.deathRate();
  mFeedEnergyType=theAnimal.feedEnergyType();
  mGestating=theAnimal.gestating();
  mLactating=theAnimal.lactating();
  mMaintenance=theAnimal.maintenance();
  mJuvenile=theAnimal.juvenile();
  mSexualMaturity=theAnimal.sexualMaturity();
  mBreedingExpectancy=theAnimal.breedingExpectancy();
  mYoungPerBirth=theAnimal.youngPerBirth();
  mWeaningAge=theAnimal.weaningAge();
  mWeaningWeight=theAnimal.weaningWeight();
  mGestationTime=theAnimal.gestationTime();
  mEstrousCycle=theAnimal.estrousCycle();
  mLactationTime=theAnimal.lactationTime();
  mMilk=theAnimal.milk();
  mMilkGramsPerDay=theAnimal.milkGramsPerDay();
  mMilkFoodValue=theAnimal.milkFoodValue();
  mFleece=theAnimal.fleece();
  mFleeceWeightKg=theAnimal.fleeceWeightKg();
  mImageFile=theAnimal.imageFile();
}
Member Function Documentation
LaAnimal & LaAnimal::operator= (const LaAnimal & theAnimal)
Assignement operator
Definition at line 83 of file laanimal.cpp.
References breedingExpectancy(), deathRate(), description(), estrousCycle(), feedEnergyType(), fleece(), fleeceWeightKg(), gestating(), gestationTime(), growTime(), LaGuid::guid(), imageFile(), juvenile(), killWeight(), lactating(), lactationTime(), maintenance(), mBreedingExpectancy, mDeathRate, mDescription, meatFoodValue(), mEstrousCycle, mFeedEnergyType, mFleece, mFleeceWeightKg, mGestating, mGestationTime, mGrowTime, milk(), milkFoodValue(), milkGramsPerDay(), mImageFile, mJuvenile, mKillWeight, mLactating, mLactationTime, mMaintenance, mMeatFoodValue, mMilk, mMilkFoodValue, mMilkGramsPerDay, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, name(), LaGuid::setGuid(), sexualMaturity(), usableMeat(), weaningAge(), weaningWeight(), and youngPerBirth().
{
  if (this == &theAnimal) return *this;     // Gracefully handle self assignment
  mName=theAnimal.name();
  mDescription=theAnimal.description();
  setGuid(theAnimal.guid());
  mMeatFoodValue=theAnimal.meatFoodValue();
  mUsableMeat=theAnimal.usableMeat();
  mKillWeight=theAnimal.killWeight();
  mGrowTime=theAnimal.growTime();
  mDeathRate=theAnimal.deathRate();
  mFeedEnergyType=theAnimal.feedEnergyType();
  mGestating=theAnimal.gestating();
  mLactating=theAnimal.lactating();
  mMaintenance=theAnimal.maintenance();
  mJuvenile=theAnimal.juvenile();
  mSexualMaturity=theAnimal.sexualMaturity();
  mBreedingExpectancy=theAnimal.breedingExpectancy();
  mYoungPerBirth=theAnimal.youngPerBirth();
  mWeaningAge=theAnimal.weaningAge();
  mWeaningWeight=theAnimal.weaningWeight();
  mGestationTime=theAnimal.gestationTime();
  mEstrousCycle=theAnimal.estrousCycle();
  mLactationTime=theAnimal.lactationTime();
  mMilk=theAnimal.milk();
  mMilkGramsPerDay=theAnimal.milkGramsPerDay();
  mMilkFoodValue=theAnimal.milkFoodValue();
  mFleece=theAnimal.fleece();
  mFleeceWeightKg=theAnimal.fleeceWeightKg();
  mImageFile=theAnimal.imageFile();
  return *this;
}
QString LaAnimal::name () const
The name of this animal
Definition at line 117 of file laanimal.cpp.
References mName.
Referenced by LaGrassProcess::accept(), LaModel::doTheFallowAllocation(), LaUtils::getAnimal(), LaUtils::getAvailableAnimals(), LaAnimal(), LaAnimalParameterManager::LaAnimalParameterManager(), LaAssemblageConversion::LaAssemblageConversion(), LaMainForm::loadAnimals(), LaAssemblageConversion::on_pbnInsert_clicked(), LaAnimalManager::on_toolCopy_clicked(), operator=(), LaAnimalManager::refreshAnimalTable(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mName;
}
QString LaAnimal::description () const
The description of this animal
Definition at line 121 of file laanimal.cpp.
References mDescription.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mDescription;
}
int LaAnimal::meatFoodValue () const
Food value of meat in calories per kh
Definition at line 125 of file laanimal.cpp.
References mMeatFoodValue.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaAnimal(), LaAssemblageConversion::on_pbnInsert_clicked(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mMeatFoodValue;
}
int LaAnimal::usableMeat () const
Percentage of animals live weight that can be utilized for meat
Definition at line 129 of file laanimal.cpp.
References mUsableMeat.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaAnimal(), LaAssemblageConversion::on_pbnInsert_clicked(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mUsableMeat;
}
int LaAnimal::killWeight () const
The weight in kg at which the animals are slaughtered
Definition at line 133 of file laanimal.cpp.
References mKillWeight.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaAnimal(), LaAssemblageConversion::on_pbnInsert_clicked(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mKillWeight;
}
int LaAnimal::growTime () const
The number of weeks from birth it takes to attain slaughtering weight
Definition at line 137 of file laanimal.cpp.
References mGrowTime.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mGrowTime;
}
int LaAnimal::deathRate () const
The percentage of babies that die before being usable as either meat or breeding
Definition at line 141 of file laanimal.cpp.
References mDeathRate.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mDeathRate;
}
EnergyType LaAnimal::feedEnergyType () const
The energy type: KCalories or TDN
Definition at line 145 of file laanimal.cpp.
References mFeedEnergyType.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
 return mFeedEnergyType;
}
int LaAnimal::gestating () const
The number of calories a gestating female requires per day
Definition at line 149 of file laanimal.cpp.
References mGestating.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mGestating;
}
int LaAnimal::lactating () const
The number of calories a lactating female requires per day
Definition at line 153 of file laanimal.cpp.
References mLactating.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mLactating;
}
int LaAnimal::maintenance () const
The number of calories adult maintenance requires per day
Definition at line 157 of file laanimal.cpp.
References mMaintenance.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mMaintenance;
}
int LaAnimal::juvenile () const
The number of calories a juvenile requires per day
Definition at line 161 of file laanimal.cpp.
References mJuvenile.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mJuvenile;
}
int LaAnimal::sexualMaturity () const
The life expectancy in years of the animal
Definition at line 165 of file laanimal.cpp.
References mSexualMaturity.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mSexualMaturity;
}
int LaAnimal::breedingExpectancy () const
The number of years a female will reliably produce offspring
Definition at line 169 of file laanimal.cpp.
References mBreedingExpectancy.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mBreedingExpectancy;
}
int LaAnimal::youngPerBirth () const
The average number of young produced per pregnancy
Definition at line 173 of file laanimal.cpp.
References mYoungPerBirth.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mYoungPerBirth;
}
int LaAnimal::weaningAge () const
The age in weeks at which babies stop suckling
Definition at line 177 of file laanimal.cpp.
References mWeaningAge.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::getAreaTargetsAnimalsMapAFID(), LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mWeaningAge;
}
int LaAnimal::weaningWeight () const
The weight when babies stop suckling
Definition at line 181 of file laanimal.cpp.
References mWeaningWeight.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mWeaningWeight;
}
int LaAnimal::gestationTime () const
The number of days required for gestation
Definition at line 185 of file laanimal.cpp.
References mGestationTime.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mGestationTime;
}
int LaAnimal::estrousCycle () const
The number of days in the female estrous cycle
Definition at line 189 of file laanimal.cpp.
References mEstrousCycle.
Referenced by LaAnimal(), operator=(), LaModel::requiredValue(), and LaAnimalManager::showAnimal().
{
  return mEstrousCycle;
}
int LaAnimal::lactationTime () const
The number of days the mothers can produce milk
Definition at line 193 of file laanimal.cpp.
References mLactationTime.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::getAreaTargetsAnimalsMapAFID(), LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
 return mLactationTime;
}
bool LaAnimal::milk () const
produces milk bool
Definition at line 198 of file laanimal.cpp.
References mMilk.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mMilk;
}
int LaAnimal::milkGramsPerDay () const
weight of milk in grams provided per day after weaning
Definition at line 202 of file laanimal.cpp.
References mMilkGramsPerDay.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::getAreaTargetsAnimalsMapAFID(), LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mMilkGramsPerDay;
}
int LaAnimal::milkFoodValue () const
value, in kcalories, of milk per Kg
Definition at line 206 of file laanimal.cpp.
References mMilkFoodValue.
Referenced by LaModel::doCalcsAnimalsFirstIncludeDiary(), LaModel::getAreaTargetsAnimalsMapAFID(), LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mMilkFoodValue;
}
bool LaAnimal::fleece () const
provides a fleece bool
Definition at line 210 of file laanimal.cpp.
References mFleece.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mFleece;
}
int LaAnimal::fleeceWeightKg () const
weight of fleece (average) per year
Definition at line 214 of file laanimal.cpp.
References mFleeceWeightKg.
Referenced by LaAnimal(), operator=(), and LaAnimalManager::showAnimal().
{
  return mFleeceWeightKg;
}
QString LaAnimal::imageFile () const
The image file associated with the animal
Definition at line 219 of file laanimal.cpp.
References mImageFile.
Referenced by LaGrassProcess::accept(), LaMainForm::animalCalcClicked(), LaMainForm::animalCellClicked(), LaAnimal(), LaAnimalParameterManager::on_cboAnimal_changed(), operator=(), and LaAnimalManager::showAnimal().
{
  return mImageFile;
}
void LaAnimal::setName (QString theName)
Set the animalName
See also:
name()
Definition at line 224 of file laanimal.cpp.
References mName.
Referenced by LaAnimalManager::on_pbnApply_clicked(), and LaAnimalManager::on_toolCopy_clicked().
{
  mName=theName;
}
void LaAnimal::setDescription (QString theDescription)
Set the animal description
See also:
description()
Definition at line 228 of file laanimal.cpp.
References mDescription.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mDescription=theDescription;
}
void LaAnimal::setMeatFoodValue (int theFoodValue)
Set meatFoodValue as calories per kg
See also:
meatFoodValue()
Definition at line 232 of file laanimal.cpp.
References mMeatFoodValue.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mMeatFoodValue=theMeatFoodValue;
}
void LaAnimal::setUsableMeat (int thePercentage)
Set useableMeat as a percentage
See also:
usableMeat()
Definition at line 236 of file laanimal.cpp.
References mUsableMeat.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  if (thePercentage > 100) {thePercentage=100;}
  if (thePercentage < 0) {thePercentage=100;}
  mUsableMeat=thePercentage;
}
void LaAnimal::setKillWeight (int theKg)
Set killWeight as kg
See also:
killWeight()
Definition at line 243 of file laanimal.cpp.
References mKillWeight.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mKillWeight=theKg;
}
void LaAnimal::setGrowTime (int theWeeks)
Set the growTime in weeks
See also:
growTime()
Definition at line 247 of file laanimal.cpp.
References mGrowTime.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mGrowTime=theWeeks;
}
void LaAnimal::setDeathRate (int thePercentage)
Set the deathRate as a percentage
See also:
deathRate()
Definition at line 251 of file laanimal.cpp.
References mDeathRate.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mDeathRate=thePercentage;
}
void LaAnimal::setFeedEnergyType (EnergyType theFeedEnergyType)
Set the daily calories required for a gestating female
See also:
feedEnergyType()
Definition at line 255 of file laanimal.cpp.
References mFeedEnergyType.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mFeedEnergyType=theEnergyType;
}
void LaAnimal::setGestating (int theCalories)
Set the daily calories required for a gestating female
See also:
gestating()
Definition at line 259 of file laanimal.cpp.
References mGestating.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mGestating=theCalories;
}
void LaAnimal::setLactating (int theCalories)
Set the daily calories required for a lactating female
See also:
lactating()
Definition at line 263 of file laanimal.cpp.
References mLactating.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mLactating=theCalories;
}
void LaAnimal::setMaintenance (int theCalories)
Set the daily calories required for adult maintenance
See also:
maintenance()
Definition at line 267 of file laanimal.cpp.
References mMaintenance.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mMaintenance=theCalories;
}
void LaAnimal::setJuvenile (int theCalories)
Set the daily calories required for a juvenile
See also:
juvenile()
Definition at line 271 of file laanimal.cpp.
References mJuvenile.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mJuvenile=theCalories;
}
void LaAnimal::setSexualMaturity (int theMonths)
Set the average lifeExpectancy in years
See also:
lifeExpectancy()
Definition at line 275 of file laanimal.cpp.
References mSexualMaturity.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mSexualMaturity=theMonths;
}
void LaAnimal::setBreedingExpectancy (int theYears)
Set the average breedingLifeExpectancy in years
See also:
breedingExpectancy()
Definition at line 279 of file laanimal.cpp.
References mBreedingExpectancy.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mBreedingExpectancy=theYears;
}
void LaAnimal::setYoungPerBirth (int theInteger)
Set the average number of youngPerBirth
See also:
youngPerBirth()
Definition at line 283 of file laanimal.cpp.
References mYoungPerBirth.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mYoungPerBirth=theInteger;
}
void LaAnimal::setWeaningWeight (int theWeight)
Set the weaningAge in weeks
See also:
weaningAge()
Definition at line 291 of file laanimal.cpp.
References mWeaningWeight.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mWeaningWeight=theWeight;
}
void LaAnimal::setWeaningAge (int theDays)
Set the weaning weight
See also:
weaningWeight()
Definition at line 287 of file laanimal.cpp.
References mWeaningAge.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mWeaningAge=theWeeks;
}
void LaAnimal::setGestationTime (int theDays)
Set the gestationTime in Days
See also:
gestationTime()
Definition at line 295 of file laanimal.cpp.
References mGestationTime.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mGestationTime=theDays;
}
void LaAnimal::setEstrousCycle (int theDays)
Set the estrousCycle in days
See also:
estrousCycle()
Definition at line 299 of file laanimal.cpp.
References mEstrousCycle.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mEstrousCycle=theDays;
}
void LaAnimal::setLactationTime (int theTime)
Set the LactationTime in days
See also:
lactationTime()
Definition at line 304 of file laanimal.cpp.
References mLactationTime.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mLactationTime = theTime;
}
void LaAnimal::setMilk (bool theBool)
Set the milk bool flag
See also:
milk()
Definition at line 309 of file laanimal.cpp.
References mMilk.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mMilk = theBool;
}
void LaAnimal::setMilkGramsPerDay (int theMilkGrams)
Set the Milk Production Per Day in grams
See also:
milkGramsPerDay()
Definition at line 313 of file laanimal.cpp.
References mMilkGramsPerDay.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mMilkGramsPerDay = theMilkGrams;
}
void LaAnimal::setMilkFoodValue (int theMilkFoodValue)
Set the food value of milk in KCals
See also:
milkFoodValue()
Definition at line 317 of file laanimal.cpp.
References mMilkFoodValue.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mMilkFoodValue = theMilkFoodValue;
}
void LaAnimal::setFleece (bool theFleeceBool)
Set the fleece bool flag
See also:
fleece()
Definition at line 321 of file laanimal.cpp.
References mFleece.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mFleece = theFleeceBool;
}
void LaAnimal::setFleeceWeightKg (int theFleeceWeight)
Set the fleece weight in Kg
See also:
fleeceWeightKg()
Definition at line 325 of file laanimal.cpp.
References mFleeceWeightKg.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mFleeceWeightKg = theFleeceWeight;
}
void LaAnimal::setImageFile (QString theImageFileName)
Set the image file
See also:
imageFile()
Definition at line 330 of file laanimal.cpp.
References mImageFile.
Referenced by LaAnimalManager::on_pbnApply_clicked().
{
  mImageFile=theImageFileName;
}
QString LaAnimal::toXml () [virtual]
Return an xml representation of this layer this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 386 of file laanimal.cpp.
References LaGuid::guid(), KCalories, mBreedingExpectancy, mDeathRate, mDescription, mEstrousCycle, mFeedEnergyType, mFleece, mFleeceWeightKg, mGestating, mGestationTime, mGrowTime, mImageFile, mJuvenile, mKillWeight, mLactating, mLactationTime, mMaintenance, mMeatFoodValue, mMilk, mMilkFoodValue, mMilkGramsPerDay, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, TDN, and LaUtils::xmlEncode().
{
  QString myString;
  myString+=QString("<animal guid=\"" + guid() + "\">\n");
  myString+=QString("  <name>" + LaUtils::xmlEncode(mName) + "</name>\n");
  myString+=QString("  <description>" + LaUtils::xmlEncode(mDescription) + "</description>\n");
  myString+=QString("  <meatFoodValue>" + QString::number(mMeatFoodValue) + "</meatFoodValue>\n");
  myString+=QString("  <usableMeat>" + QString::number(mUsableMeat) + "</usableMeat>\n");
  myString+=QString("  <killWeight>" + QString::number(mKillWeight) + "</killWeight>\n");
  myString+=QString("  <growTime>" + QString::number(mGrowTime) + "</growTime>\n");
  myString+=QString("  <deathRate>" + QString::number(mDeathRate) + "</deathRate>\n");
  switch (mFeedEnergyType)
  {
    case KCalories:
      myString+=QString("  <feedEnergyType>KCalories</feedEnergyType>\n");
      break;
    case TDN:
      myString+=QString("  <feedEnergyType>TDN</feedEnergyType>\n");
      break;
  }
  myString+=QString("  <gestating>" + QString::number(mGestating) + "</gestating>\n");
  myString+=QString("  <lactating>" + QString::number(mLactating) + "</lactating>\n");
  myString+=QString("  <maintenance>" + QString::number(mMaintenance) + "</maintenance>\n");
  myString+=QString("  <juvenile>" + QString::number(mJuvenile) + "</juvenile>\n");
  myString+=QString("  <sexualMaturity>" + QString::number(mSexualMaturity) + "</sexualMaturity>\n");
  myString+=QString("  <breedingExpectancy>" + QString::number(mBreedingExpectancy) + "</breedingExpectancy>\n");
  myString+=QString("  <youngPerBirth>" + QString::number(mYoungPerBirth) + "</youngPerBirth>\n");
  myString+=QString("  <weaningAge>" + QString::number(mWeaningAge) + "</weaningAge>\n");
  myString+=QString("  <weaningWeight>" + QString::number(mWeaningWeight) + "</weaningWeight>\n");
  myString+=QString("  <gestationTime>" + QString::number(mGestationTime) + "</gestationTime>\n");
  myString+=QString("  <estrousCycle>" + QString::number(mEstrousCycle) + "</estrousCycle>\n");
  myString+=QString("  <lactationTime>" + QString::number(mLactationTime) + "</lactationTime>\n");
  myString+=QString("  <milk>" + QString::number(mMilk) + "</milk>\n");
  myString+=QString("  <milkGramsPerDay>" + QString::number(mMilkGramsPerDay) + "</milkGramsPerDay>\n");
  myString+=QString("  <milkFoodValue>" + QString::number(mMilkFoodValue) + "</milkFoodValue>\n");
  myString+=QString("  <fleece>" + QString::number(mFleece) + "</fleece>\n");
  myString+=QString("  <fleeceWeightKg>" + QString::number(mFleeceWeightKg) + "</fleeceWeightKg>\n");
  myString+=QString("  <imageFile>" + LaUtils::xmlEncode(mImageFile) + "</imageFile>\n");
  myString+=QString("</animal>\n");
  return myString;
}
QString LaAnimal::toText ()
Return a plain text representation of this layer
Definition at line 430 of file laanimal.cpp.
References LaGuid::guid(), KCalories, mBreedingExpectancy, mDeathRate, mDescription, mEstrousCycle, mFeedEnergyType, mFleece, mFleeceWeightKg, mGestating, mGestationTime, mGrowTime, mJuvenile, mKillWeight, mLactating, mLactationTime, mMaintenance, mMeatFoodValue, mMilk, mMilkFoodValue, mMilkGramsPerDay, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, TDN, and LaUtils::xmlEncode().
Referenced by LaAnimalManager::refreshAnimalTable().
{
  QString myString;
  myString+=QString("guid=>" + guid() + "\n");
  myString+=QString("name=>" + LaUtils::xmlEncode(mName) + "\n");
  myString+=QString("description=>" + LaUtils::xmlEncode(mDescription) + "\n");
  myString+=QString("meatFoodValue=>" + QString::number(mMeatFoodValue) + "\n");
  myString+=QString("usableMeat=>" + QString::number(mUsableMeat) + "\n");
  myString+=QString("killWeight=>" + QString::number(mKillWeight) + "\n");
  myString+=QString("growTime=>" + QString::number(mGrowTime) + "\n");
  myString+=QString("deathRate=>" + QString::number(mDeathRate) + "\n");
  switch (mFeedEnergyType)
  {
    case KCalories:
      myString+=QString("feedEnergyType=>KCalories\n");
      break;
    case TDN:
      myString+=QString("feedEnergyType=>TDN\n");
      break;
  }
  myString+=QString("gestating=>" + QString::number(mGestating) + "\n");
  myString+=QString("lactating=>" + QString::number(mLactating) + "\n");
  myString+=QString("maintenance=>" + QString::number(mMaintenance) + "\n");
  myString+=QString("juvenile=>" + QString::number(mJuvenile) + "\n");
  myString+=QString("sexualMaturity=>" + QString::number(mSexualMaturity) + "\n");
  myString+=QString("breedingExpectancy=>" + QString::number(mBreedingExpectancy) + "\n");
  myString+=QString("youngPerBirth=>" + QString::number(mYoungPerBirth) + "\n");
  myString+=QString("weaningAge=>" + QString::number(mWeaningAge) + "\n");
  myString+=QString("weaningWeight=>" + QString::number(mWeaningWeight) + "\n");
  myString+=QString("gestationTime=>" + QString::number(mGestationTime) + "\n");
  myString+=QString("estrousCycle=>" + QString::number(mEstrousCycle) + "\n");
  myString+=QString("lactationTime=>" + QString::number(mLactationTime) + "\n");
  myString+=QString("milk=>" + QString::number(mMilk) + "\n");
  myString+=QString("milkGramsPerDay=>" + QString::number(mMilkGramsPerDay) + "\n");
  myString+=QString("milkFoodValue=>" + QString::number(mMilkFoodValue) + "\n");
  myString+=QString("fleece=>" + QString::number(mFleece) + "\n");
  myString+=QString("fleeceWeightKg=>" + QString::number(mFleeceWeightKg) + "\n");
  return myString;
}
QString LaAnimal::toHtml ()
Return an xml representation of this layer this class inherits the serialisable interface so it MUST implement this
Definition at line 472 of file laanimal.cpp.
References KCalories, mBreedingExpectancy, mDeathRate, mDescription, mEstrousCycle, mFeedEnergyType, mFleece, mFleeceWeightKg, mGestating, mGestationTime, mGrowTime, mJuvenile, mKillWeight, mLactating, mLactationTime, mMaintenance, mMeatFoodValue, mMilk, mMilkFoodValue, mMilkGramsPerDay, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, TDN, and LaUtils::xmlEncode().
Referenced by LaMainForm::showAnimalDefinitionReport(), and LaModel::toHtml().
{
  QString myString;
  myString+="<h2>Details for " + LaUtils::xmlEncode(mName) + "</h2>";
  myString+="<table>";
  myString+="<tr><td><b>Description:</b></td><td>" + mDescription + "</td></tr>";
  myString+="<tr><td><b>Meat Food Value:</b></td><td>" + QString::number(mMeatFoodValue) + "</td></tr>";
  myString+="<tr><td><b>Usable Meat (%):</b></td><td>" + QString::number(mUsableMeat) + "</td></tr>";
  myString+="<tr><td><b>Sexual Maturity:</b></td><td>" + QString::number(mSexualMaturity) + "</td></tr>";
  myString+="<tr><td><b>Years Breedable:</b></td><td>" + QString::number(mBreedingExpectancy) + "</td></tr>";
  myString+="<tr><td><b>Young Per Birth:</b></td><td>" + QString::number(mYoungPerBirth) + "</td></tr>";
  myString+="<tr><td><b>Weaning Age:</b></td><td>" + QString::number(mWeaningAge) + "</td></tr>";
  myString+="<tr><td><b>Weaning Weight:</b></td><td>" + QString::number(mWeaningWeight) + "</td></tr>";
  myString+="<tr><td><b>Kill Weight (Kg):</b></td><td>" + QString::number(mKillWeight) + "</td></tr>";
  myString+="<tr><td><b>Grow Time:</b></td><td>" + QString::number(mGrowTime) + "</td></tr>";
  myString+="<tr><td><b>Death Rate (%):</b></td><td>" + QString::number(mDeathRate) + "</td></tr>";
  myString+="<tr><td><b>Gestation Time:</b></td><td>" + QString::number(mGestationTime) + "</td></tr>";
  myString+="<tr><td><b>Estrous Cycle:</b></td><td>" + QString::number(mEstrousCycle) + "</td></tr>";
  myString+="<tr><td><b>lactationTime:</b></td><td>" + QString::number(mLactationTime) + "</td></tr>";
  myString+="<tr><td><b>milk:</b></td><td>" + QString::number(mMilk) + "</td></tr>";
  myString+="<tr><td><b>milkGramsPerDay:</b></td><td>" + QString::number(mMilkGramsPerDay) + "</td></tr>";
  myString+="<tr><td><b>milkFoodValue:</b></td><td>" + QString::number(mMilkFoodValue) + "</td></tr>";
  myString+="<tr><td><b>fleece:</b></td><td>" + QString::number(mFleece) + "</td></tr>";
  myString+="<tr><td><b>fleeceWeightKg:</b></td><td>" + QString::number(mFleeceWeightKg) + "</td></tr>";
  myString+="<tr><td></td><td>";
  myString+="<tr><td><FONT COLOR=\"#0063F7\">Feed Requirements (pa)</FONT></td><td>";
  switch (mFeedEnergyType)
  {
    case KCalories:
      myString+="<tr><td><b>EnergyType:</b></td><td>KCalories</td></tr>";
      break;
    case TDN:
      myString+="<tr><td><b>EnergyType:</b></td><td>TDN</td></tr>";
      break;
  }
  myString+="<tr><td><b>Gestating Female:</b></td><td>" + QString::number(mGestating) + "</td></tr>";
  myString+="<tr><td><b>Lactating Female:</b></td><td>" + QString::number(mLactating) + "</td></tr>";
  myString+="<tr><td><b>Adult Maintenance:</b></td><td>" + QString::number(mMaintenance) + "</td></tr>";
  myString+="<tr><td><b>Juveniles:</b></td><td>" + QString::number(mJuvenile) + "</td></tr>";
  myString+="</table>";
  return myString;
}
bool LaAnimal::fromXml (const QString theXml) [virtual]
Read this object from xml and return result as true for success, false for failure.
See also:
LaSerialisable this class inherits the serialisable interface so it MUST implement this
Implements LaSerialisable.
Definition at line 334 of file laanimal.cpp.
References KCalories, mBreedingExpectancy, mDeathRate, mDescription, mEstrousCycle, mFeedEnergyType, mFleece, mFleeceWeightKg, mGestating, mGestationTime, mGrowTime, mImageFile, mJuvenile, mKillWeight, mLactating, mLactationTime, mMaintenance, mMeatFoodValue, mMilk, mMilkFoodValue, mMilkGramsPerDay, mName, mSexualMaturity, mUsableMeat, mWeaningAge, mWeaningWeight, mYoungPerBirth, LaGuid::setGuid(), TDN, and LaUtils::xmlDecode().
{
    //qDebug("Loading animal from xml");
  QDomDocument myDocument("mydocument");
  myDocument.setContent(theXml);
  QDomElement myTopElement = myDocument.firstChildElement("animal");
  if (myTopElement.isNull())
  {
      //TODO - just make this a warning
     //qDebug("top element could not be found!");
  }
    //qDebug("Animal::fromXml - guid found : " + myTopElement.attribute("guid").toLocal8Bit());
  setGuid(myTopElement.attribute("guid"));
    //qDebug("Animal::fromXml - guid set to : " + guid().toLocal8Bit());
  mName=LaUtils::xmlDecode(myTopElement.firstChildElement("name").text());
  mDescription=LaUtils::xmlDecode(myTopElement.firstChildElement("description").text());
  mMeatFoodValue=QString(myTopElement.firstChildElement("meatFoodValue").text()).toInt();
  mUsableMeat=QString(myTopElement.firstChildElement("usableMeat").text()).toInt();
  mKillWeight=QString(myTopElement.firstChildElement("killWeight").text()).toInt();
  mGrowTime=QString(myTopElement.firstChildElement("growTime").text()).toInt();
  mDeathRate=QString(myTopElement.firstChildElement("deathRate").text()).toInt();
  QString myFeedEnergyType = QString(myTopElement.firstChildElement("feedEnergyType").text());
  if (myFeedEnergyType == "KCalories")
  {
    mFeedEnergyType=KCalories;
  }
  else if (myFeedEnergyType == "TDN")
  {
    mFeedEnergyType=TDN;
  }
  mGestating=QString(myTopElement.firstChildElement("gestating").text()).toInt();
  mLactating=QString(myTopElement.firstChildElement("lactating").text()).toInt();
  mMaintenance=QString(myTopElement.firstChildElement("maintenance").text()).toInt();
  mJuvenile=QString(myTopElement.firstChildElement("juvenile").text()).toInt();
  mSexualMaturity=QString(myTopElement.firstChildElement("sexualMaturity").text()).toInt();
  mBreedingExpectancy=QString(myTopElement.firstChildElement("breedingExpectancy").text()).toInt();
  mYoungPerBirth=QString(myTopElement.firstChildElement("youngPerBirth").text()).toInt();
  mWeaningAge=QString(myTopElement.firstChildElement("weaningAge").text()).toInt();
  mWeaningWeight=QString(myTopElement.firstChildElement("weaningWeight").text()).toInt();
  mGestationTime=QString(myTopElement.firstChildElement("gestationTime").text()).toInt();
  mEstrousCycle=QString(myTopElement.firstChildElement("estrousCycle").text()).toInt();
  mLactationTime=QString(myTopElement.firstChildElement("lactationTime").text()).toInt();
  mMilk=QString(myTopElement.firstChildElement("milk").text()).toInt();
  mMilkGramsPerDay=QString(myTopElement.firstChildElement("milkGramsPerDay").text()).toInt();
  mMilkFoodValue=QString(myTopElement.firstChildElement("milkFoodValue").text()).toInt();
  mFleece=QString(myTopElement.firstChildElement("fleece").text()).toInt();
  mFleeceWeightKg=QString(myTopElement.firstChildElement("fleeceWeightKg").text()).toInt();
  mImageFile=QString(myTopElement.firstChildElement("imageFile").text());
  return true;
}
Member Data Documentation
QString LaAnimal::mName [private]
The name for this animal
Definition at line 253 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), name(), operator=(), setName(), toHtml(), toText(), and toXml().
QString LaAnimal::mDescription [private]
The description for this animal
Definition at line 255 of file laanimal.h.
Referenced by description(), fromXml(), LaAnimal(), operator=(), setDescription(), toHtml(), toText(), and toXml().
int LaAnimal::mMeatFoodValue [private]
Food value of meat in calories per kg
Definition at line 257 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), meatFoodValue(), operator=(), setMeatFoodValue(), toHtml(), toText(), and toXml().
int LaAnimal::mUsableMeat [private]
Percentage of animals live weight that can be utilized for meat
Definition at line 259 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), operator=(), setUsableMeat(), toHtml(), toText(), toXml(), and usableMeat().
int LaAnimal::mKillWeight [private]
The weight in kg at which the animals are slaughtered
Definition at line 261 of file laanimal.h.
Referenced by fromXml(), killWeight(), LaAnimal(), operator=(), setKillWeight(), toHtml(), toText(), and toXml().
int LaAnimal::mGrowTime [private]
The number of weeks from birth it takes to attain slaughtering weight
Definition at line 263 of file laanimal.h.
Referenced by fromXml(), growTime(), LaAnimal(), operator=(), setGrowTime(), toHtml(), toText(), and toXml().
int LaAnimal::mDeathRate [private]
The percentage of babies that die before being usable as either meat or breeding
Definition at line 265 of file laanimal.h.
Referenced by deathRate(), fromXml(), LaAnimal(), operator=(), setDeathRate(), toHtml(), toText(), and toXml().
EnergyType LaAnimal::mFeedEnergyType [private]
The feed Energy type: KCalories or TDN
Definition at line 267 of file laanimal.h.
Referenced by feedEnergyType(), fromXml(), LaAnimal(), operator=(), setFeedEnergyType(), toHtml(), toText(), and toXml().
int LaAnimal::mGestating [private]
The number of calories a gestating female requires per day
Definition at line 269 of file laanimal.h.
Referenced by fromXml(), gestating(), LaAnimal(), operator=(), setGestating(), toHtml(), toText(), and toXml().
int LaAnimal::mLactating [private]
The number of calories a lactating female requires per day
Definition at line 271 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), lactating(), operator=(), setLactating(), toHtml(), toText(), and toXml().
int LaAnimal::mMaintenance [private]
The number of calories adult maintenance requires per day
Definition at line 273 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), maintenance(), operator=(), setMaintenance(), toHtml(), toText(), and toXml().
int LaAnimal::mJuvenile [private]
The number of calories a juvenile requires per day
Definition at line 275 of file laanimal.h.
Referenced by fromXml(), juvenile(), LaAnimal(), operator=(), setJuvenile(), toHtml(), toText(), and toXml().
int LaAnimal::mSexualMaturity [private]
The life expectancy in years of the animal
Definition at line 277 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), operator=(), setSexualMaturity(), sexualMaturity(), toHtml(), toText(), and toXml().
int LaAnimal::mBreedingExpectancy [private]
The number of years a female will reliably produce offspring
Definition at line 279 of file laanimal.h.
Referenced by breedingExpectancy(), fromXml(), LaAnimal(), operator=(), setBreedingExpectancy(), toHtml(), toText(), and toXml().
int LaAnimal::mYoungPerBirth [private]
The average number of young produced per pregnancy
Definition at line 281 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), operator=(), setYoungPerBirth(), toHtml(), toText(), toXml(), and youngPerBirth().
int LaAnimal::mWeaningAge [private]
The age in weeks at which babies stop suckling
Definition at line 283 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), operator=(), setWeaningAge(), toHtml(), toText(), toXml(), and weaningAge().
int LaAnimal::mWeaningWeight [private]
The weight when babies stop suckling
Definition at line 285 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), operator=(), setWeaningWeight(), toHtml(), toText(), toXml(), and weaningWeight().
int LaAnimal::mGestationTime [private]
The number of days required for gestation
Definition at line 287 of file laanimal.h.
Referenced by fromXml(), gestationTime(), LaAnimal(), operator=(), setGestationTime(), toHtml(), toText(), and toXml().
int LaAnimal::mEstrousCycle [private]
The number of days in the female estrous cycle
Definition at line 289 of file laanimal.h.
Referenced by estrousCycle(), fromXml(), LaAnimal(), operator=(), setEstrousCycle(), toHtml(), toText(), and toXml().
int LaAnimal::mLactationTime [private]
total length of lactation
Definition at line 291 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), lactationTime(), operator=(), setLactationTime(), toHtml(), toText(), and toXml().
bool LaAnimal::mMilk [private]
flag for utilisation of milk
Definition at line 293 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), milk(), operator=(), setMilk(), toHtml(), toText(), and toXml().
int LaAnimal::mMilkGramsPerDay [private]
milk production per mother per day in grams
Definition at line 295 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), milkGramsPerDay(), operator=(), setMilkGramsPerDay(), toHtml(), toText(), and toXml().
int LaAnimal::mMilkFoodValue [private]
food value of milk per kg in KCalories
Definition at line 297 of file laanimal.h.
Referenced by fromXml(), LaAnimal(), milkFoodValue(), operator=(), setMilkFoodValue(), toHtml(), toText(), and toXml().
bool LaAnimal::mFleece [private]
flag for provision of a fleece from the animal
Definition at line 299 of file laanimal.h.
Referenced by fleece(), fromXml(), LaAnimal(), operator=(), setFleece(), toHtml(), toText(), and toXml().
int LaAnimal::mFleeceWeightKg [private]
the weight of the fleece, if available, in kg per annum
Definition at line 301 of file laanimal.h.
Referenced by fleeceWeightKg(), fromXml(), LaAnimal(), operator=(), setFleeceWeightKg(), toHtml(), toText(), and toXml().
QString LaAnimal::mImageFile [private]
name of image file
Definition at line 303 of file laanimal.h.
Referenced by fromXml(), imageFile(), LaAnimal(), operator=(), setImageFile(), and toXml().
The documentation for this class was generated from the following files:
dev/cpp/landuseanalyst/src/lib/laanimal.h
dev/cpp/landuseanalyst/src/lib/laanimal.cpp